### ISSUE TITLE
HaskForce & Haskell-idea-plugin & IntelliJ-Haskell

### ISSUE THREAD

**Issue by xkrt** [rikvdkleij/intellij-haskell#1]
Hi,
This is not an issue, I just want to show you yet another Haskell IntelliJ plugin: http://carymrobbins.github.io/intellij-haskforce in addition to what you mention in README https://github.com/Atsky/haskell-idea-plugin

And now, there is three plugins in active development. Maybe you consider unite yours efforts.
Just wanted to let you know about the existence of each other, guys. Thanks!

/cc @pjonsson @carymrobbins @Atsky @vlpolyansky @bronti @octomarat

**Comment by Pastafarianist** [comment]
@rikvdkleij At this moment, 26.4% of Haskforce's codebase is in Scala, and it requires Scala as a build dependency. So apparently @carymrobbins is migrating to Scala. Would that be a reason for you to reconsider joining efforts?

**Comment by rikvdkleij** [comment]
@Pastafarianist @carymrobbins 
Well, I'm open to collaboration but I will not give up my codebase. Especially contributions to support Windows and adding tests are welcome! Also notice that `intellij-haskell` depends mainly on `stack` and `intero` which is a major difference with `haskforce`.

**Comment by ice1000** [comment]
Maybe we can do some mutual copy to improve each other

**Comment by ice1000** [comment]
@rikvdkleij I think you should copy the haskell parser from https://github.com/Atsky/haskell-idea-plugin, their parser looks really good.

**Comment by rikvdkleij** [comment]
Did you test/run it? I need some time to investigate how it works.

**Comment by rikvdkleij** [comment]
@ice1000 Btw, this will mean large part of plugin has to be rewritten....

**Comment by ice1000** [comment]
> Did you test/run it? I need some time to investigate how it works.

No, sorry.

**Comment by rikvdkleij** [comment]
> But the current parser is really terrible

I agree, but at least it is declarative and works well as approximation of GHC parser (with all his language extensions) to implement IntelliJ features 😄 
What is lacking is layout sensitivity to get better support for non-top level expressions/declarations.

It would be nicer to hook in a Haskell parser.

**Comment by ice1000** [comment]
> It would be nicer to hook in a Haskell parser.

That'll be very very hard, AFAIK
