### ISSUE TITLE
Build sandbox project inside IntelliJ

### ISSUE THREAD

**Issue by rikvdkleij** [rikvdkleij/intellij-haskell#10]

**Comment by zjhmale** [comment]
@rikvdkleij  Do we still need this feature? I mean, stack is cool enough, I think there is no need to use cabal sandbox anymore.

**Comment by rikvdkleij** [comment]
@zjhmale Yeah, you are right. But we still need a feature to build Haskelll project inside IntelliJ, see http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_builder_api.html

I will create separate issue for that.

**Comment by zjhmale** [comment]
@rikvdkleij Great!
