### ISSUE TITLE
Adding stack sdk fails

### ISSUE THREAD

**Issue by adam-singer** [rikvdkleij/intellij-haskell#108]
Trying to add `stack` from `~/.local/bin/stack` fails to save sdk or set the project as the sdk. Seems to detect the file and version of the stack binary, selecting it as an sdk fails. 

![screen shot 2017-01-04 at 12 17 30 pm](https://cloud.githubusercontent.com/assets/654526/21657584/ce299cca-d277-11e6-9c8d-1e84233f914e.png)
 

<img width="828" alt="screen shot 2017-01-04 at 12 11 37 pm" src="https://cloud.githubusercontent.com/assets/654526/21657587/d445e56e-d277-11e6-9057-86b3ccdd38bb.png">
<img width="991" alt="screen shot 2017-01-04 at 12 11 30 pm" src="https://cloud.githubusercontent.com/assets/654526/21657588/d46f0f20-d277-11e6-9dfc-bbb3c10f8114.png">
<img width="692" alt="screen shot 2017-01-04 at 12 10 32 pm" src="https://cloud.githubusercontent.com/assets/654526/21657589/d47d605c-d277-11e6-97c1-0877557bc033.png">
<img width="618" alt="screen shot 2017-01-04 at 12 10 26 pm" src="https://cloud.githubusercontent.com/assets/654526/21657591/d47dc6d2-d277-11e6-8f6a-a8bcc91edcb2.png">
<img width="606" alt="screen shot 2017-01-04 at 12 10 15 pm" src="https://cloud.githubusercontent.com/assets/654526/21657593/d4809010-d277-11e6-9d50-f013b1fcc815.png">
<img width="776" alt="screen shot 2017-01-04 at 12 10 06 pm" src="https://cloud.githubusercontent.com/assets/654526/21657590/d47dac38-d277-11e6-997a-22108ba0aebc.png">
<img width="1103" alt="screen shot 2017-01-04 at 12 09 26 pm" src="https://cloud.githubusercontent.com/assets/654526/21657592/d47e2a8c-d277-11e6-8b15-0dd9bc2ff214.png">
<img width="611" alt="screen shot 2017-01-04 at 12 06 18 pm" src="https://cloud.githubusercontent.com/assets/654526/21657594/d48135f6-d277-11e6-88a4-da42b6d0290e.png">

**Comment by rikvdkleij** [comment]
It looks like you have to remove existing Haskell Tool Stack first.

**Comment by adam-singer** [comment]
@rikvdkleij I've done that a few times and it always ends in the same results of

![screen shot 2017-01-04 at 1 49 11 pm](https://cloud.githubusercontent.com/assets/654526/21660521/9a0daece-d284-11e6-9d5b-18e84c305f07.png)

**Comment by adam-singer** [comment]
Interesting, I had to delete all of the previous sdks defined and global libraries, then import from sources and add the stack binary as the sdk. This could be isolated to my own env cause I do depend on some custom sdk generation tools for jvm projects. Have you tested this plugin while other sdks are defined in the env?

**Comment by zjhmale** [comment]
@adam-singer 

I believe this should not be a problem. I'm working with multiple SDKs and everything works fine.
>Have you tested this plugin while other sdks are defined in the env?

![image](https://cloud.githubusercontent.com/assets/6234553/21671349/ce14c082-d355-11e6-9bf8-e016304dae30.png)

**Comment by rikvdkleij** [comment]
@adam-singer I can not reproduce your issue. Also not on Mac and by adding more then one Haskell Tool Stacks

**Comment by adam-singer** [comment]
@rikvdkleij @zjhmale thanks for looking into this! Also hit similar oddities with importing the plugin source code via sbt, removing all previous sdks fixed it, closing out since it seems on the IntelliJ side. 

```
IntelliJ IDEA 2016.3
Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
