### ISSUE TITLE
Reduce and/or hide verbose event logging 

### ISSUE THREAD

**Issue by adam-singer** [rikvdkleij/intellij-haskell#110]
Would be nice if event logging in the current state would be reduced or hidden behind a toggle flag in settings. It tends to be very useful for debugging errors but eventually should only be useful in a verbose or total error state. 

![screen shot 2017-01-04 at 10 01 25 pm](https://cloud.githubusercontent.com/assets/654526/21670548/d8c1cc1e-d2c9-11e6-989a-854864d81bc5.png)

**Comment by rikvdkleij** [comment]
It's already there, You can manage notifications in `Settings`/`Notifications`. You can dispute the default :smile:

**Comment by rikvdkleij** [comment]
I have disabled it by default.
