### ISSUE TITLE
Hide `ideaHaskellLib` as `.ideaHaskellLib` or `.idea-haskell-libs`

### ISSUE THREAD

**Issue by adam-singer** [rikvdkleij/intellij-haskell#111]
Would be nice if the unpacked libraries stayed consistent with other reference/meta directories, hidden behind a `.`. Also think it would be better named as `.idea-haskell-libs`, but that's more of a personal preference.

**Comment by zjhmale** [comment]
Yes, I actually discussed this with @rikvdkleij [before](https://github.com/rikvdkleij/intellij-haskell/pull/91#discussion_r94153177), I'll fix this if @rikvdkleij agree with it 😄

**Comment by adam-singer** [comment]
Awesome!
