### ISSUE TITLE
Can not navigate function

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#115]
I already got `Data.Traversable` source in `.ideaHaskellLibs` directory, but I can not navigate `sequence` and `sequenceA` to its declaration place which is really wired.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21690113/ddc87106-d3ad-11e6-8fac-82b606de1f40.gif)

**Comment by rikvdkleij** [comment]
No, it's not weird You are trying to navigate in library source which is not supported in all cases. Intero does not work in library files and ghci info does not always work in library files despite I start global reply with `--no-package-hiding`

**Comment by zjhmale** [comment]
Ok, so maybe we should close this issue until Intero and ghci works fine with this case?

**Comment by rikvdkleij** [comment]
I think Intero and Ghci will never support this. We can try to use the PSI-tree but it will never be a solid solution which works in all cases. 

I already use the PSI-tree in Library sources in case Ghci info does not work to find declarations within file itself (see HaskellReference). We can extend that by also searching through the top level declarations inside import modules. But it's a kind of "guessing" and will never be solid.

**Comment by rikvdkleij** [comment]
Wait, I have not read well. You are trying to go from project file to library file. That has to work. I can reproduce your issue and will fix it.

**Comment by rikvdkleij** [comment]
Problem is caused because Traversable class is not parsed complete correctly :sweat:

**Comment by rikvdkleij** [comment]
Pushed fix.

**Comment by zjhmale** [comment]
Thanks!
