### ISSUE TITLE
Auto complete add extra `-}` when multiline comment at function

### ISSUE THREAD

**Issue by adam-singer** [rikvdkleij/intellij-haskell#116]
Seems that after auto complete of `{-|-}` pressing enter before the `-}` will cause an extra  `-}` to be produced. 

<img width="182" alt="screen shot 2017-01-07 at 3 04 43 pm" src="https://cloud.githubusercontent.com/assets/654526/21745944/01c5c34a-d4eb-11e6-90d0-14d100adf40b.png">

<img width="195" alt="screen shot 2017-01-07 at 3 04 53 pm" src="https://cloud.githubusercontent.com/assets/654526/21745945/07d7514a-d4eb-11e6-991d-ecc5f4df4c99.png">

<img width="179" alt="screen shot 2017-01-07 at 3 05 24 pm" src="https://cloud.githubusercontent.com/assets/654526/21745948/0e142b3c-d4eb-11e6-904c-1300e2cc6b85.png">

**Comment by rikvdkleij** [comment]
Thanks for reporting. I will fix it.

**Comment by rikvdkleij** [comment]
I pushed a fix. Fix will be in next beta.

**Comment by rikvdkleij** [comment]
I just released beta 6 and this issue should be fixed.
