### ISSUE TITLE
Hole driven development support

### ISSUE THREAD

**Issue by rikvdkleij** [rikvdkleij/intellij-haskell#12]

**Comment by zjhmale** [comment]
Does the "Hole driven development" mean that auto generating expressions from type signatures?

**Comment by rikvdkleij** [comment]
Yes, but also the other way around.
See http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#typed-holes, http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#partial-type-signatures and  http://matthew.brecknell.net/post/hole-driven-haskell/

**Comment by zjhmale** [comment]
@rikvdkleij Thanks for the links, which comes to my mind is that we can only gain extra error messages using typed holes, but we already show the error messages right? so what exactly does this feature want to achieve?

**Comment by rikvdkleij** [comment]
To apply suggested expression or type.

Btw, error can become warning by enabling: `-fdefer-typed-holes`

**Comment by zjhmale** [comment]
Is there any ways to get suggested expression or type using typed holes? For the examples on the documents, they are just some messages and can not extract any useful infos to apply to the code on the editor.
>To apply suggested expression or type.

Thanks, I see the flag in the first link.
>Btw, error can become warning by enabling: -fdefer-typed-holes

**Comment by rikvdkleij** [comment]
This blog contains some more examples:
http://lonelyproton.com/posts/36-getting-more-familiar-with-types-through-hole-driven-development-3

This issue is an idea........  :smile:

**Comment by rikvdkleij** [comment]
@zjhmale 
>  and represent type infos for a specific typed hole, right?

Yes, you are right, that is doable

**Comment by zjhmale** [comment]
@rikvdkleij this link is great, I think I have some plans about this feature in my mind now :smile: 
>This blog contains some more examples:
http://lonelyproton.com/posts/36-getting-more-familiar-with-types-through-hole-driven-development-3

**Comment by rikvdkleij** [comment]
Current solution is good enough to support it
