### ISSUE TITLE
Option to be less chatty in event log

### ISSUE THREAD

**Issue by grassator** [rikvdkleij/intellij-haskell#122]
Currently intellij-haskell is dumping a lot of the information in the event log, which can be a bit distracting and I would assume has a performance cost. Is there an option to only show errors?

If there is none and it's an acceptable feature I could take a stab at it myself but probably would need some pointers on where would you see it best fit in the code.

Thank you for the awesome work!

**Comment by rikvdkleij** [comment]
Is it an option to just disable it's notifications in Event log? You manage those yourself in `Setttings`/`Appearance&Behavior`/`Notifications`.

**Comment by grassator** [comment]
That was helpful, didn't know about that intellij feature!

**Comment by rikvdkleij** [comment]
I have disabled it by default.
