### ISSUE TITLE
Support for hash value Stack resolver

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#125]
This was originally proposed by @NightRa on Gitter.

>Played a little more with the plugin, it to parse output from stack on windows:
CabalConfigComponent.getResolverFromLocalPkgdb, stack 1.3.2 returns "C:\Users\Ilan\Programming\Haskell-Playground.stack-work\install\ef7d292a\pkgdb", which contains no version.
Also, assuming there must be an "lts-." is problematic - there are nightlies too

Currently this plugin support LTS and Nightly Stack resolver, but a hash value resolver may not relate to a specific cabal.config file.

**Comment by rikvdkleij** [comment]
@zjhmale What is the use case?

**Comment by zjhmale** [comment]
@rikvdkleij Just for memo since @NightRa did not explain the issue more explicitly.

**Comment by NightRa** [comment]
This is how the version is computed for the cache, and the cache is used for getting the value. 
On Windows, it fails parsing, thus the cabal.config isn't downloaded, and global loading doesn't proceed 
It fails parsing because there is no (lts) version in that path

**Comment by zjhmale** [comment]
Hi @NightRa, But generally, it will be `/Users/zjh/Documents/haskellspace/while/.stack-work/install/x86_64-osx/nightly-2017-01-07/8.0.1/pkgdb` or `/Users/zjh/Documents/haskellspace/idris-lsp/.stack-work/install/x86_64-osx/lts-7.11/8.0.1/pkgdb`, I can not find any Stack docs pointing out how to translate the hash value to resolver and ghc version? And is it only happens on Windows?

**Comment by rikvdkleij** [comment]
@zjhmale maybe we can use yaml parser to get LTS version from Stack.yaml

**Comment by zjhmale** [comment]
Good idea 😄

**Comment by NightRa** [comment]
That, and also ask stack to provide it explicitly

**Comment by zjhmale** [comment]
@rikvdkleij But if we use a YAML parser, we should list all the properties which stack.yaml provides.

**Comment by zjhmale** [comment]
@NightRa Does the resolver in your stack.yaml display explicitly or it is also a hash value?

**Comment by zjhmale** [comment]
Any options to do that?
>That, and also ask stack to provide it explicitly

**Comment by rikvdkleij** [comment]
@zjhmale 

> But if we use a YAML parser, we should list all the properties which stack.yaml provides.

I do not understand problem, we can just pick what we need :smile:

**Comment by rikvdkleij** [comment]
@zjhmale @NightRa 
> Any options to do that?

We have to create Stack issue in which we ask to create an Stack option which returns Stackage version.

**Comment by rikvdkleij** [comment]
@zjhmale Btw, I think we can only download cabal.config file for LTS and Nightly versions. Maybe in other cases we should fallback to some default LTS version or cabal.config file.

Yet another solution is to encapsulate per major LTS version a cabal.config file in plugin. It's only used for package name completion.

**Comment by zjhmale** [comment]
Ah, right, I was worried that we have to list all the properties 😅 
>I do not understand problem, we can just pick what we need 😄

**Comment by zjhmale** [comment]
Which default version we should keep or we may update the default LTS version or cabal.config file constantly if any new LTS version is released?
> Btw, I think we can only download cabal.config file for LTS and Nightly versions. Maybe in other cases we should fallback to some default LTS version or cabal.config file.
Yet another solution is to encapsulate a cabal.config file in plugin. It's only used for package name completion.

**Comment by rikvdkleij** [comment]
Well there are 2 global solutions:
- Parse stack.yaml or ask Stack binary for Stackage version but we need still some default cabal.config file in case not LTS or Nightly;
- Put latest cabal.config file in plugin which we update if we release new version of plugin. Only downside is that cabal.config can be stale. Keep in mind it's only used for completion of package names.

**Comment by zjhmale** [comment]
Cool, I'll follow these 2 goals.

**Comment by rikvdkleij** [comment]
@zjhmale Well, I think we have to choose one :smile:  Most simple solution is second one.

**Comment by zjhmale** [comment]
@rikvdkleij I think these 2 goals are not in confliction, we can get the resolver both from stack binary and parsing YAML file, and we can use the default cabal.config file if the resolver can not be retrieved 😄

**Comment by rikvdkleij** [comment]
@zjhmale Okay, but it's double to get Stackage version from Stack binary and stack.yaml. There is a Java YAML parser: https://bitbucket.org/asomov/snakeyaml

**Comment by zjhmale** [comment]
I just worried that if we can not get the resolver from stack binary directly, we can parse the YAML file 😄 if you think it is redundant, maybe we can skip the parsing process.

**Comment by rikvdkleij** [comment]
The parsing solution can be done by ourselves. For getting the Stackage version from Stack binary we are depending on Stack developers.

**Comment by zjhmale** [comment]
Yeah, so the parsing solution should be the first priority, the old way is now a backup right?

**Comment by rikvdkleij** [comment]
Eventually we replace old solution by new solution. Or do you mean something else by `backup`?

**Comment by zjhmale** [comment]
I mean we could use the new solution to get local resolver but also keep the old solution code 😄 
>Eventually we replace old solution by new solution. Or do you mean something else by backup?

**Comment by rikvdkleij** [comment]
I think it's better to remove old solution. It's kind of a hack :smile:

**Comment by zjhmale** [comment]
Ok, fair enough 😄 
>I think it's better to remove old solution. It's kind of a hack 😄
