### ISSUE TITLE
Support Cabal flags per target/main

### ISSUE THREAD

**Issue by rikvdkleij** [rikvdkleij/intellij-haskell#129]
Because project repl is loaded with `--test`, also option `--no-load` is passed to Stack repl otherwise we have to choose which target/main to load in Stack repl. 
Downside is that Cabal flags for target/main are not read, for example `ghc-options`

Possible solution is that each target (executable, test-suite) has it's own Stack repl.

**Comment by rikvdkleij** [comment]
@zjhmale If we also create Stack intero repl for test target, we can run tests from there. Also no need to reload test hspec file when running test.

**Comment by zjhmale** [comment]
@rikvdkleij Cool, but we should design an easy way for the users to communicate with multiple Stack REPLs right?

**Comment by zjhmale** [comment]
And where can I find documentations about these options for `stack repl` command e.g. `--test` and `--no-load`? Thanks in advance 😄

**Comment by zjhmale** [comment]
Oh, and one question beyond this issue, what is the use case of [GlobalStackReplProcess](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/external/repl/GlobalStackReplProcess.scala)? Because we will always open a Stack based project with this plugin, why we need a global one?

**Comment by zjhmale** [comment]
@rikvdkleij https://gitlab.com/vannnns/haskero this VSCode extension support switching Intero process instance between targets defined in cabal file, I will do some investigation into this project in order to solve the issue here 😄

**Comment by thoradam** [comment]
Haskero just has one intero process and restarts it if you select different targets. I thought about doing a process per target but I figured it required parsing the cabal file to map the source files to correct targets.

**Comment by rikvdkleij** [comment]
Restarting repl takes some time. Consider switching between test and implementation files, I suspect some annoying delay Also the whole target has to be loaded again.

**Comment by zjhmale** [comment]
Parsing cabal file is not pain in this plugin now, we can always extend the cabal parser if you need. And about the source file mapping process, I will investigate how `Haskero` do this.
>Haskero just has one intero process and restarts it if you select different targets. I thought about doing a process per target but I figured it required parsing the cabal file to map the source files to correct targets.

**Comment by zjhmale** [comment]
Yeah, we should avoid restarting REPL too many times, let me do some investigation first 😄 
>Restarting repl takes some time. Consider switching between test and implementation files, I suspect some annoying delay Also the whole target has to be loaded again.

**Comment by rikvdkleij** [comment]
Solved in beta 9
