### ISSUE TITLE
Add libraries to External Libraries tree

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#130]
Just like Java, Kotlin, Scala, Go, Erlang plugin etc.

![image](https://cloud.githubusercontent.com/assets/6234553/21899696/2392f0ca-d92c-11e6-97bc-4c82ddee1cd6.png)

**Comment by rikvdkleij** [comment]
What is the difference with `Dependencies` in `Project Structure`/`Modules`?

**Comment by zjhmale** [comment]
I think there is no big difference between them, but users can easily get what libraries are currently used by the project.

**Comment by zjhmale** [comment]
@rikvdkleij And another issue in the External Libraries tree which I struggled fixing with yesterday is that no matter how I change the project SDK, the External Libraries tree always display the same SDK.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21925301/d8099e1a-d9b7-11e6-935f-b5c332db36af.gif)

**Comment by rikvdkleij** [comment]
@zjhmale It looks like tree has to be refreshed

**Comment by zjhmale** [comment]
Yes, but I did not find any proper solutions yesterday.

**Comment by zjhmale** [comment]
And after change project SDK, the stack repl process should also be restarted.

**Comment by rikvdkleij** [comment]
Yes, there are more cases when repls have to be restarted. Also when cabal.config is changed.

When stack.yaml is changed, the whole project has to be restarted because tools have to be rebuild etc.

I think we need listeners for cabal.config and stack.yaml which trigger popup to user with action if file is changed. Just like if in Scala project, sbt file is changed.

**Comment by zjhmale** [comment]
Agreed, I'll write listener to watch these two files. But refresh the External Libraries tree is a little tricky here, you can try https://github.com/ignatov/intellij-erlang/, just clone the repo and then run `./gradlew runIdea`, a intellij-erlang project can sync the SDK after you change the project SDK in `Project Structure` even I comment all the configurations in plugin.xml https://github.com/ignatov/intellij-erlang/blob/master/plugin/resources/META-INF/plugin.xml#L19-L57 which is really really wired.

**Comment by rikvdkleij** [comment]
Maybe it helps to take a look in constructor of `SetupSDKNotificationProvider` of Intellij-erlang.

**Comment by zjhmale** [comment]
I have already looked at it and it just works when the project SDK is not setup.

**Comment by rikvdkleij** [comment]
Sorry, I can not help you. I know what you feel, I have been there. I have spend a lot of time solving this kind of IntelliJ's problem :disappointed:

**Comment by zjhmale** [comment]
No worries, there always a way out 😄
