### ISSUE TITLE
Load error in Setup.hs

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#133]
`:load $ProjectRoot/Setup.hs` always fails, maybe we should skip loading this module?

![image](https://cloud.githubusercontent.com/assets/6234553/21960638/14d3f040-db2d-11e6-8401-703fe5266b14.png)

![image](https://cloud.githubusercontent.com/assets/6234553/21960633/dcff462e-db2c-11e6-80fa-abb8d649c4a3.png)

**Comment by rikvdkleij** [comment]
Fixed.
