### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by huiwang** [rikvdkleij/intellij-haskell#14]
Hello guys,

I'm learning haskell as well and i also have an idea to develop an intellij plugin in scala.

i'm cloning this project on my pc but when trying to open it, intellij says following 
Cannot determine module type ("PLUGIN_MODULE") for the following module:"intellij-haskell" The module will be treated as a Unknown module.

What's going wrong here ? Can anyone help please ?

**Comment by rikvdkleij** [comment]
Sorry for my late response.

Cool that you want to contribute!

I also cloned this project and I could open it without problems. Which version of IntelliJ do you use? You have to use IntelliJ 14.*

Do you have installed/enabled the PlugIn DevKit plugin?

**Comment by rikvdkleij** [comment]
I will write down the steps to build this project asap.

**Comment by huiwang** [comment]
Hi rik,

No i didn't install the devkit plugin. I'll try it and let u know.

Thanks

**Comment by huiwang** [comment]
Hi Rik, I enabled the devkit plugin and i don't have anymore the mentioned issue but instead i have dependency issues. Setting of this project requires that library should be found under /usr/share/scala but I'm developping either under windows or mac, so I don't have them there under /usr/share/.

Can't we use sbt or maven to handle dependencies ?

**Comment by rikvdkleij** [comment]
Hi Hui,

I do not know if that is possible because it's a IntelliJ plugin project. I
have to investigate.

Maybe you can do this task? I'm open to a good solution.

Cheers,
Rik

**Comment by huiwang** [comment]
Sure I'll look around but a plugin project should also be portable.

**Comment by rikvdkleij** [comment]
@huiwang I have added build instructions to Readme. Hopefully it's clear. Let me know if you need more info.

**Comment by huiwang** [comment]
@rikvdkleij , thanks for writing them down but i don't think that it's a good idea to rely on intellij's iml file to handle dependencies. I checked another plugin https://github.com/JetBrains/intellij-scala. It seems that they are using sbt to manage all build related tasks. I think we can learn from them to introduce sbt to this project as well.

**Comment by rikvdkleij** [comment]
@huiwang I completely agree with you :+1:

**Comment by rikvdkleij** [comment]
@huiwang Forgot to mention I'm on holiday for 2 weeks. I try to check my e-mail regularly.

**Comment by rikvdkleij** [comment]
@huiwang Are you still willing to convert this project to sbt?

**Comment by huiwang** [comment]
@rikvdkleij I'll start working on the conversion to sbt. Shall we create a new issue for this ?

**Comment by rikvdkleij** [comment]
@huiwang Cool! Yes, you can create new issue for that. I will close this one.
