### ISSUE TITLE
[Minor] Add libraries to External Libraries tree

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#141]
Just for memo

Related PR #138
Related Issue #130

**Comment by zjhmale** [comment]
@rikvdkleij I think reverting this PR is right since project SDK is shared with all projects, what I really want to implement is something like project dependencies, e.g. in intellij-scala, they do the trick here https://github.com/JetBrains/intellij-scala/blob/idea163.x/src/org/jetbrains/sbt/project/SbtProjectResolver.scala#L147

![image](https://cloud.githubusercontent.com/assets/6234553/22395192/388a30dc-e571-11e6-8ec3-f6dbae805431.png)

We need to implement an [ExternalSystemManager](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_system_integration.html?search=External) instance to achieve that, and it is not wise to spend too much time just for implementing a minor feature, I will come back for this if we get all the key features done.

**Comment by rikvdkleij** [comment]
Fixed in beta 9
