### ISSUE TITLE
failing of copy into source files

### ISSUE THREAD

**Issue by andrewufrank** [rikvdkleij/intellij-haskell#142]
i am new to IDEA and like the plugin; it works but occasionally, it is not possible to paste (neither ctrl-c nor menu item). at the same time i can type in the code i would like to paste - no problem. it seems that `copy` operation is momentarily blocked. the error msg is `[project-stack-repl] errOut:` which I assume is irrelevant.
thank you for your efforts - it will be very nice if everything works!
andrew

**Comment by zjhmale** [comment]
@andrewufrank I don't think it is an issue related to this plugin, did you try other language plugins? Or Maybe it is a Vim plugin issue? I'd like to suggest you that you should check your IntelliJ settings first.

**Comment by andrewufrank** [comment]
i guess you are right - i will try to do this. thank !
