### ISSUE TITLE
CTRL + SHIFT + P on mac do not give me type info

### ISSUE THREAD

**Issue by fokot** [rikvdkleij/intellij-haskell#143]

**Comment by zjhmale** [comment]
Hi @fokot, can you give more details about this issue? e.g. code snippet and error log. I think `Ctrl+Shift+P` works fine for me, I'm also working with OSX.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/22493150/383a6bc4-e869-11e6-8de2-8b870dd18a82.gif)

**Comment by fokot** [comment]
Thanks for quick response. I get message window saying `Could not determine type for`. But in the Event log is see 
```
18:29	[project-stack-repl] command: :type-at /Users/Frantisek/haskell/schemeinterpreter/library/SchemeInterpreter/Parser.hs 64 1 64 8 oct2dig

18:29	[project-stack-repl] stdOut: oct2dig :: (Eq a, Num a) => String -> a
					^IntellijHaskell^

18:29	[project-stack-repl] errOut: 

18:29	[project-stack-repl] command: :loc-at /Users/Frantisek/haskell/schemeinterpreter/library/SchemeInterpreter/Parser.hs 64 1 64 7 oct2dig

18:29	[project-stack-repl] stdOut: /Users/Frantisek/haskell/schemeinterpreter/library/SchemeInterpreter/Parser.hs:(64,1)-(64,8)
					^IntellijHaskell^

18:29	[project-stack-repl] errOut: 
```

**Comment by dogweather** [comment]
I also get `Could not determine info for`. My event log shows errors like these:

```
[project-stack-repl] Stack repl is not yet available. Command was: :load /Users/robb/src/nv-statutes/app/Main.hs
```

**Comment by zjhmale** [comment]
Hi @fokot, I just downloaded your project but I can not reproduce your issue, `Ctrl+Shift+P` still works fine on my side.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/22615510/b724d924-ead0-11e6-8a69-6affe8091856.gif)

**Comment by dogweather** [comment]
@zjhmale Do you know what the error log message `Stack repl is not yet available` implies? I believe I've set the Stack executable correctly in the project structure.

**Comment by zjhmale** [comment]
Hi @dogweather, I think you should wait for the Stack REPL loading process finished, there should be a loading bar at the bottom of the IDE window.

![image](https://cloud.githubusercontent.com/assets/6234553/22615586/9581ce6a-ead2-11e6-9af0-ebf215e76a09.png)

**Comment by dogweather** [comment]
Thanks @zjhmale - the process seems to fail, and it attempts to restart. It never gets as far as showing a loading bar. Investigating...

![screen shot 2017-02-03 at 8 09 27 pm](https://cloud.githubusercontent.com/assets/150670/22615599/c28d15d0-ea4c-11e6-8ded-6f3e85f3b954.png)

**Comment by rikvdkleij** [comment]
@dogweather Did you read Getting started in Readme? Which version of Intellij do you use?

**Comment by dogweather** [comment]
hi @rikvdkleij Yep, I followed the readme, and I'm running Intellij Community Edition 2016.3.4:

 
<img width="373" alt="screen shot 2017-02-08 at 1 03 21 am" src="https://cloud.githubusercontent.com/assets/150670/22730110/6cbbb46c-ed9a-11e6-9a09-cc388e0d17f9.png">

I've got Stack and homebrew updated to the latest, and I've only worked on one or two haskell projects, and always through Stack.

**Comment by rikvdkleij** [comment]
@dogweather Which stack resolver version is defined in stack.yaml?

Stack repl is available if Intero and your project are successfully build.

**Comment by dogweather** [comment]
@rikvdkleij I think I might have found the problem: my global resolver settings vs. my project settings. I'm bumping everything up to `lts-7.19` and recompiling & reinstalling.
