### ISSUE TITLE
Available for other JetBrains IDE such as PyCharm ?

### ISSUE THREAD

**Issue by feigaoxyz** [rikvdkleij/intellij-haskell#146]
Hi, I've heard really good things about your plugin.
Unfortunately I am using [PyCharm](https://www.jetbrains.com/pycharm/) instead of IDEA from JetBrains for Python programming. 

I could not find your plugin from the built-in repository browser. 
And I have also tried to download it and install from disk. But it is not working at all.

It would be great if you could make this plugin available for other IDEs from JetBrains, since I *imagine* they are using the same backend.

**Comment by rikvdkleij** [comment]
Yes, it should be possible but I have to verify that it doesn’t use any APIs that are specific to IntelliJ IDEA.

**Comment by rikvdkleij** [comment]
Sorry, it does not work for PyCharm. This plugin uses API which is not available in PyCharm. 

Why not use IntelliJ Communtity Edition?

**Comment by feigaoxyz** [comment]
thanks for checking out.
i will give IntelliJ a try.

**Comment by yunti** [comment]
Hi sorry to comment on this closed issue, but it would be great to have this work in other jetbrains IDEs, can you clarify what API it does use that is in Intellij but not in pycharm, webstorm etc... then perhaps we can persuade jetbrains to make it available in their other IDEs if there isn't another API suitable.
Currently managing multiple installs of IDEs and configuration and the space requirements etc... isn't ideal. Thanks.
