### ISSUE TITLE
False positive syntax error on empty typeclass instance definition

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#149]
The editor reports a syntax error on typeclass definitions when the body is empty, but this is valid code.

![screenshot from 2017-02-15 19-02-06](https://cloud.githubusercontent.com/assets/399718/23001069/72d27cce-f3b1-11e6-9226-d34d112f09a0.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting. I will fix the parser.

**Comment by chris-martin** [comment]
Yep, looks good to me!
