### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by levinotik** [rikvdkleij/intellij-haskell#15]
I'm trying to follow the instructions for getting started in the README. It says to use File > New Project. Is this correct? In IntelliJ 14.1, there's an option for new project from existing sources. Should I be using that instead? 

Thanks!

**Comment by rikvdkleij** [comment]
Both should work.  `File > New Project` will show you `Haskell module` and forces you to create GHC SDK. So that's the best option to start your first Haskell project. 

Also be sure to have built your sandbox.

Btw, I found a bug in IntelliJ 14.1. I hope they will fix it soon:
https://youtrack.jetbrains.com/issue/IDEA-138236

**Comment by levinotik** [comment]
Thanks for the quick reply. I'm getting the following error:

`3:48:05 PM ghc-modi error output: NG BUG: GMEIOException /Users/levinotik/github/haskell-start/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)`

and I'm not sure how to fix that. Any ideas?

**Comment by rikvdkleij** [comment]
Yeah, that is a very notorious error message :-)

You are probably using ghc-mod version 1.22.*?

**Comment by levinotik** [comment]
hmm, this is weird:

```
➜  ~  ghc-mod --version
ghc-mod version 5.2.1.2 compiled by GHC 7.8.4
```

**Comment by rikvdkleij** [comment]
Sorry, I mean Cabal version  1.22?

**Comment by levinotik** [comment]
Yup

```
➜  ~  cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library
```

**Comment by rikvdkleij** [comment]
ghc-mod does not support 1.22 yet.
See:
https://github.com/kazu-yamamoto/ghc-mod/issues/417

Very long story :-)

Btw, upcoming version of ghc-mod (which I'm testing) should solve that problem.

**Comment by levinotik** [comment]
Could I simply install the version of cabal that does work with ghc-mod?

**Comment by rikvdkleij** [comment]
Yes, version 1.20.x

**Comment by levinotik** [comment]
Sorry to bother you, but I'm new to Haskell tooling. How would I uninstall the current cabal and install 1.20.x?

**Comment by rikvdkleij** [comment]
Depends, which OS are you using? I'm using Ubuntu so I can use apt-get to install and uninstall Cabal.

https://github.com/bitemyapp/learnhaskell contains a lot of information.

**Comment by levinotik** [comment]
Yea, I've been though that github page. I have everything installed via ghcformacosx

**Comment by rikvdkleij** [comment]
Sorry, I do not know for ghcformacosx. Latest version contains 1.22 binary. You should get 1.20 binary from somewhere. Maybe download an older version and extract the Cabal binary. GHC 7.8.3-r1 contains Cabal 1.20

**Comment by levinotik** [comment]
Found this https://github.com/ghcformacosx/ghc-dot-app/releases/tag/v7.8.3-r1, thank you!

**Comment by rikvdkleij** [comment]
@levinotik Improved Readme.
