### ISSUE TITLE
Line breaks in HLint intentions

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#151]
![screenshot](https://cloud.githubusercontent.com/assets/6234553/23222702/b761c7f2-f963-11e6-849b-e0c6d6f1932e.gif)

**Comment by rikvdkleij** [comment]
Those line breaks are included in hlint suggestions. I will remove them. After applying you can use hindent to format code.

**Comment by zjhmale** [comment]
Thanks Rik, I just planned to fix it this weekend 😄

**Comment by rikvdkleij** [comment]
This solution does not work if original expression contains line breaks. For example in case expression.

**Comment by zjhmale** [comment]
Yeah, it will replace all the `\n` with `\s` and the case expression wil be align into single line 😅

**Comment by zjhmale** [comment]
But we do reformat it using hident after hlint intentions right?

**Comment by rikvdkleij** [comment]
> But we do reformat it using hident after hlint intentions right?

Yes

**Comment by zjhmale** [comment]
Wired, I will check this out later 😅

**Comment by rikvdkleij** [comment]
> Yeah, it will replace all the \n with \s and the case expression wil be align into single line :sweat_smile:

This does not work if you multiple expressions within case.

**Comment by zjhmale** [comment]
Yeah, right, it seems we got a dilemma here. Can you put some code snippet here, Rik?
>This does not work if you have multiple expressions within case.

**Comment by rikvdkleij** [comment]
Redundant do:
```
foo x = do
  case x of
    Just y -> y
    Nothing -> 0
```

**Comment by zjhmale** [comment]
One idea on my mind is that we only take care the case that the original code which need to be replaced is single line, and if the hlint intention is multiple line, then we need to replace `\n` as `\s+`, it just a trade off here 😅

**Comment by rikvdkleij** [comment]
>  then we need to replace \n as \s+, it just a trade off here

Let's not replace line breaks if hlint intention is multiple line

**Comment by zjhmale** [comment]
OK, I will do that 😄  just let hindent to handle the line break right?
>Let's not replace line breaks if hlint intention is multiple line

**Comment by rikvdkleij** [comment]
Yes, let's give it a try, also with code of original issue :smile:

**Comment by zjhmale** [comment]
Sure 😄

**Comment by rikvdkleij** [comment]
Hmm. better solution is: only remove line breaks if original code is one line and intention is multiple

But I still do not see solid solution. Could you try solution which never removes line breaks and only apply hindent's formatting?

**Comment by zjhmale** [comment]
Yeah, I'm working on it and will give feedback to you ASAP 😄

**Comment by zjhmale** [comment]
@rikvdkleij Actually, hindent will not take care of this case, so maybe we should use the `better solution` first.

**Comment by zjhmale** [comment]
Seems like we got the same trade off here 😄 
>One idea on my mind is that we only take care the case that the original code which need to be replaced is single line, and if the hlint intention is multiple line, then we need to replace \n as \s+, it just a trade off here 😅

**Comment by rikvdkleij** [comment]
So only the `better solution` left? :smile:

**Comment by zjhmale** [comment]
Yeah, the `better solution` seems to be the best approach at the moment 😅
