### ISSUE TITLE
"Go to declaration" either goes to a wrong place, or searches for usages instead

### ISSUE THREAD

**Issue by KarolS** [rikvdkleij/intellij-haskell#16]
Note: Both Ctrl-B and Ctrl-LClick are bound to "Go to declaration" action, and nothing else. Both those shortcuts result in the same behaviour, as does picking "Go to declaration" from the popup menu.

Source file and project in question: https://github.com/KarolS/PlaylistSubscriber/blob/master/src/PlaylistSubscriber/PersistentSet.hs

		readPersistentSet :: PersistentSet a -> IO [a]
		readPersistentSet s = do
			let p = persistentSetPath s
			exists <- doesFileExist p
			if exists
			then do
				contents <- readFile p
				return $ map (persistentSetDeserialization s) $ filter (/="") $ lines contents
			else return []

In the above function, if I ctrl-click on `IO`, Intellij starts searching for usages of `IO` instead. The same with `lines`, `readFile`, and many others. A small popup "Show usages" shows when I'm holding down Ctrl and hovering mouse over the identifier.

If I ctrl-click on `persistentSetPath`, `persistentSetDeserialization`, `contents`, `PersistentSet`, then it behaves correctly and jumps to the declaration.

If I ctrl-click on the first `return`, it jumps to the second `return`.

If I ctrl-click on any usage of  `PersistentSet` in `Main.hs`, then it works correctly, but all cross-project jumps don't.

----

Ubuntu 14.04, Intellij-Haskell 0.81, Intellij IDEA 14.1.1, Cabal 1.20.0.2, GHC 7.6.3, ghc-mod 4.1.3

**Comment by rikvdkleij** [comment]
@KarolS Thanks for taking a look to problem. To see the problem use IntelliJ 14.0.3 and use ctrl-click.  Go to declaration should not do Find usages but show popup with all declarations which ghc-mod returns.

**Comment by rikvdkleij** [comment]
@KarolS 
> In the above function, if I ctrl-click on IO, Intellij starts searching for usages of IO instead. 

So that is wrong behavior. It should show popup with type declaration of IO and type class instances of IO. If you use IntelliJ 14.0,3 you can see correct behavior.

**Comment by rikvdkleij** [comment]
@KarolS 
It is fixed in 14.1.2 EAP, see:
https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP
