### ISSUE TITLE
Support data kinds

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#164]
With the `DataKinds` extension enabled, this shouldn't be reported as a compile error:

![screenshot from 2017-03-23 20-56-50](https://cloud.githubusercontent.com/assets/399718/24276214/5e63f24c-100b-11e7-8cba-0ee913d72c46.png)

**Comment by zjhmale** [comment]
Cool! We need to support dependent type to some degree 😄

**Comment by rikvdkleij** [comment]
@chris-martin Thanks for reporting. It'salready fixed in my local repo. I will try to release new version soon.

**Comment by rikvdkleij** [comment]
Should be fixed in beta7.

**Comment by chris-martin** [comment]
Confirmed, lovely.
