### ISSUE TITLE
Haskell Language Server Protocol

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#165]
Since the external part is relatively sophisticated to some degree, I think we can extract those part to a standalone language server protocol in order to integrate with other text editors e.g. VSCode.

**Comment by ChShersh** [comment]
Some work on _haskell language server_ is already done here: https://github.com/alanz/haskell-lsp
Maybe consider reusing it.

**Comment by zjhmale** [comment]
@ChShersh Thanks, I walked through `haskell-lsp` months ago, but it seems still in progress and not mature enough.

**Comment by rikvdkleij** [comment]
I'm investigating to replace Intero by hsdev because hsdev is a better fit for IntelliJ plugin.

**Comment by ArturGajowy** [comment]
Hi @rikvdkleij! Lots of stuff happened since the closing of this issue - would it make sense to integrate with HLS nowadays?
