### ISSUE TITLE
Non-obvious dependency on libtinfo-dev

### ISSUE THREAD

**Issue by androidfred** [rikvdkleij/intellij-haskell#168]
Last time I tried to set up the plugin, it appeared to install fine but didn't work. 

After some digging I realized intero requires libtinfo-dev in order to be able to install properly. I'm on Ubuntu 16.04.2, so running `sudo apt-get install libtinfo-dev` fixed the problem. 

As it's likely others will have the same problem, it could be worth mentioning the dependency and how to install it in the instructions.

**Comment by zjhmale** [comment]
Thanks for the reporting 😄

**Comment by rikvdkleij** [comment]
Thanks for reporting. I have added your remark to README.

**Comment by androidfred** [comment]
@zjhmale @rikvdkleij Thank you for the awesome plugin and your continued work on it.
