### ISSUE TITLE
Show type on mouse hover

### ISSUE THREAD

**Issue by xgrommx** [rikvdkleij/intellij-haskell#169]
How can I do it? Now I need to press Alt+Command+P but this isn't comfortable.

**Comment by zjhmale** [comment]
I will tackle with this.

**Comment by rikvdkleij** [comment]
You can also change you key mapping, on Linux I have `Alt`+`=` mapped to type info.

It's `Alt`+`Command`+`P` on OSX because it's defined in this way in IntelliJ Scala plugin.

**Comment by TsumiNa** [comment]
Also want this! and if possible a colorized type info is welcomed 😄 .

**Comment by tomlanning** [comment]
Also consider this a great addition.

**Comment by rikvdkleij** [comment]
FYI, type info of the identifier under the caret is shown in the status bar.

**Comment by tomlanning** [comment]
Most of the time type and documentation information simply doesn't display anything.  There are rare instances when I request type or documentation and it works.  Any idea on what is happening?  I have a very simple stack-based project (stack 1.6.3, ghc 8.2.2, resolver lts-10.2, IntelliJ Idea CE 2017.3.2).

**Comment by rikvdkleij** [comment]
@tomlanning Did you read the README? Documentation only works when Hoogle database is generated. Type info should always work. You can enable the `Event log` to check if there are errors.

**Comment by rikvdkleij** [comment]
I will implement this feature: (type) info will be shown when mouse pointer hovers over identifier and Ctrl/Cmd key is hold. In case identifier is e.g. `Typeclass`, info will be shown.

**Comment by tomlanning** [comment]
@rikvdkleij, I followed the README exactly several times and always generate the Hoogle database.  ;-)  I enabled the `Event Log` and did see generated type info there but when I turned off the `Event Log` the type information was not displayed in the status bar.  `Quick Documentation` does not work.  For example selecting `pack` or the complete `Text.pack`, the dialog displays `No documentation because this is not Haskell identifier: pack`.  It does show the correct module name and version along with `Documentation pack = upstream . S.map safe.` on the title line.  The  project builds fine, introduced errors are properly presented, and the formatting commands seem to work as well.

**Comment by rikvdkleij** [comment]
About the documentation. Not every identifier has documentation and you do not have to select text.

About the type info. If you put your cursor on a identifier which has a type, does the type show up when you use the shortcut for getting the type? (the shortcut depends on OS, `Alt+=` or `Alt+Command+P`)

**Comment by tomlanning** [comment]
@rikvdkleij, I think we are getting close to the problem(s)!  Both `Quick Documentation` and `Show Type` work properly if I do not select the identifier and only use the keyboard shortcuts.

`Quick Documentation` does not work if I select the identifier and then use either the keyboard shortcuts or the menu.  (Sometimes the first few repeated requests using the same selected identifier will work but then it eventually fails and then all following keyboard or menu requests for selected identifiers fail.)

`Show Type` seems to always work if I do not select the identifier.  However, if I select the identifier the keyboard shortcut works but the menu item does not.  Also, a tooltip with the type information is displayed if I use the keyboard shortcut along with the text appearing in the status bar at the bottom of the display.  However, only the status bar text is displayed if I use the menu.  (I suspect this is how it is intended to work).

Thanks for the useful plugin and all the timely help.

**Comment by rikvdkleij** [comment]
> Quick Documentation does not work if I select the identifier and then use either the keyboard shortcuts or the menu. 

I can not reproduce this problem. Even when I select the identifier the documentation works. I only see a problem when I do not select exactly the identifier. So for example, I select an extra space.

>  (I suspect this is how it is intended to work).

Yes, that's right.

Btw, you can also select an expression and ask for type info.

Which `IDE Boot JDK` do you use? It looks like you do not use the bundled Open JDK. You can switch from Boot JDK inside IntelliJ. For example with `Cmd+Shift+A` and then type boot.

**Comment by tomlanning** [comment]
I apologize, I hate it when problems are not easily reproducible. Here is my configuration ...

`IntelliJ` IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2`

**Comment by rikvdkleij** [comment]
> Show Type seems to always work if I do not select the identifier. However, if I select the identifier the keyboard shortcut works but the menu item does not

I can reproduce this problem, even with the Scala plugin, looks like an IntelliJ bug. Sometimes it works, sometimes not.... Even the keyboard shortcut does sometimes not work when an expression is selected :-(

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
