### ISSUE TITLE
IntelliJ-Haskell causes editor problem in Scala files

### ISSUE THREAD

**Issue by jeremyrsmith** [rikvdkleij/intellij-haskell#170]
I filed this JetBrains issue: https://youtrack.jetbrains.com/issue/SCL-11749

After filing the issue, I found that the problem goes away when the IntelliJ-Haskell plugin is disabled. I've recommended closing the JetBrains issue, and I'm instead opening an issue here.

The problem:

> When I type an opening parenthesis (or square bracket or curly brace) *[edit: in a Scala file]* and the auto-complete pop-up is shown before I type the matching paren, the closing paren I type does not replace the automatically inserted closing paren, leading to having an extra closing paren that I must then delete.
>
> Attached is a GIF animation which demonstrates the issue (since it's difficult to explain)

![close-paren-issue-demo](https://cloud.githubusercontent.com/assets/864869/24726101/0de2214a-1a06-11e7-999b-b5bdae0352c6.gif)

**Comment by rikvdkleij** [comment]
Thanks for reporting. I could reproduce your issue and it's fixed!

Main problem was that there was not check if file is Haskell file in completion char filter.

**Comment by jeremyrsmith** [comment]
Thanks for jumping on it! Looking forward to the next release.

**Comment by rikvdkleij** [comment]
Should be fixed in beta7.
