### ISSUE TITLE
Renaming a file messes up the module name

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#171]
If I have a module named `Foo.Bar` and I rename the file from `Bar.hs` to `Baz.hs`, the module name changes to `Baz` (when it should change to `Foo.Baz`).

I believe this was introduced in beta 1.0.0-beta7 (before, if I recall, renaming a file didn't perform any module name refactoring at all).

**Comment by rikvdkleij** [comment]
It was already an issue. See PR#73 and it's history.

Of course I want to fix this.

**Comment by rikvdkleij** [comment]
Should be fixed in beta11
