### ISSUE TITLE
Go-to-declaration doesn't work with qualified imports

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#174]
It seems to work with everything else, but not qualified identifiers.

![screenshot from 2017-04-19 14-12-26](https://cloud.githubusercontent.com/assets/399718/25195431/9a01ee70-250b-11e7-8b58-1f79354758a0.png)

IntelliJ Community 2017.1.1, IntelliJ-Haskell 1.0.0-beta7, Stack 1.4.0.

**Comment by rikvdkleij** [comment]
Does it never work for qualified identifiers? 

Do you get warning in status bar that no source code is found and you have to download it?

Do you have some example code/project so I can try to reproduce your issue?

**Comment by chris-martin** [comment]
Now that I have logging enabled, I see this when I press Ctrl+B

![screenshot from 2017-04-19 15-06-49](https://cloud.githubusercontent.com/assets/399718/25197405/eec14784-2511-11e7-8ce0-cd8b55d134ae.png)

and a lot of output in the event log (truncated because I didn't wait for it it finish):

https://gist.github.com/chris-martin/137f4f2f5ee46f5b24aee5cb441c8e6e

**Comment by rikvdkleij** [comment]
I see, this is Intero bug:
https://github.com/commercialhaskell/intero/issues/312

Probably if you change `Set` to for example `Foo`, it wil work.

**Comment by chris-martin** [comment]
Sorry, I think I guessed too soon. It isn't just qualified identifiers, and not all qualified identifiers. Unqualified imports of `toList` and `filter` from `Foundation` don't work, and qualified identifiers that are references to modules within my own project do seem to work.

Importing `Data.Set` as `Foo` doesn't seem to help.

I can jump to `fromList` if I import it from `Data.Set` unqualified.

**Comment by rikvdkleij** [comment]
It looks like Stack repl does not see any dependency. From Event log of other issue I see that no external module is visible....

**Comment by rikvdkleij** [comment]
It looks like you have to simplify your project files (cabal, stack) to see what is going on.

Can you build your project with stack?

**Comment by chris-martin** [comment]
Looks like I'll have to build you some minimal examples when I find some time.

**Comment by rikvdkleij** [comment]
Looking forward to solve your issues.

**Comment by rikvdkleij** [comment]
I think I solved some of your issues.  I will release beta-8 soon.

**Comment by rikvdkleij** [comment]
Should be fixed in beta8.

**Comment by chris-martin** [comment]
Yes, this is working *quite well* nowadays :smiley:
