### ISSUE TITLE
Stylish-haskell not running

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#175]
I have a `.stylish-haskell.yaml` set up to sort imports. So for example, when I run stylish-haskell manually, this

```haskell
import Data.List (zip)
import Control.Lens
import Data.Map (Map)
import Data.Sequence (Seq)
import Data.Set (Set)
import Data.Text (Text)
```

would change to this

```haskell
import Control.Lens
import Data.List (zip)
import Data.Map (Map)
import Data.Sequence (Seq)
import Data.Set (Set)
import Data.Text (Text)
```

When I run Ctrl+alt+L ("Reformat Code"), I get this popup but nothing changes:

![screenshot from 2017-04-19 14-25-46](https://cloud.githubusercontent.com/assets/399718/25195735/8a269248-250c-11e7-933d-c9cfc8f29995.png)

Similarly, when I run Ctrl+alt+O ("Optimize imports"), I get a message, but nothing else happens:

![screenshot from 2017-04-19 14-26-12](https://cloud.githubusercontent.com/assets/399718/25195765/a08c0c84-250c-11e7-8d4e-d8537c64ef57.png)

IntelliJ Community 2017.1.1, IntelliJ-Haskell 1.0.0-beta7, Stack 1.4.0.

**Comment by rikvdkleij** [comment]
You have to do `Ctrl+Alt+Semicolon`. I can not "override" the default shortcut for code formatting.

Btw, it will first use hindent and then stylish haskell. See other shortcuts for doing them separately in menu `Code`/`Haskell`.

**Comment by chris-martin** [comment]
Ah thanks. That's unfortunate. How would you feel about a section in the readme that helps feature discovery - with a list of the default key bindings, and mentioning the `Code`/`Haskell` menu group there?

**Comment by rikvdkleij** [comment]
Yes, that would be nice but they depend on OS.

Eventually a (new) website would be the best solution but that takes some time....

**Comment by rikvdkleij** [comment]
Btw, formatting selected code can only be done by hindent.

**Comment by chris-martin** [comment]
Fortunately the `Code`/`Haskell` menu lists those shortcuts. That exists on all OSes, right?

**Comment by rikvdkleij** [comment]
Yes, that's right.

All shortcuts are defined in https://github.com/rikvdkleij/intellij-haskell/blob/1f7a0be72404da07925dd125524d94077a1a0ea4/intellij-haskell/META-INF/plugin.xml

**Comment by rikvdkleij** [comment]
@chris-martin  Can this issue be closed?

**Comment by chris-martin** [comment]
:+1:
