### ISSUE TITLE
Trailing spaces aren't stripped on save

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#177]
Even though the option is set:
![](https://sc-cdn.scaleengine.net/i/cfb4da923dfd961d44f0dc011d76c3bd.png)

its not in effect:
![save](https://cloud.githubusercontent.com/assets/1009751/25268970/0bf66ff4-267b-11e7-9564-7f0bbff83cd5.gif)

**Comment by rikvdkleij** [comment]
Should be fixed in beta8.
