### ISSUE TITLE
Enabling an extension in one package affects others

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#180]
In a multi-package project, it seems that when I enable `OverloadedStrings` in the cabal file for one package, the IntelliJ plugin thinks it's enabled for all packages.

[This example repo](https://github.com/chris-martin/intellij-haskell-OverloadedStrings-example) builds with `stack build`, but IntelliJ reports an error:

![screenshot from 2017-04-24 16-10-30](https://cloud.githubusercontent.com/assets/399718/25356645/f4a73500-2908-11e7-843e-cc605cbc73be.png)

[The file in the screenshot](https://github.com/chris-martin/intellij-haskell-OverloadedStrings-example/blob/master/example/src/Lib.hs) requires `OverloadedStrings` to be disabled to compile. That extension [is not enabled](https://github.com/chris-martin/intellij-haskell-OverloadedStrings-example/blob/master/example/example.cabal), but it *is* enabled for [a different package in the same project](https://github.com/chris-martin/intellij-haskell-OverloadedStrings-example/blob/master/example2/example2.cabal#L11).

**Comment by rikvdkleij** [comment]
Thanks for reporting. This has the same cause as #129. The repl which runs in the background is loaded without target. This can cause all kind of conflicts.

**Comment by rikvdkleij** [comment]
So multi package projects have this issue and also projects which have cabal file which contains multiple exe targets.

**Comment by rikvdkleij** [comment]
Thanks for your example project. I will use it when I will implement support for multi-package projects.

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
