### ISSUE TITLE
Join lines changes comment style from line to block

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#181]
**Actual behavior** 
when pressing Join Lines combo (Ctrl + Shift + J):
![joinlines](https://cloud.githubusercontent.com/assets/1009751/25564444/ba7bd1e2-2db3-11e7-8fee-efae59d39356.gif)

**Expected behavior**
Lines are joined as a single line-comment
```haskell
-- takes one input and makes a tuple of the results of two applications of z' 
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! It's fixed in next release.

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
