### ISSUE TITLE
Comment chars aren't removed when joining two line-comments

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#182]
**Actual behavior**
When joining lines (Ctrl + Shift + J):
![joincomments](https://cloud.githubusercontent.com/assets/1009751/25564478/536e2026-2db4-11e7-8928-80da9e783981.gif)

**Expected behavior**
Lines are joined without comment symbols in the middle

**Comment by rikvdkleij** [comment]
Should be solved otherwise reopen.
