### ISSUE TITLE
Breaks the rename refactor for Groovy classes, traits and interfaces

### ISSUE THREAD

**Issue by Mahoney** [rikvdkleij/intellij-haskell#183]
With the IntelliJ-Haskell (1.0.0-beta8) plugin installed I am unable to use the rename refactor on Groovy classes, traits and interfaces. Shift F6 does nothing and the Refactor -> Rename... option is greyed out in both the top menu and the context menu.

Java classes and interfaces can still be renamed.

This is in a gradle based groovy project, no Haskell involved.

Reference: https://youtrack.jetbrains.com/issue/IDEA-172434

**Comment by rikvdkleij** [comment]
Thanks for reporting. I will fix it.

**Comment by rikvdkleij** [comment]
Should be fixed in beta9.
