### ISSUE TITLE
should do less work when Power Save Mode is enabled

### ISSUE THREAD

**Issue by simonmichael** [rikvdkleij/intellij-haskell#186]
On first loading a project (hledger), the plugin is maxing out all cpus for almost an hour building haddocks of every dependency. With Power Save Mode enabled, at least, it should skip this.

**Comment by rikvdkleij** [comment]
Thanks for reporting.

I consider to remove the automatically building of the haddocks from the startup of the plugin. For users which want to use hoogle features I will make a separate action.

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
