### ISSUE TITLE
Hlint --json unrecognised flag

### ISSUE THREAD

**Issue by ArekCzarnik** [rikvdkleij/intellij-haskell#190]
i have  hlint (HLint v1.9.41, (C) Neil Mitchell 2006-2016) current running, but in IntelliJ 2017 +  intellij-haskell plugin something wrong with parameter --json:
`Something went wrong while calling hlint. Error: ghc: unrecognised flag: --
			did you mean one of:
			  -F
			  -v
			  -j
			unrecognised flag: --json
			Usage: For basic information, try the --help' option `

can i fix it ? or find out which hlint is called?

**Comment by rikvdkleij** [comment]
Hlint is build by IntelliJ when project is started. In this way hlint is compatible with project`s Stackage/GHC version. Can you enable Haskell event log? Maybe this gives info about what is going on. 

So IntelliJ does not take globally installed hlint but one in project, `stack exec -- hlint --numeric-version`

**Comment by ArekCzarnik** [comment]
I create the log, thanks for your help.

https://gist.github.com/ArekCzarnik/fd2eb0e5dc440191e0125449b244f4f3
stack exec -- hlint --numeric-version = 1.9.41

**Comment by vrom911** [comment]
@ArekCzarnik  @rikvdkleij , so what was the mistake? I also have this issue now.

**Comment by rikvdkleij** [comment]
I think the mistake was that not Stack binary was set in Haskell Tool Stack SDK but GHC binary.

**Comment by vrom911** [comment]
@rikvdkleij  You're right. The issue is fixed now, thanks!

**Comment by rikvdkleij** [comment]
Great!

In next version of plugin this issue will be prevented because validation while creating SDK is improved.
