### ISSUE TITLE
Cross-module usages not found

### ISSUE THREAD

**Issue by SamuraiJack** [rikvdkleij/intellij-haskell#192]
When I ctrl+click on some function the plugin correctly jumps to its definition. Then, when I ctrl+click on function definition it lists all the usages of that function, but only within the module it is declared in.

It can not find/show the usages of the (exported) function in other modules.

I observe the following errors in the haskell events log:
```
2:50 PM	[project-stack-repl] command: :browse! Ariadne.Identifier

2:50 PM	[project-stack-repl] stdOut: ^IntellijHaskell^

2:50 PM	[project-stack-repl] errOut: 
					<no location info>: error:
					Could not find module ‘Ariadne.Identifier’
					It is not a module in the current program, or in any known package.
```
In the same time "Ariadne.Identifier" is defined as the exposed module in my cabal file:
```
library
  hs-source-dirs:      shared
  exposed-modules:
    Ariadne
    Ariadne.Util
    Ariadne.Identifier
```

**Comment by rikvdkleij** [comment]
So issue in #191 is solved?

Apparently `Ariadne.Identifier` module is not loaded (yet).

Does this issue still happen if you go that  `Ariadne.Identifier` module and then back?

**Comment by SamuraiJack** [comment]
No, #191 is not solved - the ghcjs code can be "cross-compiled" using normal ghc, thats what I'm using now.

Indeed, after opening the `Ariadne.Identifier` in the editor tab, the usages in that module can be found. So one need to keep all project files opened, in order to have cross-modules references. A bit inconvenient, but still acceptable..

**Comment by SamuraiJack** [comment]
Seems there are situations that even with 2 files opened (one with definition and one with usage) the cross-reference still can not be found. Probably some race condition, or order of the opening.

**Comment by SamuraiJack** [comment]
Re-opening the file with usage fixes the above-mentioned problem.

**Comment by rikvdkleij** [comment]
Next version of plugin will be more solid....

**Comment by SamuraiJack** [comment]
Looking forward!

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9

**Comment by SamuraiJack** [comment]
Fix confirmed for beta 10. Thanks!
