### ISSUE TITLE
"not a valid Stack binary"

### ISSUE THREAD

**Issue by GinBaby** [rikvdkleij/intellij-haskell#193]
Hi there. I had some trouble today trying to import a Haskell (Stack) project. Stack didn't show up in the Project SDK list, and searching for it returned an error that it's not a valid Stack binary (see screenshot). 

There is a workaround, and I created [a file like this](https://gist.github.com/chris-martin/cb0205441ca4c08a129ee98cc60e0f58), restarted IntelliJ and all seems to be working correctly now. 

In case it's helpful:
```
    [julie@dolores:~/joy]$ which stack
    /home/julie/.nix-profile/bin/stack

    [julie@dolores:~/joy]$ stack --version | head -n 1
    Version 1.2.0 x86_64
```
![screenshot from 2017-07-14 17-18-05](https://user-images.githubusercontent.com/8098270/28233334-5a8805ca-68f6-11e7-833b-8b4d36a40ed4.png)

Thank you :)

**Comment by rikvdkleij** [comment]
Thanks for reporting. 

It looks like this issue is related to NixOS,

Is `/home/julie/.nix-profile/bin/stack` a (symbolic) link?

Btw, I recommend to upgrade to Stack binary.

**Comment by chris-martin** [comment]
I'm also running NixOS and I have `/home/chris/.nix-profile/bin/stack` (yes, it's a symlink) as my Stack path, and it works for me. Mine is Stack 1.4.0 though.

**Comment by rikvdkleij** [comment]
Okay, validation fails because it's a symlink. I will fix that.

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
