### ISSUE TITLE
Intellij Idea 2017.2 -> No "Haskell" submenu in the "Tools" menu

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#194]
Just upgraded Idea to 2017.2 and I can't "Restart Haskell Stack REPLs" because the whole sub-menu isn't present. Placing the action as a toolbar button doesn't help - button isn't visible.

**Comment by rikvdkleij** [comment]
Looks like a IntelliJ bug. Yesterday they released 2017.2.1 EAP. Maybe upgrading helps.

**Comment by Unisay** [comment]
After creating project from scratch it worked in both 2017.2 and 2017.2.1 EAP. I suspect that it has been my bad caused by accidental removal of the *.iml file. Closing the issue.
