### ISSUE TITLE
Operator named (-->) is being parsed as a comment

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#195]
As you can see in the screenshot, everything after `-->` is shown in the blue color as if the `--` were the start of an inline comment.

![Screenshot](https://user-images.githubusercontent.com/399718/28687484-84a02910-72dc-11e7-8269-8b4571c806a5.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting! It's fixed in master.

**Comment by rikvdkleij** [comment]
Should be fixed in beta 9
