### ISSUE TITLE
Fmt library operators are not parsed properly

### ISSUE THREAD

**Issue by vrom911** [rikvdkleij/intellij-haskell#196]
After using [Fmt](https://hackage.haskell.org/package/fmt) package in projects parser fails and makes error highlighting. And  warnings and hlint are not highlighted in the code below lines with the first appearance of operators from this package.
I created repository with the example usage [here](https://github.com/vrom911/FmtExample).
Also screenshot of current error is attached
![screenshot from 2017-07-27 23-58-30](https://user-images.githubusercontent.com/8126674/28692023-91cc87dc-7327-11e7-9cd8-50e796567e03.png)

**Comment by neongreen** [comment]
About HLint: this is a known problem. HLint enables `-XMagicHash` by default, which interferes with `#|`. @vrom911 if Intellij allows configuring HLint, passing the `-XNoMagicHash` parameter to it should fix the problem.

**Comment by rikvdkleij** [comment]
@vrom911 Thanks for reporting and example project.

@neongreen Thanks for your help.

I will add input field to `Other settiings > Haskell` to set arguments which will be passed to Hlint.

**Comment by rikvdkleij** [comment]
Sorry for the delay but it's now fixed in master. I hope to release new version of plugin soon.

**Comment by rikvdkleij** [comment]
It's fixed in beta12.
