### ISSUE TITLE
Can't change a file's extension from .hs

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#198]
I can't seen to change the extension of a Haskell file. For example, I wanted to rename a file from `Foo.hs` to `Foo.hsc`.
![screenshot from 2017-08-06 22-40-34](https://user-images.githubusercontent.com/399718/29010316-5b2461d6-7af8-11e7-990a-e4b52344a04d.png)

When I click "Refactor", the popup closes but nothing happens.

**Comment by rikvdkleij** [comment]
Thanks for reporting. 

This refactor will also change it's module declaration `module Foo where`. It goes wrong because the plugin does not support hsc files. I will have to take this case into account.

**Comment by rikvdkleij** [comment]
It's fixed in master besides other issues with renaming module names.

**Comment by rikvdkleij** [comment]
Should be fixed in beta11
