### ISSUE TITLE
Parameter Info or persistent hints of some kind

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#199]
I'm finding that I want something when filling out long parameter lists/constructors. Right now I'm jumping between documentation/ghci/show type and code multiple times to do this. Is there currently a better way?

Ideally, I'd like IntelliJ's `Parameter Info` command to be implemented for Haskell, but I realize this would be quite difficult to do. I played with it a bit anyway using `ParameterInfoHandlerWithTabActionSupport` just to see what it would entail, and yes, it's definitely not trivial, especially with how Haskell syntax works (infix operators, pointfree notation, etc). A very hacky solution seems doable, but I don't know if there's value in a Parameter Info command that is wildly inaccurate in many situations...

So I gave up on that for now, and just tried the simple solution of having "Show Type Info" not auto-hide as you're typing. This addresses the original problem I was having with long parameter lists to some extent. I don't need to switch away from my main editor pane as much.

But I'd like to get your thoughts on this. Or if you have any other ideas that I'm not considering?

If you're okay with the idea though, I don't mind creating a PR for it. Though if I do that, I should probably make this configurable (or a separate IntelliJ command rather than modifying the default "Show Type").

**Comment by rikvdkleij** [comment]
I understand your issue. Using the Type info is the best solution for now. Problem is that Type info is not present anymore when you are typing the function arguments. You have to give back to the function name and ask for the Type info.

I do not understand your solution completely. What do you mean by not-autohide. Do you want to show Type info in the status bar? But what if you are typing the function arguments?

Do you use the Type info shortcut?

**Comment by solicode** [comment]
> Problem is that Type info is not present anymore when you are typing the function arguments. You have to give back to the function name and ask for the Type info.

Yes, this is what I'm referring to. My proposed change is that Type Info would no longer disappear while you're typing. The hint bubble stays on the screen. You have to hit ESC for the hint to disappear.

I have this working locally. But like I said, maybe it's not a good idea to make it the default behavior, so I would have to make it a config option or a separate command so that you can assign it to a different shortcut.

**Comment by rikvdkleij** [comment]
Most simple solution is to create separate command/action.

Or implement it as parameter info. If the caret is not above function, find first previous sibling which is a function. Since beta9 also not compiling code should show Type info (but it is not 100% guaranteed for every function, for imported functions it should work) .

**Comment by rikvdkleij** [comment]
Shortcut `ctrl alt i` is already in use for Goto Instance Declarations. I will change the default shortcut for Sticky Type Info to `ctrl alt shift EQUALS`. What do you prefer to be shortcut on Max OSX?

**Comment by solicode** [comment]
Sorry, I missed that.

Hmm, I might not be a good reference because I change all my hotkeys anyway. 😛 I changed my shortcut for it to `cmd+i` (I tend to avoid 2+ modifier keys for the stuff I use frequently).

I'm fine with whatever you want to set the default to. I initially considered 3 modifier keys + `P`, but I wasn't sure about it. `ctrl alt shift EQUALS` seems fine as a default.

**Comment by rikvdkleij** [comment]
Okay. I suggested `ctrl alt shift EQUALS` as default because it's close to the default shortcut for Type Info.

But I think you are right. It's not practical to have large number of keys in actions which are used frequently.

`ctrl alt g` is still free. I will use this one for default and Mac OSX.

**Comment by rikvdkleij** [comment]
It's released in beta11.
