### ISSUE TITLE
ghc-modi integration

### ISSUE THREAD

**Issue by KasperJanssens** [rikvdkleij/intellij-haskell#2]
I think there's an issue with the way you interact with ghc-modi. For example, if I create a module, called A, and I unfortunately put my cursor in the first line, the same line as mentions 
<code>
module A where
</code>
you seem to call ghc-modi with the instruction
<code>
info A.hs A
</code>
Ghc-modi will then answer 'Cannot find info' (tried this directly on ghc-modi, command line) to inform the user that it didn't find this information. However, the plugin interprets this 'cannot find info' as if there's something wrong with ghc-modi, it seems to get interpreted as a Future that timed out and ghc-modi will not be called for 5 seconds. (Error in communication with ghc-modi: Futures timed out after [1 second]. Check if GHC SDK is set and ghc-modi is okay. ghc-modi will not be called for 5 seconds). This makes the plugin not having any type information anymore for the next 5s.

**Comment by SemanticBeeng** [comment]
Getting this for Intellij 14.0.1 and 
$ ghc-mod --version
ghc-mod version 5.4.0.0 compiled by GHC 7.10.3

setup bloodhound project as explained here:
https://www.youtube.com/watch?v=a5PAuXiVGws

Running 
$ ghc-modi 
Warning: ghc-modi is deprecated please use 'ghc-mod legacy-interactive' instead

So, can could the plugin work if ghc-modi does not work from command line?

Thanks in advance
