### ISSUE TITLE
Spaces in file path

### ISSUE THREAD

**Issue by VitorCBSB** [rikvdkleij/intellij-haskell#202]
Apparently having space characters in your file path causes some things to not work correctly, the REPL being one of them. Here's the Event Log for when I tried to import a stack project.

```
12/08/2017
12:58	[global-stack-repl] Stack repl could not be started within 5 seconds

12:58	[project-stack-repl-Test:lib] No result from Stack repl within 5 seconds. Command was: :set prompt "^IntellijHaskell^\n"

12:59	[project-stack-repl-Test:lib] No result from Stack repl within 60 seconds. Command was: :load C:\Users\Vitor Coimbra\Test\src\Lib.hs

12:59	[project-stack-repl-Test:lib] stderr: target `C:\Users\Vitor' is not a module name or a source file

12:59	[global-stack-repl] Can not write to Stack repl. Check if your Stack project environment is working okay

13:01	Hoogle database does not exist. Hoogle database can be created by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database`
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

What do you prefer for fixing? Quote the whole path or escape the spaces? I do not have Windows PC so I can not test the fix.

**Comment by VitorCBSB** [comment]
No problem!

I don't really have a preference for how to fix this, but I'm fairly sure it's not a Windows specific issue. You can try it out on your end:

```
mkdir "dir with spaces" && cd "dir with spaces"
stack new testProject
```

Then try importing this project into IntelliJ, you should run into these errors.

I had a [similar issue](https://github.com/commercialhaskell/stack/issues/1401) with stack itself some time ago and the way they fixed it was using [this quoteFileName function](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Ghci/Script.hs#L93-L95).

**Comment by rikvdkleij** [comment]
Thanks for the pointer. It's fixed in master.

**Comment by VitorCBSB** [comment]
Thanks for quickly taking care of this. :)
