### ISSUE TITLE
Error when an executable name contains a period (.)

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#204]
![screenshot from 2017-08-12 22-48-58](https://user-images.githubusercontent.com/399718/29245684-88a5541e-7fb0-11e7-8df8-4697e3a98ea0.png)

Demo project: https://github.com/chris-martin/intellij-haskell-exe-name-example

IntelliJ-Haskell v1.0.0-beta10

Stack 1.5.0

**Comment by rikvdkleij** [comment]
Sometimes GitHub close issue when I put "Fixed #[number]" in commit message :smile: In most cases not....

Thanks for reporting! It's fixed in master.

**Comment by rikvdkleij** [comment]
Should be fixed in beta11
