### ISSUE TITLE
[beta10] Plugin interferes with normal command line "stack build"

### ISSUE THREAD

**Issue by SamuraiJack** [rikvdkleij/intellij-haskell#205]
If I'm correct, when a project is opened in the IDE, it is built with stack. But it seems, it is built in some different way, not the same as "stack build" on the command line would do.

Then, if you'll try to build it from command line normally with "stack build", stack will not re-use the previous build, but instead will start a new one (starting from "Populating index cache..." etc).

Steps to reproduce:

1) Close the IDE
2) Build the project with "stack build" from command line.
3) Build it again. Notice, that 2nd build was nearly instant, since no files has changed
4) Open the IDE, restart stack repls
5) Go to command line and do "stack build" again
6) Notice, the build has started all over again.
7) Expected is that "stack build" should be instant again, since no files has changed.

**Comment by rikvdkleij** [comment]
Take a look to Haskell Event Log. When project is opened, stack build is called with more arguments because also test and benchmark dependencies have to be build/installed.

Btw, in master I have changed this behavior. First all dependencies are build and the project is build with simple build command.

**Comment by SamuraiJack** [comment]
```
Information:/usr/local/bin/stack build --fast --test --bench --no-run-tests --no-run-benchmarks
```
This looks innocent. But the IDE build process and command line builds are different - seems like each one "erases" the build files from another..

**Comment by rikvdkleij** [comment]
> But the IDE build process and command line builds are different - seems like each one "erases" the build files from another..


Yep, maybe also because of the `--fast` argument.

**Comment by SamuraiJack** [comment]
It is, yes. Were you able to reproduce it?

**Comment by rikvdkleij** [comment]
Well, in master I have changed the way the project is build when project is started.
First:
`stack build --fast --test --bench --no-run-tests --no-run-benchmarks --only-dependencies`
If that build is successful:
 `stack build --fast`

But honestly I do not see the problem. When you want to deploy your application, you have to build in your way. This build is only so Stack REPL/GHCi  can run for every Stack target of your project.

**Comment by SamuraiJack** [comment]
The thing is, the build time in the command line becomes too long. I do want to be able to build the project with regular "stack build" in the command line easily.

There's probably something else, that causes the problem, using "--fast" switch on the command line does not help.

Are you sure the plugin just executes "stack build ..." in the project's root directory? Perhaps it is done as different user? Chroot or something like that?

**Comment by rikvdkleij** [comment]
It is run as from Console. See here
https://github.com/rikvdkleij/intellij-haskell/blob/606c5f496a5f1426bb1e6cf3f0327b0a1e8cd91b/src/main/scala/intellij/haskell/external/component/StackProjectManager.scala#L80
and then
https://github.com/rikvdkleij/intellij-haskell/blob/606c5f496a5f1426bb1e6cf3f0327b0a1e8cd91b/src/main/scala/intellij/haskell/external/execution/StackCommandLine.scala#L61

and
https://github.com/rikvdkleij/intellij-haskell/blob/606c5f496a5f1426bb1e6cf3f0327b0a1e8cd91b/src/main/scala/intellij/haskell/external/execution/StackCommandLine.scala#L65

See also
https://github.com/rikvdkleij/intellij-haskell/blob/606c5f496a5f1426bb1e6cf3f0327b0a1e8cd91b/src/main/scala/intellij/haskell/external/execution/StackCommandLine.scala#L70

**Comment by SamuraiJack** [comment]
Must be something different.. My best guess its different user..

**Comment by rikvdkleij** [comment]
Maybe it help to disable inspection by Hlint. It compiles files.

**Comment by SamuraiJack** [comment]
Nope, didn't help

**Comment by rikvdkleij** [comment]
Maybe the call which checks if Hoogle database is generated:
https://github.com/rikvdkleij/intellij-haskell/blob/5d22e61c2dfa67eda8089c67ef2af188e9d8a0ff/src/main/scala/intellij/haskell/external/component/HoogleComponent.scala#L84

**Comment by SamuraiJack** [comment]
What is its equivalent in the console?

**Comment by rikvdkleij** [comment]
It's `stack hoogle --no-setup`

**Comment by rikvdkleij** [comment]
Is it still a problem in beta11?

**Comment by SamuraiJack** [comment]
Yes, same behavior.

**Comment by rikvdkleij** [comment]
> Steps to reproduce:
Close the IDE
Build the project with "stack build" from command line.
Build it again. Notice, that 2nd build was nearly instant, since no files has changed
Open the IDE, restart stack repls
Go to command line and do "stack build" again
Notice, the build has started all over again.
Expected is that "stack build" should be instant again, since no files has changed.

I can not reproduce your issue following your steps....

**Comment by SamuraiJack** [comment]
Try with this repo: https://github.com/valderman/selda (I'm trying the "selda" package inside it)

**Comment by SamuraiJack** [comment]
You'll need to create the "stack.yaml" file first, with "stack init"

**Comment by rikvdkleij** [comment]
No, also with your project, I can not reproduce your issue. I'm running the stack commands from within the project root directory, just like the plugin.

**Comment by SamuraiJack** [comment]
Hm.. Weird. I definitely see "Populated index cache" (though dependencies does not get re-compiled anymore). Some files are recompiled though.

**Comment by rikvdkleij** [comment]
After opening the project and restarting the REPLs, `stack build` is immediately finished.
