### ISSUE TITLE
Cannot import project with multiple stack files

### ISSUE THREAD

**Issue by iand675** [rikvdkleij/intellij-haskell#210]
I have a project with multiple stack files:

- One stack.yaml file in the root directory that is shared by most of the packages
- A few packages in subdirectories that have their own stack.yaml files

When I try to import packages that have their own stack.yaml files as modules, they are ignored & nothing happens.

**Comment by rikvdkleij** [comment]
Only projects which have one stack file and multiple cabal files (Cabal file per directory) are supported. Like for example the Servant project.

So:
- One stack file in the root
- One cabal file in the root and/or one cabal file per subdirectory

**Comment by iand675** [comment]
Right, so I guess I'm making a feature request for supporting modules that need different stack.yaml files. I think a reasonable behavior would be to not just check the top level directory of the project when scanning for stack.yaml files, but to do it recursively and to use the most specific stack.yaml file for a directory (which is pretty much what stack itself does).

**Comment by rikvdkleij** [comment]
I was taking a look to your repo https://github.com/iand675/dd-middleware

In my opinon this repo contains 2 projects, so you have to create IntelliJ project for each subdirectory.

**Comment by rikvdkleij** [comment]
@iand675 Do you agree that each Haskell stack project can only have one stack file? Otherwise, for example, each module could have different GHC version or you could have conflicting dependencies.

**Comment by rikvdkleij** [comment]
@iand675 Any further comments?

**Comment by iand675** [comment]
I would say that working in large monorepos it's not unheard of to have different projects started at different times be on different versions of GHC or things like that. It's quite inconvenient to have to run a separate instance of IntelliJ per project. I can understand if that isn't a priority for you, but it prevents me from using IntelliJ at work presently.

**Comment by rikvdkleij** [comment]
I'm used to run each project in a separate IntelliJ window (also in companies with big repos). I see no problem with that. 
Do you mean by separate instance of IntelliJ, a separate window?

I have to investigate if it is possible to support multiple Stack files in one IntelliJ Haskell project. It's anyway a difficult change....

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
