### ISSUE TITLE
Real-time Hoogle search + Docs

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#213]
I have a few ideas regarding the current `Hoogle For It` feature, but I'd like to hear your thoughts too.

Currently, the results looks like this:

<img width="526" alt="hoogle1" src="https://user-images.githubusercontent.com/7761921/29883015-d7017254-8de9-11e7-85f3-69ecb971bda0.png">

Also, when you choose an item, nothing happens.

I was thinking this could be improved. And as an additional feature, I thought it might be useful to be able to issue new Hoogle search requests from this popup, rather than just filter the already shown results.

What I currently have looks like this (somewhat similar to the `Navigation by Hoogle` feature):

<img width="660" alt="hoogle2" src="https://user-images.githubusercontent.com/7761921/29883030-e1c5a1f6-8de9-11e7-8abe-4ff65671037b.png">

And when you choose an item, it opens up the local docs for that item (I get that link with the `-l` option, e.g. `stack hoogle -- -l "..."`). It's a bit unfortunate that there's no inline browser using IntelliJ (that I'm aware of). For now I'm just opening the link with `BrowserUtil.browse`.

Anyway, is this something you would be interested in? Or if you have additional thoughts/ideas, I'd be happy to hear them.

...I actually just realized quite a bit of this code could probably be shared with the `Navigation by Hoogle` feature. The thing is though, that feature seems to be doing a lot more work than just plain Hoogle search. It takes 1-5 seconds for each letter I type, while the plain search I'm doing is around 100ms. I think that's a big enough difference to warrant it being separate.

**Comment by rikvdkleij** [comment]
Yes, I'm interested in extending this Hoogle feature. Your feature is nice extension to the current feature. What I do not like is that external browser is opened to show the documentation. Is it possible to show documentation in a dialog or maybe even better, a popup/tooltip which refreshes if user navigates to next Hoogle suggestion?

`Navigation by Hoogle` feels "heavy" because for each suggestion it tries to find the location. But after that similar searches will go faster because of caching.

**Comment by solicode** [comment]
I agree that opening an external browser is not ideal. I'd like to stay in the editor window as much as possible. I just don't see any nice IntelliJ solutions for this.

Oh well, I guess I'll have to abandon that idea for now. I still think there's value to being able to view a whole module's documentation all at once as an HTML page (bonus for working without an Internet connection). It's nice for discoverability and getting a quick overview of a module that you're not familiar with (without jumping into the source code).

Maybe that kind of thing isn't even suited for this particular feature. It sort of feels like it could be a different action.

> Is it possible to show documentation in a dialog or maybe even better, a popup/tooltip which refreshes if user navigates to next Hoogle suggestion?

I think that should be possible. I think I have to make 2 Hoogle queries to make that work though (one normal query, and one with the `-i` flag). I don't know if there's currently a way to avoid that.

Anyway, I could try the tooltip + refresh on up/down idea. I could even make it toggleable with that unused checkbox that `ChooseByNamePopup` comes with.

**Comment by rikvdkleij** [comment]
> I think that should be possible. I think I have to make 2 Hoogle queries to make that work though (one normal query, and one with the -i flag). I don't know if there's currently a way to avoid that.

One initial query to get the suggestions and if user navigates to a suggestion, the query with -i flag. All ingredients are already there :smile: 

> Anyway, I could try the tooltip + refresh on up/down idea. I could even make it toggleable with that unused checkbox that ChooseByNamePopup comes with.

Great!

**Comment by rikvdkleij** [comment]
@solicode Do you still want to make a contribution?

**Comment by solicode** [comment]
Unfortunately I haven't been using Haskell lately. I'd like to get back into it, but it likely won't be for a while. When I do though, I'd like to revisit this feature (assuming nobody beats me to it by then).

If you'd like to close it for now, that's fine with me. I can re-open it whenever I return to Haskell.

**Comment by rikvdkleij** [comment]
Ok, then I will close it for now.
