### ISSUE TITLE
Is it possible to enable a feature like an auto-import 

### ISSUE THREAD

**Issue by Miguelme** [rikvdkleij/intellij-haskell#214]
I think it would be nice to have a feature for auto-importing a function from a module when writting the function. Kind of when writing `sort` and then having the option to auto-import the `Data.List` module.

**Comment by rikvdkleij** [comment]
Yes, that's possible to implement. There is already similar feature, if GHC gives errors that something is not in scope, the plugin will already create intention action which shows suggestions. Selecting a suggestion will add the import.

Also GHC itself can suggest function to import, which is also supported as intention action.

**Comment by rikvdkleij** [comment]
So, in other words, it is already there :smile:  But it can be improved. For example, if import of `Data.List(filter)` is already there, it will not extend the list but create new import statement.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
