### ISSUE TITLE
Installing plugin breaks cursive code selection in .clj files

### ISSUE THREAD

**Issue by hairybreeches** [rikvdkleij/intellij-haskell#217]
I use the Cursive plugin to provide Clojure support in Intellij. 

One of the features is that the "expand selection" (I think the default is ctrl+w) function respects s-expressions, so first usage selects contents of inner pair of brackets, next usage includes brackets, next usage includes contents of next pair of brackets, etc etc.

When I installed intellij-haskell, this stopped working for me. ctrl+w did haskell-style "expand selection" - ie to next whitespace break - *even in .clj (clojure) files*. When I uninstalled intellij-haskell, this issue went away.

It looks like (sometimes?) the plugin doesn't respect filenames - it tries to apply haskell-like syntax understanding to all files, regardless of content.

**Comment by rikvdkleij** [comment]
Thanks for reporting! I will fix that.

**Comment by hairybreeches** [comment]
Beautiful, thanks 😄

**Comment by rikvdkleij** [comment]
Should be fixed in beta12.

**Comment by rikvdkleij** [comment]
I see, stupid mistake of me. Will fix it.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
