### ISSUE TITLE
Hoogle database does not exist

### ISSUE THREAD

**Issue by joetoth** [rikvdkleij/intellij-haskell#220]
Navigating to files in my own project seems to work, but when I try to look up documentation I keep getting "Hoogle database does not exist. Hoogle database can be created by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database`"

Clicking Tools`/`Haskell`/`(Re)Build Hoogle database` doesn't seem to do anything. 
From a shell I ran hoogle generate, hoogle data all and using it seems fine.

Any thoughts on what I can try or any other information you need to help me figure this out? Where is it looking for the database? I'm a Haskell n00b =)
Thanks!

IntelliJ Community Edition 2017.2.4
Stack version: 1.1.2
GHC version: The Glorious Glasgow Haskell Compilation System, version 8.0.2
Intero version: Intero 0.1.23
HLint version: HLint v2.0.9, (C) Neil Mitchell 2006-2017
Hoogle version: Hoogle 5.0.13, http://hoogle.haskell.org/
Hindent version: hindent 5.2.3
Stylish-haskell version: stylish-haskell 0.8.1.0

**Comment by rikvdkleij** [comment]
Your Stack version is too old. You will have to update Stack.

**Comment by joetoth** [comment]
That was it. Thanks!
