### ISSUE TITLE
{-# OPTIONS_GHC .... #-} not properly parsed

### ISSUE THREAD

**Issue by martijnbastiaan** [rikvdkleij/intellij-haskell#221]
The plugin fails to parse valid Haskell code, yielding the following error:

```
<q name>, <reserved id>, .......... expected but got '#-}'
```

Full error:

![screenshot from 2017-09-28 09-59-50](https://user-images.githubusercontent.com/5658854/30955564-50f8eaaa-a434-11e7-8dd2-596fbc655be4.png)

Minimum example:

```haskell
{-# OPTIONS_GHC -fplugin GHC.TypeLits.Extra.Solver #-}

main = putStr "Hello, world"
```

Which trips the plugin, even though GHC handles it just fine:

```bash
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ ghc Test.hs
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
```

and:

```bash
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ ghc Test.hs
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
```

**Comment by martijnbastiaan** [comment]
For others experiencing the same issue: as a workaround you can add `ghc-options: -fplugin GHC.TypeLits.Extra.Solver` to your cabal file. For example:

```
library
  hs-source-dirs: [..]
  exposed-modules: [..]
  build-depends: [..]
  default-language: [..]
  ghc-options: -fplugin GHC.TypeLits.Extra.Solver
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! I will fix this issue.

**Comment by martijnbastiaan** [comment]
Thanks for the quick response! Looking forward to it!

**Comment by rikvdkleij** [comment]
It's fixed master. I'm planning to do new release this week.

**Comment by rikvdkleij** [comment]
Should be fixed in beta12.

**Comment by martijnbastiaan** [comment]
I can confirm beta12 fixes this issue. Thanks again!
