### ISSUE TITLE
Wrong run configuration script is generated, if arguments were defined

### ISSUE THREAD

**Issue by progulin** [rikvdkleij/intellij-haskell#222]
Thanks for great plugin!

If we specify **Stack arguments:** into **Run Configuration** dialog, wrong script will be generated.

> Error parsing targets: Directory not found: \<contents of Stack argumets field\>

http://storage3.static.itmages.com/i/17/1001/h_1506877377_1903601_e9d14638a0.png

Possible fix is:
```
override def getState(executor: Executor, environment: ExecutionEnvironment) =
    new HaskellStackStateBase(this, environment, List("exec", executableName))
```
The next script  also is valid
```
stack build --exec "sudoku my.sudoku"
```

But later I noticed that field is called **Stack arguments** (**not Program Arguments**)
Actually, I expected to defined arguments of my program.
I think it would be nice to have both fields -- for stack and for application

Regards,
Pavel.

**Comment by rikvdkleij** [comment]
Thanks for reporting! Just added `Program arguments` to master. I'm planning to do new release this week.

**Comment by rikvdkleij** [comment]
Should be fixed in beta12.
