### ISSUE TITLE
HaskellAnnotator parsing issues with GHC 8.2.1

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#225]
I haven't fully diagnosed this, but I believe it's due to 8.2.1 and the different format warnings/errors are in. For example, here the type annotation intention is adding an extra `|` in the type signature:

<img width="408" alt="screenshot" src="https://user-images.githubusercontent.com/7761921/31126340-6a7ff0a8-a886-11e7-90f4-42a2dcf75b9e.png">

I haven't taken a look at the other regexs in `HaskellAnnotator.scala`, but I imagine this could be a problem for some of those too.

**Comment by rikvdkleij** [comment]
It's already solved in master, see https://github.com/rikvdkleij/intellij-haskell/blob/626635455077ad41d179c8ae30ef4032452da2ac/src/main/scala/intellij/haskell/external/repl/StackRepl.scala#L209

**Comment by solicode** [comment]
Sorry, didn't see that. Thanks.
