### ISSUE TITLE
Startup GHCi script not loading

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#229]
This one is my fault. I forgot to take into account that the GHCi script would be inside the jar file. In dev mode it must have worked because it wasn't yet packaged up in a jar.

The problem line is [here](https://github.com/rikvdkleij/intellij-haskell/blob/5599bbb1e35e4184d6a4b89bfd57e51f1ba8de55/src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleState.scala#L30-L32).

I guess the solution is to create a temp file like Stack does? Unless there's a different IntelliJ way of handling external files like this that I'm not aware of.

**Comment by rikvdkleij** [comment]
> This one is my fault.

No problem, can happen :smile: 

> I guess the solution is to create a temp file like Stack does?

Can you test that solution?

`com.intellij.openapi.util.io.FileUtil` has various methods to create temporary files.

**Comment by solicode** [comment]
The temp file solution seems to work. I installed the plugin from disk to confirm. Creating a PR now.
