### ISSUE TITLE
Intellij 2017.2.5 + intellij-haskell 1.0.0-beta12 not working

### ISSUE THREAD

**Issue by kgeilmann** [rikvdkleij/intellij-haskell#232]
1.0.0-beta12 does not seem to be compatible with intellij 2017.2.5. I can't import or create any project, All I get, are exceptions (full stacktraces in the attached logs), even hovering over menu items makes the IDE unhappy.

```
2017-10-12 01:29:38,199 [  14096]  ERROR - oncurrency.BoundedTaskExecutor - cannot create class 'intellij.haskell.action.HoogleNavigationAction' [Plugin: intellij.haskell] 
com.intellij.diagnostic.PluginException: cannot create class 'intellij.haskell.action.HoogleNavigationAction' [Plugin: intellij.haskell]
```

```
2017-10-11 23:04:34,250 [  59224]  ERROR - llij.ide.plugins.PluginManager - Could not initialize class intellij.haskell.external.execution.CommandLine$ 
java.lang.NoClassDefFoundError: Could not initialize class intellij.haskell.external.execution.CommandLine$
```

I'm running:
- Windows 10
- IntelliJ Community Edition 2017.2.5 (fresh install) 
- a fresh install of stack 1.5.1 (installed via the official windows 32bit installer, accepting all default values), 

[logs-20171012-013112.zip](https://github.com/rikvdkleij/intellij-haskell/files/1377529/logs-20171012-013112.zip)

**Comment by rikvdkleij** [comment]
Do you also have installed another Intellij plugin which supports Haskell?

**Comment by rikvdkleij** [comment]
It looks like the plugin jar is corrupt. Can you uninstall the plugin and install (download) again?

**Comment by kgeilmann** [comment]
I didn't install anything else, but the intellij-haskell plugin, so no interfering plugins.

I uninstalled the plugin, restarted the ide, reinstall the plugin via plugin center -> nothing changed.
I downloaded the plugin from the intellij website and installed it using Install from disc, still no success.

Then I downgraded Intellij to 2017.2.4 and now works.

**Comment by rikvdkleij** [comment]
> Then I downgraded Intellij to 2017.2.4 and now works.

@kgeilmann Really weird, I have no explanation.
