### ISSUE TITLE
Wierd test output 

### ISSUE THREAD

**Issue by ghost** [rikvdkleij/intellij-haskell#235]
Hello, 

I have this test file : 

    module Laws.LawsCheckSpec (spec) where

    import Test.Hspec
    import Test.Hspec.Checkers
    import Test.QuickCheck.Classes
    import Test.QuickCheck

    import Lib

    main :: IO ()
    main = hspec spec

    spec :: Spec
    spec =
       describe "laws testing" $  do
          testBatch (functor (undefined :: PhhhbbtttEither String (String, String, Int)))
         -- testBatch (applicative (undefined :: PhhhbbtttEither String (String, String, Int)))
          -- testBatch (monad (undefined :: PhhhbbtttEither String(String, String, Int)))

When I run it , I see this as output : 

     [?25l
    Laws.LawsCheck
       laws testing
          laws for: functor
            identity
      90/100
         compose

     Finished in 0.3330 seconds
     2 examples, 0 failures

where I expect to see this as output : 

    Laws.LawsCheck
       laws testing
         laws for: functor
           identity
           compose

      Finished in 0.0156 seconds
      2 examples, 0 failures

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
