### ISSUE TITLE
how to see the type of a here 

### ISSUE THREAD

**Issue by rwobben** [rikvdkleij/intellij-haskell#236]
Suppose I have this expression : 

     Lib.Left a <*> Lib.Left b = undefined

Is there a way I can see what type a is. so I can solve this. 
I have installed intero , stylish haskell and hindent. 

Roelof

Edit 1 : I work on Windows

**Comment by rikvdkleij** [comment]
You can just ask for the type. It's called `View type info` in menu and shortcut key depends on OS.
