### ISSUE TITLE
Too many simultaneous builds

### ISSUE THREAD

**Issue by greenrd** [rikvdkleij/intellij-haskell#238]
I just saw it running 11 simultaneous background jobs, which slows my machine down to a halt. It seems to be now building whenever I type a single character in the editor.

**Comment by greenrd** [comment]
Also the cursor jumps from where it was after the build, which makes typing harder.

**Comment by greenrd** [comment]
The problem started after I chose Build -> Recompile 'Parser.hs'. The problem went away when I restarted IntelliJ.

**Comment by rikvdkleij** [comment]
Do you have an example project so I can try to reproduce your problem? The plugin should only rebuild the project(or better library) when you navigate to code which depends on library, for example, when you navigate to a test file.

> I think the problem started after I chose Build -> Recompile 'Parser.hs'.

This should do nothing. You can not build file or project from within IntelliJ.

**Comment by greenrd** [comment]
> Do you have an example project so I can try to reproduce your problem?

I can email it to you privately if it's really necessary.

> The plugin should only rebuild the project(or better library) when you navigate to code which depends on library, for example, when you navigate to a test file.

I have also split the window vertically and opened a test file in the second pane of the window. Maybe that's why this is happening?

**Comment by rikvdkleij** [comment]
> I have also split the window vertically and opened a test file in the second pane of the window. Maybe that's why this is happening?

That was a problem but should be fixed in latest version, beta12.

**Comment by rikvdkleij** [comment]
Well, if it's still a problem you can email your example project. I have send my email address to your Gitter account.
