### ISSUE TITLE
GHCi commands sometimes don't execute

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#239]
I still haven't properly diagnosed the cause of this, but every once in a while the GHCi actions (like reload modules) don't execute. I mean, the `:reload` shows up in the REPL panel, but it doesn't run. At least not until I run another REPL command. After that, it seems to work again.

I suspect it might be the `ConsoleViewContentType.USER_INPUT` change in PR #223. Maybe reverting back to `processInputWriter` is necessary. It's like the `\n` isn't interpreted right away in `ConsoleViewContentType.USER_INPUT` mode. That's just a guess though. I can look into it.

**Comment by davidkaste** [comment]
I have the same issue, scroll down the '_Run GHCi_' panel and press <_Enter_>, it will show up your last commands. 😉 
That's because you're entering commands not exactly in the same line where the prompt '_λ>_' is.

**Comment by davips** [comment]
Why isn't the REPL behavior identical to GHCi? Isn't it GHCi?
