### ISSUE TITLE
Green background for whitespace, commas and semicolons

### ISSUE THREAD

**Issue by Oblosys** [rikvdkleij/intellij-haskell#24]
Using the Default color scheme, all whitespace gets a green background that stretches to the right end of the window. Commas and semicolons are also affected. The Darcula color scheme looks fine.

The reason seems to be that `HS_DEFAULT` tokens inherit their color from `DOC_COMMENT_MARKUP`, which is green. There isn't really a suitable token-type candidate for Default in 'Default language', as the token types are all for actual tokens, not whitespace. 

I've put together a fix, for which I'll create a pull request. It removes the style for whitespace, and makes Default inherit from the non-green Comma style. It may need some additional work though, as Default is not very descriptive. A better solution might be to have separate token types for comma, semicolon, etc., or to group them in sets with meaningful names.

**Comment by rikvdkleij** [comment]
@Oblosys Thanks for your feedback and creating a pull request. I will take a look as soon as possible. 

Because ghc-mod is improved lately, I want to continue with improving the plugin. I also want to use sbt for building the plugin.

I'm also busy with using sbt for building the plugin and supporting IntelliJ 15.

**Comment by Oblosys** [comment]
Nice, and thanks for creating the plugin! It was a bit of work to get it up and running, but it seems to work now. SBT sounds like a good idea, because it was not trivial to build the plugin from source (I'm new to IntelliJ and don't speak Scala). I've kept a log of everything I installed, which I can e-mail you if you like, so could perhaps use it in a little manual on how to build from source for non-Scala experts.

I've also made some modifications to allow plugin developers with different minor IntelliJ SDK versions to work on the same project files, without having to alter them. You can find them in pull request #26.

**Comment by rikvdkleij** [comment]
@Oblosys I just converted this project to a sbt project. You can give it a try :-) I'm not finished with testing the plugin for IntelliJ 15

**Comment by rikvdkleij** [comment]
@Oblosys Btw, sorry for the delay, I will merge your pull request soon.

**Comment by Oblosys** [comment]
I gave it a try with Community Edition 14.1.5, and it's giving me 1498 errors on make. I'll have a closer look at this when I have a bit more time. The sbt part went okay though.

**Comment by rikvdkleij** [comment]
What kind of errors do you get? I'm using 15 preview version.

**Comment by Oblosys** [comment]
I had a look at the project settings, and the SDK turned out to be '1.7 (java..)', which I changed to 'IntelliJ IDEA Community Edition..'. I also had to fix some incorrect paths to jars in /usr/local/opt/scala/idea/lib/.

Now there are 87 errors left, which I put in a [gist](https://gist.github.com/Oblosys/34833603c887a8b0848b). They all seem to be psi related, but the latest version of the plugin is installed.

**Comment by rikvdkleij** [comment]
Did you follow (build) instructions from readme?

**Comment by Oblosys** [comment]
I did. It wasn't immediately clear that I had to run the updateIdea and compile tasks from sbt on the command line rather than from within IntelliJ (maybe you could clarify that in the instructions), and I believe I had to build the lexer and parser as well (is only mentioned as required after making changes to .flex & .bnf files, not at 'How to build' section). Unfortunately, the build still failed.

**Comment by rikvdkleij** [comment]
I cloned project, started sbt console inside root folder of project and run `updateIdea`. After that I ran `compile` and I did not get compile errors. 

I clarified build instructions.

**Comment by Oblosys** [comment]
Cool. I see that there are versions of the generated files in the repo, so building the lexer and parser indeed wasn't necessary. Looks to me like the build problems are caused by the Scala installation on my machine. I'll try to get things cleaned up and will post the results.

**Comment by rikvdkleij** [comment]
Okay, hopefully you get it working soon. Be aware that master is aimed at IntelliJ 15.

Btw, I noticed some API changes in IntelliJ 15 and also some changes in latest `ghc-mod` versions. I'm also testing with ghc-mod in combination with stack. So need some time before releasing new version.

**Comment by rikvdkleij** [comment]
@Oblosys I released some time ago new version which supports IntelliJ 15. Btw, I'm still busy with improvements....
