### ISSUE TITLE
Stopping/disabling Intero

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#240]
This might somewhat overlap with #234, but the idea is to be able to disable Intero entirely (which I think isn't possible currently?).

Intero is usually fine for me (especially for my projects which are usually small), but I'm finding that in certain situations I want to be able to disable it. Like if I'm just making a quick contribution to a large open source project, Intero takes a lot of resources and seems to churn. Another is for situations where you want to lower power consumption, like if you're working on battery.

A third one I was thinking of but haven't really investigated too much into yet is for allowing a ghcid-like workflow (it seems especially nice for the times you want to do mindless refactoring). But I'm getting ahead of myself.

Anyway, is this disabling feature something you would be interested in? I wouldn't mind looking into it. I think the main thing is making sure all the intellij-haskell features that depend on Intero downgrade/disable gracefully. Maybe they already do, but it requires verification.

**Comment by rikvdkleij** [comment]
I guess you mean disabling the Stack REPL with Intero loaded? Well, if that is the case then most of the IntelliJ features will not work anymore. Btw, the plugin also uses a lot of `ghci` commands.

I think a better solution/workaround for this memory leak of ghci(https://ghc.haskell.org/trac/ghc/ticket/14336) is to restart the project REPL periodically or measure the size of the Intero process and if it is above a certain size, restart the REPL. The plugin already restarts the global REPL after all library info is requested.

I'm already busy with making the (re)start of the REPL smoother.

**Comment by rikvdkleij** [comment]
Some addition. By disabling the Stack REPLs, IntelliJ will just become an editor. Is this what you want?

**Comment by solicode** [comment]
> I guess you mean disabling the Stack REPL with Intero loaded?

Yeah, that's what I'm referring to.

I realize this would disable a lot of IntelliJ features. In certain situations, I would be fine with that. With that said, it's understandable why this proposal would be rejected.

My main motivation was: When everything is working smoothly, great. When things aren't though, I'd rather have some way to continue using IntelliJ rather than switch my IDE/editor completely. Even if it means most things (except the integrated REPL window and hoogle) are disabled. Those integrated features alone makes it nicer than working with a plain editor for me. Plus just being used to all the IntelliJ shortcuts and so on.

I acknowledge that maybe I'm the only one who would find a "simple mode" like this useful. 😛 So if it's out of scope for intellij-haskell, I completely understand.

To make "simple mode" more palettable, I was thinking about how ghcid works and if that kind of workflow could be integrated. That's what my comment about it earlier was about.

Kind of a tangent: Using `ghcid` in a separate terminal window isn't really possible right now because files are automatically saved for the annotator to work in (semi) real-time. So disabling IntelliJ's `Save files automatically` (and on deactivation) doesn't do much.

**Comment by rikvdkleij** [comment]
What do you think of my suggestion about restarting the Stack REPL?

**Comment by solicode** [comment]
> What do you think of my suggestion about restarting the Stack REPL?

For the GHCi memory leak? That seems fine for mitigating that particular issue.

The "lightweight" mode idea I'm talking about is more for when things aren't working at all. Like I said, I haven't really experienced it with my own projects as they're all fairly simple, but I notice issues with larger projects.

For example, I wanted to make a contribution to Yesod, so I opened it in IntelliJ. I see an intero process open and taking resources, but I'm not really getting anything out of it. View type info, go to definition, and all those features aren't actually doing anything. For cases like these, I thought it would be nice to have a fallback lightweight mode that doesn't even bother with those advanced features. So yes, basically I imagine it behaving more like an editor rather than an IDE in such a mode.

As for why all the features aren't working for me in some projects, I'm not yet sure. It's worth looking into. It could be due to something completely unrelated.

Perhaps a fallback mode isn't needed. I just don't have any other ideas currently. All I know is that I've experienced problems with some projects. I guess it depends on what those causes are.

It's not a LOC thing, is it? Yesod is about 20,000 LOC (which doesn't seem *that* big to me). How does everything perform for similar or bigger projects? I've only tried a few so far, but I haven't had much success yet. Or is it the more complicated multi-project setup? Or too much Template Haskell? I'm not sure.

**Comment by solicode** [comment]
But I do get this is could be out of scope for intellij-haskell. It might make more sense to have a separate plugin, like intellij-ghcid or something if that's what someone is looking for.

The only problem with that I think is that multiple plugins for the same language seem problematic in IntelliJ.

**Comment by rikvdkleij** [comment]
I already looked to ghcid. It is not suitable for IntelliJ. It has it's own usage.

We first have to get the problem clear, then we can find the right solution. When I have time I will try to use IntelliJ with large projects like Yesod and see what is going on.

**Comment by solicode** [comment]
Yeah, I doubt just dropping ghcid in IntelliJ would work all that well. I meant more like replicating that kind of workflow within an IntelliJ context (like hook into IntelliJ's triggers, use its error list component so you can cycle through them with the keyboard, and so on).

But ignoring that for now as it's off-topic anyway, is it difficult to have an option so that errors are checked on explicit save rather than constantly saving the document as you're typing? The default is fine as is, but just wondering. I'm not sure how much that option would help, but it's all I can think of at the moment.

> We first have to get the problem clear, then we can find the right solution. When I have time I will try to use IntelliJ with large projects like Yesod and see what is going on.

Alright, I'll keep an eye out for it too. If I can find better examples, I'll let you know. Yesod does seem to have a lot of "magic", so maybe it's not the greatest example. I believe I also saw some weirdness with SDL2 when I opened that a while back, but I'll have to double-check that.

**Comment by rikvdkleij** [comment]
> Alright, I'll keep an eye out for it too. If I can find better examples, I'll let you know. Yesod does seem to have a lot of "magic", so maybe it's not the greatest example. I believe I also saw some weirdness with SDL2 when I opened that a while back, but I'll have to double-check that.

It easily reproduced with the Intero project itself.  After opening the project in IntelliJ it takes only a few actions to get the Intero process to 5 GB memory usage and to get the IDE unresponsive. 
Intero is a small project so the cause of the memory leak has nothing to do with LOC.
At this moment I do not know workaround/solution for this problem other than restarting the REPL when Intero does not respond quickly. But that makes the IDE experience jerky....

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
