### ISSUE TITLE
Rebuilding Hoogle database should be backgroundable

### ISSUE THREAD

**Issue by csi-adziahel** [rikvdkleij/intellij-haskell#242]
The user should be able to send "Rebuild Hoogle database" progress window to background, same way he can do it for "Restarting Haskell Stack REPLs" window.

**Comment by rikvdkleij** [comment]
Yes, can do that but notice that `stack hoogle --rebuild` also does a rebuild so it can have some side-effects.

**Comment by csi-adziahel** [comment]
Noted. Could automatic restarting REPLs after such rebuild mitigate them?

**Comment by rikvdkleij** [comment]
> Could automatic restarting REPLs after such rebuild mitigate them?

That could help to keep everything in sync.

But a larger issue is that if Hoogle rebuild is done in background and you continue with coding, coding can also trigger builds so you can have simultaneously builds. Also compile errors can stop the Hoogle rebuild.

I can enable it and see how it works in practice.

**Comment by Sir4ur0n** [comment]
Can we close this?

**Comment by rikvdkleij** [comment]
Yep, is done in latest betas.
