### ISSUE TITLE
Error calling Hlint

### ISSUE THREAD

**Issue by johnwu93** [rikvdkleij/intellij-haskell#244]
So, after installing `stack` and the dependencies, `hindent` and `stylish-haskell`, I am having some trouble using `hlint` for intellij-haskell after installing it.

Specifically, I get an event error whenever I make an edit on a haskell file,

> Error while calling hlint: hlint: /Users/johnwu/.local/bin/hlint: hGetContents: invalid argument (invalid byte sequence)

How can resolve this issue?

I am using the latest version of `stack`, specifically, Version 1.6.1. I installed `hindent`, `stylish-haskell` and `hlint` with the following command:

```
stack install hindent stylish-haskell 
stack install hlint
```

The latest version of the dependencies I installed are the following:
- hindent 5.2.3
- HLint v2.0.11, (C) Neil Mitchell 2006-2017
- stylish-haskell 0.8.1.0

**Comment by rikvdkleij** [comment]
Hlint is build automatically by plugin because it has to be build with same Stackage version as your project. See https://github.com/rikvdkleij/intellij-haskell#getting-started

Hindent and stylish-haskell can be installed globally but hlint has to be build inside your project directory.

**Comment by rikvdkleij** [comment]
Maybe I have to be more clear 😄 

> Error while calling hlint: hlint: /Users/johnwu/.local/bin/hlint: hGetContents: invalid argument (invalid byte sequence)

That means an incompatibility issue because you have build hlint with different Stackage version than your project is using.

**Comment by johnwu93** [comment]
What commands do I have to use to install the package locally. What do I have to put in my stack.yaml file to install it?

**Comment by rikvdkleij** [comment]
If you have a Stack project (for example from a Stack template) it should just work because hlint is automatically build by plugin. See readme.

**Comment by johnwu93** [comment]
I have a Stack project and I am not sure if `Intellij-haskell` is automatically building `hlint`. I notice that `intero` is built because it is in `.stackwork/install/x86_64-osx/lts-10.3/8.2.2/bin` in my app directory, but `hlint` is not there.

Also, after installing `hlint` with `stack install hlint`, I found out that the local path of `hlint` is `/Users/johnwu/.stack/snapshots/x86_64-osx/lts-10.3/8.2.2/bin/hlint`.  I changed the path of `hlint` to this path, but I'm still getting the same error.

Can you help me with this? Is there a certain resolver that I have to use for my project in order `hlint` to work?

The resolver I am using is `lts-10.3`

**Comment by rikvdkleij** [comment]
> I changed the path of hlint to this path, but I'm still getting the same error.

Where did you change the path? You can not set the path to hlint inside IntelliJ-Haskell. 

`About Haskell Project` in `Help` menu shows which Haskell GHC/tools are used by plugin for your project.

It's difficult for me to help without any further information. For more information about what is going on, you can enable the Haskell Event Log, see README how to enable it.

**Comment by johnwu93** [comment]
I changed the path under `Settings > Other Settings > Hlint Options`. Namely, I changed it to the value `/Users/johnwu/.stack/snapshots/x86_64-osx/lts-9.18/8.0.2/bin/hindent`

Here are the stats that I have for IntelliJ-Haskell

**Stack** version 1.6.3
**GHC** version: The Glorious Glasgow Haskell Compilation System, version 8.0.2

**Intero** version: Intero 0.1.23
**HLint** version: Intero 0.1.23

**Hoogle** version: Hoogle 5.0.14,
http://hoogle.haskell.org/

**Hindent** version: hindent 5.2.3

**Stylish-haskell** version: stylish-haskell 0.8.10

Strangely enough, if I omit the Hlint option, I can get linting issues.

For example if I do

```haskell
spec :: Spec
spec =
  describe "test" $ do
    it "should work" $ "foo" `shouldBe` "foo"
```

The third and fourth line would be highlighted as a warning and I get autofix suggestions to automatically remove the unnecessary do statement

**Comment by rikvdkleij** [comment]
`Settings > Other Settings > Hlint Options` is not for the path to hlint. It's for passing options/flags to hlint.

hlint is already on the path for stack.

**Comment by Sir4ur0n** [comment]
I think this issue is no longer valid? Since HLint and Stylish Haskell are now managed directly by the plugin.

**Comment by rikvdkleij** [comment]
Yep, it is no longer valid in latest betas.
