### ISSUE TITLE
Pragmas without trailing space should be accepted by parser

### ISSUE THREAD

**Issue by csi-adziahel** [rikvdkleij/intellij-haskell#248]
Repro: type `{-# LANGUAGE RecordWildCards#-}` (note missing space between `s` and `#`)
Expected: no "incorrect syntax" highlighting 
Instead: 
![image](https://user-images.githubusercontent.com/28052643/34300004-2c0c2efa-e737-11e7-829a-98a239ffdbab.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
@csi-adziahel It's fixed in the next release.

**Comment by Sir4ur0n** [comment]
Close issue?

**Comment by rikvdkleij** [comment]
Please reopen if this is still an issue.
