### ISSUE TITLE
Error while formatting by `stylish-haskell`

### ISSUE THREAD

**Issue by pamu** [rikvdkleij/intellij-haskell#251]
### CMD + ALT + ; . Triggers the following error

Error while formatting by `stylish-haskell`. Error: stylish-haskell: user error (Language.Haskell.Stylish.Config.configFilePath: could not load default configuration at: /Users/username/.stack/snapshots/x86_64-osx/lts-8.15/8.0.2/share/x86_64-osx-ghc-8.0.2/stylish-haskell-0.7.1.0/data/stylish-haskell.yaml)

**Comment by rikvdkleij** [comment]
Maybe the `stylish-haskell` version you installed globally is not compatible with Stackage version of your Stack project. 

Could be a reason to always build `stylish-haskell` per Stack project automatically just like `intero`.

**Comment by tomlanning** [comment]
I had a similar problem when I updated the Stack resolver to a new version.  I re-installed *stylish-haskell* with `stack install stylish-haskell` in the project directory and formatting worked again without the error message.

**Comment by rikvdkleij** [comment]
@tomlanning Thanks for your confirmation! So `stylish-haskell` is not compatible over Stackage/GHC versions. I will consider to build it also automatically.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
