### ISSUE TITLE
Stuck at registering library

### ISSUE THREAD

**Issue by ezsosza** [rikvdkleij/intellij-haskell#257]
Hi,

On windows, I have installed the recent Intellij(2017.3 with latest patch) with the haskell plugin(-beta12).
Stack is installed and a new project created in shell, where building works fine.
However, when the project is opened in intellij, the build process stuck at the last phase, "Registering library for ..."
Due to this, i also get the warning bubble even when just right clicking on a function name that "Haskell support is not available while (re)building project".

Do you have a hint what can be wrong?

Thanks,

**Comment by ezsosza** [comment]
I managed to get around this issue by installing intero. However, "stack repl" takes exectly 2 minutes to start even in the shell. By increasing the timeout value in the settings it works, now, i am waiting for hlint to be built... :D 
Everything is just too slow at the moment... I guess this has nothing to do with the plugin...

**Comment by ezsosza** [comment]
Seems there were stuck ghc and stack processes in the system and slowed down everything... Now, everything works.

**Comment by rikvdkleij** [comment]
Great that it all works now!

**Comment by Displee** [comment]
I still do have this issue when I use:
```haskell
main = interact reverse
```
