### ISSUE TITLE
`SCC` pragmas are not properly parsed

### ISSUE THREAD

**Issue by lucascharlesmyers** [rikvdkleij/intellij-haskell#258]
As described [in the GHC user's manual](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html), GHC supports `SCC` pragmas that specify cost centers for profiling. These incorrectly trigger a parse error in IntelliJ-Haskell.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by ice1000** [comment]
Any repro cases?

**Comment by ice1000** [comment]
So this means pragmas can be expressions.
Possibility an easy fix

**Comment by rikvdkleij** [comment]
According to me it's already fixed.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
