### ISSUE TITLE
Incomplete import from existing sources with stack.yaml that lacks a "packages" field

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#259]
Hello everyone,
I am using Intellij-Haskell 1.0-beta12 to learn the language using http://exercism.io as my source for exercises. I noticed that importing an existing project fails for some reason when there is no packages field in the stack.yaml. I won't get any error, but the imported project lacks any module making it useless. Adding the module from the project structure afterwards does not work.

this is how a typical haskell project from exercism looks like:
https://github.com/exercism/haskell/tree/master/exercises/hello-world

please note that the stack.yaml contains no packages field

According to the stack.yaml documentation at https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md, a missing packages field should default to 
```
packages:
- .
```
adding this to the stack.yaml before the import makes the problem go away

**Comment by enolive** [comment]
Well, as a missing packages field is supported according to the stack.yaml documentation and the project builds fine using stack build or stack test, I guess it is an issue with the plugin.

**Comment by rikvdkleij** [comment]
Okay, my mistake. I assumed that the `packages` field is always there (mandatory field). 

Thanks for reporting! I will fix this.

**Comment by Sir4ur0n** [comment]
I think we can close this.
