### ISSUE TITLE
Associated datatypes aren't parsed correctly

### ISSUE THREAD

**Issue by mylincode** [rikvdkleij/intellij-haskell#260]
With the `TypeFamilies` extension, GHC allows a `class` to require associated `data` declarations. For instance, the following is syntactically valid with `TypeFamilies` enabled:
``` haskell
class Foo a where
  data Baz a
  bar :: a -> Int
```
IntelliJ-Haskell seems to have trouble with that incomplete `data` declaration, and gives a parse error on the `::` following `bar`.

The parser recovers by the next line, so the only observable impact of this issue is the incorrect red squiggle under the `::`.

**Comment by Sir4ur0n** [comment]
Close issue?

**Comment by rikvdkleij** [comment]
Please reopen if this is still an issue in latest betas.
