### ISSUE TITLE
stderr: Couldn't read "...xxx.hs" as a String

### ISSUE THREAD

**Issue by arslancharyev31** [rikvdkleij/intellij-haskell#261]
I've encounter the abovementioned issue while setting up and running my first project. I've figured out that the reason for this error was due to the fact that the filepath, which was being provided as an argument, has been using backward slash `\` instead of forward slash `/` as a file separator (I'm running it on Windows 10). It would be nice if the plugin could perform necessary checks and fixes in such cases. For now it's just stuck, and I wonder if there's anything that could be done?

**Comment by Milerius** [comment]
same for me

**Comment by rikvdkleij** [comment]
Could you more specific about the problem? For example, which file path?

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
