### ISSUE TITLE
Failed plugin

### ISSUE THREAD

**Issue by xgrommx** [rikvdkleij/intellij-haskell#264]
Hello @rikvdkleij 

I had build and assemble this plugin via git and my IDEA. But when I try to load this plugin via zip archive I got error and my IDEA doesn't work (I must turn off this plugin...)

My version of IDEA is 
```
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.400, built on March 19, 2018
Licensed to Denis Stoyanov
Subscription is active until April 18, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

**Comment by xgrommx** [comment]
@rikvdkleij So, I need disable all my plugins? Even built-in?

**Comment by rikvdkleij** [comment]
No, only the Haskell ones
