### ISSUE TITLE
No result from Stack repl within 5 seconds. Command was: :set prompt "^IntellijHaskell^\n"

### ISSUE THREAD

**Issue by klimisa** [rikvdkleij/intellij-haskell#265]
Hi, Stack Repl is not starting.

OS: Windows 10
IntelliJ: 2017.3
IntelliJ-Haskell: 1.0.0-beta12

Event Logs:
12:29	[project-stack-repl-bittrex:exe:sanity-check] Stack repl could not be started within 5 seconds

12:29	[project-stack-repl-poloniex:lib] Stack repl could not be started within 5 seconds

12:29	Hoogle database does not exist. Hoogle database can be created by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database`

12:29	[project-stack-repl-kraken:lib] No result from Stack repl within 5 seconds. Command was: :set prompt "^IntellijHaskell^\n"

12:29	[global-stack-repl] Stack repl could not be started within 5 seconds

**Comment by klimisa** [comment]
I have increased the timeout to 10 sec but I still occasionally get timeouts.

Timeout while executing C:/Users/klimisa/AppData/Roaming/local/bin/stack.exe exec -- hlint --json C:\akli\dev\eff\bittrex\src\Bittrex.hs

**Comment by rikvdkleij** [comment]
The timeout setting is only for the REPL. Not for hlint. It’s by default 3 seconds.

**Comment by klimisa** [comment]
OK good to know, I thought it was related.
Any idea why I'm getting these timeouts?
