### ISSUE TITLE
Exception in HLint integration with lts-11.x

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#266]
I noticed I don't get any hlint warnings inside the IDE when I set my resolver in stack.yaml to lts-11.x.

Additionaly, an IDE error occurs

`Expected String as JsString, but got ["LinkedList"]` where LinkedList is the name of the module hlint tries to scan.

[exception.txt](https://github.com/rikvdkleij/intellij-haskell/files/1861854/exception.txt)

hlint works fine from the CLI

```
$ hlint -V
HLint v2.1.1, (C) Neil Mitchell 2006-2018
```

My workaround is to stick with lts-10.2 where everything works fine.

**Comment by dvic** [comment]
I just installed the plugin and created a new project and I'm also seeing this issue.

**Comment by rikvdkleij** [comment]
Thanks for reporting! The Hlint API is changed in 2.1 I will have to change the Hlint integration in a backwards compatible way.

**Comment by rikvdkleij** [comment]
It takes some time to solve this issue in a proper way. Also releasing a new version of the plugin will not happen soon. 
As a workaround, to use LTS-11 for your project, you can build latest version of HLint which still works with plugin, by executing this command in the root folder of your Stack project:
`stack build hlint-2.0.15`

**Comment by rikvdkleij** [comment]
I have released new version of plugin https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta14
It's also uploaded it to Alpha channel of Jetbrains plugin repo but that can take some time before it's published

**Comment by francisdb** [comment]
Any chance this could get pushed to the default channel?

**Comment by rikvdkleij** [comment]
@francisdb I want to release version 1.0.0 asap but still to many issues, especially with responsiveness of UI.

**Comment by Sir4ur0n** [comment]
Close issue?

**Comment by rikvdkleij** [comment]
Yep, it is solved in latest betas and I want to release soon to stable plugin repo channel.
