### ISSUE TITLE
Plugin not entirely functional

### ISSUE THREAD

**Issue by mbudiu-vmw** [rikvdkleij/intellij-haskell#267]
I have installed the latest version 1.0.0-beta12 of the plugin in Intellij:  2018.1.
Some of the functionality works (e.g., syntax highlighting), but "goto declaration" does not work between different source files. Moreover, there is no "Haskell" menu under the "Tools" top-level menu.

**Comment by rikvdkleij** [comment]
It looks like Intero is not running. Please check Event log. See Readme for that.

**Comment by mbudiu-vmw** [comment]
This is the top of the stack trace in the idea logs:

```
ERROR - t.daemon.impl.ExternalToolPass - IdeaLoggingEvent[message=annotator: intellij.haskell.annotator.HaskellAnnotator@551d0ac5 (class intellij.haskell.annotator.HaskellAnnotator), throwable=java.lang.NullPointerException
	at intellij.haskell.external.repl.StackReplsManager$.$anonfun$getProjectRepl$1(StackReplsManager.scala:45)
	at scala.Option.flatMap(Option.scala:171)
	at intellij.haskell.external.repl.StackReplsManager$.getProjectRepl(StackReplsManager.scala:45)
	at intellij.haskell.external.component.LoadComponent$.load(LoadComponent.scala:52)
	at intellij.haskell.external.component.HaskellComponentsManager$.loadHaskellFile(HaskellComponentsManager.scala:96)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:66)
	at intellij.haskell.annotator.HaskellAnnotator.doAnnotate(HaskellAnnotator.scala:42)
```

I have built intero manually (`stack build intero`), but this still happens, even after I restarted idea.

**Comment by rikvdkleij** [comment]
This exception does not look like the cause of your issue. 

Btw, I do not mean the Idea log but the IntelliJ Haskell Event log. See the bullet about `Event log` in https://github.com/rikvdkleij/intellij-haskell#getting-started

**Comment by mbudiu-vmw** [comment]
I hope I have found the Idea event log for Haskell: View/Tool windows/Event log. There is only one message: `hlint is not yet available`
There is no message about Intero.
I don't really understand which version of hlint intellij is supposed to use. I have three binaries on my disk, one in /usr/local/bin, and two different ones in ~/.stack/snapshots/x86_64-linux/lts*/8.2.2/bin.
I am new to Haskell, so I don't really understand how the environment of the Haskell project is related to the environment used by IntelliJ to call various tools.

**Comment by rikvdkleij** [comment]
Most things should work-out-of-the-box after installing the Stack tool and  have a proper configured Stack project. HLint and Intero are automatically build and are only "visible" for stack in the project. The message `hlint is not yet available` means it's no been build yet.

Did you follow the `Getting started` intstructions?

**Comment by mbudiu-vmw** [comment]
I don't know if this is due to #266; I have changed the resolver in stack.yaml to lts-10.2, followed all the steps in the README again, re-imported the project, and the plugin has started working. Thank you!

**Comment by rikvdkleij** [comment]
It should not matter but I'm glad it now works for you!
