### ISSUE TITLE
Imported project doesn't contain src and tests folders

### ISSUE THREAD

**Issue by stalexxx** [rikvdkleij/intellij-haskell#268]
I've imported sample project but src/tests folders is missed
Idea 2018.1, plugin v. beta12

<img width="482" alt="2018-04-07 13 09 15" src="https://user-images.githubusercontent.com/4428951/38453854-1c250b66-3a65-11e8-9016-e65457adba1e.png">

**Comment by rikvdkleij** [comment]
How did you import the project? Did you follow https://github.com/rikvdkleij/intellij-haskell/blob/master/README.md#getting-started ?

**Comment by rikvdkleij** [comment]
Super!
