### ISSUE TITLE
Error in communication with ghc-modi

### ISSUE THREAD

**Issue by slvrtrn** [rikvdkleij/intellij-haskell#27]
Hello, I'm trying to use this plugin (version 0.9) with Intellij Idea 14.0.2 on Win8.1 64 bit
All seems to work, but I'm getting weird error every 5-10 seconds along with IDE freeze

```
Error in communication with ghc-modi: Futures timed out after [5 seconds]. 
Check if GHC SDK is set and ghc-modi is okay. ghc-modi will not be called for 5 seconds
```

I am able to run `ghc` `ghc-mod` or `ghc-modi` from terminal in my project's root directory.
Paths  in Settings -> Other -> Haskell are also correct

**Comment by rikvdkleij** [comment]
@slvrtrn Sorry, I do not support Windows. I have tested plugin only with Ubuntu and OSX.

**Comment by Miguelme** [comment]
@rikvdkleij this is happening in OS X

**Comment by rikvdkleij** [comment]
@Miguelme  Plugin does not use `ghc-mod` anymore.
