### ISSUE TITLE
Help with set up

### ISSUE THREAD

**Issue by AllanWang** [rikvdkleij/intellij-haskell#271]
Hello there. This is my first time using Haskell, so forgive me if this doesn't pertain to this plugin.

In following the readme instructions, I ran into the same issue as https://github.com/rikvdkleij/intellij-haskell/issues/250

So I just created a new project with `cabal init`, and imported it into IntelliJ.

In doing so, the project didn't seem to register any of the `.hs` files as part of the project, as I had to allow editing when I first typed there. Formatting also doesn't seem to work for me, whereas calling `hindent` works fine.

Is there anything else I should be doing in regards to the setup?

Lastly, it looks like the way to run the projects is through `cabal run`. In that case, shouldn't that be added as a default run configuration option? Or is there a better way of running these projects?

**Comment by rikvdkleij** [comment]
> So I just created a new project with cabal init, and imported it into IntelliJ.

The plugin supports only Stack projects. You will have to create a Stack project (https://docs.haskellstack.org/en/stable/README/). Stack uses Cabal internally.

To create a new project you will have to use for example:
`stack new helloworld new-template`
which uses template `new-template`
That project can be imported into IntelliJ.


> Is there anything else I should be doing in regards to the setup?

No, besides installing Stack. Most tools are automatically build except Hindent and Stylish-haskell because those are optionally (btw, that will change in next version of plugin).

**Comment by AllanWang** [comment]
Thank you for the info. I created the new project with `stack`, but I still can't get formatting to work.

Is there anything I had to do beyond adding the paths?

![image](https://user-images.githubusercontent.com/6251823/39322358-a062d7e0-4957-11e8-91a3-80d2d5f6c969.png)

I'm simply testing formatting for 

```hs
module Main where

import Lib

main :: IO ()
main  = someFunc
```
To see if it will remove the extra space

**Comment by rikvdkleij** [comment]
Be sure to use the right shortcut. It’s not default Intellij’s for formatting. CTRL+Shift+; uses both.

**Comment by AllanWang** [comment]
Hm. I tried that along with a few other haskell shortcuts and none of them seem to work.

I'm on Antergos and IntelliJ 2018.1.1 if that makes any difference.

![image](https://user-images.githubusercontent.com/6251823/39345491-af9f215a-49b6-11e8-9d10-1344e8f420db.png)

**Comment by rikvdkleij** [comment]
It should work on Linux. Check the `Event Log`, maybe there are some errors there. See https://github.com/rikvdkleij/intellij-haskell#getting-started how to enable it. 

Shortcut for Hindent: ctrl+alt+k
And for Stylish-haskell: ctrl+alt+u

**Comment by rikvdkleij** [comment]
Do other features work?

I only can recommend to follow the Getting started.

**Comment by AllanWang** [comment]
This was my mistake. Importing it with external model worked (as opposed to importing from existing sources). I'm used to Java where I import sources and the rest will generate based on the files
