### ISSUE TITLE
Multiline strings aren't highlighted

### ISSUE THREAD

**Issue by emhoracek** [rikvdkleij/intellij-haskell#272]
If you use`\` to create a multiline string, it's not highlighted like a regular string.

If you copy and paste the string, it's highlighted correctly.

Example: 
![screen shot 2018-05-02 at 11 18 28 am](https://user-images.githubusercontent.com/5353499/39532288-915ea2ea-4dfa-11e8-90b2-0eb2d530d19d.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by ice1000** [comment]
Any fixes?

**Comment by rikvdkleij** [comment]
PSI is okay. It looks like IntelliJ issue.

**Comment by ice1000** [comment]
Wat

**Comment by ice1000** [comment]
If you make the String PsiElement a separate AST node, I can include the fix to this in the impl for #340

**Comment by rikvdkleij** [comment]
I do not know what you exactly mean but the complete  string is already a HS_STRING_LITERAL.

**Comment by ice1000** [comment]
`HS_STRING_LITERAL` is a token type, I want a class (which can be created from a non-private Grammar-Kit rule).

**Comment by ice1000** [comment]
Yes yes yes yes yes! Exactly.

**Comment by rikvdkleij** [comment]
Ok 😄  Will do that.

**Comment by rikvdkleij** [comment]
@ice1000 Added `HaskellStringLiteralElement`.

**Comment by emhoracek** [comment]
woohoo! Thanks you two for figuring this out.

**Comment by ice1000** [comment]
@emhoracek My "workaround" will highlight the wrongly highlighted strings correctly but will be a bit slower than other strings. This is due to IntelliJ's design.
