### ISSUE TITLE
Builds continuously triggered when project is in a broken state

### ISSUE THREAD

**Issue by rhyskeepence** [rikvdkleij/intellij-haskell#273]
Hi, thanks for the plugin, it's massively useful. 

I have an issue which I believe is related to #238. I don't think I'm seeing simultaneous builds (at most, I see "3 processes running") but any single character change in test/executable files, after editing library files, will trigger a "build". The build will steal focus and make intellij close to unusable, especially with a larger project and many warnings.

This would probably be ok, except sometimes my project is in a broken state (writing test before the lib code exists, or refactoring) so the build is triggered on every keystroke until unbroken.

Editing library files is normally fine at this point, and will not trigger builds. It's just editing executables that is the problem.

Is the build (stack build --fast) used to start intero?
Could it be debounced, or not triggered until frame deactivation?

I don't really know where to begin looking but I'd be happy to contribute if you think it would be a good idea, or if you have any opinions of possibly options and tradeoffs.

Thanks again

**Comment by emhoracek** [comment]
I'm having the same problem and it's especially noticeable because I tend to develop in a test-driven style, so I constantly flip between tests and library. Thanks for the explanation because it'll help me work around it for now. 

I'm happy to test any fixes you're considering as well.

**Comment by rikvdkleij** [comment]
I have released new version of plugin https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta14
It's also uploaded it to Alpha channel of Jetbrains plugin repo but that can take some time before it's published

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
