### ISSUE TITLE
Where is the REPL?

### ISSUE THREAD

**Issue by Jasagredo** [rikvdkleij/intellij-haskell#275]
I made a fresh `stack`installation and executed `stack install hlint hoogle stylish-haskell`. I installed this plugin and filled in the paths to hlint and stylish-haskell on the settings.

I activated the plugin log and it says the following:

    0:19	[global-stack-repl] Stack repl will be started with command: /usr/local/bin/stack repl --with-ghc intero --no-load --no-build --ghci-options=-ignore-dot-ghci --silent --no-package-hiding --test

    0:19	[global-stack-repl] command: :set prompt "^IntellijHaskell^\n"

    0:19	[global-stack-repl] stdout: Intero-Service-Port: 51951
		Prelude> ^IntellijHaskell^

    0:19	[global-stack-repl] Stack repl is started

But nothing happens. I expected a window inside IntelliJ to show as REPL but nothing shows up, not even if I go to `Restart Haskell Stack REPLs`. I don't know where I'm going wrong. Any help would be appreciated.

BTW, I'm running on a MacOS 10.13.

Thanks in advice

**Comment by Jasagredo** [comment]
After 20 minutes of failures, re-reading the README.md I saw I had to create a new Run Configuration. Just in case someone else faces this problem.

BTW, the comment that says:

    Running REPL, tests and executables via Run Configurations;

might be a good point to say in the `Getting started` section as I knew what to expect from this plugin and skipped the `Features` section.

**Comment by rikvdkleij** [comment]
Thanks for comment.

I do not understand you. You only have to create configuration for running exe, test or REPL within IntelliJ.

The plugin uses it's own REPL (with Intero loaded), which is used as backend and it's automatically started when you open Haskell project.
