### ISSUE TITLE
Stack REPL could not be started / REPL timeout / the working directory '~/.intellij-haskell/lts-11' does not exist

### ISSUE THREAD

**Issue by rjohnsondev** [rikvdkleij/intellij-haskell#276]
Building plugin from master and starting from scratch with an lts-11 project, there are some path issues that need to be corrected before things work on linux:

1) intero requires ~/.intellij-haskell _not_ be group-writable: `chmod -R ga-w ~/.intellij-haskell`
2) you currently need to manually create '~/.intellij-haskell/lts-11': `mkdir ~/.intellij-haskell/lts-11`
3) this directory _should_ be group writable (if it's not already): ` chmod -R g+w ~/.intellij-haskell/lts-11`

After that things seem to work as expected.

**Comment by rikvdkleij** [comment]
Thanks for reporting! Cool that you are testing the plugin from master but be aware that it's WIP.

Weird that you have those permission issues because latest versions already create the `.intellij-haskell` directory and I had never any permission problems with it, also they are never reported and IntelliJ itself also create directories in home directory.

Intero should not need access to the `.intellij-haskell` directory. This directory is only used by the plugin. Intero is build inside a Haskell project because it has to be build by GHC version of project.

I will check what a reason could be why the `lts-11` directory was not created. Maybe because the `.intelli-haskell` directory was not already there?

**Comment by rjohnsondev** [comment]
Completely appreciate it's WIP, the plugin is amazing work and I was eager to try getting hlint to work with the latest lts.

Allowing the plugin to create the `.intellij-haskell` seems to give it (default?) group-writable permissions. This causes:
```
➜ /home/richard/.local/bin/stack repl --with-ghc intero --no-load --no-build --ghci-options -ghci-script=/home/richard/.intellij-haskell/repl.ghci --silent --no-package-hiding --test                                                                                                                                                                                                 ---
Intero 0.1.31 (GHC 8.2.2)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 44495
*** WARNING: /home/richard/.intellij-haskell is writable by someone else, IGNORING!
Prelude>
```
after `chmod g-w ~/.intellij-haskell`

```
➜ /home/richard/.local/bin/stack repl --with-ghc intero --no-load --no-build --ghci-options -ghci-script=/home/richard/.intellij-haskell/repl.ghci --silent --no-package-hiding --test                                                                                                                                                                                                 ---
Intero 0.1.31 (GHC 8.2.2)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 37579
^IntellijHaskell^
```

I don't think I could get the `lts-11` directory added automatically regardless of  `~/.intellij-haskell` existing or not; the editor would report an exception about the path not existing to that was pretty easy to identify and a simple `mkdir` worked a treat.

**Comment by rjohnsondev** [comment]
Yeah, I started from the root of my Haskell project.

My apologies if I'm misinterpreting Intero as being cause of the issue: I saw the repl was timing out, so I executed the command as reported in the intellij event log manually, which produced that warning about permissions and dropped to the prelude prompt. I adjusted the permissions and the repl was happy.

**Comment by rikvdkleij** [comment]
I suspect that it's not Intero which complains but Stack itself. I did not notice this problem on my Mac but I will try to reproduce this issue on Linux. I will also take a look why the `lts-11` directory was not created.

**Comment by Sir4ur0n** [comment]
Close issue?

**Comment by rikvdkleij** [comment]
Please reopen if this is still an issue in latest betas.
