### ISSUE TITLE
Jump to definition across multi-package project

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#278]
It seems like jump to definition doesn't work across multi-package projects, even though the log shows `loc-at:` commands completing successfully.

<img width="1279" alt="screen shot 2018-06-06 at 2 44 35 pm" src="https://user-images.githubusercontent.com/538571/41058588-2857eb3a-6998-11e8-8e14-df18715aea65.png">

[video.zip](https://github.com/rikvdkleij/intellij-haskell/files/2077714/jump.from.bootstrap.to.library.zip)

**Comment by aryairani** [comment]
This is with plugin 1.0.0-beta14, IntelliJ IDEA IC-181.4203.550, and the multi-package project in question is at https://github.com/unisonweb/unison/commit/d2e85729acebec2e0884143216473d61dd93a1c5.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you give me the git clone for that repo?

**Comment by rikvdkleij** [comment]
Note that the log shows `:loc-at` from another file. It looks the `Bootstrap.hs` file is not loaded. What if you do `enter` in the file?

I will also try to reproduce it.

**Comment by rikvdkleij** [comment]
It works for me but I understand how this problem can occur.
 
It's caused by that the file is not yet loaded in the REPL (because for some reason IntelliJ did not see a change in the file and so did not trigger IntellijJ's Annotator). The plugin will not load the file in the thread in which you ask for location info because that will make the UI unresponsive. I will try to find a decent solution for this problem.

**Comment by rikvdkleij** [comment]
Btw, in `unison-parser-typechecker.cabal`, the library and exe have the same `hs-source-dirs`. So the plugin can not determine to which target the files there belong.

**Comment by aryairani** [comment]
Just to confirm, you saw in the attached image that the REPL answers the question of where the `penv` symbol is defined, but the editor doesn't jump to the definition, right?

> Btw, in unison-parser-typechecker.cabal, the library and exe have the same hs-source-dirs. So the plugin can not determine to which target the files there belong.

Hm, if you're on the commit I linked above, they should be separate:
```yaml
library
  hs-source-dirs: src

...

executable bootstrap
  hs-source-dirs: bootstrap

...

executable tests
  hs-source-dirs: tests
```
Here is a clone command for it: `git clone -b topic/intellij-haskell https://github.com/unisonweb/unison`

And yes, I did notice a few times that the UI had become unresponsive even with the current plugin.  I'm not sure what triggers it.  :-\

Thanks for your help!

**Comment by rikvdkleij** [comment]
> Just to confirm, you saw in the attached image that the REPL answers the question of where the penv0 symbol is defined, right? But the editor doesn't jump to the definition.

No, not in `Bootstrap.hs`, but in other files. I suspect not in `Bootstrap.hs` because it was not loaded. You can check that in the Event Log.

> And yes, I did notice a few times that the UI had become unresponsive even with the current plugin. I'm not sure what triggers it. :-\

It would be helpful if you can tell what it triggered.

**Comment by rikvdkleij** [comment]
> Did you have a chance to look at the screenshot or video I attached at the top of this github issue? Bootstrap.hs is open in the editor and the Event Log is open below it.

Yes, also the video. I think I understand the problem and will soon release new beta.

**Comment by rikvdkleij** [comment]
> I'm trying to jump from the reference to penv0 to its definition. The log shows the definition :loc-at to be /Users/arya/unison/parser-typechecker/src/Unison/Parser.hs:(31,1)-(31,6) (which is correct) so I would expect the IDE to open Parser.hs with the cursor at position (31,1). But it doesn't open anything.

You have read that wrong. The loc-at command gives for an identifier where it is defined.So after loc-at the Bootstrap.hs file is expected.

**Comment by aryairani** [comment]
>You have read that wrong. The loc-at command gives for an identifier where it is defined.So after loc-at the Bootstrap.hs file is expected.

Hmm, I think we are almost saying the same thing!  `penv0` is defined in Parser.hs (`library`, in `unison-parser-typechecker.cabal`) and referenced in Bootstrap.hs (`executable bootstrap`, in `unison-parser-typechecker.cabal`).

When I'm editing Bootstrap.hs, I want to Cmd-Click or Cmd-B to jump to the definition of `penv0`.  When I do that, a `loc-at` command is issued in the Event Log, and the result is correct: `/Users/arya/unison/parser-typechecker/src/Unison/Parser.hs:(31,1)-(31,6)` (the definition of `penv0`).  But the editor doesn't then **show** Parser.hs:(31,1)-(31,6); it just shows a tooltip saying "No usages found in Project Files".  But I would expect it to open `/Users/arya/unison/parser-typechecker/src/Unison/Parser.hs:(31,1)-(31,6)`, like what `loc-at` returned.

In this non-working case, the reference and the definition were in separate subprojects, `library` vs `executable bootstrap`.  If I try to jump to definition within the same single project, it does jump as expected.

For example, `Builtin.hs` also references `penv0`, and when I try to jump to definition from that file, it does work.

Thanks!

**Comment by aryairani** [comment]
Hmm, okay here is a new one I just took right now.  Only Bootstrap.hs is open.  The log contents shown below is what appeared when I Cmd-Clicked on `penv0`.

<img width="1059" alt="screen shot 2018-06-08 at 11 30 57 am" src="https://user-images.githubusercontent.com/538571/41166923-7a005382-6b0f-11e8-8961-26215c2b6b07.png">

**Comment by rikvdkleij** [comment]
I have uploaded new beta, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta15

Do you want to give it a try?

Btw, I want to improve the information you see when you hover with Cmd over a identifier. Show the type and where it is defined. And also show message when that info is not available because REPL is busy.

**Comment by aryairani** [comment]
Thanks, I will give it a try!

**Comment by aryairani** [comment]
<img width="1058" alt="screen shot 2018-06-08 at 3 43 18 pm" src="https://user-images.githubusercontent.com/538571/41177611-c8d9c9c0-6b32-11e8-8862-96566d065d18.png">

Behavior seems the same in beta15.

**Comment by rikvdkleij** [comment]
Weird, I can not reproduce your issue. Have to take another look.

**Comment by rikvdkleij** [comment]
It sometimes does not work when the REPL is busy with loading the file in the background. But then you should see a message as `No info because REPL is busy at this moment` in the status bar but probably you do not see that because you seeing all Logging events so that message gets overwritten.

I will try to show that message in a different way without becoming annoying 😄

**Comment by aryairani** [comment]
Yeah the REPL doesn't appear to be busy in my case, so I wouldn't worry
about that message. I just want it to jump to the definition :)

**Comment by rikvdkleij** [comment]
> I just want it to jump to the definition :)

Yes, I understand 😄 But sometimes they needed info is not (yet) available.

**Comment by aryairani** [comment]
Maybe I'm misunderstanding, but it seems like the needed info is exactly what's being shown in the Event Log.  e.g. In the last screenshot, I want to jump to `/Users/Arya/unison/parser-typechecker/src/Unison/UnisonFile.hs:(17,3)-(17,19)`, but it doesn't perform the jump.  And in the previous screenshot, I want to jump to `Parser.hs(31,1)`, just like it shows in the log; but it doesn't perform the jump.

**Comment by rikvdkleij** [comment]
It should be a location from the `Bootstrap.hs` file to the file where the identifier is defined.
So the needed info is not there.

The question is, does it sometimes happen or does it always happen. It should only occur when the REPL is loading the `Bootstrap.hs` file in the background.

**Comment by rikvdkleij** [comment]
>  If Bootstrap.hs is already open, and I want to navigate away from Bootstrap.hs, and I have the absolute path and location of the file I want to navigate to, then why does it need any information about Bootstrap.hs?

No, that is info from identifier with same name in other file. They also refer to location where that identifier is defined. But that info is missing from the Bootstrap.hs file.

Can you check in Event Log that REPL is started for target `unison-parser-typechecker:exe:bootstrap`? That is the target of the Bootstrap.hs file.

The problem is that I can not reproduce this issue.

**Comment by rikvdkleij** [comment]
> Yes, as far as I can tell, it only happens for Bootstrap.hs.

And does it always happen or sometimes?

**Comment by rikvdkleij** [comment]
Hmm, I think a found a bug which could cause your issue. Need some time to fix that and create new beta release after that.

**Comment by rikvdkleij** [comment]
Okay, cause is something else.

The `stack.yaml` contains:
```
ghc-options:
 # All packages
 "$locals": -Werror
```
The plugin does not start the lib target with these options (I did not know that this Stack feature exists, it would be nice if the REPL also got those options passed) . But when the lib is build, every warning will make the build fail and will cause that REPL of the exe target (from the Bootstrap.hs file) is not started. Didn't you see a message like: 
`Stack REPL could not be started for target `unison-parser-typechecker:exe:bootstrap` because a dependency has build errors`

You can try to get it working by commenting out those ghc-options in `stack-yaml`.

**Comment by rikvdkleij** [comment]
> You can try to get it working by commenting out those ghc-options in stack-yaml.

I will add ghc-option `-Wwarn` to the "internal build" of libraries to prevent this problem.

**Comment by aryairani** [comment]
> Stack REPL could not be started for target `unison-parser-typechecker:exe:bootstrap` because a dependency has build errors.
No, I don't see this message.

I do see this message:
```
10:06 AM	[global-stack-repl] stderr: 
				<no location info>: error:
				Could not find module ‘Main’
				It is not a module in the current program, or in any known package.
```

**Comment by rikvdkleij** [comment]
And does disabling the `--ghc-options` in `stack.yaml` help?

**Comment by aryairani** [comment]
No, it didn't seem to make any difference.

But I started over in a clean directory (new IntelliJ project) and it works not, even with the `ghc-options` still there.  So it seems the `ghc-options` weren't the problem.  But I can't reproduce anymore. 👍 

So maybe that means Beta 15 fixed it, but something lingering in the IntelliJ project files was causing an issue?  I don't know.  Thanks for your help.
