### ISSUE TITLE
Some problem with hlint

### ISSUE THREAD

**Issue by xgrommx** [rikvdkleij/intellij-haskell#279]
Hello @rikvdkleij I have some problem with hlint and I got this notification `hlint is not yet available`. I use stack 1.6.5

**Comment by xgrommx** [comment]
And also I got this one

```
2:53 AM	[global-stack-repl] Stack REPL could not be started within 5 seconds

2:53 AM	[global-stack-repl] /Users/dstoyano/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
```

**Comment by rikvdkleij** [comment]
Hlint is built in the background so it some time before it's available.

Looks like something wrong with your Stack installation. Does ‘stack --with-ghc intero‘ work in the project's root folder? Maybe first do ‘stack build intero‘

**Comment by rikvdkleij** [comment]
Btw, you can give latest version a try https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta14 but Stack version 1.6 is not supported anymore. You need version 1.7

**Comment by xgrommx** [comment]
@rikvdkleij After all manipulation (like a removing .stack-work and installing stack 1.7.1) I still get error like a

```
2:47 PM	[project-stack-repl-app10:lib] /Users/dstoyano/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)

2:47 PM	[project-stack-repl-app10:lib] Stack REPL could not be started within 5 seconds
```

**Comment by xgrommx** [comment]
@rikvdkleij Are u sure that it correct? `stack --with-ghc intero`

**Comment by rikvdkleij** [comment]
Sorry, it is `stack repl --with-ghc intero`

**Comment by rikvdkleij** [comment]
Maybe `stack update` helps to get intero build.

**Comment by xgrommx** [comment]
@rikvdkleij I got it

```
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: app10
Using main module: 1. Package `app10' component exe:app10-exe with main-is file: /Users/dstoyano/work/app10/app/Main.hs
Intero 0.1.21 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

/Users/dstoyano/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
```

**Comment by rikvdkleij** [comment]
Is the plugin working? 

Btw, I see you have an old version of Intero. 

You have to build Intero in your project's root folder otherwise you get compatibilities issues.

**Comment by Sir4ur0n** [comment]
Should we close this?

**Comment by rikvdkleij** [comment]
Please reopen if this is still an issue in latest betas.
