### ISSUE TITLE
No Haskell support for file  ... because no Stack target could be found for this file.

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#282]
In beta16, I am getting this pop-up:  "No Haskell support for file `BootStrap.hs` because no Stack target could be found for this file." but it doesn't have a target:

https://github.com/unisonweb/unison/blob/topic/typechecker/parser-typechecker/unison-parser-typechecker.cabal#L96-L98

Any ideas?

Thanks!

**Comment by aryairani** [comment]
Might be a regression from beta15?

**Comment by rikvdkleij** [comment]
I have tested beta16 with the Unison project (`topic/intellij-haskell`) and did not notice this problem.

Normally this error occurs when the (parent) directory which the file contains is not mentioned in the Cabal file.

**Comment by rikvdkleij** [comment]
Also with `topic/typchecker` I do not see this issue.

Can you execute `Invalidate Caches/Restart` in IntelliJ File Menu and reimport project?

**Comment by aryairani** [comment]
Okay, I will try, thanks.

**Comment by rikvdkleij** [comment]
I have checked the code changes between the two latest betas in this area and I do not see any major changes.

I have tried to reproduce your issue but without success.

**Comment by aryairani** [comment]
Okay thanks for trying.  I will send an update next time I can give it a try.

**Comment by rikvdkleij** [comment]
You can also check if the Source folders in Module Settings are right configured. It should happen all automatically but maybe something went wrong.

**Comment by rikvdkleij** [comment]
I have uploaded new beta with some improvements in importer. You can give it a try if you want 😄

**Comment by aryairani** [comment]
What is the latest version now?  With beta16 I was still experiencing failed lookups and hangs.

**Comment by rikvdkleij** [comment]
Beta17 is the latest but I have beta18 in the pipeline 😄 

But I stil can not reproduce your issue....

**Comment by rikvdkleij** [comment]
Released beta18 which hopefully solves all your issues with the plugin.

**Comment by francisdb** [comment]
1.0 Beta 25 still has this

We have a project with custom `Setup.hs` creating protobuf code (proto-lens)
Those files are created in `.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen`
an example project can be found here
https://github.com/google/proto-lens/tree/master/proto-lens-tutorial/coffee-order

If I open any of the files there I get the below error and intellij ideal locks up

<img width="353" alt="image" src="https://user-images.githubusercontent.com/161305/45221124-c8580500-b2b0-11e8-93e5-8ad3998c5b32.png">

(also I can't click through to those sources, the folder is not marked as a source folder)

**Comment by francisdb** [comment]
a similar issue happens when opening the custom `Setup.hs` in the project root

```
Could not determine Stack target for file `/myproject/Setup.hs` because no accompanying `hs-source-dirs` or `main-is` can be found in Cabal file(s)
```

**Comment by rikvdkleij** [comment]
@francisdb Thanks for reporting!

Hmm, IntelliJ should ignore files which are not project sources like files in `.stack-work`.

The plugin explicitly ignores `Setup.hs` in project directory, not in other directories.

**Comment by francisdb** [comment]
These are in fact project source files but they are generated
I would still like to able to navigate to them (cmd-O)
I'm not 100% sure but I think that for java(maven)/scala(sbt) projects these kinds of folders are marked as source folders

**Comment by rikvdkleij** [comment]
@francisdb Beta34 supports generated files in `.stack-work`. If IntelliJ says `No SDK` you wil have to add the Haskell module folder to sources in Project Settings.

**Comment by francisdb** [comment]
Thanks @rikvdkleij 
Unfortunately I no longer have access to that project so can't test at the moment.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
