### ISSUE TITLE
GHCi submenu always disabled ('send to', 'load module' etc. grayed out).

### ISSUE THREAD

**Issue by davips** [rikvdkleij/intellij-haskell#283]
What is the currently preferred way to access GHCi?
From the outside of Intellij?

**Comment by rikvdkleij** [comment]
By creating a `Haskell Stack REPL` in `Run/Debug configurations`.

**Comment by rikvdkleij** [comment]
When the REPL is running those options will not be disabled anymore.

**Comment by davips** [comment]
Thanks, I have not checked it out while running the REPL.

**Comment by rikvdkleij** [comment]
Please reopen if it is still an issue.
