### ISSUE TITLE
Reformat code as part of the "normal" Intellij flow

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#284]
Hello,

First of all this plugin is really nice, thanks alot for it!

While using it I was quite surprised that the default `Reformat code` shortcut did nothing. After some fiddling I found out the Haskell reformat is actually in `Code / Haskell / Reformat XXX` and not the standard `Code / Reformat code` menu.

Is there any reason stylish and/or hindent are not plugged on the "normal" `Code / Reformat code` menu? This would mean 1 shortcut no matter the language (we use several languages in my project), and more importantly, this would allow us to use the extremely useful `Reformat code` checkbox when committing with Intellij (everybody does that in the team so that we never have to worry about code style).

That would be awesome 😄 

Also, it seems we can't assign the same shortcut to both `Code / Reformat code` and `Code / Haskell / Reformat XXX` so it's not even possible to use the same shortcut for Haskell and non-Haskell projects.

**Comment by rikvdkleij** [comment]
Thanks for your report!

> First of all this plugin is really nice, thanks alot for it!

I'm glad you like it 😄 

> Is there any reason stylish and/or hindent are not plugged on the "normal" Code / Reformat code menu?

The reason is that the plugin does not use the IntelliJ's way of formatting. That is on my my wishlist for the future when the parser is improved. Some time ago I tried to hook in somewhere in the IntelliJ API but I could not get it working. So I gave up... Maybe I will take another look.

**Comment by Sir4ur0n** [comment]
That would really be awesome, making Haskell transition even smoother for developers giving it a try ;D

**Comment by rikvdkleij** [comment]
Released beta18 which contains your request.

**Comment by Sir4ur0n** [comment]
Hi,

I just tested and it doesn't seem to totally work.

1) "Reformat" shortcut still doesn't work (Ctrl + Alt + L by default on Windows). It does absolutely nothing.
2) On commit window, I see 2 new checkboxes "Reformat code by Hindent" and "Optimize imports by GHC warnings". I thought you could "plug" on the existing "Reformat code" / "Rearrange code" / "Optimize imports" checkboxes already existing in Intellij.
Is it possible? This would be better (though I can definitely live with those 2 new checkboxes)
3) It seems like it doesn't apply Stylish-haskell.

Code example
```haskell
import Control.Arrow
import qualified Control.Concurrent as Concurrent
import qualified Control.Monad as Monad
import System.IO

expectedToBeReformattedByStylishHaskell :: String -> String
expectedToBeReformattedByStylishHaskell "foo" = "bar"
expectedToBeReformattedByStylishHaskell _ = "default value"
```

After both Hindent and Stylish-Haskell I expect it to look like this
```haskell
import           Control.Arrow
import qualified Control.Concurrent as Concurrent
import qualified Control.Monad      as Monad
import           System.IO

expectedToBeReformattedByStylishHaskell :: String -> String
expectedToBeReformattedByStylishHaskell "foo" = "bar"
expectedToBeReformattedByStylishHaskell _     = "default value"
```
but it doesn't.

Tested on beta 21.

**Comment by rikvdkleij** [comment]
>  1 "Reformat" shortcut still doesn't work (Ctrl + Alt + L by default on Windows). It does absolutely nothing.

For me it works by using the default Reformat code shortcuts (MacOS and Linux). 
Do you see an error in the Event log?

> 2 On commit window, I see 2 new checkboxes "Reformat code by Hindent" and "Optimize imports by GHC warnings". I thought you could "plug" on the existing "Reformat code" / "Rearrange code" / "Optimize imports" checkboxes already existing in Intellij.

I understand, would be nicer, but did not see a way to hook into it. Can take another look later when I have some time but at this moment there are more important issues. It takes a lot of time to find out how to hook in without hacking to prevent I break default behavior of IntelliJ in other languages.

> It seems like it doesn't apply Stylish-haskell.

Mapped only Hindent to the default Reformat code shortcut.

**Comment by rikvdkleij** [comment]
> "Reformat" shortcut still doesn't work (Ctrl + Alt + L by default on Windows). It does absolutely nothing.

I wonder if you still have a shortcut for Reformatting with Hindent ?  I have not defined it anymore (because it's using the default shortcut).

**Comment by Sir4ur0n** [comment]
I think the misunderstanding comes from the fact that I removed the default shortcuts for all Haskell (Hindent / Stylish / Hindent + Stylish). I expected the default "Reformat code" to work both in editor and in commit window.

So overall there's no way to have both Hindent and Stylish trigger when using the standard "Reformat code"?
I know I can assign the default shortcut "Ctrl + Alt + L" to "Hindent + Stylish" but we still can't apply Stylish on commit window though.

Also, I understand it may be impossible (or really hard) to plug on the existing "Reformat code", but could we at least imagine another checkbox "Reformat code by Stylish" in the commit window? I have no idea if this is complicated.

**Comment by rikvdkleij** [comment]
In the next beta I will change the way the overriding is done. Maybe that helps in your case.

> So overall there's no way to have both Hindent and Stylish trigger when using the standard "Reformat code"?

It was just a choice of my to use only Hindent.  That's easy to change. In next beta I will use them both. Hopefully it's the right choice for most of the users 😄 

> Also, I understand it may be impossible (or really hard) to plug on the existing "Reformat code", but could we at least imagine another checkbox "Reformat code by Stylish" in the commit window? I have no idea if this is complicated.

I will take a look again to the commit window and see if the default checkboxes can be overridden. So `Reformat code` will use then Hindent and Stylish Haskell. If overriding does not work it, the new checkbox will do both.

> By the way I don't know if you're aware of it (sorry I've never developed an Intellij plugin), I think I found some documentation on how to plug on the standard "Reformat code" menu: https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/formatter.html 

See my first comment of this issue.

**Comment by rikvdkleij** [comment]
Just released beta23 with again improvements.

**Comment by Sir4ur0n** [comment]
Beta 23 just tested.

Did you change something about the shortcut? Now the default one (Ctrl + Alt + L on Windows) works!

And I confirm the "Haskell reformat code" works like a charm too. Thanks a lot for the effort, it's appreciated!

This is yet another step into making Haskell adoption a lot easier 😄

**Comment by rikvdkleij** [comment]
> Did you change something about the shortcut? Now the default one (Ctrl + Alt + L on Windows) works!

Yes, I changed the way it overrides the default and appears to help in your case 😄 

Hopefully all the other features also work like a charm 😉
