### ISSUE TITLE
IDE Error about running HLint

### ISSUE THREAD

**Issue by ndmitchell** [rikvdkleij/intellij-haskell#288]
```
Cannot run program "C:\Users\ndmit_000\.intellij-haskell\lts-11\bin\hlint" (in directory "C:\Neil\extra"): CreateProcess error=2, The system cannot find the file specified
```

I think this was caused by IntelliJ tried installing HLint, but turned out to hang because my internet connection had dropped. I restarted IntelliJ, and then that popped up.

**Comment by ndmitchell** [comment]
It also didn't try installing HLint that time around. I restarted IntelliJ and it properly said HLint wan't available and started installing it, so is there one path it misses the check somehow?

**Comment by rikvdkleij** [comment]
Thanks for reporting. This issue in fixed in master. So beta18 should prevent this error when for whatever reason the HLint build failed.

**Comment by ndmitchell** [comment]
Cool, feel free to close now then.

**Comment by rikvdkleij** [comment]
Should be fixed in beta18 so I close this issue. Please reopen if still an issue.
