### ISSUE TITLE
When a new version will be released?

### ISSUE THREAD

**Issue by eldargab** [rikvdkleij/intellij-haskell#29]

**Comment by h0tk3y** [comment]
I double request for IDEA 15 compatible build.

**Comment by rikvdkleij** [comment]
I will release new version this week. Current master is already compatible with IDEA 15.

**Comment by rikvdkleij** [comment]
Sorry, I need some more time....

**Comment by rikvdkleij** [comment]
Yesterday I released new version. The id of plugin is changed so new version is seen as new plugin.
