### ISSUE TITLE
Can't find how to enable event log

### ISSUE THREAD

**Issue by sergey-kintsel** [rikvdkleij/intellij-haskell#291]
there is no such option neither in event log -> settings nor in appearance -> notifications

**Comment by rikvdkleij** [comment]
Most simple way is use `Enter action` feature of IntelliJ and type `Event log`.

Btw, which plugin version and OS are you using?

**Comment by sergey-kintsel** [comment]
Beta12 and Ubuntu. I will check later this enter action when I get to my PC

**Comment by sergey-kintsel** [comment]
I just realized the meaning of your message. I found the Event log, I meant that there is no option to turn on the plugin's logs there

**Comment by rikvdkleij** [comment]
I do not see the problem. README is still right.

**Comment by sergey-kintsel** [comment]
I don't see `Haskell Log` option
![screenshot from 2018-08-07 17-59-54](https://user-images.githubusercontent.com/4972031/43774698-d6c2ec2a-9a6b-11e8-96e1-3ecea7721e55.png)
![screenshot from 2018-08-07 18-00-40](https://user-images.githubusercontent.com/4972031/43774703-d9d2d998-9a6b-11e8-9141-426789a50a7d.png)

**Comment by rikvdkleij** [comment]
Then check if the plugin is installed in `Plugins`.

**Comment by sergey-kintsel** [comment]
that's the first thing I did. 
![screenshot from 2018-08-07 18-16-13](https://user-images.githubusercontent.com/4972031/43775294-0036d128-9a6e-11e8-8515-202e29a5b67d.png)

**Comment by rikvdkleij** [comment]
Weird, I have no idea.

Can you install the latest beta according to the README?

**Comment by sergey-kintsel** [comment]
my bad. I installed from JetBrains repository version beta12. Thanks!

**Comment by rikvdkleij** [comment]
Still weird, that it's not visible in your case. Which version of IntelliJ do you use?

**Comment by sergey-kintsel** [comment]
latest 2018.2
