### ISSUE TITLE
Stack version should be > 1.7.0

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#299]
For some [Windows reasons](https://github.com/commercialhaskell/stack/issues/3797) I built and installed Stack from master branch (problems with bash coloring symbols being wrongly displayed in terminal) instead of the good ol' Windows installer coming from https://get.haskellstack.org/stable/windows-x86_64-installer.exe.

The problem being, the current Windows installer is 1.7.xxx while master branch is 1.10.0.

And yet, when I try to import a stack project into Intellij, in the Stack SDK window, when I try to add the path to my built 1.10.0 Stack exe, I get this error:

> 
> Select path to Stack binary
> Stack version should be > 1.7.0

I think there's something wrong with the Stack version being detected 😸

**Comment by rikvdkleij** [comment]
Oops 😊 Will fix that. Thanks!
