### ISSUE TITLE
Change only the color of the interface

### ISSUE THREAD

**Issue by provalinf** [rikvdkleij/intellij-haskell#30]
Hi,
Thank you for your excellent work, finally a solution to act on the ui, however, you would it be possible to add the ability (or create a mini project) to change only the color of the default interface (without touching the icons or the style of tabs)
Thank you

PS: I obviously try changing the xml files and .propertie with more or less success ...
Sorry for the translation

**Comment by rikvdkleij** [comment]
You can colors and fonts in `Settings/Editor/Haskell`
