### ISSUE TITLE
Intellij platform plugin still on beta 12

### ISSUE THREAD

**Issue by yunti** [rikvdkleij/intellij-haskell#300]
Just in case you weren't aware the version that can be downloaded via the intellij plugin platform is still on beta 12.  Not sure if this is an error or whether you just do releases to there periodically?

**Comment by rikvdkleij** [comment]
Well, you can install latest beta manually or by configuring alpha repo channel (see README). 

My plan is to release version 1.0.0 to the stable channel but it takes more time than I expected.

**Comment by yunti** [comment]
No problem.  Sorry I had missed the alpha channel in the README, that works perfectly.  
Thanks for a great plugin!

**Comment by rikvdkleij** [comment]
Also no problem 😄 I will have to make it more clear in the README.
