### ISSUE TITLE
Hoogle database should not be stored inside .stack-work

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#301]
Hoogle database generated by the plugin should not be generated inside `./.stack-work` as it can break the behaviour of `stack hoogle`.

As discussed, how about storing this plugin-specific Hoogle database inside `./intellij-haskell` of each project?

**Comment by rikvdkleij** [comment]
@Sir4ur0n  Is fixed in next beta.

**Comment by rikvdkleij** [comment]
This issue should also be solved in beta27.

**Comment by Sir4ur0n** [comment]
Hard to test/reproduce (I noticed this some day when I had a compilation error), I trust you 😄
