### ISSUE TITLE
.hindent.yaml should not be ignored

### ISSUE THREAD

**Issue by sir4ur0n** [rikvdkleij/intellij-haskell#304]
Options inside the `.hindent.yaml` except `indent-size` (which is overridden by Intellij Indent option) and `line-length` (which is overridden by Intellij Length option) should not be ignored.

Use case:
* In `.hindent.yaml` have this option: `line-breaks: [":<|>”]`
* Reformat in the plugin a multiline containing symbol `:<|>`

Expected: Lines starting with `:<|>` are not appended to the previous line.

Example:
```haskell
type ItemApi = "item" :> Get '[ JSON] [Item] 
    :<|> "item" :> Capture "itemId" Integer :> Get '[ JSON] Item
```

**Comment by rikvdkleij** [comment]
@Sir4ur0n  Is fixed in next beta.

**Comment by rikvdkleij** [comment]
Is this issue also solved in beta27?
