### ISSUE TITLE
Jump from/to test

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#307]
In Java there's this useful shortcut to jump from/to test (Main Menu / Navigate / Test).

It would be cool to have the same feature. I'm not 100% sure of the convention in Haskell, but what I do is, if I have a Haskell file in `./src/A/B/C/D.hs` then the test file is `./test/A/B/C/DSpec.hs`

**Comment by rikvdkleij** [comment]
Yes, agree 😄 Should be doable.
