### ISSUE TITLE
Navigate/Class should be more tolerant

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#310]
Example: my Module name is `AbCd.EfGh`.
When I use `Navigate / Class` and type `Efh` it should propose `AbCd.EfGh` module, the same way it does in Java.
Use case: I have a long module name `Abcdefghijkl` and also a test `AbcdefghijklSpec`. When looking for the test I don't want to type the whole name or be spammed with non-tests modules. I want to type `AbcSpec` and find it.
I think under the hood, it intercalates `.*` between each character and uses it as a regex for the Java feature.

**Comment by rikvdkleij** [comment]
I consider to use this Navigation action also to go to a function declaration, because that is currently missing.

Good idea?

**Comment by rikvdkleij** [comment]
About your issue 😄  I will take a look how to implement.

**Comment by Sir4ur0n** [comment]
I don't get your proposal. It already works for me O_o

**Comment by rikvdkleij** [comment]
Only for functions which have a type signature/declaration (which is of course normally the case).

**Comment by rikvdkleij** [comment]
Fixed in next beta.

**Comment by Sir4ur0n** [comment]
This doesn't seem to work?
![image](https://user-images.githubusercontent.com/1204125/46406443-dbbd8b00-c70b-11e8-9f4a-9214979e4f7d.png)

![image](https://user-images.githubusercontent.com/1204125/46406453-e11ad580-c70b-11e8-8d80-046c16a082b8.png)

![image](https://user-images.githubusercontent.com/1204125/46406461-e710b680-c70b-11e8-862b-a39763fc6a5e.png)

**Comment by rikvdkleij** [comment]
Did not test for that case :smile: 
Have to check if I can solve that case.

If you enter only `FB` it should work.

**Comment by rikvdkleij** [comment]
In next beta it is really fixed :smile:

**Comment by rikvdkleij** [comment]
Should be solved in beta 29.

Also fixed a regression issue, the declaration was not displayed anymore.

**Comment by Sir4ur0n** [comment]
Seems to work like a charm, thank you!
