### ISSUE TITLE
View / Navigate / Show type should instead be View / Expression type

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#311]
In Intellij there is already an action for displaying the type of something: View / Expression type.

Instead of defining its own action (which may be another shortcut, etc.), we should "plug" on the usual Intellij action.

**Comment by rikvdkleij** [comment]
Isn't that the one of the Scala plugin?

**Comment by Sir4ur0n** [comment]
Scala exposes another shortcut under `Plug-ins / Scala / Type Info` but Intellij has `View / Expression Type` by default. It works for Java also :) But it's plugged on the same default shortcut.
I just tried by removing the Scala shortcuts and using again `View / Expression Type` shortcut on some Java statement and it works fine. However it no longer works on Scala statements.
Please also note, the `View / Expression Type` shortcut also proposes to select all scopes starting at the cursor or cursor selection, unlike the Scala one which requires to select exactly the full statement you want the type of.
![image](https://user-images.githubusercontent.com/1204125/46209181-63cb1b80-c32d-11e8-8c8f-05cc5f639540.png)

Maybe `View / Expression Type` is Java specific? That would be kind of weird though.

**Comment by rikvdkleij** [comment]
The current solution works fine and is similar as the Scala plugin. For me this issue has no priority.

**Comment by Sir4ur0n** [comment]
My bad then, I thought there was a single shortcut for all languages. A bit of waste that each language creates another action, but it's indeed not very important then :x
