### ISSUE TITLE
Repo Contains No Obvious Link to Forum

### ISSUE THREAD

**Issue by jstr045329** [rikvdkleij/intellij-haskell#312]
I cannot find a link to a forum where it's appropriate to ask questions about this plugin. (I don't count this issue page because it's for issues, not questions on how to use it.) Is there such a forum? If not, are folks interested in starting one?

**Comment by rikvdkleij** [comment]
Well, there is a Gitter channel mentioned in README.

**Comment by jstr045329** [comment]
Will check it out. Thanks!
