### ISSUE TITLE
Consider using OS-specific directories instead of ~/.intellij-haskell

### ISSUE THREAD

**Issue by liff** [rikvdkleij/intellij-haskell#315]
It looks like intellij-haskell creates and uses `~/.intellij-haskell` as some sort of cache.

Would you consider using OS-specific cache directories instead, perhaps with the aid of [directories-jvm](https://github.com/soc/directories-jvm)?

Another option would be to use IDEA’s system directory but I guess that was not chosen for a reason.

**Comment by rikvdkleij** [comment]
What is the problem of using `~/.intellij-haskell` as directory to store data?

Btw, it's not a cache, it is persistent data.

**Comment by liff** [comment]
It’s not a problem, just a matter of convention. Since there are dedicated places for this sort of thing, why not use them?

**Comment by liff** [comment]
Closing since done.
