### ISSUE TITLE
"Choose test for null"

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#318]
When jumping to the test of a module, the display on top reads: "Choose test for null"
![image](https://user-images.githubusercontent.com/1204125/46860123-04cad380-ce10-11e8-81b6-cb321c4ccc56.png)

**Comment by rikvdkleij** [comment]
@Sir4ur0n Do you fix this one?

**Comment by Sir4ur0n** [comment]
I will but I can't assign it to myself 😄
