### ISSUE TITLE
Fail to load plugin descriptor from from the file "intellij-haskell-master.zip"

### ISSUE THREAD

**Issue by av-maslov** [rikvdkleij/intellij-haskell#32]
Hi,
I am trying to install plugin from the file on disk, but I see this message:
"Fail to load plugin descriptor from from the file "intellij-haskell-master.zip""
I tried to install it using by browsing repositories, but your plugin doesn't appear in the list of available haskell packages.

**Comment by rikvdkleij** [comment]
You are probably using IntelliJ version 15. I did not upload a intellij-haskell plugin compatible for version 15 to jetbrains repo.

**Comment by av-maslov** [comment]
I see. Thanks!
