### ISSUE TITLE
how to update from older version without losing project settings ?

### ISSUE THREAD

**Issue by simonmichael** [rikvdkleij/intellij-haskell#320]
Thanks a lot for Intellij-Haskell. I just discovered that there are unreleased newer versions available. So I'd like to test, but I don't want to lose my project's IDEA settings, at least not yet. I tried to create a new project with same src dir, but it wants to overwrite the .idea directory. I don't know if that will wipe settings or not.

Could docs be updated to say how/if we can upgrade, without losing project settings ?

**Comment by rikvdkleij** [comment]
Thanks that you like to test!

Sorry, I do not know how to save or migrate your project settings. The importer is also improved so also the structure of the libraries in the setting files.

Maybe for testing you can copy your project and import that project?

**Comment by rikvdkleij** [comment]
Hi @simonmichael 
I'm curious if the plugin works for you.
(I'm still busy with improving :-) )

**Comment by simonmichael** [comment]
Hi @rikvdkleij , thanks for the ping and for improving things. I have done a little more testing, using the hledger repo. I have cloned it to "hledger2" and imported this as a new IDEA project, per https://github.com/rikvdkleij/intellij-haskell#getting-started. I plan to see how far I can get this working. Then somehow redo or transfer the config back to the original "hledger" working copy. (Because I don't want to end up with "hledger2" in paths, or lose all the non-git-controlled content in that copy.) I'll keep a snapshot of "hledger" also, for comparing old and new configs in case I find something missing from my settings later.

My experiences so far are probably beyond the scope of this issue, I'll just briefly mention them, feel free to direct me elsewhere:
- it picked lts-11/ghc-8.2.2 to build most things with, though I have fully-populated lts-12/ghc-8.4 and nightly/ghc-8.6 snapshots. My default stack.yaml specifies nightly/ghc-8.6.
- it installed ghc, hindent, hlint, hoogle, stylish-haskell, intero etc. in the background for something like 1-3 hours (2013 macbook air 8G)
- when building intero, it chose ghc 8.6 and failed to build ([details](https://gist.github.com/simonmichael/65af273396924848293a8d6b1f0aa104))
- it failed to start the stack REPL because intero not found on path
- when I CMD-clicking on things, I see a lot of warnings like
>	Ambiguous Stack target for file `/Users/simon/src/PLAINTEXTACCOUNTING/hledger2/hledger-lib/Hledger/Data/Transaction.hs`. It can belong to the source dir of more than one Stack target/Cabal stanza. The first one of `Set(hledger-lib:lib, hledger-lib:test:doctests, hledger-lib:test:easytests)` is chosen.

**Comment by simonmichael** [comment]
- I installed a ghc-8.6-compatible intero (https://github.com/commercialhaskell/intero/issues/584) and did Tools -> Haskell -> Update settings & restart REPLS. 
- While this was running, the Haskell submenu disappeared from the Tools menu.
- In the event log, things got pretty confusing. Stack REPL was started, then stopped, started again, started again but failed because already running, intero was unsuccessfully built with ghc 8.6 again.. [details](https://gist.github.com/simonmichael/5f673d6ff86105fe104f2e41c091839e).
- Nevertheless, CMD-click navigate to definition is now working in most cases, across files (and into deps!), though sometimes only after a tens-of-seconds delay. Great - this is the first time I've got this far.
- I saw type info balloons on hover, briefly. Then that stopped working. Restarting REPLs again didn't seem to help.
- Find usages doesn't work yet.
- I saw a few nice transient yellow info balloons at bottom status bar, but couldn't seem to find a log window showing these. Just now there was one explaining why Navigation wasn't available, but the reason was obscured by IDEA's own event popup in lower-right corner, which I didn't manage to close before your balloon disappeared.

**Comment by rikvdkleij** [comment]
Thanks for your reports!

Sorry but the getting-started is not valid for the latest betas. All Haskell tools are now automatically installed by the plugin ( I assume you have installed the latest beta, beta30).

The yellow info balloon is notifying that if you want Hoogle navigation support, you have to generate the Hoogle database.

So by looking to your issues I think you just have to import your project and let the plugin do it's work :smile:

**Comment by rikvdkleij** [comment]
So all Haskell tools are build by using resolver LTS-11, except intero, intero is build per project because it has to be build by same GHC version as project.

**Comment by rikvdkleij** [comment]
I did not yet test with GHC 8.6. Have to take a look why plugin with intero does not work for that version.

**Comment by rikvdkleij** [comment]
> when I CMD-click on things, I see a lot of warnings like
"Ambiguous Stack target for file /Users/simon/src/PLAINTEXTACCOUNTING/hledger2/hledger-lib/Hledger/Data/Transaction.hs. It can belong to the source dir of more than one Stack target/Cabal stanza. The first one of Set(hledger-lib:lib, hledger-lib:test:doctests, hledger-lib:test:easytests) is chosen."

Those messages are intended. The plugin starts per Stack component a Stack REPL and has to know in which REPL a file has to be loaded. This message gives warning that in which REPL that file has to be loaded is ambiguous.

**Comment by simonmichael** [comment]
> That is intended, while project is built/initialized I have to prevent those action there.

If it's possible, better to grey out the submenu or its items I think. Seeing it disappear made me doubt myself, then the software, then you. :)

**Comment by rikvdkleij** [comment]
> If it's possible, better to grey out the submenu or its items I think. Seeing it disappear made me doubt myself, then the software, then you. :)

Okay, I wrote it wrong 😄  My intention was to disable those options but for some reason they are not visible. I remember that I already took a look to it in the past and came to the conclusion that it was a IntellliJ bug with submenus but I will take another look. Can also be my mistake....

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
