### ISSUE TITLE
False positive syntax error on Database.Beam.Schema.Tables

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#323]
Repro:

- Paste snippet on https://github.com/tathougies/beam/blob/da35f937101d3b978c366ed98f0d8c343c132b68/beam-core/Database/Beam/Schema/Tables.hs#L255-L263 to Haskell module or navigate there.

Expected: no syntax error

Instead:
 
![image](https://user-images.githubusercontent.com/89889/48300349-7881fe00-e4ec-11e8-8ada-4af4c696a5c4.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Similar as #324 also no issue for me.

Which version of the plugin are you using? Maybe it helps to reinstall plugin? Or `Invalidate Caches/Restart`?

**Comment by develop7** [comment]
Invalidating cache did make the issue go away. Should've trying this first.
