### ISSUE TITLE
Pasted code lacks trailing newline

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#324]
Repro:

- Consider following code in the Haskell scratch file:
```haskell
main :: IO ()
main = pure ()
```
- Move caret to first line, then "Edit → Cut" it then "Edit → Paste" back

Expected: the code looks unchanged

Instead:
```haskell
main :: IO ()main = pure ()
```

Environment: 
```
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.15-1-default
```

**Comment by rikvdkleij** [comment]
Thanks for reporting but I can not reproduce your problem. Did my best :smile: 

Maybe @Sir4ur0n can reproduce this issue?

**Comment by develop7** [comment]
@rikvdkleij whoa. Updated it with the "environment" mentioning Linux.

**Comment by rikvdkleij** [comment]
@develop7 I'm also on Linux...

Does is help to enter some newlines underneath?

**Comment by develop7** [comment]
> Does is help to enter some newlines underneath?

In fact it does! And the issue goes away! Mind. Blown.

**Comment by develop7** [comment]
OK, so when a file has *2* line feeds in the end, I can't reproduce the issue.

**Comment by develop7** [comment]
Deleting extra LF afterwards doesn't make the issue go back

**Comment by rikvdkleij** [comment]
I still can not reproduce this issue.

The problem could be that LF is not part of definition/expression.

**Comment by rikvdkleij** [comment]
The PSI tree is as expected. 

For some reason when you are cutting the line of code, the LF is not included.

**Comment by rikvdkleij** [comment]
It looks like I have to change to the parser for fixing your case but that will break other features.

**Comment by develop7** [comment]
@rikvdkleij the issue's bigger than just that: it seems that reformatting wipes, erm, some empty lines, see [Peek 2018-11-11 15-02.zip](https://github.com/rikvdkleij/intellij-haskell/files/2569343/Peek.2018-11-11.15-02.zip)

I'm kind of certain it wasn't the case until some of recent betas.

**Comment by rikvdkleij** [comment]
I have changed the parser so definitions will include one newline (not when EOF). I will test it for a few days and then release a new beta.

**Comment by develop7** [comment]
> Hindent removes the empty lines (always has been the case AFAIK).

Oh. Got it, sorry.

> I have changed the parser so definitions will include one newline

Sweet, thanks! Looking forward for it!

**Comment by rikvdkleij** [comment]
Should be fixed in beta35.

**Comment by develop7** [comment]
Nope, the issue affects beta35 too.

**Comment by rikvdkleij** [comment]
Did you do `Invalidate Caches/Restart`?

I can still not reproduce your issue. Not on MacOS and not on Linux.

**Comment by rikvdkleij** [comment]
I'm glad there is an explanation.

**Comment by develop7** [comment]
OK, I've removed this ephemeral file type back then but it keeps reappearing from time to time, making the issue pop up again:

![image](https://user-images.githubusercontent.com/89889/49364042-50a14700-f6f4-11e8-9513-a69d70974266.png)

Affects both Mac OS and Linux installations of both 2018.2 & 2018.3 (Ultimate).

**Comment by develop7** [comment]
Upstream issue: https://youtrack.jetbrains.com/issue/IDEA-203738

**Comment by rikvdkleij** [comment]
Maybe @ice1000 has an idea about it. I'm getting confused by all those different names: `Haskell`, `Haskell Language`, `Haskell file`, `Haskell language file` ...

**Comment by ice1000** [comment]
This isn't a problem, it's just the cache. IntelliJ's gonna cache file status and this might affect editing experience.

**Comment by develop7** [comment]
@ice1000 not according to IDEA devs it isn't, see https://youtrack.jetbrains.com/issue/IDEA-203738#streamItem-0-0-200-25892316

**Comment by ice1000** [comment]
Ok

**Comment by rikvdkleij** [comment]
I have changed the id of the Haskell filetype so it overrides the default one of IntelliJ. So there is only Haskell file type left. Hopefully that fixes this issue.

**Comment by develop7** [comment]
Fixed!

**Comment by develop7** [comment]
OK, the issue's back, in beta45 on IDEA 2019.1

**Comment by rikvdkleij** [comment]
Still only one Haskell file type....

**Comment by rikvdkleij** [comment]
@develop7 Can you also check that there is only one Haskell file type.

**Comment by develop7** [comment]
Yep, it's only one. I've checked it first thing before reopening. 

Funny thing though, the YAML file type is affected too. I'll go file an issue against it, and link here.

**Comment by develop7** [comment]
Okay, here goes [IDEA-211228](https://youtrack.jetbrains.com/issue/IDEA-211228)

**Comment by rikvdkleij** [comment]
@develop7  Thanks!

**Comment by develop7** [comment]
Okay, I apologize: now it is on me and the GPaste tool which had "trim clipboard content" option set to On.
