### ISSUE TITLE
Hoogle rebuild database does nothing with 1.0-beta

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#326]
I realized that executing Rebuild Hoogle database from Tools, Haskell seems to do nothing.
I don't get any error messages or error logs, but

* Hoogle Navigation stays disabled in the menu
* Ctrl+Q tells me that there is no hoogle database enabled

![grafik](https://user-images.githubusercontent.com/20992515/48382589-f9eeb180-e6e1-11e8-9834-f3af57d0cbe7.png)

`stack hoogle` works fine

Here is the output from Help, Haskell Project:

```
Stack version: 1.9.1

GHC: 8.4.4
Intero: Intero 0.1.34

HLint: HLint v2.1.10, (C) Neil Mitchell 2006-2018

Hoogle: Hoogle 5.0.17.3, http://hoogle.haskell.org/

Hindent: hindent 5.2.7

Stylish-haskell: stylish-haskell 0.9.2.0
```

Steps that I already tried:

* stack upgrade
* creating a new haskell project with both stack new and from IntelliJ IDEA
* throwing away all contents of the intellij-haskell directory in $HOME and $HOME/.cache
* switching back to lts-11x resolver in the stack.yaml
* upgrading to the latest beta plugin (1.0.0-34)

any suggestions how to solve/further analyze this problem would be highly appreciated!

**Comment by enolive** [comment]
Yep, it does

**Comment by rikvdkleij** [comment]
I see the problem. A regression issue. Thanks for reporting!

**Comment by rikvdkleij** [comment]
Should be fixed in beta35.

**Comment by enolive** [comment]
I can confirm that it works. Thanks!
