### ISSUE TITLE
Some imports are not highlighted as usages

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#328]
Repro:

* Import a project from https://github.com/develop7/ijhaskell-import-sample
* Navigate `Lib.hs`
* Position caret at 1) `Columnar` type usages on L15 or L16 2) `PrimaryKey` entry on L21

Expected: the appropriate `Columnar` and `PrimaryKey` imports are highlighted as usages and are navigated at by the "Edit → Find → Go to next/previous highlighted element usage" action. The `Columnar` usage in the L16 is highlighted as such when the caret is on it's usage on L15 and vice versa. Exactly same way `Identity` entries are highlighted: 
![image](https://user-images.githubusercontent.com/89889/48671797-9da2ec00-eb3e-11e8-9065-c054b5d3a5f3.png)

Instead: they are not: 
![image](https://user-images.githubusercontent.com/89889/48671813-b57a7000-eb3e-11e8-9d4e-73ef329386b3.png) 
![image](https://user-images.githubusercontent.com/89889/48671818-bf9c6e80-eb3e-11e8-8d65-e6fb614d0ab2.png)

Plugin version: 1.0 beta 35.

**Comment by rikvdkleij** [comment]
Thanks for reporting! It's fixed.

**Comment by develop7** [comment]
Resolved in beta36
