### ISSUE TITLE
Ignore keywords in regular pragmas

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#332]
Repro: 

* Consider following source fragment:
  ```haskell
  {-# OPTIONS_GHC -fno-warn-type-defaults #-}
  ```

Expected: `type` is not highlighted as keyword

Instead: 
![image](https://user-images.githubusercontent.com/89889/49142990-18bc8d00-f30b-11e8-8244-bcab40397e2f.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Yes, I also so noticed that but that not find good solution.

Maybe @ice1000 knows how to solve this?

**Comment by ice1000** [comment]
I'm not sure. I'll try this weekend (struggling with my essay 😭).

**Comment by ice1000** [comment]
Fixed.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/49316928-92e24280-f4c0-11e8-915b-75e13ef2e509.png)

Can I see your color settings?
It's here:

![image](https://user-images.githubusercontent.com/16398479/49316960-a9889980-f4c0-11e8-9692-66e211857abe.png)

**Comment by ice1000** [comment]
Well, it's really weird. I'm having the same issue, let me investigate more

**Comment by ice1000** [comment]
Seems that the property "bold" cannot be undone -- I can make other contents bold, but I can't make bold text unbold. Why? Oh my god.

**Comment by ice1000** [comment]
![a](https://user-images.githubusercontent.com/16398479/49317292-e86b1f00-f4c1-11e8-88cf-b0f6ebe9cb2d.gif)

**Comment by ice1000** [comment]
Trying to set the value explicitly in the config file

**Comment by ice1000** [comment]
Not working. Oh no!

**Comment by ice1000** [comment]
Well, at least the color is no longer orange...

**Comment by ice1000** [comment]
Let's re-open this @rikvdkleij.

My local dev branch resolves this in an ideal way, I hope I can re-close this issue in the PR :wink:
