### ISSUE TITLE
"Quick definition" tooltip should show whole definition

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#337]
Repro:

- Create new project with `stack new`, build it and import to IDEA
- Navigate to `src/Lib.hs` and change `someFunc` implementation following way:
  ```haskell
  someFunc = do
    putStrLn "someFunc"
  ```
- Navigate back to `app/Main.hs`, position caret to the `someFunc` call and issue `Quick Definition`

Expected: the tooltip shows whole definition, including function type and its' clauses

Instead: the tooltip shows only `someFunc = do` line.

**Comment by rikvdkleij** [comment]
Thanks for reporting! I know how to fix it.

**Comment by rikvdkleij** [comment]
Should be fixed in beta37.

**Comment by develop7** [comment]
Confirming it's fixed, yay!

**Comment by develop7** [comment]
Thanks, man!
