### ISSUE TITLE
Language injection for strings

### ISSUE THREAD

**Issue by ice1000** [rikvdkleij/intellij-haskell#340]
Like this
![image](https://user-images.githubusercontent.com/16398479/49250427-ca7fba80-f3ec-11e8-87ea-781234339e0d.png)

I may create a PR for this.

**Comment by ice1000** [comment]
@rikvdkleij To impl this, I need a special AST type for string literals, while currently there isn't one:

```bnf
private literal             ::= DECIMAL | HEXADECIMAL | OCTAL | FLOAT | CHARACTER_LITERAL | STRING_LITERAL

private general_id          ::= QUASIQUOTE | q_name | symbol_reserved_op | reserved_id | LEFT_PAREN | RIGHT_PAREN | FLOAT |
                                  SEMICOLON | LEFT_BRACKET | RIGHT_BRACKET | literal | LEFT_BRACE | RIGHT_BRACE |
                                  COMMA | QUOTE | BACKQUOTE | fixity |
                                  inlinelike_pragma | DIRECTIVE | scc_pragma

private line_expression     ::= general_id+
```

I need you to modify the AST shape, cus it's large change and we have different Grammar-Kit version, which is gonna cause some large diff

**Comment by ice1000** [comment]
Ping?

**Comment by rikvdkleij** [comment]
Can we not sync our grammar kit versions?

I want to release new beta today and tomorrow I got on holiday. I have no time. Also afraid to break thing now.

I would say, just go ahead.

Btw, what is the purpose of having Haskell language injection for strings?

**Comment by ice1000** [comment]
> I want to release new beta today and tomorrow I got on holiday. I have no time. Also afraid to break thing now.

I understand.
So you mean I can re-generate the parser and cause a large diff?

**Comment by ice1000** [comment]
> Btw, what is the purpose of having Haskell language injection for strings?

Example usage taken from my plugin:
![](https://plugins.jetbrains.com/files/10413/screenshot_17879.png)

**Comment by ice1000** [comment]
Notice the doc-string above before line 32, and the regex string at line 39.

**Comment by rikvdkleij** [comment]
> Notice the doc-string above before line 32, and the regex string at line 39.

Sorry, but I do not see it...

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/49296273-cb185f80-f485-11e8-8e5b-df2b16e8a65d.png)

**Comment by rikvdkleij** [comment]
> So you mean I can re-generate the parser and cause a large diff?

Well, you can just develop with your locally generated parser and later we will see.
Maybe we can use the same grammar kit version later. It could also be that the large diff is caused by optimized imports.

**Comment by ice1000** [comment]
> It could also be that the large diff is caused by optimized imports.

Yeah and the generated code style is now different.

**Comment by ice1000** [comment]
Closing as implemented.
