### ISSUE TITLE
Absurd completion in import statements

### ISSUE THREAD

**Issue by ice1000** [rikvdkleij/intellij-haskell#347]
![image](https://user-images.githubusercontent.com/16398479/49313693-1c404780-f4b6-11e8-9386-a0bf2522164e.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting! I can reproduce it.

**Comment by rikvdkleij** [comment]
Should be fixed.

**Comment by ice1000** [comment]
Closing.
