### ISSUE TITLE
Auto completion issue

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#35]
will show code completion hint dialog when typing inside a string literal.

![report](https://cloud.githubusercontent.com/assets/6234553/14733420/705c707e-0895-11e6-8b77-3e285ec26104.gif)

**Comment by rikvdkleij** [comment]
I will fix that in next release. Thanks for reporting.

**Comment by zjhmale** [comment]
maybe i will give it a shot if i get some times :)
