### ISSUE TITLE
Feature Request: Navigate to Class Instances

### ISSUE THREAD

**Issue by Cosmius** [rikvdkleij/intellij-haskell#353]
It would be desirable that I can navigate to the instances of the class

e.g.

```haskell
class Show a where      -- [1]
   show :: a -> String  -- [2]

-- might be in other file
instance Show Int where -- [3]
  show x = undefined    -- [4]
```

I want to navigate from line 1 to line 3.
And it would be better if when I click `show (23 :: Int)`, I can navigate to line 4 instead of line 2.

**Comment by ice1000** [comment]
Yes, and there should be something like `LineMarker`s, just like they are in IntelliJ's Scala/Java support.

I want this as well, can you do that? @rikvdkleij

**Comment by rikvdkleij** [comment]
It's already there: Navigate/Haskell/Instance Declaration.

**Comment by ice1000** [comment]
@Cosmius Hi, could you plz try a little bit?

**Comment by ice1000** [comment]
Also, @Cosmius could u plz report the issue related to jumping to the wrong definition you mentioned yesterday?

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
