### ISSUE TITLE
Error while calling hlint

### ISSUE THREAD

**Issue by normenmueller** [rikvdkleij/intellij-haskell#363]
After the update to `1.0.0-beta37` I get the following error when initiating "GoTo":

    Error while calling hlint: Warning: Can't find file "MachDeps.h" in directories
    /Users/nrm/Sources/MDPM/learning/haskell/misc/scratch/lib/base-4.12.0.0/GHC
    .
    Asked for by: /Users/nrm/Sources/MDPM/learning/haskell/misc/scratch/lib/base-4.12.0.0/GHC/Base.hs  at line 109 col 1

**Comment by rikvdkleij** [comment]
There is no relation between a GoTo action and Hlint. This is a Hlint issue.

**Comment by normenmueller** [comment]
Ah. OK. So let's close this one.
