### ISSUE TITLE
Completion for record projectors is broken

### ISSUE THREAD

**Issue by ice1000** [rikvdkleij/intellij-haskell#369]
Giving unexpected type info

![screen](https://user-images.githubusercontent.com/16398479/50512024-e600e280-0aca-11e9-9a60-be91b91f7d2f.gif)

Maybe `.split(":")` will help.

**Comment by rikvdkleij** [comment]
I do not understand why it's only problem for `binderKind` field.

I'm trying to reproduce it....

**Comment by rikvdkleij** [comment]
But I have some issue with code completion. Maybe that is the cause.

**Comment by ice1000** [comment]
> I do not understand why it's only problem for binderKind field.

No, all record fields are completed that way. Not limited to `binderKind` field.

**Comment by ice1000** [comment]
Yes.

```haskell
type AstBinderInfo  = AstBinderInfo' AstTerm' Name
data AstBinderInfo' t c = AstBinderInfo
  { binderName :: c
  , binderType :: t c
  , binderKind :: AstBinderKind' (t c)
  } deriving (Eq, Ord, Show)

-- | i should be something like a @Term@
data AstBinderKind' t
  = LambdaBinder
  -- ^ Lambda abstraction
  | TelescopeBinder Visibility
  -- ^ Pi type's binding
  | LetBinder t
  -- ^ Let binding
  | GeneratedBinder t
  -- ^ Intermediate value binding generated
  deriving (Eq, Ord, Show)
```

I think it's enough, missing definitions can be mocked arbitrarily (too large don't post).

**Comment by rikvdkleij** [comment]
Nope, can not reproduce it. 

Weird that that the code completion shows a single colon between name and type.

Maybe a Windows issue. I will check later on Windows.

**Comment by rikvdkleij** [comment]
This issue is caused because `DuplicateRecordFields` is  enabled. Will fix it.

**Comment by rikvdkleij** [comment]
Should be fixed in beta39.  

FYI, enabiing `DuplicateRecordFields` causes ghci `browse` to return different syntax for record field declarations (it contains `$sel`). 

Btw, enabiing `DuplicateRecordFields` breaks definition location for record fields in `intero`.

**Comment by rikvdkleij** [comment]
@ice1000 Is this issue fixed?

**Comment by ice1000** [comment]
Yes!
Closing.
