### ISSUE TITLE
Does hlint work?

### ISSUE THREAD

**Issue by yury-pachin** [rikvdkleij/intellij-haskell#37]
Inspection by HLint;
Quick fixes for HLint suggestions;

How does it work? I don't see any suggestions.

**Comment by zjhmale** [comment]
@yury-pachin it will occurs error when something is wrong and deteted by hlint, you can hover to the position to see the lint message and press `alt+enter` to quick fix it.

![2016-04-24 11 57 25](https://cloud.githubusercontent.com/assets/6234553/14765485/33a965a6-0a16-11e6-9a47-5fcf5c2de4e7.png)
![2016-04-24 11 57 38](https://cloud.githubusercontent.com/assets/6234553/14765484/33a8f490-0a16-11e6-8ee8-e7f6ef2a9716.png)

**Comment by yury-pachin** [comment]
For instance http://take.ms/wi6Bb
And ide doesn't show any suggestion. When obviously http://take.ms/nXC71

**Comment by zjhmale** [comment]
yeah, i also find this issue, i'm trying to fix it out.

**Comment by yury-pachin** [comment]
Thanks!

**Comment by rikvdkleij** [comment]
@zjhmale  Thanks for explaining 👍 

Well, I'm in doubt if everyone wants to have HLint on by default. In my opinion it's better to improve README

**Comment by zjhmale** [comment]
hlint turn on by default when using emacs/spacemacs. 😄

**Comment by rikvdkleij** [comment]
hlint is optional dependency so not by default enabled.
