### ISSUE TITLE
Other jetbrains IDE

### ISSUE THREAD

**Issue by Vozf** [rikvdkleij/intellij-haskell#370]
The plugin is unavailable in other ides and I don't see any particular global reason for plugin to be bounded to IDEA solo. So are there any plans for making it available for all ides other than IDEA. I've seen this issue but there was neither the explanation of reasons to use IDEA api nor there were any plans for making it crosside available https://github.com/rikvdkleij/intellij-haskell/issues/146 The answer to use IDEA is definitely not the answer people want to hear.

**Comment by rikvdkleij** [comment]
The explanation in #146 is that the plugin uses an API which is only available in IntelliJ. 

Maybe the plugin can be changed in a way to make it independent from IntelliJ but that has to be investigated. Any help is appreciated.

**Comment by yunti** [comment]
@rikvdkleij Can you confirm the API you're using which isn't in Pycharm?  Thanks.

**Comment by rikvdkleij** [comment]
@yunti Sorry for the late response.

> Can you confirm the API you're using which isn't in Pycharm?

Took a quick look into the code but I can't remember where the problem is/was.

**Comment by yunti** [comment]
@rikvdkleij no problem if it's anything like the intellij reasonml plugin then it probably uses modules which are only available in intellij and not pycharm, webstorm etc....

**Comment by Vozf** [comment]
Why is this getting closed?

**Comment by rikvdkleij** [comment]
I have no time to investigate this. Also no prio for me.
If you want to help go ahead and I will support you.
