### ISSUE TITLE
Feature request: automatically close quotes

### ISSUE THREAD

**Issue by yunti** [rikvdkleij/intellij-haskell#373]
For several languages in intellij when adding quotes (double or single) these are automatically added as a pair with the cursor ready in between.  However with the Haskell plugin this isn't currently the case and would be a great addition.

(brackets, curly and square all work like this really well).

**Comment by rikvdkleij** [comment]
That's an issue introduced in the latest beta. Already fixed in master.

**Comment by yunti** [comment]
Excellent, thanks for all your work.
