### ISSUE TITLE
Less intrusive "No Haskell Support" warning

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#374]
Please consider making it a hint bar on top of the editor window or adjusting available inspection profiles: anything more subtle. Currently it pollutes event log tool window with less than helpful messages, worsening the out-of-Stack-project editing experience.

**Comment by rikvdkleij** [comment]
Do you mean this one?
`No Haskell support for file [name] because no Stack target could be found for this file")`

**Comment by rikvdkleij** [comment]
Or `Haskell support is not available while project is initializing`?

**Comment by develop7** [comment]
Ya, the former one, `No Haskell support for file [name] because no Stack target could be found for this file`

**Comment by rikvdkleij** [comment]
Hmm, when do you get this message? It should normally not happen.

**Comment by develop7** [comment]
I get it while editing a Haskell source outside of any Haskell module. Here's a screenshot of event log 
![screenshot from 2019-01-11 14-25-10](https://user-images.githubusercontent.com/89889/51078602-c1128f00-16c8-11e9-8cb9-74a249eed3af.png)

**Comment by rikvdkleij** [comment]
Ok, then I understand the cause of the message.

Message is to warn user that there is no Haskell support because no REPL is running. Only syntax highlighting.

**Comment by develop7** [comment]
Works for me, looking forward to test it!

**Comment by rikvdkleij** [comment]
> Works for me, looking forward to test it!

Great to hear 😄

**Comment by rikvdkleij** [comment]
Should be fixed in beta41.

**Comment by ice1000** [comment]
Nice!

**Comment by rikvdkleij** [comment]
In beta41 the UI  should also be much more responsive.

**Comment by develop7** [comment]
Couldn't find the message in the "Messages" and "Events", all's great otherwise.

**Comment by rikvdkleij** [comment]
They are only visible when you enable `Haskell Logs` in Event Log.

**Comment by rikvdkleij** [comment]
Hmm, otherwise I have to create another NotificationGroup. Could consider that..

**Comment by rikvdkleij** [comment]
Created new Notification group to show the warnings in the status bar.

**Comment by develop7** [comment]
Sweet, that should do it.

**Comment by rikvdkleij** [comment]
Btw, do you notice that UI is more responsive?

**Comment by develop7** [comment]
To think of it I actually do!

**Comment by rikvdkleij** [comment]
Done in beta42.

**Comment by develop7** [comment]
Yup that does it indeed

**Comment by rikvdkleij** [comment]
Great, thanks for testing!
