### ISSUE TITLE
Installs a local copy of ghc-8.6.3, even though it's already installed system-wide

### ISSUE THREAD

**Issue by mouse07410** [rikvdkleij/intellij-haskell#376]
I have `ghc-8.6.3` installed as a part of Haskell Platform. And I'm somewhat limited in disk space - to the point when I cannot afford every project installing its own copy of GHC, especially the one that's already installed.

Is there anything I (or you) can do to prevent this pointless cloning?

**Comment by rikvdkleij** [comment]
>  I cannot afford every project installing its own copy of GHC,

That's not right. Stack only installs GHC when it's not there yet (in `~/.stack`)..

> Is there anything I (or you) can do to prevent this pointless cloning?

Take a look to the `system-ghc` option.

**Comment by mouse07410** [comment]
`system-ghc: true` is set is all of my `stack` config files.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
