### ISSUE TITLE
TemplateHaskell not building?

### ISSUE THREAD

**Issue by Vlix** [rikvdkleij/intellij-haskell#381]
I'm just trying out IntelliJ with my Haskell project, and it's not going very well.

Next to the "`stack haddock` doesn't work because of a bug in GHC", I've also run up against TemplateHaskell not building. It's a `persistent` function that takes a `FilePath`:
```
share [mkPersist sqlSettings, mkMigrate "migrateModels"]
    $(persistFileWith lowerCaseSettings "config/models")
```
I have a multi-project stack setup. The directory where the `stack.yml` is located ("big-project") has directories which all have `.cabal` files with the necessary `src` and `config` directories. ("project1", "project2", etc.)
The error I get is that it doesn't find the file... though it's right there and building with stack from anywhere in the main "big-project" directory works no problem, but stack run by IntelliJ can't find the file?
```
19:35	error:
  • Exception when trying to run compile-time code:
      config/models: openFile: does not exist (No such file or directory)
    Code: persistFileWith lowerCaseSettings "config/models"
  • In the untyped splice:
      $(persistFileWith lowerCaseSettings "config/models") at /home/user/big-project/project1/src/PersistentModels.hs:25:5
```

**Comment by Vlix** [comment]
I also get this:
`Can not determine Stack target for file Haskell file because no accompanying `hs-source-dirs` can be found in Cabal file(s)`

All the .cabal files are fine. Every library/executable/test-suite has defined the `hs-source-dirs` correctly. What the hell is `Haskell file` anyway?

**Comment by rikvdkleij** [comment]
> Next to the "stack haddock doesn't work because of a bug in GHC", 

Can you elaborate?


> Can not determine Stack target for file Haskell file because no accompanying `hs-source-dirs` can be found in Cabal file(s)

Looks like you are using an old beta version of the plugin because message should mention file path.

To install latest beta see,
https://github.com/rikvdkleij/intellij-haskell#installing-latest-beta-of-the-plugin

It will automatically install all Haskell tools in an IntelliJ sandbox.

**Comment by rikvdkleij** [comment]
When you give example project I can try to reproduce problem with latest version.

**Comment by Vlix** [comment]
The stack haddock problem is because of a bug in the latest GHC versions. GHC doesn't keep to one of its own invariants concerning module re-exports with type families or something, which makes haddock segfault or whatever.
(I believe `esqueleto` has this problem, so just try `stack build --haddock` on the latest version with the latest GHC and it'll probably fail to build documentation. And our own project in production has the same, it's rather annoying.)

I'll try the latest beta this week to see if that at least fixes the one error.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
