### ISSUE TITLE
optF pragma incorrectly parsed

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#382]
Based on [tasty-discover documentation](https://hackage.haskell.org/package/tasty-discover) and [GHC spec](https://downloads.haskell.org/~ghc/8.6.3/docs/html/users_guide/phases.html?highlight=optf#ghc-flag--optF%20%E2%9F%A8option%E2%9F%A9), the string following `-optF` should be passed to the preprocessor.

Intellij Haskell incorrectly interprets options containing `--` in a pragma, example:
```haskell
{-# OPTIONS_GHC -F -pgmF tasty-discover -optF --tree-display #-}
```
The error is
```
Error:(1, 4) HaskellTokenType.CON_ID, HaskellTokenType.DIRECTIVE or HaskellTokenType.NEWLINE expected, got 'OPTIONS_GHC'
```

![image](https://user-images.githubusercontent.com/1204125/52487689-72b8b900-2bbe-11e9-9c13-baab034f7b0e.png)

**Comment by Sir4ur0n** [comment]
Surprisingly this seems to work fine with new lines:
```haskell
{-# OPTIONS_GHC
  -F -pgmF tasty-discover -optF --tree-display
 #-}
```

**Comment by rikvdkleij** [comment]
Thanks for reporting! Will fix it.

**Comment by rikvdkleij** [comment]
Okay, this was really an unexpected struggle to get fixed. Problem is that parser sees everything that starts with `--` as comment.

Got a proper solution at the cost of no code completion within the pragma.

**Comment by rikvdkleij** [comment]
@ice1000 Do you know a better solution?

**Comment by ice1000** [comment]
Yes, create a lexer state and parse everything inside the pragma as some trivial tokens

**Comment by rikvdkleij** [comment]
@ice1000 
That's not clear for me, Can you give example?

**Comment by rikvdkleij** [comment]
@ice1000 

On a second thought, that's what I already implemented as solution for this issue. See the commit. The point is that the whole options_ghc pragma is one big token. So I thought, maybe you  know a better solution.

**Comment by ice1000** [comment]
@rikvdkleij I'll try to elaborate my solution with a PR.

**Comment by rikvdkleij** [comment]
@ice1000 Many thanks in advance!

I do not want to push but any idea when you can create a PR?

**Comment by ice1000** [comment]
This weekend.

**Comment by ice1000** [comment]
I see some garbage lexical tokens like `HS_DOUBLE_QUOTE`. These are no longer used but kept `general_pragma_content`..

**Comment by ice1000** [comment]
Checkout my PR. I hope I'm not making stupid mistakes.

Bomb my PR with edge cases!
