### ISSUE TITLE
Renaming a module should rename it in the .cabal file as well

### ISSUE THREAD

**Issue by kenranunderscore** [rikvdkleij/intellij-haskell#383]
Right now, if I use the `Refactor -> Rename...` option on a module, it correctly renames it everywhere but in the `.cabal` file.
This seems to be relevant only for projects which do not use `package.yaml` though.

**Comment by rikvdkleij** [comment]
Thanks for reporting 😄

**Comment by ice1000** [comment]
@rikvdkleij To implement this you may be interested in RenameHandler

**Comment by rikvdkleij** [comment]
@ice1000 Thanks for the pointer!
