### ISSUE TITLE
Rename sometimes aborted and leaves names inconsistent

### ISSUE THREAD

**Issue by letmaik** [rikvdkleij/intellij-haskell#384]
After initiating rename on a local variable, all the occurences change while I type, but then for weird reasons it may happen that the final rename doesn't work when I press enter. This results in the identifier under the cursor to have the new name, but all the others to revert to the old name. This is very annoying as it means I need to check each time whether everything went alright.

**Comment by rikvdkleij** [comment]
Thanks for feedback!

Does the name of the identifier starts with a quote`'` or ends on a dot`.`?

**Comment by letmaik** [comment]
No, just letters.

**Comment by rikvdkleij** [comment]
I only know this annoying behavior with identifiers which start with quote or ends on dot, that is an IntelliJ bug: https://youtrack.jetbrains.com/issue/IDEA-204576

Can you give some info about how I can reproduce this issue? When does it happen?
I can only guess that this happens just after loading a module and the cache is invalidated.

You can enable Event log to see what is going in the background. See README how to enable.

**Comment by rikvdkleij** [comment]
It should be improved in beta45, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta45. Also uploaded to the JB plugin repo but can take some days before they have approved.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
