### ISSUE TITLE
High cpu usage with ghc-mod

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#39]
sometimes when auto complete code, it will get stucked and freeze IDEA.

![2016-04-24 11 50 58](https://cloud.githubusercontent.com/assets/6234553/14765915/e611e14c-0a29-11e6-80ef-d9250d3681f0.png)

i currently use 

```
ghc-mod version 5.5.0.0 compiled by GHC 7.10.3
```

**Comment by rikvdkleij** [comment]
I'm busy with replacing `ghc-mod` by `stack repl` offline.

Reason is long history of issues with `ghc-mod`. My last issue was that I could build project with `stack` but `ghc-mod` did did not work.

**Comment by zjhmale** [comment]
any link about this `ghc-mod` upstream issue?

**Comment by rikvdkleij** [comment]
No, I did not report it this time.

**Comment by rikvdkleij** [comment]
I only see advantages in replacing `ghc-mod` by `stack`. Most important advantage is no dependency anymore. When it builds with "your" GHC version and Stack, plugin also works.

**Comment by zjhmale** [comment]
https://www.reddit.com/r/haskell/comments/3cf5yd/stack_ghcmod_work_in_progress/ some deprecated attempt.

**Comment by zjhmale** [comment]
can you show any details about you current stage? i'm really interested 😄 . do you attemp to add a subcommand for stack to do the auto complete stuff instread of using ghc-mod?
>I'm busy with replacing ghc-mod by stack repl offline.

**Comment by zjhmale** [comment]
after disable `HaskellCompletionContributor.scala`, when editing code still get high cpu usage with ghc-mod

![2016-04-24 10 00 07](https://cloud.githubusercontent.com/assets/6234553/14768022/f5b773ee-0a67-11e6-92fc-b444f89e5732.png)

have you met this issue before? @rikvdkleij i think it's a big issue here, really disturb :joy:

**Comment by rikvdkleij** [comment]
>can you show any details about you current stage? i'm really interested 😄 . do you attemp to add a subcommand for stack to do the auto code completion stuff instread of using ghc-mod?

`stack repl` of `ghci` can give me almost same info as `ghc-mod` but it's obtained in different away. Have to use some tricks :-)

**Comment by rikvdkleij** [comment]
I had issues with running `ghc-mod check` in interactive mode. This check is also not consistent, see issue #275 of `ghc-mod`. Workaround is to go again back to for checking files with `ghc-mod check` instead of checking files in interactive mode (legacy mode) of `ghc-mod`.

So I suspect checking files in interactive mode is causing this problem.

**Comment by rikvdkleij** [comment]
I have pushed changes to replace ghc-mod legacy-interactive `check` by `ghc-mod check`.

Can you give it a try?

**Comment by zjhmale** [comment]
ok, i'll update it.

**Comment by zjhmale** [comment]
is it possible that `ghc-mod` will search `.idea` and `.stack-work` directory? there are a lot file there.

**Comment by zjhmale** [comment]
i just tried https://github.com/mkasa/neco-ghc-lushtags/blob/master/bin/ghc-mod-cache and it works fine, the cpu usage of ghc-mod remained around at %15. we should implement a similar middle layer inside the plugin 😄

**Comment by zjhmale** [comment]
currently, i just comment the code here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/external/GhcModProcess.scala#L102-L107 to get a better performence for self usage 😂 . btw, i can not quite figure out what is `ghc-modi` or `ghc-mod legacy-interactive` command's job here, no docs or wiki can be found about it.

**Comment by rikvdkleij** [comment]
I have implemented a ghc-mod cache with com.google.common.cache but apparently it does not prevent ghc-mod from running high cpu usage. So some special condition in which it occurs.

See for example: GhcModInfo

**Comment by rikvdkleij** [comment]
Btw, I found the problem I had with ghc-mod getting to work, it was built with older Stackage lts version than currently used in my Haskell projects.

**Comment by rikvdkleij** [comment]
> currently, i just comment the code here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/external/GhcModProcess.scala#L102-L107 to get a better performence for self usage :joy: . 

If you comment those line out, there will be no communication anymore between ghc-mod legacy-interactive and intellij 

>btw, i can not quite figure out what is ghc-modi or ghc-mod legacy-interactive command's job here, no docs or wiki can be found about it.
There is no difference, see https://github.com/DanielG/ghc-mod/issues/639

**Comment by zjhmale** [comment]
cool, see it. sorry i did not walk through the whole project 😂 
>I have implemented a ghc-mod cache with com.google.common.cache but apparently it does not prevent ghc-mod from running high cpu usage. So some special condition in which it occurs.

See for example: GhcModInfo

**Comment by zjhmale** [comment]
my ghc-mod is build with ghc 7.10.3 and i use ghc 7.10.2 with my haskell projects, maybe i should reinstall ghc-mod then.
>Btw, I found the problem I had with ghc-mod getting to work, it was built with older Stackage lts version than currently used in my Haskell projects.

**Comment by zjhmale** [comment]
i know, but it really get much faster 😂 
>If you comment those line out, there will be no communication anymore between ghc-mod legacy-interactive and intellij

**Comment by rikvdkleij** [comment]
>i know, but it really get much faster :joy:

Wait till I replaced `ghc-mod` by `stack repl` :smile:

**Comment by zjhmale** [comment]
can't wait to use it 😄 
>Wait till I replaced ghc-mod by stack repl.

**Comment by zjhmale** [comment]
yeah, i know `ghc-mod legacy-interactive` is just a replacement of `ghc-modi`, i mean through the doc here http://www.mew.org/~kazu/proj/ghc-mod/en/ `ghc-mod` covers all the commands `ghc-modi` has, i can't figure out why should have an interactive mode.
>There is no difference, see DanielG/ghc-mod#639

**Comment by rikvdkleij** [comment]
@zjhmale I forgot to mention that IntelliJ gets more responsive if you disable autopopup code completion

**Comment by zjhmale** [comment]
thx for mention that, but after i disabled communication with ghc-modi and intellij, i can still get code completion for some symbols, so maybe it's just fine for now. 😄 
>@zjhmale I forgot to mention that IntelliJ gets more responsive if you disable autopopup code completion

**Comment by rikvdkleij** [comment]
You currently only getting completions from getVariants in HaskellReference.

**Comment by zjhmale** [comment]
indeed 😂 
>You currently only getting completions from getVariants in HaskellReference.

**Comment by rikvdkleij** [comment]
ghc-mod is not used anymore in latest version.
