### ISSUE TITLE
Unexpectedly long start-up time

### ISSUE THREAD

**Issue by sheyll** [rikvdkleij/intellij-haskell#393]
This plugin is great, thanks a lot. 

There is this one problem though: It takes about 5 Minutes on a decent workstation to load our project.

We have around 200 modules and 30000 lines of code.

In the event-log we see that the many modules are being loaded several times (one module 14 times for example).

It seems that it is `:browse!`-ed every time it is imported.

```
$ grep 'browse' startup.1.log | grep B9Lib.Util
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 6 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 6 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 6 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 8 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 8 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 6 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 6 ms
4:39 PM	[project-stack-repl-vm-deployment:lib] Command :browse! B9Lib.Util took + 5 ms
```

Is this a bug, or a configuration problem on my behalf, or just wrong expectations? 

I am surprised, that the same modules are loaded so many times.

**Comment by rikvdkleij** [comment]
Thanks!

Yes, I see, that can be approved. Reason is that that kind of caching is done per file. But because of another change that can be changed.

But I do not think that is the main reason of the long initialization time. For every library component a REPL is sequentially started (otherwise REPL gives error). That takes some time, also because there have to be some pause after that one REPL is started up and next one will be started.

How many library components does your project have?

**Comment by sheyll** [comment]
Well, we have a single cabel file with one `lib` and three executables.
My colleague, who made the log file with intellij-idea, is currently away, and I desperately try to find how to produce a log file from the plugin, do you have a tip for me how I can make log files with intellij-haskell plugin output?

**Comment by rikvdkleij** [comment]
As last point in https://github.com/rikvdkleij/intellij-haskell#getting-started is written how you can enable the Haskell Event Log.
I do not know how to redirect to log file.

**Comment by rikvdkleij** [comment]
One lib component is not much. Then the reason is also the preloading of (library) module identifiers.

**Comment by sheyll** [comment]
Yeah I got that event log from the comprehensive README (thanks for that btw), but I just have no clue on how my colleague managed to get logs, intellijs documentation was not helpful to me, either.

What are module identifiers?

**Comment by rikvdkleij** [comment]
> What are module identifiers? You mean the symbols exported by a module?

Yes.

**Comment by scameronde** [comment]
I am a colleague of sheyll but not the one that produced the first log lines.

I am working on a new computer (new Core i7, 32 GB ram, fast ssd) and get better results, but I do want to double check if the warm-up times are corresponding with your expectations (running on linux).

- on the command line `stack clean; stack build` of our project takes 40 seconds
- "Busy with preloading caches"  runs for  1 minute and 30 seconds
- "Navigation ist not available at the moment ..."  for another 20 seconds.

The log contains 1694 lines "Command :browse! ..." each somewhere between 3ms and 300ms

And as sheyll said: thank you for this great plugin!

**Comment by rikvdkleij** [comment]
@scameronde Thanks for your feedback!

I'm busy which improvements which have to speedup the start-up time but do not expect large improvements. The plugin needs to do some preloading to become responsive. Also limited by the REPL which can not handle concurrent requests.

**Comment by rikvdkleij** [comment]
It should be improved in beta45, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta45. Also uploaded to the JB plugin repo but can take some days before they have approved.

**Comment by rikvdkleij** [comment]
Is it improved in beta45?

**Comment by scameronde** [comment]
It improved a lot.

- time for "Busy preloading caches" went from 90 seconds down to 32 seconds
- time for "Navigation is not available ..." went from 20 to 15 seconds

All in all, you managed to more than half the startup time. Impressive.

Thank you a lot!

**Comment by rikvdkleij** [comment]
@scameronde Great to hear!

**Comment by sheyll** [comment]
@rikvdkleij Wow, thanks so much!
