### ISSUE TITLE
Add option to disable Repl

### ISSUE THREAD

**Issue by AllanWang** [rikvdkleij/intellij-haskell#395]
I'm building a compiler that uses happy, so as a result there are notably big files (> 1000 lines)

The plugin worked great before generating the happy files, but afterwards, the ide would constantly freeze and my macbook pro would run quite hot.

![image](https://user-images.githubusercontent.com/6251823/53676216-26b4dd80-3c6d-11e9-9d6d-15466da2dbf2.png)

It seems like the repl is repeatedly trying to reload. While I would certainly like it to work, I would also like to disable it if it doesn't work the first 30 tries, while keeping the remaining features within the plugin (syntax highlighting + linting). Would it be possible to either cancel the attempts after a lot of tries, or to disable it manually altogether?

**Comment by rikvdkleij** [comment]
Does it help to increase the REPL timeout in Settings?

**Comment by AllanWang** [comment]
Thanks! 30 seconds seems to work better for me. We also downgraded happy since the compile time went from 5 seconds from old builds to 2 minutes in new builds. That was probably the reason
