### ISSUE TITLE
Add SUT_NAME variable to Haskell Test Module template

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#396]
A common Haskell pattern is in tests to import the tested module as `SUT` to easily see what is being tested:
```haskell
-- A.Bc.Def.FooSpec.hs
import qualified A.Bc.Def.Foo as SUT
```

We need to have the module name available for the file template. E.g. provide variable `${SUT_NAME}`.

I'll try to find time to provide a PR about this.

**Comment by rikvdkleij** [comment]
> I'll try to find time to provide a PR about this.

Great!
