### ISSUE TITLE
File navigation goes to wrong file

### ISSUE THREAD

**Issue by AllanWang** [rikvdkleij/intellij-haskell#401]
If I have `Base.hs` in both my src folder and test folder, and I have a module in my source folder that imports the source `Base`, it seems to navigate to the test version. Not sure why this is the case

**Comment by rikvdkleij** [comment]
When they have also the same module name, the plugin does not know which one. 

And what if you import `Base` in a test file, which one do you mean then?

**Comment by AllanWang** [comment]
That makes sense. When I did my import it defaulted to the test file which is what I wanted so I didn't realize. Thanks!
