### ISSUE TITLE
Cannot download cabal config file for stack resolver lts 13.14

### ISSUE THREAD

**Issue by mouse07410** [rikvdkleij/intellij-haskell#402]
We've already been there in #377 - but apparently it's not resolved:
```
15:48	Can not download cabal config file for stack resolver lts-13.14, please check your network environment.
```

Your current beta of the plugin, Intellij IDEA 2019.1. 
```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
$ 
```
and `intero` is on the path in `$HOME/.cabal/bin/`

How to proceed?

**Update**
Not sure if it's related - but I'm getting a ton of these:
```
[project-stack-repl-SplitStr:lib]  : can't load .so/.DLL for: libHSghc-prim-0.5.3.dylib (dlopen(libHSghc-prim-0.5.3.dylib, 5): image not found)
```

`SplitStr` is the name of my project. Don't know what `stack` it uses, but `stack` in general runs on this machine. Can't figure what executable is trying to `dlopen(libHSghc-prim...)`, but it would be good to know. Also, all the main/normal components appear to work:
```
$ happy --version
Happy Version 1.19.9 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Marlow

Happy is a Yacc for Haskell, and comes with ABSOLUTELY NO WARRANTY.
This program is free software; you can redistribute it and/or modify
it under the terms given in the file 'LICENSE' distributed with
the Happy sources.
$ happy --version
Happy Version 1.19.9 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Marlow

Happy is a Yacc for Haskell, and comes with ABSOLUTELY NO WARRANTY.
This program is free software; you can redistribute it and/or modify
it under the terms given in the file 'LICENSE' distributed with
the Happy sources.
$ hindent --version
hindent 5.2.7
$ hdocs --version
Usage:
  hdocs <module> - get docs for module/file
  hdocs <module> <name> - get docs for name in module/file
  hdocs dump [r] - dump all installed docs, if [r], find docs for reexported declarations

flags
              --pretty       pretty JSON output
  -g GHC_OPT  --ghc=GHC_OPT  option to pass to GHC

$ intero --version
Intero 0.1.39
$ hsdev version
0.3.3.1
$
```
but of course all of the above were installed via `cabal`, not `stack`. `stack` fails to install most of them.

**Comment by rikvdkleij** [comment]
This issue has nothing to do with Stack. Plugin tries to download a file from stackage.org which fails.

**Comment by mouse07410** [comment]
Can you do anything about it? Maybe have the plugin copy from `$HOME/.cabal/config` if it exists, and https://stackage.org did not provide its own?

Also, would you know what's happening with (or, more importantly, what causes) this:
```
[project-stack-repl-SplitStr:lib]  : can't load .so/.DLL for: libHSghc-prim-0.5.3.dylib (dlopen(libHSghc-prim-0.5.3.dylib, 5): image not found)
```

**Comment by rikvdkleij** [comment]
> Can you do anything about it? Maybe have the plugin copy from $HOME/.cabal/config if it exists, and https://stackage.org did not provide its own?

Yes, will change the plugin so it will fallback to a default `cabal.config`.

> Also, would you know what's happening with (or, more importantly, what causes) this:

Looks like this issue:
https://github.com/chrisdone/intero/issues/43

You should not install intero globally. The plugin builds intero with same Stackage resolver/GHC version as your project.

**Comment by mouse07410** [comment]
I'd very much prefer to be able to force the plug-in to use my local intero, because as you saw for yourself, the plug-in fails to build it on my setup (the now-famous libiconv problem).

**Comment by rikvdkleij** [comment]
> Are there other solutions/workarounds that I'm missing?

No, not with current solution.

**Comment by mouse07410** [comment]
If the plugin would not automatically attempt to build everything, or at least have an option to not plunge into building `intero` as soon as the project is created - perhaps I could place the needed binaries where it expects them, and avoid this problem.

If there would be a per-resolver or per-GHC location that the plugin knew about, and looked there for the needed binaries such as `intero` before or instead of trying to build it itself - I think it would resolve my problems, or at least improve the situation.

**Comment by rikvdkleij** [comment]
Next beta will fall back to default `cabal.config` if the one of project's resolver can not be downloaded.

**Comment by mouse07410** [comment]
Thank you - appreciated!

May I ask to take `$HOME/.stack/global-project/stack.yaml` and `$HOME/.cabal/config` as the defaults, please? There is a reason why `cabal` and `stack` allow customizing their installations, and IMHO it is not proper for the plugin to drop it all and pull defaults from elsewhere. If those defaults worked OK for the user - he wouldn't need to customize those files in the first place.

**Comment by rikvdkleij** [comment]
> May I ask to take $HOME/.stack/global-project/stack.yaml and $HOME/.cabal/config as the corresponding defaults, please? There is a reason why cabal and stack allow customizing their installations, and IMHO it is not proper for the plugin to drop it all and pull defaults from elsewhere. If those defaults worked OK for the user - he wouldn't need to customize those files in the first place.

I do not understand this remark. It has nothing to do with the `cabal.config` of this issue.

**Comment by mouse07410** [comment]
> I do not understand this remark

I mean - when a new project is created via Intellij-Haskell, it appears to download `stack.yaml` and such from wherever it downloads the LTS itself. It would be nicer if it took the local `stack.yaml` found as `~/.stack/global-project/stack.yaml`.

**Comment by rikvdkleij** [comment]
The plugin does not download `stack.yaml`

**Comment by rikvdkleij** [comment]
This cabal.config is only used for code completion in cabal file (which I told you before).

**Comment by mouse07410** [comment]
You are right about cabal.config. I apologise. 

Regarding stack.yaml - somehow when a new project is created, something places stack.yaml file there. I wonder what they entity is, and whether it should be a copy of "~/.stack/global-project/stack.yaml".

**Comment by rikvdkleij** [comment]
That is from stack's default template for a new project.

**Comment by mouse07410** [comment]
I wonder if that can be a template on my local machine, which I could customize?

**Comment by rikvdkleij** [comment]
Please reopen when still an issue.
