### ISSUE TITLE
Weird display with NumericUnderscores

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#406]
Display is weird for numbers with underscores:

```haskell
{-# LANGUAGE NumericUnderscores #-}

foo = 10_000
```

![image](https://user-images.githubusercontent.com/1204125/55312194-2a52a480-5465-11e9-8fe9-de2b8375c488.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting! Will fix it.

**Comment by rikvdkleij** [comment]
Fixed in next beta.

**Comment by rikvdkleij** [comment]
Should be solved in beta46.

**Comment by Sir4ur0n** [comment]
Thank you!
