### ISSUE TITLE
Git commit loops

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#407]
When commiting in Intellij (Git), most of the times, it loops a few times before it actually commits.
I tried to make a gif to better explain:
![intellij-haskell-commit-bug](https://user-images.githubusercontent.com/1204125/55313699-b87c5a00-5468-11e9-8422-b2974f97a1b9.gif)

Using either "Commit" or "Commit and push", with either keyboard shortcut or mouse click, this happens.

As you can see I need to click at least 5 times before it triggers.

**Comment by rikvdkleij** [comment]
And of you only select the “Haskell” options?

**Comment by Sir4ur0n** [comment]
I'll give it a try and let you know!

**Comment by Sir4ur0n** [comment]
Indeed it seems that unchecking everything but the Haskell options works like a charm. Thank you!
