### ISSUE TITLE
Troubles with HLint under 2019.1

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#408]
After upgrading to 2019.1, I noticed some troubles with HLint. 
For some reasons, at some point I don't get any more hints from HLint.

For example, 

```haskell
data Age = Age Int
```

should get me a warning that I can replace `data` with `newtype`. This warning stops appearing after some time with the latest version of IntelliJ-Haskell (45-beta). The only way to get the warnings back is to restart the REPL. I downgraded to 44-beta and cannot reproduce this issue there.

I cannot say for sure if the upgrade to 2019.1 or a problem with 45-beta is the cause.

**Comment by rikvdkleij** [comment]
It's an issue of beta45. Already fixed locally. Problem is that IntelliJ inspection is running before file is saved.

**Comment by rikvdkleij** [comment]
Should be solved in beta46.

**Comment by enolive** [comment]
works fine now! Thanks
