### ISSUE TITLE
Feature request: Adapt it to work with Idris

### ISSUE THREAD

**Issue by PhilAndrew** [rikvdkleij/intellij-haskell#41]
It would be really great if Idris could work within IntelliJ and it is close to Haskell in syntax. It also has a IDE mode.

**Comment by rikvdkleij** [comment]
My first priority is to develop a solid Haskell plugin. Maybe later use my knowledge to create Purescript and Idris plugins.

**Comment by PhilAndrew** [comment]
Someone has started an Idris plugin for IntelliJ here https://github.com/cb372/intellij-idris

**Comment by zjhmale** [comment]
@PhilAndrew I have already ported a VSCode Extension for Idris https://github.com/zjhmale/vscode-idris, I'm also working on a Language Server Protocol for it. But personally I think the Idris toolchain is not mature enough (package manager, lint tool, stylish tool etc.) and a text editor is cool enough for playing around with it currently. Maybe someday we can integrate Haskell, Purescript, Idris and Agda in one powerful language plugin 😄 , that will be wonderful.

**Comment by rikvdkleij** [comment]
Sorry but I will not adapt the plugin to work with Idris.
