### ISSUE TITLE
Hoogle database still not available

### ISSUE THREAD

**Issue by mouse07410** [rikvdkleij/intellij-haskell#411]
Somewhat similar to #372 , except it persists.
Tools are present:
```
$ ll ~/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-13/bin
total 107168
drwxr-xr-x   7 ur20980  staff       224 Apr  2 18:27 ./
drwxr-xr-x  14 ur20980  staff       448 Apr  2 23:02 ../
-rwxr-xr-x   1 ur20980  staff   9928976 Apr  2 17:32 hindent*
-rwxr-xr-x   1 ur20980  staff  14049432 Apr  2 17:08 hlint*
-rwxr-xr-x   1 ur20980  staff  20504036 Apr  2 17:37 hoogle*
-rwxr-xr-x   1 ur20980  staff   1654460 Apr  2 17:32 intero*
-rwxr-xr-x   1 ur20980  staff   8723164 Apr  2 18:27 stylish-haskell*
$ 
```

"Rebuild the Hoogle database" appears to succeed - except it doesn't seem to load anything from remote sites like Hackage ("Messages" after "Menu->Tools->Haskell->(Re)Build Hoogle database"):
```
Information:/Users/ur20980/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-13/bin/hoogle generate --local=/Users/ur20980/src/Str3Split/.stack-work/install/x86_64-osx/lts-13.2/8.6.4/doc --database=/Users/ur20980/Library/Caches/com.github.rikvdkleij.intellij-haskell/Str3Split/hoogle
Information:Starting generate
Information:[1/4] Str3Split... 0.00s
Information:[2/4] base... 
Information:0.49s
Information:[3/4] ghc-prim... 
Information:0.20s
Information:[4/4] integer-gmp... 
Information:0.01s
Information:Found 24 warnings when processing items
Information:Reordering items... 0.00s
Information:Writing tags... 
Information:Writing names... 
Information:0.02s
Information:Writing types... 
Information:0.05s
Information:Took 0.81s
```

Generated DB describes functions I wrote, but not what's on Hackage/Stackage:
<img width="499" alt="Screen Shot 2019-04-03 at 3 47 47 PM" src="https://user-images.githubusercontent.com/5923577/55509131-6cc4de80-5629-11e9-91aa-e26b738e0847.png">

Please let me know what log might help you, and how to obtain/retrieve it. Thanks!

**Update**
Going into the project directory `$HOME/src/Str3Split` and running `stack hoogle ...` there produced:
```
$ stack hoogle --rebuild -- --count 50
Rebuilding database ...
Haddock index for local packages already up to date at:
/Users/ur20980/src/Str3Split/.stack-work/install/x86_64-osx/lts-13.2/8.6.4/doc/index.html
Haddock index for local packages and dependencies already up to date at:
/Users/ur20980/src/Str3Split/.stack-work/install/x86_64-osx/lts-13.2/8.6.4/doc/all/index.html
Haddock index for snapshot packages already up to date at:
/Users/ur20980/.stack/snapshots/x86_64-osx/lts-13.2/8.6.4/doc/index.html
Built docs.
Starting generate
Reading ghc-pkg... 0.05s
[4/38] base... 0.51s     
[11/38] ghc... 1.51s      
[33/38] xhtml... 0.03s           
Packages missing documentation: ghc-paths network random rts syb
Found 37 warnings when processing items

Reordering items... 0.02s
Writing tags... 0.07s
Writing names... 0.10s
Writing types... 0.32s
Took 4.28s
Generated DB.
package base
package bytestring
package deepseq
package array
package filepath
package ghc-prim
package unix
package containers
package binary
package directory
package time
package transformers
package ghc-boot-th
package integer-gmp
package process
package rts
package ghc-boot
package ghc-heap
package ghci
package mtl
package pretty
package template-haskell
package terminfo
package text
package hpc
package parsec
package stm
package Cabal
package Str3Split
package ghc
package ghc-compact
package ghc-paths
package haskeline
package libiserv
package network
package random
package syb
package xhtml
$ 
```
It did not affect the outcome - same "No documentation" popup as shown above.

**Comment by rikvdkleij** [comment]
I guess this issue is solved in next beta.

**Comment by mouse07410** [comment]
I think it is!! @rikvdkleij thank you!!

(Will re-open if it pops up again, in the meanwhile I'm very happy.)

**Comment by mouse07410** [comment]
Strange: for some Haskell-provided functions the plugin finds the documentation, but for, e.g., `Data.List` members it does not. Needless to say, this is after I did `(Re)Build Hoogle database`.

Here's the code in question (file `src/Lib.hs`):
```
module Lib
  ( splitStr
  , chunker
  , splitMore
  ) where

import Data.List (intercalate, unfoldr)

--import Data.List.Split
splitStr :: Int -> String -> String
splitStr n z =
  foldr
    (\x c st ->
       case n - st of
         0 -> ' ' : x : c 1
         _ -> x : c (succ st))
    (const "")
    z
    0

chunk'' :: Int -> [a] -> [[a]]
chunk'' n = takeWhile (not . null) . unfoldr (Just . splitAt n)

chunker :: Int -> [a] -> [[a]]
chunker = chunk''

splitMore :: Int -> String -> String
splitMore n z = intercalate " " $ chunk'' n z
```

Here's the good answer I get highlighting `takeWhile`:
<img width="394" alt="Screen Shot 2019-04-16 at 21 56 05" src="https://user-images.githubusercontent.com/5923577/56255337-838c1c00-6092-11e9-8fdf-a4f3f2dcc7f6.png">

Here's the bad answer I get highlighting `intercalate`:
<img width="261" alt="Screen Shot 2019-04-16 at 21 57 02" src="https://user-images.githubusercontent.com/5923577/56255369-97d01900-6092-11e9-87d7-57207ecf3fe8.png">
Same `No documentation found / Data.OldList    -- No type info available` message for `unfoldr`.

It does give me docs for `unwords`, if I replace `intercalate " "` with `unwords`. But not for `intercalate` and `unfoldr`... Why???

**Comment by mouse07410** [comment]
https://github.com/rikvdkleij Do you have any idea what prevents some documentation from showing or from being retrieved? Any prediction on when it might be fixed?

**Comment by mouse07410** [comment]
@rikvdkleij ping?

**Comment by rikvdkleij** [comment]
I will take a look soon.

**Comment by mouse07410** [comment]
Any luck finding the cause...?

**Comment by rikvdkleij** [comment]
Hmm, works for me on master.

**Comment by mouse07410** [comment]
Is master what's available as Beta? Because it doesn't work for me, as you can see from the screenshots above.

**Comment by rikvdkleij** [comment]
You try can try beta47.

**Comment by mouse07410** [comment]
> You try can try beta47.

Currently available is beta46, of Apr 29th. Hopefully beta47 would become available soon?

**Comment by rikvdkleij** [comment]
Waiting for approvement of Jetbrains. Otherwise you can download the zip from here https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta47 and install manually.

**Comment by rikvdkleij** [comment]
Beta48 is approved by Jetbrains.

**Comment by mouse07410** [comment]
Thanks. Installed the beta-48 update. Somewhat different interface, nice, but this problem remains. I rebuilt the Hoogle database. Anything else that I should try to remedy this?

![Screen Shot 2019-06-04 at 2 38 22 PM](https://user-images.githubusercontent.com/5923577/58904966-acb24b80-86d6-11e9-9893-fb5dbb155db3.png)

Is there anything else that might help you help me? Maybe a zip of this project?

**Comment by rikvdkleij** [comment]
Are you sure the Hoogle db is generated correctly?

> Is there anything else that might help you help me? Maybe a zip of this project?

Yes, that is okay.

Btw, in my local version I have removed `intero`. Currently doing some testing. 
I will soon release a new beta which can be tested. Are you interested and do you want to test this version without `intero`?

**Comment by rikvdkleij** [comment]
Hmm, wait, now I also have an issue with documentation but it's different than yours.

Do you see an message in the Event log which says something like:
```
No documentation because no location info could be found for identifier `intercalate` because No info because Data.List is not loaded or found
```

In your case the documentation tool windows mention `Data.OldList` while it should mention `intercalate`.

**Comment by rikvdkleij** [comment]
Works again for me. Issue was related to removing `intero`.

**Comment by mouse07410** [comment]
Here's the project: 
[str3split.tar.gz](https://github.com/rikvdkleij/intellij-haskell/files/3254709/str3split.tar.gz)

> I will soon release a new beta which can be tested. Are you interested and do you want to test this version without `intero`?

I certainly am interested - though it depends on what you're replacing `intero` dependency with. 

> In your case the documentation tool windows mention `Data.OldList` while it should mention `intercalate`

Well, it seems to claim that `intercalate` is in the `Data.OldList` module, and it has no documentation for it. Attempts to `import Data.OldList(intercalate)`, of course, failed.

**Comment by mouse07410** [comment]
On another machine, same update, same code, same symptoms. And an observation - `unwords` documentation was there, but look at the bottom of the popup:
![Screen Shot 2019-06-04 at 19 32 35 ](https://user-images.githubusercontent.com/5923577/58920440-36c2da00-8700-11e9-821c-e47294213d6d.png)

And here's how `unfoldr` doc fails:
![Screen Shot 2019-06-04 at 19 33 07 ](https://user-images.githubusercontent.com/5923577/58920449-417d6f00-8700-11e9-8304-64e5be270ae5.png)

**Comment by rikvdkleij** [comment]
> I certainly am interested - though it depends on what you're replacing intero dependency with.

Intero is removed, not replaced by something else. So the REPL/GHCi does not load intero anymore.

**Comment by mouse07410** [comment]
> Intero is removed, not replaced by something else. So the REPL/GHCi does not load intero anymore.

Yes I'm certainly interested. Likewise, I'd be very interested in the ability to use pre-installed tools (e.g., `~/.local/bin/hlint` or `~/Library/Haskell/bin/hlint` - both directories on the PATH, BTW) instead of re-building these tools by the plugin).

**Comment by rikvdkleij** [comment]
About the update. The versions are as expected because they equal to versions in latest LTS-13.

About the Hoogle documentation issue. I will change the implementation to get consistent output. For some reason the output with constraints on module name(s) does not always work as expected.

**Comment by rikvdkleij** [comment]
> Yes I'm certainly interested.

Great!

> Likewise, I'd be very interested in the ability to use pre-installed tools (e.g., ~/.local/bin/hlint or ~/Library/Haskell/bin/hlint - both directories on the PATH, BTW) instead of re-building these tools by the plugin)

The plugin needs this feature anyway when supporting Cabal projects (which is now doable because intero is removed). So then the plan is to add to Haskell settings a field which contains the path to folder which contains the Haskell tools binaries with the remark that building the tools not automatically can have the consequence that a feature of the plugin because tool API is not expected by plugin. The plugin is only tested with the Haskell tools in certain  Stackage LTS.
It's appreciated if you can reword that and create a warning text in Haskell settings window because I'm not a native English speaker :smiley:

**Comment by rikvdkleij** [comment]
Btw, I really want to remove the extra Stack arguments (which I added for you because of intero) because it's a really ugly feature which is unmaintainable. If you don't mind I will remove it in the next version.

**Comment by mouse07410** [comment]
1. I doubt that my English is any better than yours, but I'll be happy to assist rewording the warning. Give me some time for that.

2. If I can tell the plug-in to use tools that reside in a specified directory (and but to attempt rebuilding them), I think it would suffice - therefore the extra Stack arguments may be removed. I'd expect that any invocation of Stack would respect the global configuration files like `~/.stack/config.yaml` and `~/.stack/global-config/stack.yaml`, so whatever flags/parameters I need, would come from there.

I welcome this direction of development very much.

**Comment by mouse07410** [comment]
@rikvdkleij here's the vetted text. You can edit it more, but it's been approved by the native English speakers:
```
WARNING! This plugin was tested only with the Haskell tools from the Stackage LTS.
Providing a folder with your own Haskell tools (and thus avoiding automatic rebuild
or download of these tools) could cause some features of this plugin to break,
because the API that your tools provide may differ from what the plugin expects.
```

**Comment by rikvdkleij** [comment]
@mouse07410 Thanks!

Btw, I will continue with development of plugin asap.

**Comment by rikvdkleij** [comment]
Should be fixed in beta49, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta49.

It does not yet contain the new setting with own Haskell tools folder. Had to release asap because of issue #438

**Comment by mouse07410** [comment]
Understood, thanks!

From your experience, how fast does Jetbrains make the updates available? A couple of days? A week? Longer?

**Comment by rikvdkleij** [comment]
You can install new version by downloading the zip and installing from disk inside IntelliJ.

> From your experience, how fast does Jetbrains make the updates available? A couple of days? A week? Longer?

Each time differently, so I have no idea this time.

**Comment by rikvdkleij** [comment]
It's been approved!

**Comment by mouse07410** [comment]
> It's been approved!

Wow! JetBrains must have heard us. And it works! Thank you!!

Looking forward for the new settings now.

I wonder if it would be possible to have not one but multiple directories allowed, so that, e.g., I could use tools in both `~/.local/bin/` and `~/.cabal/bin/` (and maybe in `~/.ghcup/bin/`).

**Comment by rikvdkleij** [comment]
> I wonder if it would be possible to have not one but multiple directories allowed, so that, e.g., I could use tools in both ~/.local/bin/ and ~/.cabal/bin/ (and maybe in ~/.ghcup/bin/).

To keep it simple it will be one directory. You can always create symbolic links.

> Does this plugin support debugging? I seemed unable to set a breakpoint - but perhaps it was a pilot error...

No, that's a project on it's own. I think it's doable but it is a lot of work and investigation.
See also https://github.com/rikvdkleij/intellij-haskell/issues/105

**Comment by mouse07410** [comment]
I think Hoogle database is functional now, thanks.
