### ISSUE TITLE
Warning about prompt-cont

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#413]
I have customized many things including `prompt-cont` in my `~/.ghci` to have a better support for multi line edition in GHCI.

However this raises many warnings in Intellij haskell:
```
15:21	Stack REPL could not be started for target `api-haskell:lib` because Some flags have not been recognized: prompt-cont, [0;34mλ| [m
```

FWIW here's my `.ghci` file:
```
-- Better prompt
:set prompt "\ESC[36m\n%s\n\ESC[0;34mλ> \ESC[m"
-- For multi line (e.g. when defining a type with let), the following prompts are different and don't repeat the modules
:set prompt-cont "\ESC[0;34mλ| \ESC[m"
```

In turn, those warnings seem to break Intellij (cannot navigate to definition, etc.).

I found https://github.com/rikvdkleij/intellij-haskell/issues/212 but I was wondering if the code still works?

FYI my current project uses GHC 8.6.3/8.6.4 (stackage range 13.10 - 13.16).

**Comment by Sir4ur0n** [comment]
I just tested Intero directly with my `.ghci` file. I do get a warning but it doesn't seem to break anything:
![image](https://user-images.githubusercontent.com/1204125/56086072-471cae00-5e4f-11e9-80b0-ba1413ddef30.png)

Maybe Intellij Haskell should ignore warnings? Or log them but not break?

**Comment by rikvdkleij** [comment]
The issue is not your `.ghci` file but the confusing error message.

Plugin only shows this kind of error message when the REPL can not be started because a dependency could not be successfully build. 

I will fix issue of the confusing error message.

**Comment by Sir4ur0n** [comment]
Thanks, I'll wait for the next beta release to try this 😄

**Comment by rikvdkleij** [comment]
Should be solved in beta46.

**Comment by Sir4ur0n** [comment]
Thank you!
