### ISSUE TITLE
How to eable on NixOS? error: attribute 'ghc863' missing

### ISSUE THREAD

**Issue by baracoder** [rikvdkleij/intellij-haskell#415]
This might be a stupid question, but I am failing to set up this plugin on NixOS unstable.
It looks like the specific version of the compiler is not available. Has anyone got it working?
```
3:01	Executing `/home/bara/.nix-profile/bin/stack --system-ghc -j1 --stack-root /home/bara/.cache/intellij-haskell/lts-13 --resolver lts-13 --compiler ghc-8.6.3 --local-bin-path /home/bara/.cache/intellij-haskell/lts-13/bin install stylish-haskell` failed: /home/bara/.nix-profile/bin/stack --system-ghc -j1 --stack-root /home/bara/.cache/intellij-haskell/lts-13 --resolver lts-13 --compiler ghc-8.6.3 --local-bin-path /home/bara/.cache/intellij-haskell/lts-13/bin install stylish-haskell:   
				Selected resolver: lts-13.16
				error: attribute 'ghc863' missing, at (string):1:43
				(use '--show-trace' to show detailed location information)
```

**Comment by rikvdkleij** [comment]
My experience is that `—system-ghc` causes trouble with nix.

**Comment by baracoder** [comment]
Thank you for the reply @rikvdkleij and sorry for not being more clear about the error: The error occurs if I select Update Haskell tools or Reload REPL. Is there a way to disable `--system-ghc` for that steps?
I can build the project itself without problems using `stack build`

**Comment by rikvdkleij** [comment]
If the `stack.yaml` contains `nix: enable: true` then the plugin will not add `--system-ghc`

**Comment by baracoder** [comment]
I have set `nix: enable: true` and the argument `--system-ghc` is gone from the command, but still the error is the same. I think `--compiler ghc-8.6.3` still selects this version, which is not in nixpkgs. I will try to update to the development version of the plugin, since it seams to reference 8.6.4, which is available, so this should work out.

**Comment by rikvdkleij** [comment]
Beta46 does not indicate compiler anymore for installing Haskell tools.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
