### ISSUE TITLE
Only do syntax highlight between /begin{code}.../end{code} for literate Haskell

### ISSUE THREAD

**Issue by dandoh** [rikvdkleij/intellij-haskell#421]
Is this easy to add give the current implementation of the plugin?

**Comment by rikvdkleij** [comment]
Currently literate Haskell is not supported.

**Comment by declension** [comment]
(see #117)

**Comment by dandoh** [comment]
Intellij plugin Texify IDEA now support language injecting languages inside /begin{} ... /end{}.
This was mentioned here https://github.com/Hannah-Sten/TeXiFy-IDEA/pull/1251
and completed here https://github.com/Hannah-Sten/TeXiFy-IDEA/pull/1363

Now you can just mark `lhs` files as Latex files, then inject Haskell in
begin{code} environment.
