### ISSUE TITLE
ConfigFileWatcher produces a lot of threads and freezes IDEA while initial project indexing

### ISSUE THREAD

**Issue by batya239** [rikvdkleij/intellij-haskell#425]
ConfigFileWatcher runs read task over unbounded (!) application thread pool executor (com.intellij.openapi.application.impl.ApplicationImpl#ourThreadExecutorsService). So if there are frequent updates in BulkFileListener, ConfigFileWatcher will create a several number of new threads (they are will not be killed in future). Additionally if initial project indexing in process all these threads are waiting for smart mode and stay parking.

Sample thread dump attached.

[dump.txt](https://github.com/rikvdkleij/intellij-haskell/files/3212656/dump.txt)

If you need more information please contact me.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Hmm, weird, the logic does not have to be scheduled to run in a `ReadTask`. 
I can completely remove the code which schedules the read task with `ProgressIndicatorUtils.scheduleWithWriteActionPriority(readTask)`

**Comment by rikvdkleij** [comment]
Should be fixed in next version.

**Comment by rikvdkleij** [comment]
Can we close this issue?
