### ISSUE TITLE
"Couldn't resolve to any modules."

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#427]
I was trying to use "Organize Imports" to eliminate the redunant import (seen in the ghcid output in the terminal in the top-right).  It didn't do anything, and I wondered if it was related to this message in the log:

```
Command :loc-at /Users/arya/opensource/unison/parser-typechecker/src/Unison/Codebase2.hs 
stdout: Couldn't resolve to any modules.
```
But in the project settings, we can see that it's part of the `unison-parser-typechecker` module.

This is in unisonweb/unison@2b9e8fb9b3db310e122f3f47cc33e43200cda76c.

![image](https://user-images.githubusercontent.com/538571/58362487-859d8380-7e65-11e9-879a-c2689311b5ff.png)

**Comment by rikvdkleij** [comment]
Do you mean: `Optimize imports`?

No, if optimizing imports does not work, it's not related to that error of intero.

**Comment by rikvdkleij** [comment]
Optimizing imports is done by GHC warnings and/or HLint suggestions. Have to investigate why it does not work (anymore). 

Can also relate to this issue https://github.com/ndmitchell/hlint/issues/589. Still have to solve that properly.

**Comment by rikvdkleij** [comment]
I can reproduce your issue with optimize imports. 

For the time being you can also apply the HLint suggestion, that works (navigate to warning and apply suggestion with `alt`+`enter`.

**Comment by rikvdkleij** [comment]
Should be fixed in beta47.

**Comment by rikvdkleij** [comment]
@aryairani Can we close this issue?

**Comment by aryairani** [comment]
Sure, I haven't encountered it since beta47.
