### ISSUE TITLE
IDE dies preloading caches

### ISSUE THREAD

**Issue by declension** [rikvdkleij/intellij-haskell#430]
Hi! On several small-ish Haskell projects (that have been on `intellij-haskell` for some time) I am now experiencing out of memory errors whenever loading the project(s).

### Steps to replicate
 * Plugin `v1.0.0-beta48`
 * IDEA 2019.1.3 with a few other plugins
 * JRE 1.8 
 * Stack 1.9.3, resolver lts-12.26 (but a few others too)
 * A smallish Hakyll project
 * Load the project
 * Wait for _Busy with preloading caches_

### Expected
Builds and caching finishes without error 

### Actual
GUI performance starts decreasing fast and IDEA complains of out of heap space. Have tried twice increasing (currently at 1.6GB).

### Notes
I've tried reimporting the project a few times, and manually deleting a few caches.
On a separate machine, on `beta-46`, this doesn't seem to be happening (have decided not to upgrade though so hard to tell if it's related).

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you share the project so I can try to reproduce this issue?

**Comment by declension** [comment]
Hi. Sorry about the delay. It's a private project so I'm cloning / stripping, trying to find a more minimal repo that still breaks, will push it then!

**Comment by declension** [comment]
@rikvdkleij create a minimal(ish) example repo: https://github.com/declension/intellij-haskell-430

**Comment by declension** [comment]
Update: same problem, on a similar project (uses resolver `lts-13.7`) at work (colleague's machine)

Plugin: `beta48`
Stack `2.1.1`

But then same project (exactly) on _my_ work machine:
Plugin: `beta46`
Stack `2.1.1` (and `1.9.3` previously)
seems to have _different_ problems (_Stack REPL could not be started within 30 seconds_...)

Does that help? :thinking:

**Comment by rikvdkleij** [comment]
> But then same project (exactly) on my work machine:
Plugin: beta46
Stack 2.1.1 (and 1.9.3 previously)
seems to have different problems (Stack REPL could not be started within 30 seconds...)

See https://github.com/rikvdkleij/intellij-haskell/issues/438

**Comment by rikvdkleij** [comment]
Thanks for your minimal example. I will take a look asap.

**Comment by rikvdkleij** [comment]
Should be fixed in beta49, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta49

**Comment by declension** [comment]
This is great - solved the problem for my colleague (combined with Stack downgrade) and looks fine on this work machine. I'll check soonish on my home codebase & machine

Thanks @rikvdkleij !

**Comment by rikvdkleij** [comment]
Great to hear!

You do not need to downgrade stack because in beta49 intero is not used anymore.

**Comment by declension** [comment]
> You do not need to downgrade stack because in beta49 intero is not used anymore.
Great! I've upgraded again, and can confirm on both machines, beta49 is working well! Thanks for a speedy fix :rocket:  

PS: docs still mention Intero quite a lot BTW

**Comment by rikvdkleij** [comment]
> PS: docs still mention Intero quite a lot BTW

Removed the references to intero.
