### ISSUE TITLE
Hoogle database warning gives out of date menu location

### ISSUE THREAD

**Issue by CSchank** [rikvdkleij/intellij-haskell#433]
Running v1.0.0-beta48, an event came up in my log stating:
```
13:45	Hoogle database does not exist. Hoogle features can be optionally enabled by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database`
```

The menu option lists the old menu location, which caused momentary confusion, and should be fixed to reflect the new menu.

Also, out of curiosity, why was that menu option then greyed out when I went to the menu?

Best regards,
Chris

**Comment by rikvdkleij** [comment]
> The menu option lists the old menu location, which caused momentary confusion, and should be fixed to reflect the new menu.

Should be fixed in next beta.

> Also, out of curiosity, why was that menu option then greyed out when I went to the menu?

It's available when project is not initializing, hoogle binary is available and project is not building in the background.
