### ISSUE TITLE
"The selected file is not a valid Stack binary"

### ISSUE THREAD

**Issue by michaelpeternell** [rikvdkleij/intellij-haskell#434]
In the "Select path to Stack binary" dialog I navigated to my "stack.exe" file, clicked it, and pressed the "OK" button. Then a dialog appeared which says "The selected file is not a valid Stack binary".

I opened a command line to check:

    D:\Dev\HaskellStack\bin>.\stack --version
    Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
    
    D:\Dev\HaskellStack\bin>cd ..

    D:\Dev\HaskellStack>stack --version
    Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1

How does IntelliJ-Haskell decide if a stack binary is "valid"? The stack binary that I selected is the only stack binary in my system, and it's even in the PATH.

I haven't found a section in the README file that talks about system requirements, so: Is Windows 10 even supported?

(I found this plugin, because it is linked in [the Haskell wiki](https://wiki.haskell.org/IDEs).)

**Comment by rikvdkleij** [comment]
Plugin should work on Windows but I did not test that for a while.

Which version of plugin do you use?

@Sir4ur0n do you also have this issue? AFAIK you also work on Windows

**Comment by Sir4ur0n** [comment]
Hey,

I confirm it works fine on Windows 10. I don't think I ever had this issue O_o
@michaelpeternell would you mind try to reinstall Stack, just to be sure? And how did you install it? From the 64 bit installer provided at https://docs.haskellstack.org/en/stable/README/ ?

Cheers

**Comment by michaelpeternell** [comment]
I just found the stack installer in my downloads folder: stack-1.9.3-windows-x86_64-installer.exe
I don't know exactly where I downloaded it, but I know that I went to www.stackage.org and followed some links, a few weeks ago. For the intellij-haskell version: I downloaded and installed intellij yesterday, because I've read that it has a haskell plugin. The plugin is IntelliJ-Haskell v1.0.0-beta48. I will probably uninstall IntelliJ in a few days.

I don't want to reinstall stackage just to check this issue. When I reinstall Stack I fear that everything breaks and I have to spend a day to fix it. And then the Stackoverflow people will tell me that my question is off-topic because ... whatever. I used to write code in a different programming language on a different operating system, so this is all new to me. BTW, after I tried out IntelliJ-Haskell, I found Visual Studio Code with Haskelly, and it actually worked. (I was very surprised, I didn't actually expect that such a thing as a "haskell ide" is even possible.) It uses Intero too. But according to #438 stackage 2 breaks intero. You see, bugs everywhere: like Linux in 1998. Why am I using Haskell, and not PHP then? Because when a Haskell program compiles, it actually works, and doesn't throw funky runtime errors. And the safety and security properties of Haskell are important to me.

**Comment by rikvdkleij** [comment]
@michaelpeternell You can try beta49, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta49

**Comment by michaelpeternell** [comment]
@rikvdkleij : yes, it works now :)

**Comment by rikvdkleij** [comment]
Great!

**Comment by cbxzcm** [comment]
Hi.

I have this same problem in Windows 10 with plugin version 1.0.0-beta52.

My stack version:
```
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```
