### ISSUE TITLE
Support Stack 2

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#438]
Stack 2 just got released. I upgraded on my Windows Machine (`stack upgrade`) but now Intellij Haskell seems broken. I don't have access to it right now, but can someone else try and report please? I feel like some changes will be needed (too afraid to upgrade Stack on my work machine because of this).

**Comment by rikvdkleij** [comment]
What kind of error that you get?

**Comment by rikvdkleij** [comment]
In my local version in which I have removed intero everything works okay.

So I installed beta48 and noticed that the global REPL does not want to startup anymore. Looks like an issue in the combination of stack and intero.

**Comment by rikvdkleij** [comment]
Hmm, `stack build intero` does nothing on LTS-13.25. Can also be some other issue....

**Comment by rikvdkleij** [comment]
It's a bug in stack 2.

When I do `stack build intero` with stack 1.9.3 the build just works.

**Comment by rikvdkleij** [comment]
I do not what is going in stack 2 but it can also not find intero when it's build..

```
rik@maxwell:~/projects/quicksort$ /home/rik/.local/bin/stack.old exec -- which intero
/home/rik/projects/quicksort/.stack-work/install/x86_64-linux-tinfo6/lts-13.25/8.6.5/bin/intero
rik@maxwell:~/projects/quicksort$ /home/rik/.local/bin/stack exec -- which intero
```

**Comment by rikvdkleij** [comment]
I think I have to speed up a new release without intero.

**Comment by Sir4ur0n** [comment]
Just reproduced on my Windows machine:
```
9:11 PM	[global-stack-repl] Stack REPL could not be started within 30 seconds

9:11 PM	[global-stack-repl] 'stty' is not recognized as an internal or external command,

9:11 PM	[global-stack-repl] operable program or batch file.

9:11 PM	[project-stack-repl-haskell:lib] Stack REPL could not be started within 30 seconds

9:11 PM	[project-stack-repl-haskell:lib] 'stty' is not recognized as an internal or external command,

9:11 PM	[project-stack-repl-haskell:lib] operable program or batch file.
```

**Comment by rikvdkleij** [comment]
Just released beta49 which does not depend on intero anymore, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta49
