### ISSUE TITLE
Improve error / log messages

### ISSUE THREAD

**Issue by declension** [rikvdkleij/intellij-haskell#439]
Hi. Thanks again for your hard work on such a great plugin.

I've noticed some of the error / log / IDE user messages feel a bit weird or unfriendly (to a native speaker at least). Some examples...

### Non-idiomatic English
> Starting initializing Haskell project

Nothing wrong - but it sounds a bit odd (IMO)

> _Can not load file in REPL because could not determine path for file `${actionContext.psiFile.getName}`. File exists only in memory"_

Again - fine, but we could maybe make a clearer message here..

> _Busy with preloading..._

_Busy with x_ sounds weird - just _Busy x_ sounds better

### Errors / Typos
e.g. 
> _Can not add package $p as module because it's absolute file path ${packagePath.getAbsolutePath} does not exist._

That should be _its_

> _Busy with preloading stack component info cache_

Should probably be _Stack_

Hardly urgent, of course, but always nice to have friendly messages!  I can try to push some fixes if that helps :up:

**Comment by rikvdkleij** [comment]
>  can try to push some fixes if that helps up

That would be great! Let me know if I can help with providing some context of the message.
