### ISSUE TITLE
Add support for IntelliJ 2016.2

### ISSUE THREAD

**Issue by JanGe** [rikvdkleij/intellij-haskell#44]
Since upgrading to the latest version, the `intellij-haskell` plugin is reported as incompatible. Opening old Haskell projects will result in the following error message:

    Unknown Module Type
    Cannot determine module type ("HASKELL_MODULE") for the following module:"haskell-project"
    The module will be treated as a Unknown module.

**Comment by rikvdkleij** [comment]
Thanks for reporting. 

I'm busy with a new release which will support 2016.2. 
I hope to publish a beta release soon.

**Comment by rikvdkleij** [comment]
Beta is released.
