### ISSUE TITLE
Quick Documentation finding some but not all Haddock

### ISSUE THREAD

**Issue by cederber** [rikvdkleij/intellij-haskell#441]
View > Quick Documentation (keyboard shortcut F1 on OS X) can find some (but not all) third-party Haddock and I haven't seen it find any Haddock from the current project.

This is with IntelliJ-Haskell v1.0.0-beta49 on IntelliJ IDEA 2019.1.3 Community Edition, macOS Mojave 10.14.5.

Appreciate any insight you have into this--attaching screenshots below.

Thanks for the great plugin!

Failed lookup of local Haddock:

<img width="565" alt="missing_project_haddock" src="https://user-images.githubusercontent.com/1390810/59790657-4bb57680-9285-11e9-82eb-d95b1f8958a5.png">

Successful lookup of library Haddock:

<img width="482" alt="working_library_haddock" src="https://user-images.githubusercontent.com/1390810/59790723-71db1680-9285-11e9-974a-9892012d3776.png">

Failed lookup of library Haddock:

<img width="451" alt="missing_library_haddock" src="https://user-images.githubusercontent.com/1390810/59790762-87e8d700-9285-11e9-99e7-cff78d9f91d1.png">

The Haddock that this lookup should have found:

<img width="563" alt="missing_library_haddock_present_in_source" src="https://user-images.githubusercontent.com/1390810/59790786-90d9a880-9285-11e9-9390-43de64256c4f.png">

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
I can not reproduce this issue.
For example, the documentation lookup for `withObject` works for me.

Maybe a Rebuild Hoogle database helps?
(See Haskell main menu)

**Comment by cederber** [comment]
Thanks for taking a look!

Indeed, after a "Rebuild Hoogle database" I'm able to view Haddock from library packages. Regarding project-local Haddock, it appears that documentation only gets indexed for symbols that are exported by the module, which makes sense but I hadn't realized.

Overall seems to be working now. Closing this issue.
