### ISSUE TITLE
No result from Stack REPL within 30 seconds. Command was: :show modules

### ISSUE THREAD

**Issue by aberent** [rikvdkleij/intellij-haskell#442]
I recently upgraded to v1.0.0-beta49. Since I did:

- Finding Haskell problems when the source is modified is taking around a minute, even if the code and changes are trivial
- If there are Haskell problems in my source I get messages in the event log saying  "No result from Stack REPL within 30 seconds. Command was: :show modules"

I have tested this with a trivial project containing just the source file:

```haskell
module Main where

main :: IO ()
main = return ()

xxx
```

Version Information:
intellij-haskell v1.0.0-beta49

IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-16-generic

Stack version: 2.1.1

GHC: 8.6.5
HLint: HLint v2.1.11, (C) Neil Mitchell 2006-2018

Hoogle: Hoogle 5.0.17.3, http://hoogle.haskell.org/

Hindent: hindent 5.3.0

Stylish-haskell: stylish-haskell 0.9.2.2

**Comment by michaelpeternell** [comment]
I had the same error message. For me: system was Windows 10, stack version 1.9.3

**Comment by rikvdkleij** [comment]
> Finding Haskell problems when the source is modified is taking around a minute, even if the code and changes are trivial
If there are Haskell problems in my source I get messages in the event log saying "No result from Stack REPL within 30 seconds. Command was: :show modules"

I guess those two are related.

I will try to reproduce this issue.

**Comment by rikvdkleij** [comment]
It's fixed in beta50, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta50

Thanks for reporting!

**Comment by aberent** [comment]
Many thanks, I can confirm that everything is back to normal.
