### ISSUE TITLE
Quasiquotes' content should be subject to "Inject language or reference" intent

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#445]
The user should be able to inject language or reference against quasiquote content the way he is able doing so for regular string:

![image](https://user-images.githubusercontent.com/89889/60672975-54aa6880-9e7f-11e9-8f3a-7225a7b9a546.png)

**Comment by rikvdkleij** [comment]
@ice1000 Can you solve this issue?

**Comment by ice1000** [comment]
Could you please give me some pseudo-code on how the injection rule should be implemented? Like does the words between `[` and `|` matter?

**Comment by ice1000** [comment]
And should the injection be automatic (like RegEx stuffs in Java), which disables you to customize your own injection?

**Comment by develop7** [comment]
> Like does the words between `[` and `|` matter?

No. Not at first, that is.

> And should the injection be automatic (like RegEx stuffs in Java), which disables you to customize your own injection?

Again, not at first. Let's start with that lightbulb to show up.

**Comment by ice1000** [comment]
So it's the part between two `|` matters, right?

**Comment by develop7** [comment]
@ice1000 ya, the literal, being the subject for language embedding, is between the leftmost and rightmost `|`s. However, whole *expression* is enclosed between `[` and `]` (we might want to have whole expression lightbulb-enabled, not just the string).

Actually GHC manual knows more on the subject than me — https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-QuasiQuotes

**Comment by rikvdkleij** [comment]
@ice1000 it would be very cool if you could implement this feature request!

**Comment by ice1000** [comment]
This should be easy, but it's (possibly) conflicted with the new parser

**Comment by rikvdkleij** [comment]
@ice1000 Well, there is a lot to fix when we are going to use the new parser. So I do not see that as an  reason for not implementing this feature now. Again, it would be very cool if you could help!

**Comment by rikvdkleij** [comment]
@ice1000 Can you solve this? Otherwise let me know how to solve this.

Many thanks!!

**Comment by ice1000** [comment]
You'll need to port these classes:

https://github.com/rikvdkleij/intellij-haskell/pull/358/files#diff-1f054804631f0876da44e65b6fa0f3cdR253-R254
https://github.com/rikvdkleij/intellij-haskell/pull/358/files#diff-d11748638a9822291c3e8a7c3d491605R51
https://github.com/rikvdkleij/intellij-haskell/pull/358/files#diff-ab991e31cf0934dfd57301c0189ef3d7R7-R22
https://github.com/rikvdkleij/intellij-haskell/pull/358/files#diff-c61a64eea3421b74a0107ae54594d57fR12-R28

And use `LiteralTextEscaper` instead of `HaskellStringEscaper`, I believe.
I just don't have a working computer that has a reliable Scala environment, sorry.

**Comment by rikvdkleij** [comment]
@ice1000 Thanks for your reply but it's not clear for me. Can you be more explicit about the steps?

Otherwise it can also wait till you have working Scala environment (or does that take ages? 😄)

**Comment by ice1000** [comment]
Oh, Scala! My Scala!

**Comment by ice1000** [comment]
Scala plugin throws exceptions on my IntelliJ, oh my

**Comment by rikvdkleij** [comment]
Maybe plugin version not compatible with IntelliJ version?

**Comment by ice1000** [comment]
IDK

**Comment by ice1000** [comment]
Don't leave, I'm working on it

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/68087601-82032500-fe25-11e9-906c-3750af4f0b76.png)

**Comment by ice1000** [comment]
So many changes like this. I'm feeling aweful

**Comment by ice1000** [comment]
And this
![image](https://user-images.githubusercontent.com/16398479/68087633-cc84a180-fe25-11e9-9dfb-8cb0ca7bdb56.png)

**Comment by rikvdkleij** [comment]
> Don't leave, I'm working on it

Thanks!

**Comment by rikvdkleij** [comment]
Yeah, generated code is still hard to maintain...

**Comment by ice1000** [comment]
> Yeah, generated code is still hard to maintain...

I'd not committing them into the repo

**Comment by rikvdkleij** [comment]
> I'd not committing them into the repo

Ok, will do that soon.

**Comment by ice1000** [comment]
???

**Comment by rikvdkleij** [comment]
I mean I will remove the generated code soon from the repo.

**Comment by ice1000** [comment]
Really? I didn't mean to social pressure you

**Comment by ice1000** [comment]
I didn't compile it as I don't have Scala env. Please check if it works fine though

**Comment by rikvdkleij** [comment]
> Really? I didn't mean to social pressure you

Well, the generated is a problem so I think it's good solution to remove it from repo. Only downside is that project can not be build when for example travis build is setup.

**Comment by ice1000** [comment]
> Well, the generated is a problem so I think it's good solution to remove it from repo. Only downside is that project can not be build when for example travis build is setup.

If you use gradle, there's a plugin for running grammar-kit generation. The downside is that the `methods` is no longer usable.

**Comment by rikvdkleij** [comment]
What do you mean by

>  the`methods` is no longer usable.

?

**Comment by ice1000** [comment]
> What do you mean by
> 
> themethods is no longer usable.
> 
> ?

I was talking about an attribute provided by Grammar-Kit that you can use in your .bnf files.
The gradle plugin is not abled to generate the methods indicated by the `methods` attribute of your parsing rules.

**Comment by ice1000** [comment]
Btw, there are ways to invoke grammar-kit via command line. See this revision of this plugin: https://github.com/intellij-solidity/intellij-solidity/tree/0d696bd75b9e48261e46171e3a387bf008a84ae5 (don't look at the master branch, they've already switched to the gradle plugin)

**Comment by rikvdkleij** [comment]
@ice1000 Thanks for the pointer.

**Comment by rikvdkleij** [comment]
It's fixed in beta56.

**Comment by develop7** [comment]
Thanks!

**Comment by develop7** [comment]
Confirming it works, thanks again @rikvdkleij @ice1000
