### ISSUE TITLE
Editor > Code Style > Haskell loading forever

### ISSUE THREAD

**Issue by dandoh** [rikvdkleij/intellij-haskell#449]
OS: Mac OS
Step to reproduce:
- Install latest intellj-haskell
- Open Setting > Editor > Code Style > Haskell
![image](https://user-images.githubusercontent.com/10379980/60858795-e0085e80-a1dd-11e9-81b5-5f41bcf8fd0c.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I can reproduce this issue.

**Comment by iupii** [comment]
The same :)

**Comment by rikvdkleij** [comment]
Should be solved in beta52.
