### ISSUE TITLE
[Feature] Added an intention that generates a type annotation for un-annotated functions

### ISSUE THREAD

**Issue by dandoh** [rikvdkleij/intellij-haskell#451]
Repeat #224. 
The latest [intellj-elm](https://github.com/klazuka/intellij-elm/releases) has this feature, and I think it would be nice for intellj-haskell to have this too.

**Comment by rikvdkleij** [comment]
So you want support even when GHC does not give suggestions? So without `-Wall`

**Comment by dandoh** [comment]
No, just the normal one like GHC with `-Wall`, I think mostly people need it for top-level functions.
The things is that there are lots of bad old codes without annotations for top-level functions, I have to `Haskell.showType` to find out their type and annotate them myself. So it would be useful to have the intention for this.

**Comment by rikvdkleij** [comment]
Hmm, when `-Wall` is enabled you should see the intentions to add type signatures to top-level functions.

**Comment by dandoh** [comment]
You mean if I do this, I'll see the intentions if the signature is missing?: 
![image](https://user-images.githubusercontent.com/10379980/61325328-793d0380-a7e2-11e9-9d1a-80d5bb7316cc.png)
I tried but doesn't seem to work.

**Comment by rikvdkleij** [comment]
No, in your project's cabal file.

**Comment by dandoh** [comment]
Oh you're right. I added this to package.yaml and it works
```
library:
  source-dirs: src
  ghc-options:
    - -Wmissing-signatures
```
But do you think it should be the default behavior?
