### ISSUE TITLE
"Reformat Code" action breaks working code (ViewPatterns)

### ISSUE THREAD

**Issue by mnn** [rikvdkleij/intellij-haskell#452]
I have a following code (uses Yesod library):

```hs

mkYesod
  "App"
  [parseRoutes|
/categories CategoriesR GET
/categories/#Text CategoryR GET
/images/#Text ImageR GET
|]
```
which requires
```hs
{-# LANGUAGE ViewPatterns              #-}
```
After "Reformat code" action this lang. extension disappears thus breaks the code. I guess TH and/or QuasiQuotes in combination with ViewPatterns are a problem. This workaround works:

```hs
fakeViewPatternToStopFormatterFromRemovingLanguageExtension ((== 1) -> True) = undefined
```

While I don't think this plugin does the formatting, I don't know where else to post (I don't know what tool is responsible for formatting code).

Plugin version: v1.0.0-beta51
Complete code: https://gitlab.com/monnef/img-hall-be/blob/18cfcf65c37f5f0da9aba666abcc0bae16e11d79/app/YesodServer.hs#L48

**Comment by rikvdkleij** [comment]
> While I don't think this plugin does the formatting, I don't know where else to post (I don't know what tool is responsible for formatting code).

Reformatting in the plugin is done by `hindent` first (and then by `stylish-haskell`). I guess `hindent` is responsible for breaking the code.

**Comment by rikvdkleij** [comment]
Hindent is not used anymore.
