### ISSUE TITLE
Readonly dirs

### ISSUE THREAD

**Issue by asimaranov** [rikvdkleij/intellij-haskell#453]
![tempsnip](https://user-images.githubusercontent.com/25568730/61460126-c94ccf00-a976-11e9-94ac-a56041b8f5fa.png)
The plugin creates readonly directories and gets stucked while trying to write to them

**Comment by rikvdkleij** [comment]
No, the `lts-13` directory is created by stack.

**Comment by rikvdkleij** [comment]
Can this issue be closed?

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
