### ISSUE TITLE
Start fails on Nixos

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#455]
Hi,

I just recently started using Nixos and tested my workflow with Intellij and Haskell on it.
When importing for the first time a Haskell project in Intellij, it installs many tools using this command:
```bash
~/.nix-profile/bin/stack -j1 --stack-root ~/.cache/intellij-haskell/lts-13 --resolver lts-13 --local-bin-path ~/.cache/intellij-haskell/lts-13/bin install hoogle
```
However this fails as it requires Zlib which requires special Stack integration.
The command is successful if I manually type it in a terminal and add `--nix-packages "zlib"` option to it:
```bash
~/.nix-profile/bin/stack --nix-packages "zlib" -j1 --stack-root ~/.cache/intellij-haskell/lts-13 --resolver lts-13 --local-bin-path ~/.cache/intellij-haskell/lts-13/bin install hoogle
```

Have I missed something (this is completely possible as I'm a huge noob in Nix/Nixos)? Or is something missing for Nixos use?

Note, in my project `stack.yaml` it was correctly configured:
```yaml
resolver: lts-13.26
packages:
  - .
nix:
  enable: true
  packages: 
    - zlib
```

Cheers!

**Comment by friedbrice** [comment]
I think your configuration is correct; I think the problem might be an oversight in the tools-creation logic. As a stopgap, you could use a feature coming in the next release that will allow you to build your tools separately and specify their paths directly in the plugin options.

**Comment by friedbrice** [comment]
Here's the PR if you'd like to follow it: https://github.com/rikvdkleij/intellij-haskell/pull/454#issuecomment-513466559

**Comment by rikvdkleij** [comment]
Stack's nix integration is not without flaws.

You can try to add `zlib` to to `shell.nix` or `default.nix` to be sure of `zlib` in the nix-shell.

I have not so good experience with stack it's nix integration, especially not on macOS.
See
https://github.com/commercialhaskell/stack/issues/4406
https://github.com/commercialhaskell/stack/issues/4329

Btw, you can better use nix and cabal new style. But yes, the plugin does not support that yet. It's on my wish list and did already some preparations.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.

**Comment by Sir4ur0n** [comment]
I guess this can be closed as we now can explicitly pass tool paths rather than relying on the plugin installing them, thank you 😄

**Comment by rikvdkleij** [comment]
Thanks for the confirmation.

Eventually the plugin should support Cabal/Nix projects but that's a separate issue :smile:
