### ISSUE TITLE
Deriving via color

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#457]
Hi,

It seems the `deriving via` syntax is not correctly colored, I would expect both `deriving` and `via` to be colored as keywords, but `via` isn't.

```haskell
{-# LANGUAGE DerivingVia #-}

newtype Foo = Foo Int
  deriving Show via Int
```

* `deriving` appears as a keyword (orange).
* 😢 `via` appears as a regular word (white).

**Comment by rikvdkleij** [comment]
Thanks for reporting!

According to this list, https://wiki.haskell.org/Keywords, `via` is not a keyword. Also in https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-DerivingVia `via` is not colored as keyword.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Okay, it's listed here, https://gitlab.haskell.org/ghc/ghc/blob/1befd2c00f8a8fc1ca62ef18ca3028c58e35dabd/compiler/parser/Lexer.x#L797, as keyword.
But it should only be keyword in context of `DerivingVia`.

**Comment by rikvdkleij** [comment]
@ice1000 Do you have a nice solution for solving this?

**Comment by ice1000** [comment]
I do

**Comment by ice1000** [comment]
Only if you have a nice solution to access a file's pragmas @rikvdkleij

**Comment by rikvdkleij** [comment]
@ice1000 Thanks!

> Only if you have a nice solution to access a file's pragmas @rikvdkleij

Is this what you mean?
http://github.com/rikvdkleij/intellij-haskell/blob/6350b2828aff2bdc31946cddcf65212410b4d697/src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala#L40-L40

**Comment by ice1000** [comment]
Probably, I can try

**Comment by rikvdkleij** [comment]
@ice1000 did you try?

**Comment by ice1000** [comment]
I didn't, but here's how-to:

Open up [this function](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/highlighter/HaskellHighlightingAnnotator.scala#L9), it's invoked for every `PsiElement` in your Haskell files. Write some codes to detect if there's `DerivingVia` pragma and it's a `deriving Show via Int` code, do whatever you want to find the TextRange for the `deriving` and `via` PsiElement. Use `holder.createInfoAnnotation([your text range here], null).setTextAttributes(HaskellSyntaxHighlighter.Keyword)` to highlight it as a keyword.

**Comment by rikvdkleij** [comment]
@ice1000 Thanks!

**Comment by develop7** [comment]
Any progress with the issue? beta74 is still affected

**Comment by rikvdkleij** [comment]
No progress. Didn't give it priority.

**Comment by rikvdkleij** [comment]
Should be fixed in next version.

**Comment by develop7** [comment]
Cannot confirm unfortunately — `via` in https://github.com/develop7/restograph/blob/master/src/Restograph/Model.hs#L18 appears like a function, not keyword: 
![Screenshot from 2020-06-22 14-04-01](https://user-images.githubusercontent.com/89889/85280708-522a8f80-b491-11ea-904a-caec8104787a.png)

ij-haskell 1.0beta75 after cache invalidation

**Comment by rikvdkleij** [comment]
@develop7 Thanks for reporting!
Hmm, I didn't check that case with two times `deriving` :smile:

**Comment by rikvdkleij** [comment]
Fixed in beta76.

**Comment by develop7** [comment]
Confirming it's fixed! Thanks!
