### ISSUE TITLE
Automatically strips trailing spaces even when not saving

### ISSUE THREAD

**Issue by arthurborisow** [rikvdkleij/intellij-haskell#459]
Hi, 

I noticed some strange behavior after I installed the plugin. Whenever I try to edit a line and start with a space char and I am not fast enough the space character will be stripped.
These are my settings:
<img width="604" alt="Screen Shot 2019-08-01 at 20 08 20" src="https://user-images.githubusercontent.com/786034/62313053-6ab84280-b498-11e9-83fe-c68790a66534.png">
To overcome the issue I have to do this (which is not an option really):
<img width="592" alt="Screen Shot 2019-08-01 at 20 11 15" src="https://user-images.githubusercontent.com/786034/62313094-89b6d480-b498-11e9-8751-9fb46db7fe57.png"> 
or this:
<img width="586" alt="Screen Shot 2019-08-01 at 20 11 54" src="https://user-images.githubusercontent.com/786034/62313125-a0f5c200-b498-11e9-996c-eb5999af8e3c.png">
Both approaches are not perfect though. When I disable the plugin the space is preserved unless I save the file (which is an expected behavior).

It was reproduced on two machines with macOS Mojave with latest Intellij Idea CE

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you give an example how I can reproduce this issue? Is it only in Haskell files?

**Comment by arthurborisow** [comment]
Steps to reproduce:
1. Open Intellij Idea with installed plugin
<img width="492" alt="Screen Shot 2019-08-01 at 21 14 18" src="https://user-images.githubusercontent.com/786034/62316957-5462b480-b4a1-11e9-878b-9b1aaed1eb48.png">

2. Click Create New Project. Choose Haskel module and Project SDK
<img width="691" alt="Screen Shot 2019-08-01 at 21 14 54" src="https://user-images.githubusercontent.com/786034/62317007-6b090b80-b4a1-11e9-9917-7742cf1c5982.png">

3. Click Next and choose the name for new project
<img width="689" alt="Screen Shot 2019-08-01 at 21 16 34" src="https://user-images.githubusercontent.com/786034/62317120-a60b3f00-b4a1-11e9-9d65-40fcfc5be8c4.png">

4. Click Finish and choose Yes when prompted to create a new directory

5. Wait until all background tasks are finished

6. Ensure the Strip trailing spaces on save are turned on.
<img width="628" alt="Screen Shot 2019-08-01 at 21 24 04" src="https://user-images.githubusercontent.com/786034/62317596-b243cc00-b4a2-11e9-874e-9cf7b6aeb2ed.png">

7. Open file src/Lib.hs

8. Move the cursor to the last line
<img width="354" alt="Screen Shot 2019-08-01 at 21 21 31" src="https://user-images.githubusercontent.com/786034/62317420-5711d980-b4a2-11e9-8456-e3dad1aefc00.png">

9. Press space (can repeat multiple times)

10. Wait couple of seconds.

**Actual result:**
All spaces are deleted

**Expected result:**
All spaces are preserved

**Comment by arthurborisow** [comment]
> Is it only in Haskell files?

@rikvdkleij as far as I tested, yes

**Comment by rikvdkleij** [comment]
Thanks for your report!

Found the issue and fixed it. I did not notice this issue because I had the option `Always keep trailing space on caret line` enabled.

**Comment by arthurborisow** [comment]
Great news! Thank you!

**Comment by rikvdkleij** [comment]
Should be solved in beta52.
