### ISSUE TITLE
Compilation errors are duplicated

### ISSUE THREAD

**Issue by arthurborisow** [rikvdkleij/intellij-haskell#460]
Steps to reproduce:

1. Open Intellij Idea with installed plugin
<img width="492" alt="Screen Shot 2019-08-01 at 21 14 18" src="https://user-images.githubusercontent.com/786034/62316957-5462b480-b4a1-11e9-878b-9b1aaed1eb48.png">

2. Click Create New Project. Choose Haskel module and Project SDK
<img width="691" alt="Screen Shot 2019-08-01 at 21 14 54" src="https://user-images.githubusercontent.com/786034/62317007-6b090b80-b4a1-11e9-9917-7742cf1c5982.png">

3. Click Next and choose the name for new project
<img width="689" alt="Screen Shot 2019-08-01 at 21 16 34" src="https://user-images.githubusercontent.com/786034/62317120-a60b3f00-b4a1-11e9-9d65-40fcfc5be8c4.png">

4. Click Finish and choose Yes when prompted to create a new directory

5. Open file src/Lib.hs

6. Make some mistake in code, for instance, change `putStrLn` to `putStrL` and open Haskell Problem sidebar.

**Actual result:**
The Variable not in scope error is shown twice:

<img width="1065" alt="Screen Shot 2019-08-01 at 22 17 06" src="https://user-images.githubusercontent.com/786034/62320902-1a49e080-b4aa-11e9-9578-6cccfa8a6176.png">

**Expected result:**
Error is shown once like when `stack build` is run

<img width="600" alt="Screen Shot 2019-08-01 at 22 18 49" src="https://user-images.githubusercontent.com/786034/62321024-57ae6e00-b4aa-11e9-99b1-87bb210c98eb.png">

**Comment by rikvdkleij** [comment]
Thanks for reporting (again)!

I have found the cause. It's introduced when I removed intero and had to execute `set +c` in ghci, which effects that all messages are duplicated.

**Comment by arthurborisow** [comment]
@rikvdkleij thanks for quick response

**Comment by rikvdkleij** [comment]
Should be solved in beta52.
