### ISSUE TITLE
Unable to run test

### ISSUE THREAD

**Issue by mouse07410** [rikvdkleij/intellij-haskell#462]
Normally, I'd do `stack build --test`, and it would create/build a test-executable and run it:
```
$ stack build --test
Str2Split-0.1.0.0: unregistering (local file changes: ChangeLog.md README.md Str2Split.cabal app/Main.hs package.yaml src/Lib.hs test/Spec.hs)
Building all executables for `Str2Split' once. After a successful build of all of them, only specified executables will be rebuilt.
Str2Split> configure (lib + exe + test)
Configuring Str2Split-0.1.0.0...
Str2Split> build (lib + exe + test)
Preprocessing library for Str2Split-0.1.0.0..
Building library for Str2Split-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_Str2Split
Preprocessing test suite 'Str2Split-test' for Str2Split-0.1.0.0..
Building test suite 'Str2Split-test' for Str2Split-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_Str2Split
Linking .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test/Str2Split-test ...
Preprocessing executable 'Str2Split-exe' for Str2Split-0.1.0.0..
Building executable 'Str2Split-exe' for Str2Split-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_Str2Split
Linking .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-exe/Str2Split-exe ...
Str2Split> copy/register
Installing library in /Users/uri/src/Str2Split/.stack-work/install/x86_64-osx/679ca7ead208183d6a7360e565c63d62dbea1bdfa5636a9dc6b7fca3424c6e66/8.6.5/lib/x86_64-osx-ghc-8.6.5/Str2Split-0.1.0.0-7QLxoIcNTm129eEkCQEeFn
Installing executable Str2Split-exe in /Users/uri/src/Str2Split/.stack-work/install/x86_64-osx/679ca7ead208183d6a7360e565c63d62dbea1bdfa5636a9dc6b7fca3424c6e66/8.6.5/bin
Registering library for Str2Split-0.1.0.0..
Str2Split> test (suite: Str2Split-test)
            
Progress 1/2: Str2SplitTest suite not yet implemented
                       
Str2Split> Test suite Str2Split-test passed
Completed 2 action(s). 
$ find . -name Str2Split-test -print
./.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test
./.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test/Str2Split-test
$ ./.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test/Str2Split-test
Test suite not yet implemented
$ otool -L ./.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test/Str2Split-test
./.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Str2Split-test/Str2Split-test:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libHSbase-4.12.0.0-ghc8.6.5.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSghc-prim-0.5.3-ghc8.6.5.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libHSrts_thr-ghc8.6.5.dylib (compatibility version 0.0.0, current version 0.0.0)
$ 
```
So far so good.

But not so with this plugin, as it insists on passing `--exec` argument to `stack` regardless of whether it makes sense or not. It also refuses to let me point it at the correct executable:
![Screen Shot 2019-08-07 at 21 37 04 ](https://user-images.githubusercontent.com/5923577/62669263-fdefed00-b95c-11e9-8d46-3a00feaa432b.png)

As you can see, even though the executable `Str2Split-test` does exist (as shown above), there's no way to convince the plugin to use it in the Run Configuration. Nor is there a way to tell the plugin that a specific configuration does **not** have an executable.

On the same note, more often than not when I am defining my Run Configurations, I **don't have** the executables built yet - one of the purposes of such a Run Configuration is to **build** the appropriate executable.

Even if I circumvent the plugin constraints and define the appropriate commands via IDEA External Tools, it still will force the executable it thinks should be used, and break my build.

### Comment
I have a series of small test-projects: StrSplit, Str2Split, Str3Split - all very similar. Complete source of Str3Split was posted in another issue.

**Comment by mouse07410** [comment]
@rikvdkleij ping? 

I think this goes into design of the plugin, and its intended use case - whether it's supposed to build and run anything but the main executable.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I will take a look later.

**Comment by mouse07410** [comment]
Adding "Stack tester" config option helped a lot. It's not as generic as I'd like (i.e., being able to just specify whatever executable I think it should use ;) - but it does the job. Thank you!
