### ISSUE TITLE
Improve format of tooltip

### ISSUE THREAD

**Issue by declension** [rikvdkleij/intellij-haskell#466]
Having tooltips for compiler fails at the source position is great, and part of the charm of a good IDE.

However, I've found anything but the simplest compiler errors become unreadable, mainly just because of the lack of newlines (edit: also, some duplication of sorts, see image)

### An example tooltip
![intellij-haskell-tooltip-formatting](https://user-images.githubusercontent.com/3322808/63124059-513bee00-bfa2-11e9-9c1f-7d6b1f956416.png)
 
### vs the stdout
![intellij-haskell-stdout-formatting](https://user-images.githubusercontent.com/3322808/63124288-d9ba8e80-bfa2-11e9-9c1d-b270b5d777f8.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I remember that I looked to this before. Can be regression issue. 

Btw, there is also the `Haskell Problems View`

**Comment by declension** [comment]
> Btw, there is also the Haskell Problems View

Oh, cool! I might use that a bit more...

**Comment by declension** [comment]
Hmm in the same codebase just now, this _doesn't_ happen elsewhere (but it's a significantly shorter error message)

**Comment by rikvdkleij** [comment]
If you can reproduce the issue let me know

**Comment by declension** [comment]
Yes - it was reliably happening on the example in the screenshot, just seems not to be on _every_ tooltip (and perhaps content length-related)

**Comment by rikvdkleij** [comment]
Can you give some example code?

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
