### ISSUE TITLE
Alternative to "extra stack arguments" configuration option

### ISSUE THREAD

**Issue by zeme-wana** [rikvdkleij/intellij-haskell#468]
After updating from v1.0.0-beta51 to v1.0.0-beta52, I noticed that the extra-stack-arguments configuration option [has been removed](https://github.com/rikvdkleij/intellij-haskell/commit/42238fefca8e46c72637f230206c7576af9b2e97). 
This was very useful to us, as it allowed to override the default --fast and --no-interleaved-output flags, as well as to add other flags that would match our default configuration in package.yaml.
Is there a way to obtain the same behavior within the plugin?

**Comment by rikvdkleij** [comment]
> Is there a way to obtain the same behavior within the plugin?

No.
Extra stack arguments were added as temporary workaround to get the Haskell tools built in case of`system-ghc: true` and/or `-dynamic`. 
Since beta53 (not officially released, only in alpha plugin repo) it is possible to set the paths to the Haskell tools (so you can build the Haskell tools in your own way).

Why do you want to override the default flags? `--fast` helps to get faster feedback and `--no-interleaved-output` makes it possible to jump to the error from within the Messages view.

**Comment by zeme-wana** [comment]
I see. We have a large project that takes about 10 minutes to cold-build. When I open IntelliJ, the plugin will start building (with `--fast` and `--interleaved-output`), but because we use `-O1` in `package.yaml`, it will need to start from scratch, and when we run `stack build`, it will start from scratch again; same thing when we run `Update Settings and Restart REPLs`. In other words the build from the plugin and the build from `stack build` override each other due to optimization flags changes.
Maybe this is not the intended way to use the plugin, but adding `--ghc-options="-O1"` to the extra stack arguments fields, just did the trick.
RE `--interleaved-output`: it was just to get more feedback on what the plugin is building and when.
I didn't notice that you could jump to error from within the Messages view.

**Comment by rikvdkleij** [comment]
Hmm, for development it's best to have `--fast` but for creating a deliverable the build has to be optimized. Shouldn't you do the `stack build` on a different location (build server?)?

Without good arguments I'm trying to prevent to add again the option for extra stack arguments because they are some kind of a hack

**Comment by zeme-wana** [comment]
Being able to add extra stack arguments just happened to be very convenient for us, seeing that we build and deploy locally with nix, making each of our dev machines a kind of build server.
I understand that it was meant to be a temporary workaround, but it just fit our use case so perfectly! I won't insist to have brought back though if it was not meant to exist in the first place. 
So this issue can be closed as far as I'm concerned.

**Comment by rikvdkleij** [comment]
Do you use the stack's nix integration?

Well, if you have no other option in your way of working, I can put them back.

**Comment by mouse07410** [comment]
I'd say - it would be great to have what Beta-54 added, plus restoring the "extra stack arguments".

Thanks!

**Comment by zeme-wana** [comment]
> Do you use the stack's nix integration?

Yes we use stack's nix integration.
We use the plugin for development, then when ready to deploy, we run `stack build` locally. We wrap the executable produced by stack into a nix derivation, and we mention that derivation in nixops to deploy.

> Well, if you have no other option in your way of working, I can put them back.

We definitely don't want to stop using the plugin, and at the same time we like that we can deploy from any machine, and without rebuilding from scratch every time. It would be awesome if we could keep doing that!

**Comment by rikvdkleij** [comment]
Ok, I will put this feature back in next release. Before I release new version my plan is to fix some bugs. So it can take some time before new version is released. Hopefully that isn't a problem. Otherwise let me know.

**Comment by mouse07410** [comment]
Certainly not a problem for me. And thanks for making and improving this plugin!

**Comment by rikvdkleij** [comment]
Released beta55 in which the setting to add extra stack arguments is back. https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta55

Also uploaded to alpha plugin repo.

**Comment by mouse07410** [comment]
Unfortunately, beta-55 consistently gives me
```
20:24	Stack REPL couldn't be started for target `Str3Split:test:Str3Split-test` due to: cannot satisfy -package Str3Split-0.1.0.0
```

**Comment by rikvdkleij** [comment]
@mouse07410 Hmm, weird. I have no idea. Will take a look later today.

**Comment by rikvdkleij** [comment]
@mouse07410 I can not reproduce your problem. Also not with your example project `Str3Split`

Maybe your extra stack arguments settings contains something from before.

**Comment by mouse07410** [comment]
> Maybe your extra stack arguments settings contains something from before.

More likely - something stuck from the previous builds, which is impossible to clean normally because there's no "stack clean" possibility.

I cleaned the project, and the rebuild succeed (and REPL started). 

I'm still a little confused how to make the plugin display documentation on a function or such, but that's a different question.

**Comment by rikvdkleij** [comment]
You can always do `stack clean` from the shell :wink:

**Comment by mouse07410** [comment]
> You can always do `stack clean` from the shell ;)

Likewise, `stack build` (with any parameters/arguments I may need), `stack update`, `stack test`, etc. 

Are you suggesting that there's no value in having plugin configuring those for the IDE, letting the IDE help in setting work dir for the operation, env vars, arguments, etc. etc.?

**Comment by rikvdkleij** [comment]
I mean not able to run `stack clean` from the IDE is not really an excuse :smile: 

But yes, when I develop in Haskell, the REPL runs next to the IDE. In the REPL the tests are ran. It would be nice to run the tests from the IDE itself without creating a configuration (like in Java and Scala) but I have to investigate how to develop that.

**Comment by rikvdkleij** [comment]
> I'm still a little confused how to make the plugin display documentation on a function or such, but that's a different question.

Any suggestions are welcome!

**Comment by mouse07410** [comment]
> I mean not able to run `stack clean` from the IDE is not really an excuse

I can do a lot from the terminal in a shell, and I can do a lot using VS Code. 

But we're discussing how to make this nice plugin better and more usable, right? Not how to accomplish what a reasonable developer may want with a different product?

> > confused how to make the plugin display documentation
>
> Any suggestions are welcome!

Is there a standard way that IntelliJ IDEA provides? Sometimes I press F1, and the doc shows up on the right, sometimes it throws me to a browser opening Jetbrains Editor help web-site. 
Perhaps, if one hovers over a highlighted item in the source window for 0.7 seconds, it's a good time to open a doc popup for that item?

**Comment by rikvdkleij** [comment]
You can also view the documentation and other context info in the Documentation tool window. It automatically syncs with the editor.

**Comment by mouse07410** [comment]
Pardon my ignorance - but what is Documentation Tool Window, and how do I get it opened?

**Comment by rikvdkleij** [comment]
When you ask the doc for identifier, the popup contains option to open Tool window.

**Comment by mouse07410** [comment]
> ...you ask the doc for identifier...

Again, pardon my ignorance - *how* do you ask...? I thought it's `F1`, but sometimes it works, and sometimes it doesn't.

**Comment by zeme-wana** [comment]
@mouse07410 
Make sure that these are all checked:
```
File -> Settings -> Editor -> General -> Code Completion -> Show the documentation popup in 
File -> Settings -> Editor -> General -> Code Completion -> Show the parameter info popup in 
File -> Settings -> Editor -> General -> Code Completion -> Show full method signature
File -> Settings -> Editor -> General -> Code Completion -> Show parameter name hints on completion 
```

Then you should be able to get haddock on mouse hovers.
Also check the Messages tab and make sure that the plug in built with no errors.
Try `Haskell -> (Re)build Hoogle Database` if all else fails.

**Comment by rikvdkleij** [comment]
It is also possible to show info in Documentation Tool window which gives more info and syncs with location of cursor in editor.

**Comment by mouse07410** [comment]
> ...possible to show info in Documentation Tool window...

My problem is - I don't know how.

**Comment by mouse07410** [comment]
> Make sure that these are all checked...

I'm afraid that's OS-specific. Here's what my `File ->` gives me:
<img width="651" alt="Screen Shot 2019-09-08 at 12 39 41" src="https://user-images.githubusercontent.com/5923577/64491359-e3e44b80-d235-11e9-9e2f-2b384aad4b55.png">

Here's what should've helped:
<img width="838" alt="Screen Shot 2019-09-08 at 12 42 29" src="https://user-images.githubusercontent.com/5923577/64491427-7d136200-d236-11e9-9cea-3c4b29a899c2.png">

But, regardless, sometimes I get help by pressing `F1`, sometimes - just by hovering, and sometimes - not at all.

**Comment by rikvdkleij** [comment]
I have tried to make screenshot but without success because it's a popup.

But when you press F1 above an identifier, a popup appears and in the top-right corner there is button with three vertical dots. You have to press that button and  there you can select `Open as Tool window`.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
