### ISSUE TITLE
compilation errors when building plugin

### ISSUE THREAD

**Issue by joprice** [rikvdkleij/intellij-haskell#472]
I am interested in contributing, so I tried building the project by following the steps in the contributing guidelines, but the build failed with many compilation, e.g. missing imports like `import com.intellij.compiler.impl._`. It seems like something is missing from the classpath. I made sure to run `updateIdea`, and I did see the correct idea build get downloaded when starting sbt.

**Comment by rikvdkleij** [comment]
Great to hear!

Thanks for reporting. I can reproduce this issue with sbt. There are 2 libraries with same package name. For now I do not know how to solve this.

Alternative solution is to import the project in IntelliJ. Compiling inside IntelliJ works. You can try that.

**Comment by rikvdkleij** [comment]
@joprice Adapted the build instructions because of this issue.

**Comment by mutcianm** [comment]
Please add java plugin as an internal plugin dependency
See https://github.com/JetBrains/sbt-idea-plugin/issues/24#issuecomment-532883050

**Comment by rikvdkleij** [comment]
@mutcianm Thanks for helping!
