### ISSUE TITLE
Parse error when having kind '(m, n) on type signature

### ISSUE THREAD

**Issue by dandoh** [rikvdkleij/intellij-haskell#473]
The following file would compile without errors, but the plugin can not recognize the syntax and show error: `'#' or HaskellTokenType.RIGHT_PAREN expected, got ','`
![image](https://user-images.githubusercontent.com/10379980/64831503-0367d500-d5a4-11e9-8554-e8cddc80102e.png)

Code snippet:
```haskell
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE DataKinds #-}

module Nothing where

import Data.Proxy
import GHC.TypeLits

foo :: (KnownNat m, KnownNat n) => Proxy '(m, n)
foo = Proxy

```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Will fix it.

**Comment by rikvdkleij** [comment]
It's fixed in beta56.
