### ISSUE TITLE
Intellij / maybe the Haskell Plugin makes stack in terminal recompiling everything systematically

### ISSUE THREAD

**Issue by nhenin** [rikvdkleij/intellij-haskell#475]
Hi, 
When I'm using `Intellij` and updating some files into my project via this IDE, `stack` in my terminal recompiles everything all the times instead of recompiling only the necessary files... It is acting like if the IDE is changing the state of all the files of my Haskell Project every time... Could it be a configuration issue ?

**Comment by rikvdkleij** [comment]
IntellIJ saves files automatically so that could be the reason.

But why do want to use `stack` for building your project while using the IntelliJ-Haskell plugin?

**Comment by nhenin** [comment]
Sometimes, the plugin gets jammed somehow, and I find it clearer to see compilation message sometimes... I may not know some features that would change my mind...  Do you a way to configure Intellij for not touching all the files for nothing ?

**Comment by rikvdkleij** [comment]
> Do you know a way to configure Intellij for not touching all the files for nothing ?

No, you can't disable it completely, see also https://stackoverflow.com/questions/28949290/turning-off-intellij-auto-save/28950477#28950477

> and I find it clearer to see compilation messages
sometimes... 

You can see them in Haskell Problem Tool window

> Sometimes, the plugin gets jammed somehow, it does not update things and I need to update settings and restart REPLs etc...

Can you explain how to reproduce that? Normally when project library code is changed and user navigates to code which depends on library code (e.g. test code), the library code is rebuilt and dependent REPLs are restarted. 
Do you have this experience with multi-package project?

**Comment by nhenin** [comment]
yes it's a multi-package project, I didn't find a pattern to reproduce these issues yet, I'll keep you posted when I find one...

**Comment by dandoh** [comment]
@nhenin It could be the case that intellj-haskell compiles with `--fast` flag, but your terminal doesn't.

**Comment by nhenin** [comment]
thank you @dandoh  !! That was exactly that !

**Comment by rikvdkleij** [comment]
Thanks for helping @dandoh !

@nhenin 
But I still wonder why you need to rebuild your project while using the plugin...

**Comment by nhenin** [comment]
```
2019-10-15
1:19 p.m.	[project-stack-repl-dolla-cli-client:lib] Stack REPL couldn't be started within 30 seconds

1:19 p.m.	[project-stack-repl-dolla-cli-client:lib] : can't load .so/.DLL for: /Users/nhenin/dev/Dolla-Blockchain/.stack-work/install/x86_64-osx/233d9c1c289865fb5772f2d25418c14a29c7724b55f0d5d0cf33890cbb8117bd/8.6.5/lib/x86_64-osx-ghc-8.6.5/libHSdolla-team-0.0.0.1-5I3qjA2kKXNIXMdRfbnlN3-ghc8.6.5.dylib (dlopen(/Users/nhenin/dev/Dolla-Blockchain/.stack-work/install/x86_64-osx/233d9c1c289865fb5772f2d25418c14a29c7724b55f0d5d0cf33890cbb8117bd/8.6.5/lib/x86_64-osx-ghc-8.6.5/libHSdolla-team-0.0.0.1-5I3qjA2kKXNIXMdRfbnlN3-ghc8.6.5.dylib, 5): Symbol not found: _dollazmbasezm0zi0zi0zi1zmG3BvKzzg94wLIcAsghvybLW_DollaziCommonziLoggingziCore_zdfLoggableLogger2_bytes (show balloon)

1:19 p.m.	[project-stack-repl-dolla-cli-client:lib]   Referenced from: /Users/nhenin/dev/Dolla-Blockchain/.stack-work/install/x86_64-osx/233d9c1c289865fb5772f2d25418c14a29c7724b55f0d5d0cf33890cbb8117bd/8.6.5/lib/x86_64-osx-ghc-8.6.5/libHSdolla-team-0.0.0.1-5I3qjA2kKXNIXMdRfbnlN3-ghc8.6.5.dylib

1:19 p.m.	[project-stack-repl-dolla-cli-client:lib]   Expected in: flat namespace

1:19 p.m.	[project-stack-repl-dolla-cli-client:lib]  in /Users/nhenin/dev/Dolla-Blockchain/.stack-work/install/x86_64-osx/233d9c1c289865fb5772f2d25418c14a29c7724b55f0d5d0cf33890cbb8117bd/8.6.5/lib/x86_64-osx-ghc-8.6.5/libHSdolla-team-0.0.0.1-5I3qjA2kKXNIXMdRfbnlN3-ghc8.6.5.dylib)
```

**Comment by nhenin** [comment]
I have messages like that for example and Intellij get lost...

**Comment by rikvdkleij** [comment]
I have seen those error in issues of @mouse07410. @mouse07410 can you help?

**Comment by rikvdkleij** [comment]
@nhenin Did you solve this issue?

**Comment by nhenin** [comment]
about having to recompile everything each time, I have fixed the issue by using `--fast` flag... Now the plugin stay jammed from time to time, so I'm still using the terminal sometimes, but it looks like it's less at each updates.... Obviously I'm not giving you that much information to solve the jamming issue...

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
