### ISSUE TITLE
Unknown command ':type-at'

### ISSUE THREAD

**Issue by folex** [rikvdkleij/intellij-haskell#477]
Happens on project [paxoslease](https://github.com/NicolasT/paxoslease) when I try to invoke `Quick documentation` on any variable or function.

![image](https://user-images.githubusercontent.com/1949356/66965363-12014a80-f082-11e9-8225-e823cf649df1.png)

Rebuilding Hoogle DB / Update settings & restart REPL / restarting IDE didn't help.

**Plugin version**: 1.0.0-beta55 , from custom plugins repo.
**IDEA**:
```
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.4386.10, built on October 9, 2019
macOS 10.14.6
```

**Messages:**
```
Information:/usr/local/bin/stack build --fast --no-interleaved-output indexed-prelude:lib paxoslease:lib
Information:indexed-prelude> build (lib)
Information:indexed-prelude> copy/register
Information:paxoslease     > configure (lib)
Information:paxoslease     > build (lib)
Information:paxoslease     > copy/register
Information:Completed 2 action(s).
Information:Log files have been written to: /Users/folex/Development/paxoslease/.stack-work/logs/
```

**Event Log:**
```
1:59 AM	Ambiguous Stack target for file `/Users/folex/Development/paxoslease/paxoslease-interactive/src/Lib.hs`. It can belong to the source dir of more than one Stack target/Cabal stanza: `Set(paxoslease-interactive:exe:paxoslease-interactive-acceptor, paxoslease-interactive:exe:paxoslease-interactive-proposer)`  |  `paxoslease-interactive:exe:paxoslease-interactive-acceptor` is chosen.
```

**Comment by Sir4ur0n** [comment]
Could it be that your project uses an old version of GHC? I see it's using Stack snapshot LTS 6.15 (i.e. GHC 7.10.3) which is quite old!

**Comment by folex** [comment]
That was it! Works with `lts-13.26` and `lts-14.10`, thank you :)

**Comment by rikvdkleij** [comment]
@Sir4ur0n Thanks!
