### ISSUE TITLE
Parsing paths fails for long PATH list in windows

### ISSUE THREAD

**Issue by GalLalouche** [rikvdkleij/intellij-haskell#478]
For some reason, the output of `stack path` will split a very long `%PATH%` list into two lines, which will break the parsing in `intellij.haskell.util.ScalaUtil.linesToMap` (it will throw an `IndexOutBounds` exception).
Trimming my (admittedly too long) `%PATH%` solved the issue.

Tested on Windows 7.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Nice you find the cause. I do not see an urgent reason to solve this.
