### ISSUE TITLE
SDK creation fails if path ends in /stack

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#48]
When first setting this up, I tried to set `/home/chris/.nix-profile/bin/stack` as the path to Stack when creating the SDK, since that's my path to Stack. The first several times it failed silently; the dialog closed and no SDK was added. After a restart of IntelliJ, it started giving an error popup "The selected directory is not a valid home for Stack binary".

It took me a while to figure out that it's actually asking for the path of a directory that contains a stack executable, not the path of a stack executable. It probably ought to either be able to strip the `/stack` from the end on it or have better failure behavior.

intellij community 2016.2.4

intellij-haskell 1.0.0-beta

**Comment by rikvdkleij** [comment]
Thanks for reporting. I will improve that in next version.

**Comment by rikvdkleij** [comment]
I try to reproduce your problem. I do not find a way to select binary instead of folder.

There is already validation and most part is handled by IntelliJ code.

**Comment by rikvdkleij** [comment]
I will change `Stack binary` to `Stack binary folder`

**Comment by chris-martin** [comment]
I didn't use the file browser ui, I just pasted the path into the bar, and when I pressed enter, the dialog closed with no feedback.

**Comment by rikvdkleij** [comment]
Okay, I could reproduce this by pasting path and directly after that, press enter. In that case file browser do not have time to go to location. No SDK is created in that case. 
The code which which is normally invoked for validation and so on, is not invoked. I do not know how to hook into there.

But when importing project by using the wizard, it will not allow to create project without SDK.

**Comment by rikvdkleij** [comment]
Btw, same problem for other SDK's, for example Java SDK

**Comment by rikvdkleij** [comment]
On second thought, I took another look to IntelliJ's code for creating SDK's and I have some idea how to change/override it and make it more solid. In thw new way Stack binary has to be selected. Makes it also better solution, for example, to support Windows.

But it will be breaking change....

**Comment by rikvdkleij** [comment]
Fixed in beta 4.

**Comment by chris-martin** [comment]
Just tried it in beta 5, makes a lot more sense to me now. Thanks!
