### ISSUE TITLE
Background task "Busy with installing hlint ..." 

### ISSUE THREAD

**Issue by totraku** [rikvdkleij/intellij-haskell#480]
In IntelliJ Idea Ultimate version 2019.2.4 I have on both: mac osx (v 10.15.1) and the latest windows 10 the same problem:

> Bussy with installing hlint in /Users/$USER/Library/Caches/com.github.rikvdkleij.intellij-haskell/lts-13/bin (According path in Windows 10)

This process keeps running the whole time and the option to rebuild the hoogle database stays unavailable.

![image](https://user-images.githubusercontent.com/36606809/68112703-38ccd700-fef2-11e9-9d68-e4f7758e078c.png)

![image](https://user-images.githubusercontent.com/36606809/68112714-42563f00-fef2-11e9-862d-28e789b1032c.png)

![image](https://user-images.githubusercontent.com/36606809/68112723-4aae7a00-fef2-11e9-8d45-6ea4876ef3c7.png)

**Comment by rikvdkleij** [comment]
Enable Event log to see what is going on.

Can you install hlint manually?

**Comment by totraku** [comment]
I opened the event log and now somehow everything works. I am not sure what the cause is and how it resolved. I will check the windows machine later and report here

**Comment by rubenhensen** [comment]
I have the same problem. Not sure what's going on, I'm running linux (POP_OS).

**Comment by GordonGgx** [comment]
me too.

**Comment by GordonGgx** [comment]
I've used stack ` install hlint` to install it, but this plug-in doesn't seem to search for the content in` ~. / local / bin` by itself

**Comment by rikvdkleij** [comment]
@GordonGgx Hlint will be automatically installed in the IntelliJ-Haskell cache folder.

When you want to install Hlint yourself, you will have to use beta57.
In beta57 you can set the path to Hlint via Haskell Settings.

**Comment by GordonGgx** [comment]
> @GordonGgx Hlint will be automatically installed in the IntelliJ-Haskell cache folder.
> 
> When you want to install Hlint yourself, you will have to use beta57.
> In beta57 you can set the path to Hlint via Haskell Settings.

Yes, I found it.
