### ISSUE TITLE
new hang — possibly related to updating .cabal file after removing an entry from `packages:` in stack.yaml

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#482]
[threadDumps-freeze-20191106-143858-IC-191.7141.44.zip](https://github.com/rikvdkleij/intellij-haskell/files/3816395/threadDumps-freeze-20191106-143858-IC-191.7141.44.zip)

Thanks for your efforts!

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I took a look to threadDumps but it's not directly clear why IntelliJ should hang. 
After you changed the cabal file, did you restart the REPLs? It looks like IntelliJ wanted to check a Haskell file in the background but the REPL was not (yet) running.

**Comment by aryairani** [comment]
I'm not sure :-\  We can close it if you want.

**Comment by aryairani** [comment]
Oops I meant to comment and let you close it, not close it myself ;-)
