### ISSUE TITLE
Error while calling hlint: Couldn't find file: hlint

### ISSUE THREAD

**Issue by joe307bad** [rikvdkleij/intellij-haskell#483]
I started the project [following the directions](https://docs.haskellstack.org/en/stable/README/) on the Haskell Stack site. Then I installed this plugin using the directions in the README. Everytime I make an edit to a Haskell file, I get a notification balloon that says:
```
Error while calling hlint: Couldn't find file: hlint
```
IntelliJ version:
```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
```
Plugin version:
```
1.0.0-beta52
```
I also tried manually installing the latest beta (`v1.0.0-beta55`) from GitHub and still get the  same error.

Also, it seems everything works fine for IntelliJ IDEA CE, so I will use that for now.

**Comment by rikvdkleij** [comment]
Normally Hlint is automatically installed in the background when one opens a Haskell project for the first time. Check the Event log so see what's going on.

When for whatever reason the Hlint build fails, you can also try the latest beta (beta55) which gives you the option to install Haskell tools by yourself and configure them in Haskell Settings.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
