### ISSUE TITLE
Add support for Ormolu

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#485]
Similar to #319 but for Ormolu

Ormolu formatting is pretty nice, quite some effort and thinking has been put into its design to be both predictable and pragmatic (think Git diff, readability).

They also explain why Yet Another Formatter [in their doc](https://github.com/tweag/ormolu/blob/master/DESIGN.md#analysis-of-the-existing-solutions)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

No problem to implement this one. 
Two remarks:
 - Ormolu is not on Stackage so it can not be automatically build
- Settings page has to be extended with path to Ormolu and some indicator to switch between Hindent/Stylish Haskell and Ormolu

**Comment by Sir4ur0n** [comment]
Indeed, my bad, it's not yet added to Stackage :(
This is linked to https://github.com/tweag/ormolu/issues/412

I guess this issue is on hold until Stackage is supported, sorry for the inconvenience :sweat_smile:

**Comment by rikvdkleij** [comment]
No problem. It's not really a must that Ormolu has to be on Stackage but make life easier :smile:

**Comment by Sir4ur0n** [comment]
Ormolu is now on Stackage, however for the moment it is on Nightly, not LTS 14 (which AFAIU is the LTS used by the plugin to install stuff).

I guess we need to wait until the next LTS containing it before moving on? ^^'

**Comment by rikvdkleij** [comment]
> I guess we need to wait until the next LTS containing it before moving on? ^^'

Yes. In the meantime I will take a look how Ormolu works. Eventually I want to replace Hindent by Ormolu because Hindent is no longer maintained AFAIK.

**Comment by rikvdkleij** [comment]
@Sir4ur0n Question: currently the reformatter works by first using Hindent and then Stylish-Haskell. I wonder if it has to keep working this way or is it sufficient to run Ormolu on it's own? What's your opinion?

**Comment by Sir4ur0n** [comment]
IMHO Ormolu alone is enough. It takes care of imports (indeed import syntax is quite different between Stylish and Ormolu).

Also, in terms of usability, using 2 formatters at once (Hindent **then** Stylish) has weird consequences, like using "Undo" just after a format forces to undo several times (1st Undo undoes Stylish, 2nd undoes Hindent).

**Comment by rikvdkleij** [comment]
beta58 contains Ormolu support by setting path in Haskell Settings.

**Comment by Sir4ur0n** [comment]
What about the "Haskell reformat code" and "Haskell optimize imports" checkboxes in the Commit window?
![image](https://user-images.githubusercontent.com/1204125/74415492-c13d0b00-4e43-11ea-9134-8b3db4cdfeb5.png)

I'm not sure how Hindent/Stylish/Ormolu interact with this feature

**Comment by rikvdkleij** [comment]
The `Haskell optimize imports` has nothing do with the reformatters.

`Haskell reformat code` is the same action as in the editor. So when the path to `ormolu` is defined in Haskell settings then `ormolu` otherwise hindent/stylish.

**Comment by Sir4ur0n** [comment]
I see, thank you!

I am eagerly waiting for LTS 15 [to be released](https://www.stackage.org/blog/2020/02/upcoming-lts-15-ghc-8-8-2) to try all this together 😄

**Comment by declension** [comment]
[LTS 15](https://www.stackage.org/lts-15.0) is out! :tada:

**Comment by Sir4ur0n** [comment]
So far things seem to work just fine, thank you! 

Though I wonder: is there a way to configure "Look in the path for the executable"? Currently I have to provide the full path, and as we use Nix for package management in my team, this leads to annoying (and potentially moving) paths like `/nix/store/f6pjcpcmsgqbj5jgkx15vjcz13vhcwj8-hlint-2.2.2/bin/hlint` that we need to reconfigure every now and then.

FYI the `shell.nix` we use (simplified):
```nix
with import <nixpkgs> {};

let
  unstable = import <nixpkgs-unstable> {};
in
  mkShell {
    # Useful packages for One Catalog, you can manually use `nix-shell` to get a shell with everything configured, or even better, install `direnv`, see `.envrc`
    buildInputs = [
        # Packages needed to build/run the Haskell applications
        stack
        lzma
        zlib

        # Used by Intellij for formatting, code analysis and documentation
        unstable.ormolu
        unstable.hlint
        unstable.haskell.packages.ghc882.hoogle
    ];
  }

```

**Comment by rikvdkleij** [comment]
Should be doable but then I have to extend the Haskell settings with also this way of configuring and find out which one is valid.

Isn't it an option to create a symbolic link `hlint` to the full nix path?

**Comment by Sir4ur0n** [comment]
I searched for a way to "create" symlinks from the `shell.nix` file but failed so far.
I'll take another look tomorrow, maybe I'll have more luck.

In the meantime I keep thinking this would be great.
Note, it could also apply to the `stack` executable, which would help making our projects even more isolated 😄 

But that's easy of me to ask when you are the one developing it, so don't pressure yourself on this 😅

**Comment by rikvdkleij** [comment]
Need some time to figure this out.

As a workaround you can just copy the binaries to e.g. to your`~/bin`
Then at least you have a stable solution because you’re using the nix unstable channel.

**Comment by Sir4ur0n** [comment]
Well I simplified the `shell.nix` I mentioned above, actually we pin the Nixpkgs version:
```nix
with import (builtins.fetchTarball {
       name = "nixpkgs-unstable-2020-02-23";
       url = https://github.com/nixos/nixpkgs/archive/1fe82110febdf005d97b2927610ee854a38a8f26.tar.gz;
       # Hash obtained using `nix-prefetch-url --unpack <url>`
       sha256 = "08x6saa7iljyq2m0j6p9phy0v17r3p8l7vklv7y7gvhdc7a85ppi";
     }) {};
```

The solution you mentioned with copying it to `~/bin` is the same as installing globally, which is exactly what we would like **not** to do as different projects may use different versions of Nixpkgs :sweat_smile: 

As for the two possible ways of configuring, I am not aware of what this implies in the plugin codebase, but can't we imagine that if the configured string is e.g. `ormolu` then just look in the path, otherwise treat it as a full path?
That way the conf in Intellij would be (for Nix users):
![image](https://user-images.githubusercontent.com/1204125/75337275-f65a4c00-588c-11ea-963d-3f7c195379bc.png)

**Comment by rikvdkleij** [comment]
>  which is exactly what we would like not to do as different projects may use different versions of Nixpkgs sweat_smile

But the Haskell tools are not a direct dependency of your nix project. It's only used for IntelliJ.

> As for the two possible ways of configuring, I am not aware of what this implies in the plugin codebase, but can't we imagine that if the configured string is e.g. ormolu then just look in the path, otherwise treat it as a full path?

Yes, that's an idea. Need some time to find out how to implement that.

**Comment by rikvdkleij** [comment]
>> As for the two possible ways of configuring, I am not aware of what this implies in the plugin codebase, but can't we imagine that if the configured string is e.g. ormolu then just look in the path, otherwise treat it as a full path?

>Yes, that's an idea. Need some time to find out how to implement that

I wonder how to find the PATH. Isn't that set in the nix-shell? So how can I find it from within IntelliJ?

**Comment by Sir4ur0n** [comment]
Unfortunately Intellij currently doesn't well support Nix, however I currently start Intellij via my Nix shell:
```shell
$ nix-shell
[...] $ idea-ultimate
```
Thus Intellij has access to my path.

**Comment by rikvdkleij** [comment]
Ok, can you give me the complete nix script(s) to install the Haskell tools via nix so I can test this?

**Comment by rikvdkleij** [comment]
@Sir4ur0n FYI, it already works now when I remove the validation in Settings and the Haskell tools binaries are on the PATH.

**Comment by Sir4ur0n** [comment]
Sorry I completely missed your previous message! Here it is:

```nix
with import (builtins.fetchTarball {
       name = "nixpkgs-unstable-2020-02-23";
       url = https://github.com/nixos/nixpkgs/archive/1fe82110febdf005d97b2927610ee854a38a8f26.tar.gz;
       # Hash obtained using `nix-prefetch-url --unpack <url>`
       sha256 = "08x6saa7iljyq2m0j6p9phy0v17r3p8l7vklv7y7gvhdc7a85ppi";
     }) {};

mkShell {
  buildInputs = [
      # Packages needed to build/run the Haskell applications
      stack
      lzma
      zlib

      # Used by Intellij for formatting, code analysis and documentation
      unstable.ormolu
      unstable.hlint
      unstable.haskell.packages.ghc882.hoogle
  ];
}
```

As for your last message: do you mean it works on some modified version of the plugin? Or it can already work on the latest release?

**Comment by rikvdkleij** [comment]
> As for your last message: do you mean it works on some modified version of the plugin? Or it can already work on the latest release?

It works almost: I only have to remove the validation which checks if absolute path exists.

**Comment by rikvdkleij** [comment]
@Sir4ur0n should work in beta64

**Comment by Sir4ur0n** [comment]
I confirm this works like a charm :tada: 

Thank you very much, this is awesome! :pray:
