### ISSUE TITLE
Ribbon with Hoogle database doesn't exist. Keeps showing up. 

### ISSUE THREAD

**Issue by abhishekvaid** [rikvdkleij/intellij-haskell#488]
I installed latest version of the plugin and plugin seems to be working fine. However, I'm facing two issues: 

Issue 1: 
A Ribbon pops up every time I open the IDE. I have already installed hoogle through stack from CMDline. 
- Hoogle features can be enabled by menu option `Haskell`/`(Re)Build Hoogle database`

Issue 2:
formatting with hindent ( from code toolbar menu) doesn't do anything either. I installed hindent through stack also.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

About issue 1. The popup means that if you want Hoogle support, you need to build the Hoogle database by using the menu option mentioned in the popup.

About issue 2. Hindent (like the other Haskell tools) should be automatically build the first you open a Haskell project. No need to build the tools yourself.
About your issue. Check the Haskell Event log and you can use the `About Haskell Project` menu option to see if the Haskell tools are installed.

Btw, which version do you use? The latest in public repo or alpha repo?

**Comment by abhishekvaid** [comment]
Hi Thanks a prompt response. 

Issue 2 is working now. It's strange but it just started working. I can format now.

Issue 1 is still happening. My plugin version is 1.0.0-beta52. I do get that I need to build Hoogle DB, but how. I tried it from CMD after reading a few posts, but it didn't work. 

Can you tell me exact series of steps I need to do here to circumvent this problem.

**Comment by rikvdkleij** [comment]
You can build the Hoogle db via the menu action `Haskell/(Re)Build Hoogle database`.

Hopefully this helps.

**Comment by rikvdkleij** [comment]
@abhishekvaid Is issue 2 solved?

**Comment by chansey97** [comment]
@rikvdkleij 

I have the same problem of Hoogle. Every time I open the IDE, it tell me that:

> 0:34	Hoogle database doesn't exist. Hoogle features can be enabled by menu option `Haskell`/`(Re)Build Hoogle database`

I don't quite understand this sentence...

Hoogle is a website for search `type signature`, right? 

What do you mean by "The popup means that if you want Hoogle support, you need to build the Hoogle database by using the menu option mentioned in the popup." ?

Could you give me some reference about "Hoogle database" ? 

Sorry, I am not very familiar with Haskell ecosystem. 

Thanks.

**Comment by rikvdkleij** [comment]
This popup means that you can create locally a Hoogle db by using the menu option. This gives you navigation support via hoogle inside your project and libraries.

This is hoogle on the server:
https://hoogle.haskell.org/

In the latest beta's the message of the popup is changed to:
`Hoogle features can be enabled by menu option `Haskell`/`(Re)Build Hoogle database`

**Comment by chansey97** [comment]
I clicked "Haskell/(Re)Build Hoogle database", yes, it will connect internet and download something, but after that, nothing happened (no error or successful information prompt).

If I restart the IDE, then error "Hoogle database doesn't exist. Hoogle features can be enabled by menu option Haskell/(Re)Build Hoogle database" popup again.

About Navigation:

> Navigate to declaration or identifier powered by Hoogle (called Navigate>Navigation by Hoogle in IntelliJ menu);

For example, if I have following code

```
main :: IO ()
main = do
  print $ qsort [5,4,3,2,1,0]
```

I double click `IO` and open "Navigation by Hoogle" in the menu, but the button is grey...

**Comment by rikvdkleij** [comment]
> I double click IO and open "Navigation by Hoogle" in the menu, but the button is grey...

Then something goes wrong while creating the Hoogle db. You can enable the Haskell Event log to see what is going on, see https://github.com/rikvdkleij/intellij-haskell#getting-started

**Comment by chansey97** [comment]
I enable Haskell Event Log by enabling checkbox in the Settings>Appearance & Behavior>Notifications->Haskell Log, and restart IDE to open a Haskell project.

Then the Event log window will print a lot of logs. I searched the "hoogle", it seems that only one line be relevant:

```
...

18:17	[global-stack-repl] stdout: -- not currently imported
					base-4.13.0.0:Control.Monad.ST.Lazy.Imp.unsafeIOToST ::
					IO a -> base-4.13.0.0:Control.Monad.ST.Lazy.Imp.ST s a
					base-4.13.0.0:Control.Monad.ST.Lazy.Imp.unsafeInterleaveST ::
					base-4.13.0.0:Control.Monad.ST.Lazy.Imp.ST s a
					-> base-4.13.0.0:Control.Monad.ST.Lazy.Imp.ST s a
					^IntellijHaskell^

18:17	Finished with preloading library files cache

18:17	Hoogle database doesn't exist. Hoogle features can be enabled by menu option `Haskell`/`(Re)Build Hoogle database`

18:17	Finished initializing Haskell project

18:17	[global-stack-repl] Command :browse! Control.Monad.ST.Safe took + 3 ms
...
```

Then I click `Haskell` -> `(Re)Build Hoogle database`, the window printed
```
2020/4/28
18:23	Building or rebuilding Hoogle database
```
Nothing else...

After that, I restart IDE, the same info appeared `Hoogle database doesn't exist. Hoogle features can be enabled by menu option `Haskell`/`(Re)Build Hoogle database``.

Could you tell me which folder Hoogle downloads in? I want to see if the database is actually downloaded.

**Comment by rikvdkleij** [comment]
The hoogle db is generated in [cachedir]/`intellij-haskell`/[projectname]

Cachedir on Linux is `~/.cache`.
For other OS see https://github.com/soc/directories-jvm

**Comment by chansey97** [comment]
I found [cachedir] on my windows, it is `C:\Users\Chansey\AppData\Local\rikvdkleij\intellij-haskell\cache` ,not `C:\Users\Chansey\AppData\Local\rikvdkleij\intellij-haskell`

Following is my directory structure in `C:\Users\Chansey\AppData\Local\rikvdkleij\intellij-haskell\cache`

├── 8.2.1.ghci
├── default.ghci
├── lib
│   └── quick-sort (There are lot of thing in it)
├── lts-13
│   ├── bin
│   ├── build-plan
│   ├── build-plan-cache
│   ├── config.yaml
│   ├── global-project
│   ├── indices
│   ├── loaded-snapshot-cache
│   ├── precompiled
│   ├── setup-exe-cache
│   ├── setup-exe-src
│   └── snapshots
├── quick-sort **(It is empty!)**
└── repl.ghci


I open a project named `quick-sort`, then click menu action `Haskell/(Re)Build Hoogle database.`. 

It seems to download something in the `Backgound Task` by stack, but after that the `quick-sort` folder still empty.

**Comment by rikvdkleij** [comment]
I have no idea what is going wrong. After you click the action to (re)build the Hoogle db,  you should see a background action which rebuilds your project.

I just checked with this project https://github.com/rikvdkleij/quicksort and it works.

Btw, if you want to try the latest beta, see https://github.com/rikvdkleij/intellij-haskell#installing-latest-beta-of-the-plugin

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
