### ISSUE TITLE
"Stack repl is not yet available"

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#49]
The event log prints this many times:

`12:02 AM   [project-stack-repl] Stack repl is not yet available. Command was: :load /home/chris/foo/Foo.hs`

There are no other messages, and I don't know what this message means. I'm not trying to use a REPL; I'd just like compile messages to show up in the editor. I haven't managed to get this plugin to do anything yet. Really excited about getting it working though :)

intellij community 2016.2.4

intellij-haskell 1.0.0-beta

My distro is NixOS, in case that's relevant (since it often is with this sort of thing...)

**Comment by rikvdkleij** [comment]
That means Stack repls are not available because Stack is building project. There should be info in event log about progress of building.

**Comment by chris-martin** [comment]
> There should be info in event log about progress of building.

Unfortunately, there is nothing else.

I've had this file open for plenty of time for Stack to build the project (it's a small single-file affair that I just started), so it doesn't seem like that's happening.

**Comment by rikvdkleij** [comment]
I have not experience with NixOS.

Can  you run this command in root of your project?
`stack repl --with-ghc intero --verbosity warn --fast --no-load --no-build --ghc-options -v1 --terminal --test`

**Comment by chris-martin** [comment]
```
> stack repl --with-ghc intero --verbosity warn --fast --no-load --no-build --ghc-options -v1 --terminal --test
Intero 0.1.18 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

Prelude> 
```

**Comment by rikvdkleij** [comment]
Thanks. That seems to work.

This is the build command before it start the repls:
`stack build --test --only-dependencies --haddock --fast`

Can you try that also?

Problem could be that because of NixOS the environment variables as seen by IntelliJ, are different then from command line.

**Comment by chris-martin** [comment]
That works also.

That does seem plausible. Do the "Path variables" in the IntelliJ settings get set as environment variables when intellij-haskell runs these commands?

**Comment by rikvdkleij** [comment]
I only this hit this kind of problem with testing on OSX. So in case of OSX I'm passing the environment variables to the process. I can change this code so it's not only done for OSX.

I will upload new version with this change so you can try if it works.

**Comment by rikvdkleij** [comment]
You can download new version of plugin from here and install it from disk:
https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0.beta2

**Comment by rikvdkleij** [comment]
Can you check version 1.0.0-beta3?

**Comment by chris-martin** [comment]
Just tried 1.0.0-beta3 - Nothing seems to be different.

**Comment by rikvdkleij** [comment]
Can you give complete Event log?

It's very difficult to find cause remote.

**Comment by chris-martin** [comment]
I haven't omitted anything, it's exactly the same as it was before. The event log contains this line repeatedly:

```
[project-stack-repl] Stack repl is not yet available. Command was: :load /home/chris/foo/Foo.hs
```

and nothing else.

**Comment by rikvdkleij** [comment]
Does your project contains a Haskell module in project settings?

Can you remove Intellij project configuration files and reimport project (path to Stack folder is now set, I assume)

**Comment by rikvdkleij** [comment]
To elaborate: I suspect the Stack repls are not started because your project is not recognized as Haskell project. A project is recognized as Haskell project if Haskell SDK contains path to Stack folder AND it contains a Haskell module. Because IntelliJ's validation for creating proper SDK was failing, it created a project without Haskell module.

**Comment by chris-martin** [comment]
Oh! I'm sorry, I guess I just didn't realize that the setup instructions had to be followed that closely. Also I had to switch from IntelliJ 15 to 2016.

But now I have this working! Thank you so much! This is going to drastically improve how I use Haskell.

**Comment by rikvdkleij** [comment]
No problem. I'm glad it works for you!

Btw, I'm still busy with improvements and adding features.

**Comment by andrewufrank** [comment]
i have imported a project (haskell code) but i do not see how to make it a haskell project. the directories are marked as source, but not the project. how can i change the type of the project?
thank you!

**Comment by rikvdkleij** [comment]
@andrewufrank Can you give some info about what you have done and what you currently see in project/module settings?

Did you import Stack project?

**Comment by andrewufrank** [comment]
i have imported a project (haskell code) but i do not see how to make it a haskell project. the directories are marked as source, but not the project. how can i change the type of the project?
the solution i found is to create a new haskell project and then copy all files over - not very good.
thank you for a nice tool!

**Comment by chris-martin** [comment]
This is back, and this time I have a very log event log for you.

https://gist.github.com/chris-martin/9f1365fbe2cce62f702efc33b02fefd9

**Comment by chris-martin** [comment]
`stack build intero` on the command line does fail, though. Is that the problem?

**Comment by chris-martin** [comment]
Related? https://github.com/commercialhaskell/intero/issues/334

Also, I just upgraded my dependencies to LTS 8.0.

**Comment by chris-martin** [comment]
Ah yes, I figured this one out. I had `containers` upgraded beyond the LTS, and apparently that causes intero not to compile. I was quite caught by surprise to find out that changing the dependencies in my project could cause the IDE to not work anymore.

**Comment by rikvdkleij** [comment]
Because Intero has to be compatible with your project, the same dependencies are used. Everything has it's pros and cons. Otherwise you have build it manually yourself for each project.
