### ISSUE TITLE
Not working with rainbow brackets plugin

### ISSUE THREAD

**Issue by dima74** [rikvdkleij/intellij-haskell#490]
All brackets have yellow color, when using [rainbow brackets plugin](https://github.com/izhangzhihao/intellij-rainbow-brackets):

![image](https://user-images.githubusercontent.com/6505554/70864613-caede380-1f64-11ea-90d5-1d06b8f41c25.png)

It is likely because expressions have flat structure, thus preventing rainbow brackets plugin from finding matched brackets. Screenshot with PSIViewer plugin:

![image](https://user-images.githubusercontent.com/6505554/70864835-67b18080-1f67-11ea-86d0-0005341cae59.png)

**Comment by izhangzhihao** [comment]
It's there any plan to implement a proper PSI tree?

**Comment by rikvdkleij** [comment]
@izhangzhihao Yes, see https://github.com/rikvdkleij/intellij-haskell/tree/layoutlexer, Any help is welcome.

**Comment by rikvdkleij** [comment]
@dima74 @izhangzhihao It works in beta66!

**Comment by dima74** [comment]
@rikvdkleij yes, and if I understand correctly it works with other betas too (at least it worked for me in beta65), because `@izhangzhihao` added [workaround](https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/a2aae887b4e599f8d7b0cfa8239f0ff311a668e6) for haskell in [rainbow brackets 5.31](https://github.com/izhangzhihao/intellij-rainbow-brackets/releases/tag/5.31)

**Comment by rikvdkleij** [comment]
@dima74 okay, I see. So the credits go to @izhangzhihao.
