### ISSUE TITLE
On Windows, opening previously created stack project, causes intellij-haskell to try and create instead of open

### ISSUE THREAD

**Issue by rubin55** [rikvdkleij/intellij-haskell#494]
After following the "Getting Started" section of the README.md, I succesfully opened a stack project without errors, with verified-working hoogle lookups for types and syntax highlighting, hlint, etc.

However, on re-opening of the project (close project, at project window, open the project in the list) I get the following errrors: 

```
30/12/2019
13:40	Couldn't create new Stack project:  'stty' is not recognized as an internal or external command,
			operable program or batch file.
			[0mDownloading template "new-template" to create project "husky-tricks" in the current directory[0m
			[0mThe template would create the following files, but they already exist:
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\.gitignore
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\ChangeLog.md
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\README.md
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\Setup.hs
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\app\Main.hs
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\package.yaml
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\src\Lib.hs
			C:\Users\rubin\Syncthing\Source\Rubin\husky-tricks\test\Spec.hs
			Use --force to ignore this, and overwite these files.[0m
```

I see two issues here:

 1. what is the stty command doing here?
 2. Why is stack create called when the project clearly exists?

**Comment by rikvdkleij** [comment]
Looking to the errors you didn't request to (re)open a project but you created a new project.

`stty`command  is not from the plugin.

**Comment by rubin55** [comment]
I miread the README.md; it currently states that: 

 * After your project is built successfully, import project in IntelliJ by using File>New>Project from Existing Sources... from the IntelliJ menu;
 * In the New Project wizard select Import project from external model and check Haskell Stack;

I tried to do that from the Project dialog that IntelliJ starts up with; there, you cannot select New Project from Existing Sources, so I selected New Project, thinking the "from Existing Sources" part would come later (it didn't).

Regardless, the error was a one-off anyways; after opening the project a 2nd time, it did not happen anymore.

**Comment by rikvdkleij** [comment]
Yes, I see, that is confusing! I will adapt the README, Thanks!
