### ISSUE TITLE
On Windows, hover over "putStrLn" does not show documentation

### ISSUE THREAD

**Issue by rubin55** [rikvdkleij/intellij-haskell#495]
I have an example Lib.hs file with a few functions. one using `product`, the other using `putStrLn`. Hovering over `product` gives me relevant hoogle documentation. Hovering over `putStrLn` does not:

Not for `putStrLn`:
![no-hover-docs-for-putstrln](https://user-images.githubusercontent.com/6214491/71582739-28ad2e80-2b14-11ea-8f9e-7d1c0dd2b44e.png)

Yes for `product`:
![yes-hover-docs-for-product](https://user-images.githubusercontent.com/6214491/71582750-35ca1d80-2b14-11ea-8187-2e66baeb3fe2.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting! 

Can you try the latest beta, beta57?. It works for me.

**Comment by rubin55** [comment]
I downloaded beta57 from the releases page, replaced the intellij-haskell plugin directory in ~/.IntelliJ*/config/plugins, started IntelliJ and opened the project (hosted here btw: https://github.com/rubin55/husky-tricks); intellij-haskell rebuilds itself due to lts14 usage. closed the project after all build jobs were done, exited IntelliJ, re-opened the project, still no documentation for putStrLn:
![using-beta57-still-no-docs-for-putstrln](https://user-images.githubusercontent.com/6214491/71619800-dbda5e00-2bce-11ea-8893-fe2539ffd834.png)

**Comment by rubin55** [comment]
I also notice that GoTo (ctrl-b) works for the `product` case, and not for the `putStrLn` case, maybe that's significant?

**Comment by rikvdkleij** [comment]
> I would like to understand what the plugin is doing to fill those fields; maybe a hoogle search is going awry - is there a way to log the commands or calls that the plugin is making?

Yes. you can enable the `Haskell Event log`, see README.

> . Closed the project after all build jobs were done, exited IntelliJ, re-opened the project, still no documentation for putStrLn:

Did you build the Hoogle database? A notification popups when your open a project and it's not done yet.

> I also notice that GoTo (ctrl-b) works for the product case (i.e, opens Foldable.hs at the product implementation), and not for the putStrLn case, maybe that's significant?

Maybe the event log contains some clue....

**Comment by rubin55** [comment]
Hoogle database was created/updated, yes.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
