### ISSUE TITLE
Hlint inspection -> show inspection information links to deprecated hlint home

### ISSUE THREAD

**Issue by rubin55** [rikvdkleij/intellij-haskell#496]
When selecting "show inspection information", a link is presented, which points to community.haskell.org/~ndm/hlint/ . However, community.haskell.org is defunct , according to: https://wiki.haskell.org/Community_server_(defunct)

It happens here:
![hlint-homepage-link-dead](https://user-images.githubusercontent.com/6214491/71583324-9eb29500-2b16-11ea-9c75-c47b3b8404d5.png)

Maybe better to link to: https://github.com/ndmitchell/hlint

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
