### ISSUE TITLE
double-qualifying autocompleted identifiers in beta57?

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#497]
Given:
```
import qualified Unison.HashQualified'         as HQ'
```
![image](https://user-images.githubusercontent.com/538571/71592463-5dae8680-2afe-11ea-9918-1a755b22df83.png)

See how the autocomplete is `HQ'.HQ'.requalify`?  But it should just be `HQ'.requalify` as the longer name doesn't exist.

Here's a crazier example:
given
```
import qualified Unison.Codebase.Editor.Output.BranchDiff as OBranchDiff
```
![image](https://user-images.githubusercontent.com/538571/71592546-a9613000-2afe-11ea-8e11-3aed689d4577.png)

P.S. This may have been in beta55 too, I'm not sure.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I can not reproduce this issue. I tried several scenarios.

What are your code completion settings and at which location do you request code completion?

**Comment by aryairani** [comment]
Oops, where can I find my code completion settings?

As a test just now, I did
```
git clone --recursive https://github.com/unisonweb/unison
```
did "New project from existing sources..."
"Haskell Tool Stack 1.9.3 (2.1.3 )"

Navigate -> File -> `HandleInput.hs:206:49` and did Ctrl+Space (Code Completion -> Basic).

![image](https://user-images.githubusercontent.com/538571/71597207-4bd5df00-2b10-11ea-9efd-3cac77d2b484.png)

The first completion is `HQ'.Unison.HashQualified'.NameOnly`, which doesn't exist; it should be `HQ'.NameOnly`.

The import was
```
import qualified Unison.HashQualified'         as HQ'
```

**Comment by rikvdkleij** [comment]
> Oops, where can I find my code completion settings?

If you go to settings and then search for "code completion" you will find them.
For me `Match case` and `First letter only` are enabled.

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/71598693-dec54800-2b15-11ea-9b50-56b94ef4db8f.png)

**Comment by rikvdkleij** [comment]
Eventually I could reproduce your issue and fix it.

**Comment by aryairani** [comment]
❤️

**Comment by rikvdkleij** [comment]
Should be fixed in beta59

**Comment by aryairani** [comment]
Thanks Rik!

**Comment by rikvdkleij** [comment]
@aryairani I wonder if you experience IDE freezes with beta59

**Comment by aryairani** [comment]
I'll keep you posted!  Probably safe to close IDE freeze tickets with earlier builds, if you want?

**Comment by rikvdkleij** [comment]
If beta61 solves the issue we can close them all 😄
