### ISSUE TITLE
Automatic imports don't work

### ISSUE THREAD

**Issue by i-schuetz** [rikvdkleij/intellij-haskell#499]
I seem to be unable to auto import modules. They're in the same (or nested) directory. Project: https://github.com/i-schuetz/dmmf

They don't work anywhere. Just a random example:
E.g. https://github.com/i-schuetz/dmmf/blob/master/src/Types/PersonalName.hs#L3

**Comment by rikvdkleij** [comment]
Thanks for reporting!

What do you mean exactly? What do you expect?

I have cloned your project and opened inside IntelliJ,  For me the auto completion on importing  project modules works in e.g. `PersonalName.hs`.

**Comment by rikvdkleij** [comment]
Took a better look and found a serious bug. Thanks!

**Comment by i-schuetz** [comment]
Thanks for looking again into it @rikvdkleij! I haven't had time.
