### ISSUE TITLE
When ghc-modi reports an error, the plugin times out

### ISSUE THREAD

**Issue by KasperJanssens** [rikvdkleij/intellij-haskell#5]
Minor nitpick, ghc-modi reported that I should do a cabal install, basically, before I could call ghc-modi. In the idea, ghc-modi kept timing out, so it took me some time to find out what the issue was (until I decided to run ghc-modi myself). Might be an idea to intercept and display that error message instead of timing out. But a minor issue, like I said.

Edit: Maybe I try to fix this myself one of these days, it's not very urgent and seems like within my reach, as complexity goes.

**Comment by rikvdkleij** [comment]
Fixed
