### ISSUE TITLE
Parse failure when using TypeFamilyDependencies

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#500]
The parser seems to break when using [TypeFamilyDependencies](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-TypeFamilyDependencies) extension.

Example:
```haskell
{-# LANGUAGE TypeFamilyDependencies #-}

class Foo (bar :: *) where
  type MyType bar = alias | alias -> bar
```

This compiles fine with GHC/Stack (`lts-14.16`)

The parser breaks on the vertical pipe.

![image](https://user-images.githubusercontent.com/1204125/72175311-313b1a00-33dc-11ea-872e-91af29095ab4.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I will fix this parser issue.

**Comment by rikvdkleij** [comment]
Should be fixed in beta58.

**Comment by Sir4ur0n** [comment]
Thank you, this seems to be fixed with beta 58 :100:
