### ISSUE TITLE
Publish again the plugin

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#501]
Hi,

I could not find any issue regarding this yet. It seems that this plugin is no longer published on Intellij website (and thus, on auto updating from Intellij), is this intentional?

I think many users never come on Github to manually download and install the latest release :disappointed: 

Cheers!

**Comment by rikvdkleij** [comment]
Well, the latest releases are still published to the alpha plugin repo.

My plan is/was is that changes are first tested before they are published to the normal repo. I try to be careful with publishing new releases... but I admit it's time to do publish a new release to the normal repo.

**Comment by Sir4ur0n** [comment]
Also, don't you agree it's time to go out of beta? 65K+ downloads, this plugin is now used for real in many projects and teams.
Not being tagged as beta would maybe help more developers feel safe using it?

**Comment by rikvdkleij** [comment]
Yes, you are right.

Plan is to release a 1.0.0 version soon with:
- Some small fixes and  (performance) improvements 
- Upgrade to LTS-15. 
- Replace Hindent by Ormolu 
- Create a workaround for the fact that the source code of base-4.13 (GHC 8.8.2) is not on Hackage

Would be great to get some testing support!

**Comment by rikvdkleij** [comment]
@Sir4ur0n if beta72 is okay, it will become 1.0.0

**Comment by Sir4ur0n** [comment]
As explained in the folding issue, there's a minor bug with regards to the folding settings. Other than that, it looks good to me, I think going out of beta is nice once this is fixed!

**Comment by rikvdkleij** [comment]
Folding issue should be fixed in beta73.
I've uploaded beta73 to the stable channel of the Jetbrains plugin repo.

**Comment by rikvdkleij** [comment]
So I've changed my mind :smile: but at least everyone can now use the latest beta.

Next step is to go to 1.0.0

**Comment by Sir4ur0n** [comment]
I think it's now ok to publish as stable release, don't you agree?

**Comment by rikvdkleij** [comment]
@Sir4ur0n it’s published to to stable channel, see my 2 previous comments.

**Comment by Sir4ur0n** [comment]
I think I have misunderstood your comments :sweat_smile: 

You have published the 73 beta on the stable Intellij channel, correct?

What do you think is missing to actually tag it as 1.0.0?

**Comment by rikvdkleij** [comment]
> You have published the 73 beta on the stable Intellij channel, correct?

Yes.

> What do you think is missing to actually tag it as 1.0.0?

Some more testing/feedback. Version 1.0.0 gives high expectations :smile:

**Comment by rikvdkleij** [comment]
Still no version 1 but latest versions are published to stable channel.
