### ISSUE TITLE
Build plugin failed.

### ISSUE THREAD

**Issue by skyrylyuk** [rikvdkleij/intellij-haskell#504]
Hello

I am passionate about your work
In my opinion - at the moment - this is the best tool to work with.

Can you update 'How to build project' section in documentation or provide addition instructions how correct setup work environment  for build.

Kind regards.

**Comment by rikvdkleij** [comment]
> I am passionate about your work
In my opinion - at the moment - this is the best tool to work with.

Thanks!

> Can you update 'How to build project' section in documentation or provide addition instructions how correct setup work environment for build.

These instructions https://github.com/rikvdkleij/intellij-haskell/blob/master/CONTRIBUTING.md should be right. Otherwise let me know what your problem is.

**Comment by skyrylyuk** [comment]
Hello 

I have next issue:




1. Set correct version openjdk version (1.8.0_232), scala (2.13.1), sbt(1.3.7)  host MasOS
2. Clone project into empty directory
3. Navigate to project directory
4. Execute in shell command from tutorial `sbt updateIdea`

As result receive error 

`sbt updateIdea
[info] Loading global plugins from /Users/skyrylyuk/.sbt/1.0/plugins
[info] Loading settings for project intellij-haskell-build from plugins.sbt ...
[info] Loading project definition from /Users/skyrylyuk/pump/intellij-haskell/project
[info] Loading settings for project intellijHaskell from build.sbt ...
[info] Set current project to IntelliJ Haskell (in build file:/Users/skyrylyuk/pump/intellij-haskell/)
[success] Total time: 0 s, completed Jan 30, 2020 8:16:56 PM
[error] Expected ';'
[error] Not a valid command: updateIdea
[error] Not a valid project ID: updateIdea
[error] Expected ':'
[error] Not a valid key: updateIdea (similar: update, updateIntellij, updateCacheName)
[error] updateIdea
[error]           ^`
<img width="761" alt="Screen Shot 2020-01-30 at 20 17 23" src="https://user-images.githubusercontent.com/785578/73478300-85636980-439e-11ea-93af-209cdcceb8e8.png">

Kind regards

**Comment by rikvdkleij** [comment]
Ok, I see, this command is changed to 
`updateIntellij`
in later versions of `sbt-idea-plugin`, see https://github.com/JetBrains/sbt-idea-plugin

**Comment by skyrylyuk** [comment]
Thanks, your advice is work!

But I have one more question, does `sbt runIDE` should work for run IDE with plugin? 
If answer is yes, may be you can help with next issue
`
JDK Required: Cannot load a JDK class: com.sun.jdi.Field
Please ensure you run the IDE on JDK rather than JRE.
<img width="642" alt="Screen Shot 2020-01-30 at 21 26 18" src="https://user-images.githubusercontent.com/785578/73483106-949ae500-43a7-11ea-9e66-0f1296e2e23d.png">

`

**Comment by rikvdkleij** [comment]
> But I have one more question, does sbt runIDE should work for run IDE with plugin?

I never used that way to run the plugin. But your issue is that you need to install locally a JDK instead of JRE.

**Comment by skyrylyuk** [comment]
I use sdkman to setup JDK and other java tools
How do you think it can be reason of this issue?

**Comment by rikvdkleij** [comment]
I don't know.

You can also start the plugin from inside IntelliJ according to the instructions in `CONTRIBUTING.md`

**Comment by garetht** [comment]
@skyrylyuk The `sbt-idea-plugin` [automatically downloads the IDEA source into](https://github.com/JetBrains/sbt-idea-plugin#intellijdownloaddirectory-in-thisbuild--settingkeyfile) a folder in the home directory. When I got a similar error I deleted the the entire IDEA directory there and tried running `runIDE` again from within the SBT shell, which worked.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
