### ISSUE TITLE
Doesn't load sources of base-4.13.0

### ISSUE THREAD

**Issue by arthurborisow** [rikvdkleij/intellij-haskell#511]
Try to create new project with latest haskell 8.8.2. It won't download sources for base-4.13.0 so you can't navigate to them. But if you change haskell version to 8.6.5 it will download base-4.12.0 and everything works smoothly.

Plugin version: 1.0.0-beta58
Stack version: 2.1.3
GHC: 8.8.2

MacOs X Catalina 10.15.2

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Base 4.13 is not on Hackage..

**Comment by rikvdkleij** [comment]
FYI: https://github.com/haskell-infra/hackage-trustees/issues/240

**Comment by arthurborisow** [comment]
thanks for your input. I guess nothing can be done here from your part so ticket can be closed. Anyway appreciate your work on this plugin!

**Comment by rikvdkleij** [comment]
@arthurborisow I have put in the intellij-haskell gitter channel some instructions how to workaround

**Comment by arthurborisow** [comment]
@rikvdkleij thanks, it's working

**Comment by rikvdkleij** [comment]
Should be fixed in beta64
