### ISSUE TITLE
Lags on code editing

### ISSUE THREAD

**Issue by Nexmean** [rikvdkleij/intellij-haskell#513]
Starting from beta58 there appeared lags when editing code (write, delete, etc).

No special steps. I am just using plugin with project ~100KLOC and 20 packages.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you try beta59?

**Comment by Nexmean** [comment]
@rikvdkleij yes, I tried today. Beta59 is affected too.

**Comment by rikvdkleij** [comment]
Does it help if you disable HLint inspection?

**Comment by rikvdkleij** [comment]
Should be fixed in beta61

**Comment by Nexmean** [comment]
Thank you, now it works fine.

**Comment by rikvdkleij** [comment]
Great! Thanks for the confirmation!
