### ISSUE TITLE
unexpected hang in beta59

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#515]
I had started typing a type when it hung; not sure if coincidence or not.

<img width="450" alt="Screen Shot 2020-02-19 at 4 30 46 PM" src="https://user-images.githubusercontent.com/538571/74878688-c283a180-5335-11ea-85bf-0f50fec3631a.png">

[threadDumps-freeze-20200219-162702-IC-193.6015.39.zip](https://github.com/rikvdkleij/intellij-haskell/files/4227549/threadDumps-freeze-20200219-162702-IC-193.6015.39.zip)

**Comment by aryairani** [comment]
So far so good, after restarting IDEA.

**Comment by rikvdkleij** [comment]
There is a bug in beta58 and 59. Can you try beta61?

**Comment by ilyakooo0** [comment]
This still happens in beta-61 for me

**Comment by ilyakooo0** [comment]
[threadDumps-freeze-20200225-182206-IU-193.6494.35-ConcurrentHashMap.computeIfAbsent-50sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4250733/threadDumps-freeze-20200225-182206-IU-193.6494.35-ConcurrentHashMap.computeIfAbsent-50sec.zip)

**Comment by rikvdkleij** [comment]
Should be solved in beta62.

**Comment by rikvdkleij** [comment]
Problem was still in beta62. Released beta63 which should solve this issue :smile:

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
