### ISSUE TITLE
IDE is stuck after restart

### ISSUE THREAD

**Issue by L7R7** [rikvdkleij/intellij-haskell#516]
As I already said in Gitter, I experience some significant lags and freezes when working with Stack projects. It seems to be better after the latest plugin update (I'm on 1.0.0-beta61 now), but I just had a lag just now. What I did is the following:

1. The stack project is the only instance of IntelliJ that is running
1. I added a new dependency to the cabal file
1. After saving the file, I clicked on "Update Settings and restart REPLs". It updates stuff, but seems to be stuck in "Busy preloading caches", so I restart IntelliJ after a while
1. After the restart, the IDE freezes for several minutes before the IDE is usable again. The IDE logs show a lot of `Not enough pooled threads; dumped threads into file '/...` messages.

I'll attach the zip containing logs and diagnostic data in [idea-logs-20200221-200932.zip](https://github.com/rikvdkleij/intellij-haskell/files/4237688/idea-logs-20200221-200932.zip). I hope that helps. Let me know if you need more information, I'm happy to help.

I'm running Ubuntu 19.10, 1.0.0-beta61 of the Haskell plugin, and have the following IDE details:
```IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.5616.10, built on February 19, 2020
IntelliJ IDEA EAP User
Expiration date: March 20, 2020
Runtime version: 11.0.6+8-b722.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-41-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: uk.co.ben-gibson.remote.repository.mapper, zielu.gittoolbox, Lombook Plugin, intellij.haskell, com.intellij.plugins.watcher, org.intellij.plugins.hcl, name.kropp.intellij.makefile, org.jetbrains.plugins.go-template, com.intellij.kubernetes, org.intellij.scala, org.jetbrains.plugins.vue```

**Comment by rikvdkleij** [comment]
So, I found a thread blocked while doing a file access action during a read action. I will take a look how to prevent that.

**Comment by rikvdkleij** [comment]
Should be solved in beta62

**Comment by rikvdkleij** [comment]
Problem was still in beta62. Released beta63 which should solve this issue :smile:

**Comment by L7R7** [comment]
Seems to be solved by beta63 indeed. I'll close the ticket for now
