### ISSUE TITLE
Incompatible with 2020.1 EAP?

### ISSUE THREAD

**Issue by dsvensson** [rikvdkleij/intellij-haskell#517]
Trying to create a run configuration yields this message:

_"Unable to save plugin settings: The plugin intellij.haskell failed to save settings and has been disabled. Please restart IntelliJ IDEA"_

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I can not reproduce this issue in 2019.3.3. Will try later in 2020.1

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
