### ISSUE TITLE
Problems with hash (#)

### ISSUE THREAD

**Issue by Nexmean** [rikvdkleij/intellij-haskell#519]
There are two problems with hash symbol. Both can be reproduced with lens.

1) Problem with (#) as operator
```haskell
_Success # res
```
In code above `_Success #` parsed as one token, so there is not working "go to defenition" and "type info" shows type of `(_Success #)`.

2) Problem with `OverloadedLabels`
```haskell
a ^. #info . #code
```
Code above uses `generic-lens` with `OverloadedLabels` to access fields of some struct. But if I ask for "type info" on "#" it shows me type of `(#)` operator in `lens` and if I ask for type info on another symbol it shows me type of nearest definition of this field.

In both cases extension `MagicHash` isn't enabled. In second case `OverloadedLabels` extension is enabled.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
@Nexmean thanks for becoming a GitHub sponsor!

**Comment by Nexmean** [comment]
@rikvdkleij thank you! You are doing really great job for the Haskell community!

**Comment by rikvdkleij** [comment]
Should be fixed in beta64

**Comment by Nexmean** [comment]
Thank you! Now it works fine.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
