### ISSUE TITLE
Character '|' leans backward.

### ISSUE THREAD

**Issue by dandoh** [rikvdkleij/intellij-haskell#522]
I notice the difference how character `|` is rendered between Haskell and Elm (and all other languages), not sure if because `intelli-haskell` thou?

Screenshots:
Haskell:
![image](https://user-images.githubusercontent.com/10379980/75708748-6c94ef00-5c8f-11ea-82c3-a4df22a42f74.png)
Elm:
![image](https://user-images.githubusercontent.com/10379980/75708766-7585c080-5c8f-11ea-9f91-672237cf2c6b.png)

I'm using `Jetbrains Mono` btw.

**Comment by Nexmean** [comment]
You can setup it self. Go to Settings > Editor > Color Scheme > Haskell, choose "reversed symbol" in list of tokens, toggle off "Inherit values from:" and then toggle off "italic".

**Comment by dandoh** [comment]
@Nexmean Thank you !

**Comment by rikvdkleij** [comment]
@Nexmean Thanks for your help!
