### ISSUE TITLE
trouble autocompleting a class name

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#523]
Maybe similar to #497 

![image](https://user-images.githubusercontent.com/538571/75768250-45e4c000-5d44-11ea-9a61-201746ee019d.png)

![image](https://user-images.githubusercontent.com/538571/75768274-509f5500-5d44-11ea-9a63-e97e62c7505a.png)

I was expecting it to complete to `Codebase.BuiltinAnnotation` 😬

**Comment by rikvdkleij** [comment]
Thanks for reporting! I will take a look soon.

**Comment by rikvdkleij** [comment]
Should be fixed in beta64

**Comment by aryairani** [comment]
It looks like it.  Thanks!
