### ISSUE TITLE
possible hang (beta63)

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#526]
[threadDumps-freeze-20200305-224904-IC-193.6494.35-EventLogConsole.doPrintNotification-153sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4295866/threadDumps-freeze-20200305-224904-IC-193.6494.35-EventLogConsole.doPrintNotification-153sec.zip)

**Comment by rikvdkleij** [comment]
Thanks!

I don't see an issue with the plugin itself. It looks like you have enabled the Haskell Event log which is producing a lot of log lines and that buffer is getting full.

**Comment by aryairani** [comment]
Oh no, haha ok.  Well, do you recommend I turn it off?

**Comment by rikvdkleij** [comment]
> Oh no, haha ok. Well, do you recommend I turn it off?

Normally yes, that's also the default.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
