### ISSUE TITLE
wrong redundant import removed (beta64)

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#527]
For this example, I have a redundant imported symbol, per `ghcid`'s output: 

![image](https://user-images.githubusercontent.com/538571/76909851-c518de80-6882-11ea-936e-5297951f8895.png)

intellij-idea shows the same redundant import
![image](https://user-images.githubusercontent.com/538571/76909826-ad415a80-6882-11ea-97bb-13d70e8bc93d.png)

and the following action:
![image](https://user-images.githubusercontent.com/538571/76909887-ee396f00-6882-11ea-84d9-a162c058dcc6.png)

but when executed, line 23 was removed (the qualified import), not line 24:
![image](https://user-images.githubusercontent.com/538571/76909922-027d6c00-6883-11ea-9ab7-fe293dd4c5ce.png)

which is not what we wanted:
![image](https://user-images.githubusercontent.com/538571/76909991-29d43900-6883-11ea-9da2-a32322e6fb87.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Should be fixed in beta65.

**Comment by aryairani** [comment]
Seems improved!  I ran into a related issue though:

![image](https://user-images.githubusercontent.com/538571/78139225-264dbf80-73f6-11ea-95b5-7fcc272603a7.png)

becomes:

![image](https://user-images.githubusercontent.com/538571/78139293-441b2480-73f6-11ea-8227-27cf24a33781.png)

In this case, the `(..)` should go away as part of `ExceptT(..)` 😬

**Comment by aryairani** [comment]
Oh, sorry, maybe not really related; I can move it to a new ticket if you want?

**Comment by aryairani** [comment]
Same with:

![image](https://user-images.githubusercontent.com/538571/78139502-a4aa6180-73f6-11ea-97dd-b1ebb6019352.png)

![image](https://user-images.githubusercontent.com/538571/78139531-ae33c980-73f6-11ea-96f4-766faae6febe.png)

(The parens don't go away with `Codebase(Codebase)`.)

**Comment by rikvdkleij** [comment]
@aryairani Can this one be closed?

**Comment by aryairani** [comment]
I think so.  I did a lot of "Remove redundant import"s in beta66 yesterday (as you may have guessed), and didn't encounter this issue.

**Comment by aryairani** [comment]
Hmm, I tried to test out the original scenario after updating to beta68, but actually not seeing the warnings inline at all now.  Should I open a separate ticket, or something else I can try?  I already deleted and recreated the project.

![image](https://user-images.githubusercontent.com/538571/78269139-2b367000-74d7-11ea-9f60-faa79e27d882.png)

**Comment by rikvdkleij** [comment]
The warnings are not there because of the compile error. The inline warnings are derived from GHC warnings.

**Comment by aryairani** [comment]
We have `-Werror` enabled in stack.yaml, so warnings end up as GHC errors, but this hasn't changed recently, and they are still just warnings in GHCi. So but unless something changed between beta64 and beta68 with respect to how errors & warnings are handled, I wonder if there's a different explanation?

**Comment by rikvdkleij** [comment]
Okay, I have enabled `-Wall` _and_ `-Werror` and it works for me.

Maybe it's the case that file is not yet loaded in the REPL, that happens sometimes when the project is opened and IntelliJ wants to show annotations for the file but the REPL is not yet ready. I have created a solution for that but doesn't work in all cases. So then e.g. you just have to press an enter to load the file in the REPL and see the annotations.

**Comment by rikvdkleij** [comment]
> Maybe it's the case that file is not yet loaded in the REPL, that happens sometimes when the project is opened and IntelliJ wants to show annotations for the file but the REPL is not yet ready. I have created a solution for that but doesn't work in all cases. So then e.g. you just have to press an enter to load the file in the REPL and see the annotations

I found an issue related to this, could be your issue.

**Comment by rikvdkleij** [comment]
@aryairani Can you confirm that changing the file e.g. by just pressing an enter, shows the warnings.

If that's is the case then I know your issue and that is an non-deterministic issue for already long time. I'm investigating the right solution for this issue.
