### ISSUE TITLE
Access denied - stack init trying to write to windows system32 - Win 10 x64

### ISSUE THREAD

**Issue by Vic152** [rikvdkleij/intellij-haskell#530]
![image](https://user-images.githubusercontent.com/6089679/77780551-11ff7080-704c-11ea-9601-b6d212b0e212.png)

Hi Guys,
I tried to follow the installation but got the error in the screenshot.

**Comment by rikvdkleij** [comment]
`stack init` is used to create stack project from cabal project.

You have to use `stack new` to create a new project but you can also create new project from IntelliJ,

Btw, you're in a strange folder to create a project 😄

**Comment by Vic152** [comment]
@rikvdkleij I knew I was doing something wrong. Let me correct it and I will close the issue. Thanks!

**Comment by Vic152** [comment]
All good. Wrong dir. Windows sucks.

![image](https://user-images.githubusercontent.com/6089679/77803360-d927c180-7074-11ea-954b-b4b479b7db79.png)
