### ISSUE TITLE
"Reformat code" action doesn't work

### ISSUE THREAD

**Issue by mnn** [rikvdkleij/intellij-haskell#532]
Hotkey nor dialog isn't doing anything, not even showing "no lines changed" popup like for example in TypeScript. In `Code` -> `Haskell` both items are grayed out. I saw in a status bar the plugin was installing ormolu. I don't see any errors in Messages tab nor anything at bottom right (siren icon with crashes).

Test code:
```hs
data    A =            A Int

test    []    =     []   
test   x            =   [head    x]
```

Tried reformat action, same action with selection, and reformat file dialog. All of those did nothing.

In plugin settings I left the defaults, so "Build tools using system GHC*" checked and "Use custom Haskell tools" unchecked. From those options I get the impression it should be working without me installing and setting up anything manually.

Plugin version: 1.0.0-beta66
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Linux (Manjaro stable, updated today)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you check if Ormolu is installed? Go to menu: Help > About Haskell project.

**Comment by mnn** [comment]
It doesn't seem so:

```
Stack version: 2.1.3

GHC: 8.6.5

HLint: -
Hoogle: -
Ormolu: -
Stylish-haskell: -
```

**Comment by rikvdkleij** [comment]
Not one Haskell tool is automatically installed.

Can you check the Haskell Event log what is going wrong or is the plugin still busy with installing the tools?

**Comment by mnn** [comment]
No, not busy (no spinner in status bar).

After opening a project nothing in haskell warnings, tons of logs in haskell log, but only a few mentions of hlint not being available yet, no mentions of ormolu or stylish-haskell.

I tried to run `Update Haskell Tools` from menu, but I don't see anything wrong in the logs:

```
29.03.20
13:15	Updating Haskell Tools

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  /usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Downloading timestamp

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Downloading snapshot

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Updating index

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Updated package index downloaded

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Calculating hashes to check for hackage-security rebases or filesystem changes

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Updating preexisting cache, should be quick

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Populating cache from file size 657934336, hash efbf1fdc2ee168634185dba48dd6d957319f4bde297dfcb3bc8da5d8aca8c9ac

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Populating package index cache ...

13:15	/usr/local/bin/stack update --stack-root /home/xxx/.cache/intellij-haskell/lts-15:  Package index cache populated
```

**Comment by rikvdkleij** [comment]
How do log proceed because this only the start?

**Comment by mnn** [comment]
I am not sure I understand. That log was just from clicking on "Update Haskell Tools".

Here is a complete log when I opened the project (it was too long for a comment): https://gitlab.com/snippets/1958394

**Comment by rikvdkleij** [comment]
And you don't see some background action running? Or a balloon error?

I just checked and it works for me.

**Comment by mnn** [comment]
Nope, no error balloon, no red siren or spinner (that rotating circle). I created this project in older plugin version, could that be a problem? I'll try later installing those tools externally (I believe they were working out of the box before I updated, I think from beta 56).

**Comment by rikvdkleij** [comment]
> Nope, no error balloon, no red siren or spinner (that rotating circle).

It should be a background action.

>  I created this project in older plugin version, could that be a problem?

That could be a problem because the Settings are changed. I wonder if it works if you reimport your project. If that is the case I have to mention that in the release notes. Especially for people which didn't use the latest beta versions in the alpha plugin repo.

**Comment by mnn** [comment]
Tried fresh import (deleted .idea dir and iml file; followed "Setup the project" from readme) and unfortunately that didn't help. :disappointed: 

> It should be a background action.

I am pretty sure those are shown in status bar along spinner, all those finished quickly, even the ormolu one. Just to be sure I checked htop and there didn't seem to be running anything using CPU/IO/network related to Haskell tools.

I noticed there are few lines in the event log about ambiguous Stack targets, e.g.:

```
16:25	Ambiguous Stack target for file `/mnt/dev/haskell/gododoc/app/CmdArgsParser.hs`. It can belong to the source dir of more than one Stack target/Cabal stanza: `Set(gododoc:exe:gododoc-dev, gododoc:exe:gododoc)`  |  `gododoc:exe:gododoc-dev` is chosen.
```

Not sure if it is related, since Stack has no issues building and installing these binaries.

**Comment by rikvdkleij** [comment]
> Tried fresh import (deleted .idea dir and iml file; followed "Setup the project" from readme) and unfortunately that didn't help.

That's a pity....

> Not sure if it is related, since Stack has no issues building and installing these binaries.

No, it's not related.

> I am pretty sure those are shown in status bar along spinner, all those finished quickly, even the ormolu one. Just to be sure I checked htop+glances and there didn't seem to be running anything using CPU/IO/network related to Haskell tools.

Really mysterious. Also, because when something goes wrong there should be an error.

**Comment by rikvdkleij** [comment]
Maybe you can check the `idea.log`

**Comment by rikvdkleij** [comment]
Maybe I found the cause. It's only weird that I can't reproduce this issue on Ubuntu.

Let me know if you want to test this fix. In that case I will release a new version.

**Comment by mnn** [comment]
I am sorry, I didn't yet got to the idea log file. I would love to test the fix, but unfortunately I most likely won't have time until Tuesday. :worried:

**Comment by rikvdkleij** [comment]
Okay, then I wait to create a new release because I just found out that IntelliJ 2020.1 EAP broke the plugin it's importer :disappointed:

**Comment by rikvdkleij** [comment]
@mnn I just released beta67 which maybe solves this issue.

**Comment by mnn** [comment]
Tried beta67, no change in installed tools. I also tried purging caches in `~/.cache/intellij-haskell` which didn't seem to have any effect. But it takes quite a long time now (minute or two?) until items in `Haskell` menu become available even though no background tasks are running (no spinner at bottom). "(Re)Build Hoogle database" and all items in "GHCi" submenu are never available.

I am attaching a log file from the beta67 run where I opened a Haskell project, used format code hotkey, format file dialog (it said file is already formatted), from menu selected to update tools and restart repls, waited until items in menu were no longer grayed out and then closed IDEA. I only see a lot of spam from other plugins, but not much from intellij-haskell, nothing seemed relevant (the exception at the end is thrown during closing). Maybe you'll have better luck.

[intellij-haskell_beta67__idea.log](https://github.com/rikvdkleij/intellij-haskell/files/4407082/intellij-haskell_beta67__idea.log)

PS: I checked cache dir in user and project dir (find+grep) and found no dir/file containing "ormolu". I am very sure I saw "ormolu" being mentioned in a status bar (I assume a background task).

**Comment by rikvdkleij** [comment]
Hmm, weird.

Maybe it's a stack issue which we for some reason don't see. Can you try to delete the whole cache folder of `intellij-haskell` and see if that works. On Linux in '~/.cache`

**Comment by mnn** [comment]
Here are logs of start and project open with empty cache: 
[intellij-haskell_beta67_purged_cache](https://github.com/rikvdkleij/intellij-haskell/files/4409513/intellij-haskell_beta67_purged_cache_verbose__idea.log)

The log seems same to me. Isn't it possible to enable more verbose logging from the plugin?

**Comment by rikvdkleij** [comment]
Yes, I also see nothing relevant in the log.

> Isn't it possible to enable more verbose logging from the plugin?

Yes, will do that in next version.

**Comment by mnn** [comment]
This seems promising (event log from beta 68, after deleting cache dir of the plugin):

```
20:58	[1 of 2] Compiling Main             ( /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs, /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.o )

20:58	/home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:

20:58	Could not find module ‘Prelude’

20:58	There are files missing in the ‘base-4.13.0.0’ package,

20:58	try running 'ghc-pkg check'.

20:58	Use -v (or `:set -v` in ghci) to see a list of the files searched for.

20:58	|

20:58	1 | import Distribution.Simple

20:58	| ^

20:58	/home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:

20:58	Could not find module

20:58	‘Distribution.Simple’

20:58	There are files missing in the ‘Cabal-3.0.1.0’ package,

20:58	try running 'ghc-pkg check'.

20:58	Use -v (or `:set -v` in ghci) to see a list of the files searched for.

20:58	|

20:58	1 | import Distribution.Simple

20:58	| ^^^^^^^^^^^^^^^^^^^^^^^^^^

20:58	--  While building simple Setup.hs using:

20:58	/usr/bin/ghc-8.8.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.0.1.0 /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3

20:58	Process exited with code: ExitFailure 1

20:58	/usr/local/bin/stack --system-ghc -j2 --stack-root /home/xxx/.cache/intellij-haskell/lts-15 --resolver lts-15 --local-bin-path /home/xxx/.cache/intellij-haskell/lts-15/bin install ormolu

...

20:58	Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail

20:58	[1 of 2] Compiling Main             ( /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs, /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.o )

20:58	/home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:

20:58	Could not find module ‘Prelude’

20:58	There are files missing in the ‘base-4.13.0.0’ package,

20:58	try running 'ghc-pkg check'.

20:58	Use -v (or `:set -v` in ghci) to see a list of the files searched for.

20:58	|

20:58	1 | import Distribution.Simple

20:58	| ^

20:58	/home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:

20:58	Could not find module ‘Distribution.Simple’

20:58	There are files missing in the ‘Cabal-3.0.1.0’ package,

20:58	try running 'ghc-pkg check'.

20:58	Use -v (or `:set -v` in ghci) to see a list of the files searched for.

20:58	|

20:58	1 | import Distribution.Simple

20:58	| ^^^^^^^^^^^^^^^^^^^^^^^^^^

20:58	--  While building simple Setup.hs using:

20:58	/usr/bin/ghc-8.8.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.0.1.0 /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-mPHDZzAJ.hs /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/xxx/.cache/intellij-haskell/lts-15/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3

20:58	Process exited with code: ExitFailure 1
```

full log: https://gitlab.com/snippets/1959512

**Comment by rikvdkleij** [comment]
You can help me by googling on the error messages in combination with archlinux. 

Or disable use System GHC in Haskell settings.

**Comment by rikvdkleij** [comment]
@mnn that second option should help on archlinux, so not using system GHC for building tools.

**Comment by mnn** [comment]
Disabling System GHC helped, thank you. :slightly_smiling_face: Didn't even realize I have ghc installed (I use stack for everything, even scripts).

Might be worth mentioning it in readme, if this issue is a problem with arch-based distros (not isolated to my setup). Or maybe change default settings to not have it enabled?

Eh, Ormolu seems even more opinionated than stylish-haskell (no import groups, less aesthetically pleasing import formatting). By the way, is it possible to use stylish-haskell, or only ormolu is supported now?

**Comment by rikvdkleij** [comment]
> Or maybe change default settings to not have it enabled?

Yes, I should consider that because people don't read the README :smile: 

You can still use Stylish-Haskell but it's mapped to the default way of reformatting.
