### ISSUE TITLE
Some syntax can be left behind when removing redundant imports

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#533]
![image](https://user-images.githubusercontent.com/538571/78139225-264dbf80-73f6-11ea-95b5-7fcc272603a7.png)

becomes:

![image](https://user-images.githubusercontent.com/538571/78139293-441b2480-73f6-11ea-8227-27cf24a33781.png)

In this case, the `(..)` should go away as part of `ExceptT(..)` 😬

**Comment by rikvdkleij** [comment]
Thanks for reporting! I can reproduce this issue.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
