### ISSUE TITLE
optimize imports can leave a lot of blank lines behind

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#535]
![image](https://user-images.githubusercontent.com/538571/78140972-d290a580-73f8-11ea-874f-635b7b81ce51.png)

becomes

![image](https://user-images.githubusercontent.com/538571/78141036-e6d4a280-73f8-11ea-8408-e3123f63c82a.png)

and

![image](https://user-images.githubusercontent.com/538571/78141107-02d84400-73f9-11ea-80cb-efb597ca33cb.png)

becomes

![image](https://user-images.githubusercontent.com/538571/78141174-18e60480-73f9-11ea-95c8-ad68979e5eea.png)

Sorry this isn't a super reproducible test case; let me know if you need me to do better :)

Also, import stuff is pretty low priority for me :)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
Should be fixed in beta69.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
