### ISSUE TITLE
syntax left behind when removing redundant imports of pattern synonym

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#537]
not urgent :)

![image](https://user-images.githubusercontent.com/538571/78191760-ae5ab600-7444-11ea-8589-b5c8733cb2f2.png)

yields:

![image](https://user-images.githubusercontent.com/538571/78191788-bdd9ff00-7444-11ea-892d-02fd981034b4.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting! Another case :smile:

**Comment by rikvdkleij** [comment]
Should be fixed in beta69.

**Comment by aryairani** [comment]
If you want, I don't mind at all if you want to close these issues once you feel they're fixed.  It may be a while before I get around to confirming on my end. 😓
