### ISSUE TITLE
Stylish-haskell doesn't work after last update

### ISSUE THREAD

**Issue by sashasashasasha151** [rikvdkleij/intellij-haskell#538]
Stylish-haskell doesn't work after last beta update (beta68)
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.6073.9, built on March 4, 2020

**Comment by rikvdkleij** [comment]
The default reformatter is now Ormolu but stylish-Haskell is still there. It has it’s own shortcut.

**Comment by sashasashasasha151** [comment]
Yes, I know, but this shortcut (from keymap) doesn't work

**Comment by rikvdkleij** [comment]
Works for me. Are the Haskell tools installed? Recently Stackage LTS-15 is used.

**Comment by sashasashasasha151** [comment]
Hm, maybe I broke smth locally, what I need to it? I just have a project with lts-14.27 where all other things work fine

**Comment by rikvdkleij** [comment]
The LTS of the Haskell tools is independently of your project's LTS.

When tools are not installed they should  be automatically installed when you open a project. If your are using Archlinux (based) distro you will have to disable the option in Haskell Settings to build tools with GHC globally installed.

**Comment by sashasashasasha151** [comment]
I use mac os

**Comment by rikvdkleij** [comment]
Then take a look in the Haskell Event log what is going wrong. Btw, it takes some time before all tools are installed. Don't you see some background task?

What does the menu option `Help` > `About Haskell project` display?

**Comment by sashasashasasha151** [comment]
![image](https://user-images.githubusercontent.com/25207759/78452512-439fb980-7694-11ea-9bbb-47d8b6c3f8f8.png)
Hm, really, but why?
In event log I always have different things, but all works fine and I didn't care
```
Project won't be built because building its dependencies failed
Stack REPL couldn't be started for target `agora:lib` due to: cannot satisfy -package agora-0.1.0.0
[global-stack-repl] Stack REPL couldn't be started within 30 seconds
```

**Comment by rikvdkleij** [comment]
You're using an old version of Stack. Please upgrade.

By default Haskell event log doesn't show so much. But you enable more logging (see README) which is useful when something fails.

**Comment by sashasashasasha151** [comment]
Any possibilities to add support for stack 1.9.3?
Newer versions of stack can't work with git packages which are based on hpack, so it is not possible to build our project

**Comment by rikvdkleij** [comment]
> Any possibilities to add support for stack 1.9.3?

Sorry, no, that's not doable to maintain.

**Comment by rikvdkleij** [comment]
Btw, if the other feature of the plugin just work, you can build the Haskell tools yourself and indicate in Haskell settings their paths.

**Comment by sashasashasasha151** [comment]
![image](https://user-images.githubusercontent.com/25207759/78454728-8072ad00-76a2-11ea-88fb-e567112731b5.png)
There is no Stylish-haskell path

**Comment by rikvdkleij** [comment]
Ok, I will add stylish-haskell in next version. But at least you can use Ormolu.

**Comment by sashasashasasha151** [comment]
Thank you

**Comment by rikvdkleij** [comment]
Should be fixed in beta69.
