### ISSUE TITLE
Errors and warnings are not persistent

### ISSUE THREAD

**Issue by srahmi** [rikvdkleij/intellij-haskell#539]
They appear and disappear quickly.
If I want to see them I have to change the code and then they reappear and disappear.

- IntelliJ-Haskell 1.0.0-beta52
- Glasgow Haskell Compiler, Version 8.8.3, stage 2 booted by GHC version 8.6.3
- MacOSCatalina 10.15.4
- IntelliJ IDEA 2019.3.4 Build #IU-193.6911.18, built on March 17, 2020

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you please try the latest beta version, see here https://github.com/rikvdkleij/intellij-haskell#installing-latest-beta-of-the-plugin how to install.

**Comment by srahmi** [comment]
Thank you!
Now only warnings are not persistent.

**Comment by rikvdkleij** [comment]
Should be fixed in beta69.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
