### ISSUE TITLE
Lots of timeouts on "stack unpack" commands lead to missing navigation to external libraries

### ISSUE THREAD

**Issue by netvl** [rikvdkleij/intellij-haskell#541]
I've just installed the latest beta version (68) on a 2020.1 version of IDEA, and encountered an issue that navigation to third-party libraries, as well as documentation resolution, does not work. In addition, the "preloading caches" step of REPL reload takes quite a long time.

I've enabled "Haskell logs" and was immediately able to see that a lot of command like this one:
```
C:/ProgramData/chocolatey/bin/stack.exe --no-nix unpack array-0.5.4.0
```
are marked as "timed out".

This turned out to be the cause of this issue, because once I ran this command manually, it showed me something like
```
Cabal file info not found for array-0.5.4.0, updating
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
No package index update available, but didn't update cache last time, running now
Calculating hashes to check for hackage-security rebases or filesystem changes
No old cache found, populating cache from scratch
Populating cache from file size 660706304, hash 3bd391b1e6e7bb251fad3b5320bdb10b1c247d588615a98918f67141f71b99aa
Populating package index cache ...
Package index cache populated
```
And this run took about 1-2 minutes to complete.

After I did this, I've got no issues at all with reloading the REPL (which now took a couple of seconds), and the navigation to external libraries, as well as documentation resolution, started to work perfectly.

Maybe it would make sense to mention somewhere in the docs that for libraries resolution to work correctly, it is necessary to run something like the above command manually one time? I'm not well versed in stack yet, so maybe there is a more generic command to do the same thing which does not involve an arbitrary package name. Maybe it would also make sense to run something like it by the plugin directly, but without a timeout at first?

```
> stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2

> Plugin version
1.0.0-beta68

> IntelliJ IDEA version
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Normally this works much faster. Looks like there was a problem with fpcomplete's s3 server.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
