### ISSUE TITLE
feature request: create imported haskell project with `idea <path to haskell project>`

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#542]
If I launch `idea` from the command-line and pass the path to a maven or scala/sbt project, IntelliJ seems to detect it and create modules of the appropriate type.  If I pass it a stack project, though it doesn't seem to detect it.  So then I need to close the project, delete the `.idea/` folder that was created, and reopen the project manually with "Import from Existing Sources".

Would it be possible for intellij-haskell to register itself with whatever sort of project type auto-detection is happening for the others?

Sorry, I assume this isn't much information to go on. 😅

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I will have to investigate this.

**Comment by rikvdkleij** [comment]
Btw, which version of IntelliJ are you using because the project importer is broken in 2020.1 because of a bug in IntelliJ. It's fixed in 2020.1.1 Preview version.

**Comment by aryairani** [comment]
I'm not sure which version I was using when I reported, but I currently have 2019.3.  😬

**Comment by aryairani** [comment]
This seems to work great in beta70 and IntelliJ 2020.1.1
