### ISSUE TITLE
Is there any way to add dependencies/packages automatically?

### ISSUE THREAD

**Issue by chansey97** [rikvdkleij/intellij-haskell#543]
For example, when there is a lack of package, the code area will be marked in red, but the packages cannot be imported automatically. I have to modify package.yaml manually. Is there any way to automatically import these packages. (e.g. like Java, click the red line and import that package)

![dep](https://user-images.githubusercontent.com/4015056/79684108-7edbe400-8261-11ea-8383-802ae48612d4.JPG)

Thanks.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

No, that's not possible. AFAIK that is not possible with Java.

It's possible to add an import when an identifier can't be found but the package/library should be installed.

**Comment by chansey97** [comment]
The inconvenience is that when a package is missing, such as: `Data.List.Split`, I have to search Google to find its name `split` and then add it to `package.yaml`. This must be done for each project. 

For current intellij-haskell, is this a good practice or not?  Sorry, I am not very familiar with Haskell ecosystem.

**Comment by rikvdkleij** [comment]
You can use hoogle for searching.

I don't see a simple solution for your request. Also after adding a dependency the project has to be rebuilt and and REPLs have to be restarted.

**Comment by chansey97** [comment]
hoogle is good.

Thanks.
