### ISSUE TITLE
What's the meaning of "Can not download cabal config file for stack resolver lts-15.9" mean?

### ISSUE THREAD

**Issue by chansey97** [rikvdkleij/intellij-haskell#544]
I am using this plugin to write Haskell code. Everything is OK. 

Thank you very much for this excellent work!

But a have a question:

Each time I open a Haskell project in the IDE, it tell me that:

> 2:28	Can not download cabal config file for stack resolver lts-15.9, please check your network environment. Falling back to default Cabal.config

I'm sorry, since I am not very familiar with Haskell ecosystem, I don't quite understand the meaning of this sentence:

1. intellij-haskell use `stack` to manage packages and build project, right? Why it need to download `cabal` config file?

2. Is there any way to fix it?

Thanks.

**Comment by rikvdkleij** [comment]
Can be hiccup of Stackage but not really an issue. It falls back to a default one and this config file is only used for auto-complete support of package names in a cabal file.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
