### ISSUE TITLE
How to get auto-complete to work?

### ISSUE THREAD

**Issue by veqryn** [rikvdkleij/intellij-haskell#545]
I'm learning Haskell, but proficient at other languages.
I have installed all the pre-requisites, and was able to initialize a project structure using stack, as well as use ghc to compile a 'hello world' program and run it.

How do I get auto-complete to work?

I am expecting that if I define a variable or function, that if I start writing that function's name I can have it auto-complete.  Right now, I don't get any completion.  Does this plugin do that?

**Comment by rikvdkleij** [comment]
> Does this plugin do that?

Yes, it should all work out-of-box when the REPLs are started in the background. Probably something went wrong and you enable the Haskell event log to see what is going on. See the last but in https://github.com/rikvdkleij/intellij-haskell#getting-started

**Comment by veqryn** [comment]
It took me re-running through the whole setup a second time, plus marking every folder with my haskell code as a "Sources Root", before auto-complete would work.
thanks!
