### ISSUE TITLE
Is there any way to send params in Run/Debug Configuration?

### ISSUE THREAD

**Issue by chansey97** [rikvdkleij/intellij-haskell#547]
I have a project, in which there are 3 modules (`Common.hs`, `A.hs` and `B.hs`).

Common.hs
```haskell
module Common where
doTest :: Bool -> Int
doTest b = 1
```

A.hs
```haskell
module A where
import Common
test = doTest True
```

B.hs
```haskell
module B where
import Common
test = doTest False
```

As you can see that variable `test` are duplicate in module A and module B.  

So when I click the run button (a Haskell Stack REPL configuration) and input `test` in the REPL, it will prompt a error
```
<interactive>:1:1: error:
    Ambiguous occurrence ��test��
```

Is there any way to workaround it? 

For example, in stack, it support params:

`stack ghci --no-load`, to skip loading all defined modules into ghci, and then we can `:load A` manually. 

Or

`stack ghci src/A.hs`, to load `A.hs` directly.

Can I add some params to `Haskell Stack REPL configuration`?  But I don't know how to add... (sorry, I am not familiar with IntellIJ IDEA)

Thanks.

**Comment by rikvdkleij** [comment]
No, you can't add parameters to the REPL configuration.

A workaround is to first enter `:load` which will clear imported modules.

**Comment by chansey97** [comment]
Thanks.
