### ISSUE TITLE
Support collapsing of imports

### ISSUE THREAD

**Issue by declension** [rikvdkleij/intellij-haskell#548]
It would be excellent to support folding of _lots_ of things, but IMO the low hanging fruit here is probably visual collapsing (folding) of Haskell imports, especially considering how many imports many Haskell files have.

They are big, take up a lot of space, and I'd say less complex / varied than other code structures (though type signatures vs implementations would be nice too...). Obviously this should work with all import syntax styles and layouts (Ormolu's, stylish-haskell's, hindent's etc)

The normal key binds could then apply (ctrl-+ and ctrl-- typically, or "collapse all") as well as the gutter GUI versions of this.

As usual it's possible this is already implemented and somehow not active (but I'm using Beta-69 and have never noticed it)

### Example
Most people will be familiar with this feature, but as an example from PyCharm (but IDEA the same really):

![screenshot-pycharm-unfolded-imports-2020-05-06](https://user-images.githubusercontent.com/3322808/81150986-74675d00-8f78-11ea-888c-77963dcbe673.png)

vs

![screenshot-pycharm-folded-imports-2020-05-06](https://user-images.githubusercontent.com/3322808/81151380-d922b780-8f78-11ea-97ba-93554f3f7c29.png)

Thanks!

**Comment by rikvdkleij** [comment]
Thanks for reporting.

Will implement this in next beta.

**Comment by rikvdkleij** [comment]
Fixed in beta70

**Comment by declension** [comment]
Wow - thanks!

**Comment by Sir4ur0n** [comment]
@rikvdkleij thank you for this feature!

While I confirm this works, it actually works **too well**. By default it folds all imports of Haskell modules, and doesn't even seem to respect the `Preferences / Editor / General / Code Folding / Fold by Default / General / Imports` option. Also, in the same category, I did not find a Haskell specific setting.

So overall, it seems impossible to disable this feature?

I personally would like by default to be unfolded, while still supporting folding mechanisms (Clicking the `+` or `-` symbols, or using `C-+` or `C--`). Do you think this would be possible please?

Again, thank you! :bow:

**Comment by rikvdkleij** [comment]
@Sir4ur0n Ok, I understand. I will investigate how to hook in the general `Code Folding` settings.

**Comment by declension** [comment]
@rikvdkleij thanks so much - beta71 is amazing with the folding now!

**Comment by rikvdkleij** [comment]
@Sir4ur0n 
> So overall, it seems impossible to disable this feature?

Done in beta72

**Comment by Sir4ur0n** [comment]
Thanks again, it looks really nice ❤️ 

I noticed it seems bugged though, on the "File header" setting: the configuration value seems to be the same as "imports" (smells like a copy/paste incident).

Once this minor issue is fixed, I will consider this feature perfect 😄

**Comment by Sir4ur0n** [comment]
I think the bug is here: https://github.com/rikvdkleij/intellij-haskell/blob/2484edbb7a43e389cd6084fa89a661310917ac48/src/main/scala/intellij/haskell/editor/HaskellFoldingSettings.java#L26

`isCollapseFileHeader` uses `COLLAPSE_IMPORTS` which looks buggy 😄

**Comment by rikvdkleij** [comment]
Oops :smile: 

Thanks for reporting!

**Comment by Sir4ur0n** [comment]
Awesome, thank you 🙇 IMO we can close this issue
