### ISSUE TITLE
Error when creating Haskell Stack Runner for imported project

### ISSUE THREAD

**Issue by DavidAntliff** [rikvdkleij/intellij-haskell#550]
I'm using 1.0.0-beta69 with Intelli-J IDEA Community 2020.1.1.

I have successfully created a new Haskell Module project, and I'm able to create a new Haskell module project. When I do this, I select my Haskell Tool Stack (which I've also set to Default), version 2.3.1.

However when I attempt to open an existing Stack project (created manually, not via this plugin, works from command-line as per README), I get the following error when I try to create a Haskell Stack Runner:

_! Run Configuration Error: Haskell Stack SDK is configured for the project_

Also, I am not able to select a -exe from the Executable dropdown - the list is empty.

![Capto_Capture 2020-05-08_15-18-00_](https://user-images.githubusercontent.com/11261038/81366583-22246880-913f-11ea-90a6-31cabab62d17.png)

I can't work out how to set the Haskell Tool Stack for an existing project. I can't find anything relevant in Preferences > Languages & Frameworks > Haskell, or elsewhere.

Following the [README](https://github.com/rikvdkleij/intellij-haskell/blob/master/README.md#getting-started), after clicking Import in the Welcome to IntelliJ IDEA, I don't get the option to configure the SDK, instead I just get a Finder dialog where I select the root directory of the project, and then the project opens. This is different from what the README says, as I get no chance to configure the Haskell Stack SDK.

**Comment by DavidAntliff** [comment]
I found the "Project Structure" dialog for my imported project, and under Platform Settings > SDKs, I see Haskell Tool Stack, and the Stack binary home path is set _correctly_ here.

**Comment by DavidAntliff** [comment]
Additionally, code navigation is not working for the imported project. I suspect this is a symptom of the project not being correctly initialised yet. Should this happen automatically when the project is imported, or do I have to do this manually somehow?

**Comment by mo-gr** [comment]
I had a similar issue and fixed it by navigating into the "Project Structure" -> "Modules" and re-importing the code base as a Haskell stack module. Basically, hitting the + and select the project root. After that IntelliJ-Haskell properly recognised that it's a Haskell Project and configured the project accordingly

**Comment by DavidAntliff** [comment]
@mo-gr thanks for the response. I tried that a few times - removing and re-adding the Content Root - including visiting the Dependencies tab and changing "Project SDK 1.8" (Java I assume) to "Haskell Tool Stack 2.3.1". I tried removing/adding the Content Root before/after that, but it doesn't seem to pick up the fact it's a Haskell project. I also tried setting the folders containing .hs files as "Sources" but that didn't help either.

**Comment by rikvdkleij** [comment]
Currently the project importer is broken when importing a project from the Welcome Screen in IntellliJ 2020.1 because the IntelliJ SDK is changed.
As a workaround, the project importer is still working when using the option to import from existing sources in the File menu

**Comment by DavidAntliff** [comment]
I tested this with beta70 and now it pops up a dialog asking for the Haskell Stack SDK. I choose this and the project opens successfully. The correct executables are now available in the Configuration dialog. Thank you!

**Comment by rikvdkleij** [comment]
Thanks for the confirmation!
