### ISSUE TITLE
ui unresponsive: Popup$HeavyWeightWindow.show

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#554]
Here's a thread dump. 😬
Thanks for your work! 😅 

[threadDumps-freeze-20200511-170000-IC-201.7223.91-Popup$HeavyWeightWindow.show-15sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4612060/threadDumps-freeze-20200511-170000-IC-201.7223.91-Popup.HeavyWeightWindow.show-15sec.zip)

**Comment by rikvdkleij** [comment]
Same as #555
