### ISSUE TITLE
ui unresponsive: Window.pack

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#555]
[threadDumps-freeze-20200511-170333-IC-201.7223.91-Window.pack-15sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4612084/threadDumps-freeze-20200511-170333-IC-201.7223.91-Window.pack-15sec.zip)

**Comment by aryairani** [comment]
[threadDumps-freeze-20200511-170524-IC-201.7223.91-Window.pack-15sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4612100/threadDumps-freeze-20200511-170524-IC-201.7223.91-Window.pack-15sec.zip)

I'll add one character to the buffer and get a 15 second delay :-\

**Comment by rikvdkleij** [comment]
Thanks for reporting!

But I see nothing in the thread dumps that relates to a problem with the plugin.

I found this line:
```
"BaseDataReader: error stream of fsnotifier" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
```
It looks like you have an issue with your JRE/JDK installation, see also this https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000719010-IntelliJ-IDEA-Stopped-Working-Freezes-on-Splash-Screen

**Comment by rikvdkleij** [comment]
Maybe this helps also: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879

**Comment by aryairani** [comment]
Hmm, I didn't quite understand, and I am on a different machine now with a potentially different installation, so maybe we should just close this.

If I'm using the latest IDEA though with the bundled JDK, is that good enough, or are there extra steps I'd need to take?

---
IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: intellij.haskell, izhangzhihao.rainbow.brackets

**Comment by rikvdkleij** [comment]
Yes, it would be good enough to use the bundled JDK. I also have no idea what is going on on your machine.

On second thought, this
`"BaseDataReader: error stream of fsnotifier" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)`
is not an issue...

**Comment by rikvdkleij** [comment]
Maybe it helps to increase heapsize of IntelliJ.
