### ISSUE TITLE
ui unresponsive: CPlatformComponent.nativeCreateComponent

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#556]
Two back to back with the same title:

[threadDumps-freeze-20200511-170314-IC-201.7223.91-CPlatformComponent.nativeCreateComponent-15sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4612085/threadDumps-freeze-20200511-170314-IC-201.7223.91-CPlatformComponent.nativeCreateComponent-15sec.zip)

[threadDumps-freeze-20200511-170250-IC-201.7223.91-CPlatformComponent.nativeCreateComponent-15sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/4612086/threadDumps-freeze-20200511-170250-IC-201.7223.91-CPlatformComponent.nativeCreateComponent-15sec.zip)

**Comment by rikvdkleij** [comment]
Same as #555
