### ISSUE TITLE
Stack REPL couldn't be started within 30 seconds

### ISSUE THREAD

**Issue by thma** [rikvdkleij/intellij-haskell#557]
I've got two windows 10 boxes where I'm using the intellij-haskell plugin.
On one machine everything works fine on the other I cant get the plugin to work correctly.

Intellij Version (2020.1.1 Ultimate) + Plugin Version are equal on both machines.
(I've tried plugin version from 1.0.0-beta60 to 1.0.0-beta71)

If I change a file in the Intellij editor I see the following messages in the log:

11:05	HLint inspection is started for file ReservationUseCase.hs

11:05	[project-stack-repl-RestaurantReservation:lib] Stack REPL will be started with command: C:/Users/Thomas Mahler/AppData/Roaming/local/bin/stack.exe repl RestaurantReservation:lib --no-build --ghci-options -ghci-script=C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\repl.ghci --silent --ghc-options -v1

11:05	HLint inspection is started for file ReservationUseCase.hs

11:05	"C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\lts-15\bin\hlint.exe" --json D:\play\RestaurantReservation\src\UseCases\ReservationUseCase.hs:  "C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\lts-15\bin\hlint.exe" --json D:\play\RestaurantReservation\src\UseCases\ReservationUseCase.hs

11:05	[project-stack-repl-RestaurantReservation:lib] Stack REPL couldn't be started within 30 seconds

11:05	"C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\lts-15\bin\hlint.exe" --json D:\play\RestaurantReservation\src\UseCases\ReservationUseCase.hs:  []

11:05	HLint inspection is finished for file ReservationUseCase.hs

On the box that works fine my profile name is "mahlerth".
On the failing box it is "Thomas Mahler"
I think the issue may be related to the blank in my profile name.

If I enter the stack repl command in the intellij terminal I get the following error:

$ C:/Users/Thomas Mahler/AppData/Roaming/local/bin/stack.exe repl RestaurantReservation:lib --no-build --ghci-options -ghci-script=C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\repl.ghci --silent --ghc-options -v1
**bash: C:/Users/Thomas: Is a directory**

If I start stack without providing the full path the command does not produce an error:
$ stack repl RestaurantReservation:lib --no-build --ghci-options -ghci-script=C:\Users\Thomas Mahler\AppData\Local\rikvdkleij\intellij-haskell\cache\repl.ghci --silent --ghc-options -v1

Are there any workarounds possible?

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Sorry, no idea (beside changing the user directory name), I have no Windows experience.
