### ISSUE TITLE
Is the plugin supposed to work with IntelliJ 2020.1.1 ?

### ISSUE THREAD

**Issue by pysaumont** [rikvdkleij/intellij-haskell#559]
I can't save the plugin settings. This causes an error and IntelliJ automatically disables the plugin. According to JetBrains support (Serge Baranov) who had a look to my logs, the plugin in not compatible and should not be used!

**Comment by rikvdkleij** [comment]
Which version of the plugin are you using?

**Comment by pysaumont** [comment]
1.0.0-Beta52

**Comment by rikvdkleij** [comment]
Try the latest beta, see Readme.

**Comment by pysaumont** [comment]
Works fine with 1.0.0-Beta71

Thanks !
