### ISSUE TITLE
Add some option like point free

### ISSUE THREAD

**Issue by xgrommx** [rikvdkleij/intellij-haskell#56]
Hello @rikvdkleij. How about add some interesting stuff like https://github.com/bmillwood/pointfree. For example https://github.com/lambdabot/lambdabot

**Comment by rikvdkleij** [comment]
Good idea :+1:

**Comment by rikvdkleij** [comment]
Btw, HLint also suggests eta-reduce refactorings. Only the refactor tool does not apply them,  see 
http://mpickering.github.io/posts/2015-11-22-hlint-refactor.html
and
https://github.com/mpickering/apply-refact/issues/25

**Comment by xgrommx** [comment]
@rikvdkleij So, in hlint will be support for pointfree?

**Comment by rikvdkleij** [comment]
Yes, to my experience. Only the Refactor does not support pointfree refactorings. So automatically apply pointfree suggestions does not work at this moment.

I need to spend some time to write code which will apply the HLint suggestions.

**Comment by rikvdkleij** [comment]
Should work in beta 4 by using Hlint suggestions.

**Comment by rikvdkleij** [comment]
@xgrommx Can this issue be closed?
