### ISSUE TITLE
Existential quantified constraint does not parse

### ISSUE THREAD

**Issue by sloosch** [rikvdkleij/intellij-haskell#566]
Hi!

The following code fails to parse the `=>` in the data declaration.
````haskell
{-#LANGUAGE ExistentialQuantification#-}

module Foo where

class IsFoo a

data AnyFoo = forall a. IsFoo a => AnyFoo a
````

The parse error is:
`
<q name>, <ttype>, HaskellTokenType.DERIVING, HaskellTokenType.DIRECTIVE, HaskellTokenType.INCLUDE_DIRECTIVE, HaskellTokenType.NEWLINE, HaskellTokenType.PRAGMA_START, HaskellTokenType.SEMICOLON or HaskellTokenType.VERTICAL_BAR expected, got '=>'`

**Comment by rikvdkleij** [comment]
Which version of the plugin?

I can't reproduce in beta72.

**Comment by sloosch** [comment]
Was in beta69 :blush: 

Works fine in the newer version!
