### ISSUE TITLE
Empty tooltips over string literals

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#568]
Repro: hover mouse over a regular string literal, wait

Expected: no tooltip

Instead: an empty tooltip pops up, like this

<details>
<summary>GIF</summary>

![Peek 2020-06-02 15-23](https://user-images.githubusercontent.com/89889/83519743-33198d00-a4e5-11ea-9b04-bef49c08a619.gif)

</details>

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Yes, noticed this after some deprecation warnings were fixed. Should be fixed in beta74.

**Comment by develop7** [comment]
Nope, it's beta74

**Comment by rikvdkleij** [comment]
Ok, i see, it's fixed in master.

**Comment by rikvdkleij** [comment]
Should be fixed in beta75

**Comment by develop7** [comment]
Confirming: it's fixed
