### ISSUE TITLE
Commit is not possible when "Haskell Reformat Code" is set and the cabal file is included in staged files

### ISSUE THREAD

**Issue by L7R7** [rikvdkleij/intellij-haskell#569]
If the "Haskell Reformat Code" checkbox is set and the cabal file is staged for the commit, pressing "Commit" doesn't work. It works if I don't include the cabal file in the commit.

The "Haskell optimize imports" checkbox doesn't make any problems.

I'm on bea74, but I observed this behaviour before. I think this bug existed in previous versions already. My IntelliJ version is:
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.4357.23, built on May 27, 2020

**Comment by rikvdkleij** [comment]
Should be fixed in beta75

**Comment by L7R7** [comment]
I didn't find the time to test beta75, but I just tried it in beta76 and worked for a simple example
