### ISSUE TITLE
Always builds with $HOME/.stack as stack root

### ISSUE THREAD

**Issue by cdfa** [rikvdkleij/intellij-haskell#571]
Hi, I recently moved my stack root to another drive because it was getting too big. I set the environment variable `$STACK_ROOT` to the new locations and when I run `stack build` everything works fine.

However, when I open the project in intellij, it starts building dependencies with the default stack root. Even when I `--stack-root /home/stack` to the stack arguments in the settings, it does not use my new root.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Maybe it helps to use IntelliJ Setting `Path Variables`?

**Comment by cdfa** [comment]
This works! Did not not about the setting. Thank you! :)

**Comment by cdfa** [comment]
Oh, it works for the REPLs it uses for providing language support, but the run configurations still use the default stack root.

**Comment by rikvdkleij** [comment]
Ok, I see, will fix that.

**Comment by rikvdkleij** [comment]
Should be fixed in beta75

**Comment by cdfa** [comment]
Can confirm! Thank you :)
