### ISSUE TITLE
No documentation available as Hoogle (database) isn't available

### ISSUE THREAD

**Issue by thisisnotamerica** [rikvdkleij/intellij-haskell#572]
Hello, sorry i'm really noob.
Try to install local Hoogle, 
`stack build --haddock-deps`
`stack hoogle`
`hoogle generate`

doesnt work. (i havent "Haskell" in "Tools")

**Comment by rikvdkleij** [comment]
The plugin will automatically install hoogle and when a project is imported/opened, a notification popups which tells about the option to generate the hoogle db.

**Comment by JKTKops** [comment]
I have the same problem. The popup appears, but the directory the plugin says it installs the tools to (AppData/Local/rikvdkleij/intellij-haskell/cache/lts-15/bin) does not exist (although .../lts-15 does). The "(Re)Build Hoogle database" option is grayed out and there is no "Haskell" option in the Tools menu.

**Comment by rikvdkleij** [comment]
@JKTKops on windows I have seen similar problems before because of permission issues or some kind of virus scanner which runs in the background .
Can also be that your project is not recognized as Haskell project but I can only guess because of no further info.

**Comment by JKTKops** [comment]
It is recognized as Haskell (if nothing else, I have custom Haskell syntax coloring which is being applied). I am on Windows, I'm not sure what permission issues would be causing problems but I do have a virus scanner. I could try temporarily disabling it, but not for a few hours as I'm currently working.

**Comment by moritzploss** [comment]
Having the same issue on macOS Catalina. I get the notification pop-up, but the menu item is greyed out, and I get "No documentation..." on hover.

**Comment by rikvdkleij** [comment]
@moritzploss That could mean that for some reason the hoogle executable is not automatically built (successfully)

**Comment by moritzploss** [comment]
Thanks @rikvdkleij ! After some digging I found that my company's Cylance Antivirus was blocking it, so I guess it's not just a Windows issue. I haven't found a workaround so far and had to switch to another computer (works perfectly now!). Thanks for this great plugin!

**Comment by rikvdkleij** [comment]
@moritzploss Thanks for your reply.
Great to hear you have found the cause and are happy with the plugin!

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
