### ISSUE TITLE
`qualified` and `as` in imports are a different color from the `import` keyword

### ISSUE THREAD

**Issue by drathier** [rikvdkleij/intellij-haskell#573]
<img width="231" alt="Skärmklipp 2020-06-08 13 18 22" src="https://user-images.githubusercontent.com/3695812/84024644-89c21380-a98a-11ea-8bcd-e0bc4b93a693.png">

I would've expected `import`, `qualified` and `as` to all be formatted as keywords here  :)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Yep, in scope of an import they are keywords.

**Comment by drathier** [comment]
Here's a full list: https://wiki.haskell.org/Keywords

**Comment by rikvdkleij** [comment]
Yes, i know the keywords 😄 I mean, you can create an identifier which is named `qualified` which is not a keyword. So I can not just define this keyword, depends on context but I will fix it.

**Comment by drathier** [comment]
Just trying to be helpful ^^,

**Comment by rikvdkleij** [comment]
@drathier I can not reproduce this issue. Which plugin version are you using?

**Comment by drathier** [comment]
`1.0.0-beta52` on quite an old intellij: `2019.2`

**Comment by rikvdkleij** [comment]
@drathier please update both. Especially plugin which needs at least 2019.3.2

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
