### ISSUE TITLE
Cannot find definition imported via `import A.B as B hiding (D(..))`

### ISSUE THREAD

**Issue by drathier** [rikvdkleij/intellij-haskell#574]
Jump to definition couldn't find the definition of a type that was imported like this:
`import A.B as B hiding (D(..))`
which means
- import everything from A.B except (D(..))
- If there's a naming conflict, there's now a qualified name `B` that refers to `A.B` so we can disambiguate when we've imported more than one thing unqualified with the same name

**Comment by rikvdkleij** [comment]
Thanks for reporting!

**Comment by rikvdkleij** [comment]
I try to reproduce your issue:
```
module Foo where

import Data.Vector as DV hiding (fromListN)

test = DV.fromList
```
but I don't notice an issue with go to definition.

Only the go to doesn't work for `fromListN` but that's expected.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
