### ISSUE TITLE
Jump to definition on types in type signatures doesn't work

### ISSUE THREAD

**Issue by drathier** [rikvdkleij/intellij-haskell#575]
Tried to use jump to definition (keymap > navigate > declaration or usages) on a type in a type signature, without any luck. Neither for types defined in the same module nor imported types.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you give an example?

**Comment by drathier** [comment]
Unfortunately the code-base I'm seeing this in isn't open source. If jump to definition works for you on types in type signatures, I'd be happy to dig deeper.

**Comment by rikvdkleij** [comment]
Yes, for me it works. Curious about your case.

**Comment by drathier** [comment]
I've got this and #574 working now, after a little dance. I think the underlying issue for this and for #574 could be that intellij-haskell and my terminal stack ghci instance use the same .stack-work folder but with different flags. 

If I load a project in intellij, wait for it to build fully, then `:reload` in ghci, wait for it to build fully, then close and open the project in intellij again, jump to definition stops working. Message `Navigation is not available at this moment: No info because REPL isn't (yet) available.` or `Navigation is not available at this moment: No info because  isn't loaded or found` (with a double-space between `because` and `isn't`, so presumably an empty string being formatted there) show up at the bottom of the screen when trying to jump to definition.

If I then run `Haskell > Update settings and restart REPLs`, it starts working again, until I close the project, even if I run `:reload` in my `stack ghci` using the same `.stack-work` folder. Maybe  it eventually gets corrupted and I have to do the dance again, I haven't tested it enough yet. I'm going to try running ghci with a different --work-dir now and see if that helps.

It might be worth noting that in this project I'm working on, I get `ghc: panic! (the 'impossible' happened)` every few days, so it's already a bit of an edge-case.

**Comment by rikvdkleij** [comment]
@drathier Thanks for your explanation.

I took a quick look and stack has an option to set a custom work directory. I could consider to start each repl with `--work-dir=.intellij-stack-work`

**Comment by drathier** [comment]
So after a little more use, with a separate --work-dir for my terminal ghci, jump to definition in intellij still slowly breaks over time (hours or days, "cannot find declaration to go to"). I have to use the "Update settings and restart repls" option to get it to work again.

**Comment by rikvdkleij** [comment]
Yes, I also noticed this issue. Should be fixed in next version.

**Comment by drathier** [comment]
I feel like I haven't expressed my appreciation to you here yet, so thank you for all your great work here, what you've already built is far better than anything I ever used before, and you've made my haskell dev experience much better!

**Comment by rikvdkleij** [comment]
@drathier Thank your very much! Appreciated!

I'm glad to hear that the plugin works so well for you. (but there are so many things which still can be improved 😄 )

**Comment by rikvdkleij** [comment]
@drathier 
Should be fixed in beta79.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
