### ISSUE TITLE
Garbage Text in Type Errors

### ISSUE THREAD

**Issue by JKTKops** [rikvdkleij/intellij-haskell#576]
When I introduce a type error and bring up the error message, it displays as in the following image:
![image](https://user-images.githubusercontent.com/23443007/84712096-67516c80-af2d-11ea-8c52-c43045ed10b3.png)
The real message is hiding in there but it's quite hard to read.

These are clearly UTF-8 encoding errors. My IntelliJ encoding is set at UTF-8.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Do you have example project?

**Comment by JKTKops** [comment]
I don't have a minimal breaking example but it happens in any of my existing stack projects (for example, [this one](https://github.com/JKTKops/Thcheme)). Sidenote: I messed with the plugin with that project but the whole project was written in Emacs; seems like I accidentally committed the .idea folder so you may have to nuke it.

**Comment by rikvdkleij** [comment]
I have checked out your example project but i can't reproduce your issue. Error messages are okay.

**Comment by rikvdkleij** [comment]
@JKTKops 

Maybe this helps https://github.com/tweag/rules_haskell/issues/523

**Comment by rikvdkleij** [comment]
I can't reproduce this issue.
