### ISSUE TITLE
A question !

### ISSUE THREAD

**Issue by GordonGgx** [rikvdkleij/intellij-haskell#578]
@rikvdkleij  Default the intellij-haskell use stack build project. Why not use stack's work path with default ? Can get the resource configuration of a stack through `stack path`. Now it's the plug-in itself to download a lot of compilation tools.

**Comment by GordonGgx** [comment]
The error Cannot run program "~/.local/bin/hlint" (in directory "/home/ggx/Documents/stack/HelloGUI"): error=2, No such file or directory

**Comment by rikvdkleij** [comment]
Thanks for your interest!

The main reason is that building Haskell tools should not interfere with user's Haskell projects. Also because plugin depends on API of Haskell tools.
