### ISSUE TITLE
deriving newtype syntax gets highlighted as error if the declaration is in one line

### ISSUE THREAD

**Issue by L7R7** [rikvdkleij/intellij-haskell#582]
When doing newtype deriving, the `newtype` keyword is marked as syntax error, unless I split the declaration into two lines like in the following image:
![image](https://user-images.githubusercontent.com/16477399/86611388-e545e800-bfae-11ea-8a30-0123aadf3730.png)

Only the first occurence gets marked as syntax error, even if there is more than one single-line newtype declaration. It compiles fine with both variants (if `DerivingStrategies` and `GeneralizedNewtypeDeriving` is enabled, of course).

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Will fix that.

**Comment by rikvdkleij** [comment]
Fixed in beta76.

**Comment by L7R7** [comment]
Works for me, Thanks!
