### ISSUE TITLE
Stack REPL couldn't be started for target `xxx` due to: cannot satisfy -package yyy

### ISSUE THREAD

**Issue by nhenin** [rikvdkleij/intellij-haskell#583]
Hi, 

I have a multi-project structure and I'm using the beta75 version of your plugin. I'm using ghc 8.8.3 and stack Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0

Running stack on the terminal works but somehow there are some issues when I'm trying to do it in Intellij, I have the followings errors for each of my sub-project : 

```
Stack REPL couldn't be started for target `dolla-base:lib` due to: cannot satisfy -package adjunctions-4.4
Stack REPL couldn't be started for target `dolla-osprey:lib` due to: cannot satisfy -package byline-0.3.2.1
Stack REPL couldn't be started for target `dolla-consensus:lib` due to: cannot satisfy -package aeson-1.4.7.1
...
``` 
For each project it cannot satisfy the first package by alphabetical order for each of my subproject...

The plugin does not give me any compilation feedback anymore, like it's jammed...

Also this at the beginning : 
Information:Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Information:Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail

I'm using lts-16.2 which is using ghc 8.8.3

**Comment by rikvdkleij** [comment]
Looks like the stack build failed because the REPLs can't find the build dependencies.

> Information:Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Information:Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail

Are you sure that plugin is using stack verison 2.3.1?

**Comment by nhenin** [comment]
Yes I think so : 
![image](https://user-images.githubusercontent.com/471741/87139118-c04bc080-c29f-11ea-8dfe-a28a7f48df34.png)

**Comment by nhenin** [comment]
Stack looks to be not align with the latest version of GHC and Cabal .... https://github.com/commercialhaskell/stack/issues/5244
Could it be an issue ?

**Comment by nhenin** [comment]
@rikvdkleij I can't use the plugin anymore :-(

**Comment by rikvdkleij** [comment]
Sorry to hear.

Your `stack.yaml` looks a bit suspicious. Normally it only contains paths to folders which contain a Cabal file/project. 

> Yes I think so :

No that is not version 2.3.1

Otherwise can you share your project so i can try to reproduce your issue?

**Comment by rikvdkleij** [comment]
Btw, the next version of the plugin will use the Stack binary from the PATH.

**Comment by nhenin** [comment]
Ho my bad for the version... I have the right one now : 
![image](https://user-images.githubusercontent.com/471741/87290835-cd1a1f80-c4fe-11ea-83f6-bbe54f828ae3.png)

But I still have the same issues without obviously the warnings I referred previously .... (`Stack has not been tested with GHC versions above 8.6, and using 8.8.3, ...`)

Sorry I can't give you access, the project is not open source :-( 

Regarding the `stack.yaml`, they are paths to folders which contain a `package.yaml` like this : 

![image](https://user-images.githubusercontent.com/471741/87291281-621d1880-c4ff-11ea-987b-2cfc6fa20a5c.png)

Here is the content of the `package.yaml` for the first sub-project `dolla-base` : 

![image](https://user-images.githubusercontent.com/471741/87291329-7103cb00-c4ff-11ea-890c-2c52eb80d71b.png)

**Comment by nhenin** [comment]
Worst case scenario, I'm going to make a similar project with the same structure aside... And see If I reproduce the issue...

**Comment by nhenin** [comment]
https://github.com/Eventuria/multiProjectExample, I have the same issue on that example...

**Comment by nhenin** [comment]
Some feedback while I was creating that `multiProjectExample`... I had to do a `stack build` in the terminal before being able to correctly setups things in Intellij... Basically Generating the cabal files with stack in the terminal ... Are you not supporting in  a the way the use of `package.yaml` files ?

**Comment by nhenin** [comment]
I have create a simpler structure and I still have the problem : https://github.com/Eventuria/SimpleProject

**Comment by rikvdkleij** [comment]
> Some feedback while I was creating that multiProjectExample... I had to do a stack build in the terminal before being able to correctly setups things in Intellij... Basically Generating the cabal files with stack in the terminal ... Are you not supporting the use of package.yaml files ?

Yes, they are supported because stack creates the cabal files as you mentioned.
But normally the `stack.yaml` file only contains a couple of references to cabal files/projects....

> I'm not using cabal files directly... I may have a configuration that you don't support with the plugin ? Because using stack in the terminal is always working...

Thanks for your example project!
It works on my machine with the current master version...

**Comment by rikvdkleij** [comment]
@nhenin Can you try beta76?

**Comment by nhenin** [comment]
Yes it works now :-) How do I add the stack binary path in Intellij when I'm clicking on the icon directly ? I have to run Intellij by my terminal now..

**Comment by rikvdkleij** [comment]
Great to hear that everything works now!

> why are you using the option --silent ? Can I remove it ?

To reduce the GHC output and i think the reason was to make parsing the output easier.
I will reconsider this option.
You can not remove it.

> P.S : Intellij asked to add the stack binary path to PATH, do you have an explanation in the README for it ? It could be useful for users if it can't be avoided...

This change is since beta76 and i still have to update the README.

> It was hidding an error that I have never seen so far ....

Weird that you did not notice this issue when not using IntelliJ 😄

**Comment by nhenin** [comment]
> Weird that you did not notice this issue when not using IntelliJ 😄
Yeah It's weird :-)
