### ISSUE TITLE
Use ANSI escape sequence processor in the initial tool setup progress bar

### ISSUE THREAD

**Issue by ForNeVeR** [rikvdkleij/intellij-haskell#585]
As I noted in #584, during the initial tool setup (at least in 1.0.0.-beta74 build on Windows, IDEA #IU-203.833), the following image is shown in the IDE progress window:

![image](https://user-images.githubusercontent.com/92793/87172421-6a5a3580-c2fe-11ea-804f-a49f2336c5e3.png)

The latest progress line always starts with `[0m`, which, I believe, is an ANSI escape sequence fragment.

I believe that IntelliJ-Haskell could process this escape sequence and provide more accurate text information to the user, i.e. not show this `[0m`. IDEA code base has the corresponding utility functions available.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Also because of #584, do you want to solve this?

**Comment by ForNeVeR** [comment]
I think so.
