### ISSUE TITLE
Auto-Completion on Types and Type Constructors defined in the same file (at least Record or Union) stopped working after upgrade to 1.0.0-beta76

### ISSUE THREAD

**Issue by enolive** [rikvdkleij/intellij-haskell#588]
after the latest update I noticed that I am no longer able to auto-complete my defined types (and also their type constructors) where they are defined. I am on the latest IntelliJ Ultimate (2020.1.3)

However, this still works when putting them in a module and trying to access from a different file

I tried to update my Haskell tools which unfortunately did not help. I can also reproduce the problem in a fresh Haskell project.

Steps to reproduce:

* create a new haskell project (for instance with `stack new hello-haskell new-template`)
* put in some types in Lib.hs

```haskell
module Lib where

data Test = Test String

data Person = Person {first :: String, last :: String}

data Union = First | Second

someFunc :: IO ()
someFunc = putStrLn "someFunc"
```
when trying to use the types by starting to type in `Lib.hs` (Test, Union, Person) or their Type constructors (Test, Person, First, Second) I don't get any auto-completion suggestions. However, using them inside of `Spec.hs` (after importing Lib, of course) works perfectly.

I noticed some strange TypeInfo in the auto-complete selection in 1.0.0-beta75 (which I am going back for now, as this is a deal breaker for me :cry:). Thought it might help

![grafik](https://user-images.githubusercontent.com/20992515/87470059-80c50180-c61c-11ea-84ba-aa7caa9b64cf.png)

![grafik](https://user-images.githubusercontent.com/20992515/87470136-a2be8400-c61c-11ea-8965-ea144f5e3156.png)

**Comment by rikvdkleij** [comment]
Thanks for extensive report!

Because the were in duplicates in the code completion suggestions i made a change there. So that probably caused your issue. Will take a look.

**Comment by rikvdkleij** [comment]
Should be fixed in https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta77

Not yet officially released because i first want to know if bug #587 is fixed

**Comment by enolive** [comment]
I can confirm that the fix works, at least for Record and Union types.

I still don't get any auto-completion suggestions for type aliases (such as `type LastName = Name`)

beta75:

![grafik](https://user-images.githubusercontent.com/20992515/87851427-f1a83a00-c8f8-11ea-9a01-3f8375d8cd51.png)

beta77:

![grafik](https://user-images.githubusercontent.com/20992515/87851450-2f0cc780-c8f9-11ea-83c0-4f68905fc59a.png)

**Comment by rikvdkleij** [comment]
Ok, thanks, will fix that.

**Comment by rikvdkleij** [comment]
Should be fixed in beta78

**Comment by enolive** [comment]
Yeah, I can confirm that. Thanks for your help! :heart:
