### ISSUE TITLE
Cannot start the compiler: the SDK is not specified

### ISSUE THREAD

**Issue by ForNeVeR** [rikvdkleij/intellij-haskell#590]
When trying to start my Haskell project, I'm getting an error:
> Cannot start compiler: the SDK is not specified for module "icfpc-mmxx-starterkit-haskell".
> Specify the SDK in the Project Structure dialog.

But, since the latest beta, I cannot specify and SDK, because Stack SDK is no more:
![image](https://user-images.githubusercontent.com/92793/87846943-1f43b200-c8fe-11ea-8011-212515965d69.png)

**Comment by rikvdkleij** [comment]
The Haskell Stack SDK is removed because it’s not needed anymore. Can you  try to reimport your project?

**Comment by rikvdkleij** [comment]
Btw, the error message is not from the plugin. Did you try to build the project from within IntelliJ?

**Comment by ForNeVeR** [comment]
The only time I've imported this project was using the new plugin version; I never had a previous one installed on this machine.

I didn't tried to build the project using IntelliJ, I just pressed the green "Run" button, this one:
![image](https://user-images.githubusercontent.com/92793/87852183-ee797200-c929-11ea-9c05-1150e6520a32.png)

And thanks, now I can see what's happening here. I had this command added to my run configuration by default:
![image](https://user-images.githubusercontent.com/92793/87852201-1e287a00-c92a-11ea-8005-e433110e6439.png)

After I removed that, everything is okay.

**Comment by rikvdkleij** [comment]
Yep, so that will trigger a build which needs a SDK, which is not defined. Also the build action from within IntelliJ is not implemented. Didn't have prio for me because it's not really need for Haskell support.

Btw, it's also mentioned in the README that IntelliJ's build action is not implemented. I will implement this to prevent confusion in the near future.

**Comment by rikvdkleij** [comment]
Should be solved in latest versions but IntelliJ's build action is not implemented.
