### ISSUE TITLE
Access violation when building Haskell Tools

### ISSUE THREAD

**Issue by TranHHoang** [rikvdkleij/intellij-haskell#592]
Hi, I tried to install Intellij-Haskell plugin on IntelliJ 2020.1 (Windows 10), but the Hoogle and HLint were not working. I turned on the Haskell Log and saw that when trying to build Haskell tools, the compilation failed with "access violation" error. 

I think because this plugin uses lts-16.6 (which is the issue of ghc-8.8.3, already addressed [here](https://gitlab.haskell.org/ghc/ghc/-/issues/17926)).

Any solution for this issue? Thanks.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

You.build the Haskell tools yourself and configure their paths in Haskell Setttings.

**Comment by TranHHoang** [comment]
I will try, thanks. Hope to see it fixed in the next release!

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
