### ISSUE TITLE
There's a significant room to improve the contributor experience

### ISSUE THREAD

**Issue by ForNeVeR** [rikvdkleij/intellij-haskell#597]
While setting up a local development environment for the plugin, I was constantly frustrated by the intricacies of this process.

_This issue doesn't mean to be offensive at all; I'd really like to help to improve the contributor experience as much as possible. Please forgive me if I should address this issue to some other project, e.g. `SbtIdeaPlugin`; I would gladly do so if you direct me to this project._

For background, I know Scala a little (was actively using it for several pet projects a couple of years ago), _and_ I'm one of IDE developers at JetBrains (so, well, I'm _supposed_ to know stuff about IDEA plugin development). So, I believe that if I was confused by the initial dev env setup, most of the other contributors will probably struggle with it, too.

I was expecting a straightforward experience like the one you get when using [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin): when using this nice contraption, you could build the plugin from terminal (`./gradlew buildPlugin`) and start the IDE from your terminal, too (`./gradlew runIde`); working with the project from the IDE exactly mirrors these commands.

But when trying to set up IntelliJ Haskell, I was very confused by these issues:
- `sbt runIDE` starts an IDE (I've found that it uses a version in `~/.IntelliJ-HaskellPluginIC` for a purpose I don't understand), but it has no development version of the IntelliJ-Haskell plugin installed, and there's no clear documented way to make it so.

  As an anecdote, in my case it actually _had_ IntelliJ Haskell plugin installed, because it offered to import my main IDEA configuration (which has the plugin installed from the plugin portal), and I blindly accepted it. So, I was blocked for several hours trying to get why isn't the code I'm adding to the plugin getting called: some of the breakpoints were hit, some of them weren't, and, as the result, I was knocking my head against a wall for several hours straight.
- I _have_ to manually perform these actions from the `CONTRIBUTING.md` file: set up the right IDEA Plugin SDK (I had multiple versions of these, and thought I should use the one from `~/.IntelliJ-HaskellPluginIC/sdk`).
- Some of the required settings are very subtle: e.g. changing the `unmanaged-jars` dependency scope from `compile` to `provided` (without this, everytihing was very terrible and the plugin was bricking any IDEA installation I add it to).
- One of the points requires me to "create `plugin` configuration for `intellij-haskell`;". I thought it was an SBT task configuration with the `plugin` task, but
  a) it isn't
  b) the error SBT gives when I'm trying to run `sbt plugin` is extremely cryptic ("missing ;", what?), and I was very confused by what's wrong with it

I believe this issue is actionable in two directions:
1. First of all, you could put some IDEA run configurations to the repository: e.g. this `plugin` run configuration. It would help me, as a new contributor, **a lot**.
2. You could (or maybe even _should_?) put the module definitions into the repository, so nobody will have to change that `provided`/`compile` switch again.
3. Also, I understand that most of the issues are caused by clunky development experience of IDEA plugins in Scala, but it seems like [the mainstream Scala plugin](https://github.com/JetBrains/intellij-scala) has most of them solved, and the resulting experience is much more straightforward (essentially, one has to just open the project and run the `scalaCommunity` configuration, and that's it). So, probably, you could try to migrate current plugin build infrastructure to the one like in intellij-scala.

**Comment by rikvdkleij** [comment]
Thanks for your extensive report but I don't use the sbt idea plugin for the intellij-haskell plugin development.

The sbt plugin is only used for:
- Building the plugin in codeship
- Downloading the intellij community source code

See also https://github.com/rikvdkleij/intellij-haskell/blob/master/CONTRIBUTING.md but I understand this this setup can be confusing if you have different experience with the Gradle plugin.
Also be aware that when I started this plugin, the situation was completely different and was also not maintained by Jetbrains. Keeping the plugin setup up-to-date has already costs me a lot of energy/time because breaking changes are/were not documented...

> Some of the required settings are very subtle: e.g. changing the unmanaged-jars dependency scope from compile to provided (without this, everytihing was very terrible and the plugin was bricking any IDEA installation I add it to).

Yes, i have mentioned that in the CONTRIBUTING.md . Years ago `provided` was not accepted by sbt (I can't remember exactly the problem but it didn't work) so I had to document that. That's also a headache for me. I will try again to set that dependency on `provided`

I can't really comment on the sbt idea plugin issues itself because I don't use the plugin for development.

> 1. First of all, you could put some IDEA run configurations to the repository: e.g. this plugin run configuration. It would help me, as a new contributor, a lot.

Ok, will do that.

> 2. You could (or maybe even should?) put the module definitions into the repository, so nobody will have to change that provided/compile switch again.

You mean by module definitions the intellij jars?
The only proper solution is to set the `unmanaged.jar` in `build.sbt` to provided. Will take a look again. See also above.
I can not add the intellij settings files because they are specific to my machine.

> 3. Also, I understand that most of the issues are caused by clunky development experience of IDEA plugins in Scala, but it seems like the mainstream Scala plugin has most of them solved, and the resulting experience is much more straightforward (essentially, one has to just open the project and run the scalaCommunity configuration, and that's it). So, probably, you could try to migrate current plugin build infrastructure to the one like in intellij-scala.

I can take a look but it's no really need to make contributions to the intellij-haskell plugin. The CONTRIBUTING.md should be enough. 
Also my experience with sbt itself and sbt idea plugin that it can be really time consuming to get it right. 

So my question is, why do you want to use the sbt idea plugin for development? I'm open to improvements but I don't see the benefits.

**Comment by rikvdkleij** [comment]
So FYI, I already have tried different ways to get the `unmanaged.jars` to `provided` but still without success. sbt is one rabbit hole 😄 

For example 
https://github.com/JetBrains/sbt-idea-plugin/blob/287ca662e9f1d2367e044229564bd5fd125d43b5/ideaSupport/src/main/scala/org/jetbrains/sbtidea/Init.scala#L139
https://github.com/JetBrains/sbt-idea-plugin/blob/717e49a74767bd2b060237c2f7dd7685cbaf4fd0/ideaSupport/src/main/scala/org/jetbrains/sbtidea/Quirks.scala#L16
Also does not work..

**Comment by rikvdkleij** [comment]
Maybe it’s an idea if I add to the CONTRIBUTING.md an animated gif which shows how to set up the environment.

**Comment by ForNeVeR** [comment]
> The sbt plugin is only used for:
> 
> * Building the plugin in codeship
> * Downloading the intellij community source code

One problem of current `CONTRIBUTING.md` is that this is not stated there. Look, it contains four sections:
- "How to build project" (okay! It mostly builds out-of-the-box!)
  - it is unclear what for is `sbt updateIntelliJ` (and I still didn't get it even after your explanation; what's "codeship"?)
  - it is unclear what for are the plugins (Grammar-Kit and PsiViewer); are they only for the grammar development?
- "How to prepare plugin for deployment" (it is unobvious if I, as a developer, need that)
- "How to run/debug plugin inside IntelliJ" (does it depend of the previous steps?)
- "Development remarks" (mostly clear)

I do believe that these could be documented a bit clearly.
 
> Also be aware that when I started this plugin, the situation was completely different and was also not maintained by Jetbrains. Keeping the plugin setup up-to-date has already costs me a lot of energy/time because breaking changes are/were not documented...

Yes, I understand that, and I don't blame anyone (and never meant to). Your work is wonderful, thanks a lot for it!

> I can't really comment on the sbt idea plugin issues itself because I don't use the plugin for development.

I am still new at the state of things in the modern Scala world, so forgive my confusion. For me, it looks like the sbt-idea-plugin is very much used during the development: it creates (or somewhat influences) the IDEA modules created during the development, right? So, this "unmanaged-jars" dependency we're having so much trouble with – it comes from the sbt-idea-plugin, right?

> > 2\. You could (or maybe even should?) put the module definitions into the repository, so nobody will have to change that provided/compile switch again.
> 
> You mean by module definitions the intellij jars?

Actually I meant the file `.idea/modules/IntelliJ Haskell.iml` but, after taking a look at it, I'm not sure if it will do much good for us.

It looks like the `provided/compile` flag is, indeed, contained within this file, but it contains too much unrelated stuff (in my case, for some reason multiple links to stuff from `$USER_HOME$/.IntelliJ-HaskellPluginIC/sdk/202.6397.20/lib`), so it would be unwise to put it into the repository as-is.

> I can not add the intellij settings files because they are specific to my machine.

Some of them aren't; for example, you could share the run configurations (though I can see you've already did that) and stuff like `.idea/modules.xml`, though the modules themselves aren't in very good shape to be shared :(

> I can take a look but it's not needed for making contributions to the intellij-haskell plugin. The CONTRIBUTING.md should be enough.

My main point being that `CONTRIBUTING.md` contains too much manual steps that every contributor has to perform, and some of them aren't, unfortunately, very clear. If we agree that we couldn't completely get rid of the manual steps, then we could try to improve wording and maybe add a couple of screenshots into it.

> Also my experience with sbt itself and sbt idea plugin that it can be really time consuming to get it right.

Yeah, I can see that 😄

> So my question is, why do you want to use the sbt idea plugin for development? I'm open to improvements but I don't see the benefits.

I don't _want_ to use the sbt-idea-plugin per se; actually, while filing this issue, I wasn't even aware of its existence. 

I am a simple-minded person: I see a command "runIDE", I think that it should do the right thing (after seing the same in the gradle-intellij-plugin), so I run the command. And I get very confused when it does its cryptic and half-baked things (like downloading and setting up an IDE, but not installing the plugin into it).

Could we somehow _remove_ these commands using our `build.sbt`, so nobody else gets confused by them?

> So FYI, I already have tried different ways to get the `unmanaged.jars` to `provided` but still without success. sbt is one rabbit hole 😄

Honestly, I'm still confused on how it actually works, but I could agree on that stamenent. It's a pity we couldn't get it to work automatically :(

> Maybe it’s an idea if I add to the CONTRIBUTING.md an animated gif which shows how to set up the environment.

I don't think an animated GIF is required (believe me, it isn't the funniest experience in the world to try to follow directions in looped GIF), but a couple of screenshots (e.g. the one describing the provided module dependency setting) would definitely help.

**Comment by rikvdkleij** [comment]
Thanks again for your feedback again!

> So, this "unmanaged-jars" dependency we're having so much trouble with – it comes from the sbt-idea-plugin, right?

Yes, that's right.

So the point is that I have to improve the CONTRIBUTING.md.

**Comment by rikvdkleij** [comment]
@ForNeVeR It took some time but I have improved the CONTRIBUTING.md

**Comment by ForNeVeR** [comment]
Alright, thanks a lot! I read the update, and it looks great!

Let's consider this issue as resolved, then.

I anyway had plans to make some small new contributions to the plugin, so I'll _have_ to thoroughly re-read the contributing guide when I'll be doing that, and will leave additional feedback (probably as PR) if I'll still have any problems.

**Comment by rikvdkleij** [comment]
> I anyway had plans to make some small new contributions to the plugin, so I'll have to thoroughly re-read the contributing guide when I'll be doing that, and will leave additional feedback (probably as PR) if I'll still have any problems.

@ForNeVeR  Thanks!
