### ISSUE TITLE
Possible duplicate of issue 235

### ISSUE THREAD

**Issue by jorge-barroso** [rikvdkleij/intellij-haskell#599]
I left a comment there but thought of opening a new issue to get this noticed:
https://github.com/rikvdkleij/intellij-haskell/issues/325#issuecomment-669306516_

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Can you check your `stack.yaml` file? For some reason the `resolver` does not contain a string but a map(key-value pairs).

**Comment by jorge-barroso** [comment]
Thanks for the quick heads up 😁 I'll let you know what's in there after 6pm UK time

**Comment by jorge-barroso** [comment]
stack.yaml from a project created by the extension
`# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
#
# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/8.yaml

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#
# extra-deps: []

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.3"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
`

Global stack.waml from ./.cache/intellij-haskell/lts-16/global-project/stack.yaml
`# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/jorge/.cache/intellij-haskell/lts-16/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-16.7
`

**Comment by rikvdkleij** [comment]
Ok, problem is clear. Currently only resolvers as a string are supported. So only e.g. `lts-15`
I will also add support for urls.

**Comment by rikvdkleij** [comment]
Fixed in beta84 which is also uploaded to alpha plugin repo.
