### ISSUE TITLE
Feature request: Auto-Indent & Reformat code

### ISSUE THREAD

**Issue by majorgilles** [rikvdkleij/intellij-haskell#60]
First all, many thanks for creating this plugin, it's already a god-sent... Plugin is working fine with latest versions of stack and ghc 8 to boot...

First of all, the feature 'Keep indent on empty lines' in style settings are already usable, but it would be nice to have the ability quickly reformat a source code file according to styling rules as is already the case for other languages.

An 'optimize imports' solution would also be nice.

Keep up the great work!

**Comment by rikvdkleij** [comment]
Thanks for your kind words.

Version 1.0.0-beta3 supports formatting by Hindent and/or Stylish haskell. Only max line length and indent size can be configured in IntelliJ. Other styling rules are defined inside hindent and stylish haskell.

Optimize imports is already available by using compiler warnings.
