### ISSUE TITLE
Missing syntax highlighting in list comprehension

### ISSUE THREAD

**Issue by TiziG** [rikvdkleij/intellij-haskell#603]
The syntax highlighting fails for some list comprehensions

### Sample code: 
```
fooA = [x == x | x <- [1]]
fooB = [     x | x <- [1]]
```

### Expected:
Syntax highlighting should be equal in both lines.

### Actual:
![image](https://user-images.githubusercontent.com/39971587/90753990-cf735480-e2c8-11ea-8d35-fb20a32136b9.png)
**First line:** Vertical Bar gets highlighted in italic font style and '1' gets highlighted in blue.
**Second line:** Nothing gets highlighted.

Also, I would recommend against styling the vertical bar symbol in italic, as it becomes nearly indistinguishable (depending on the font used) from the forward slash:
![image](https://user-images.githubusercontent.com/39971587/90755563-c7b4af80-e2ca-11ea-83ed-674a35087d18.png)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Looks similar as https://github.com/rikvdkleij/intellij-haskell/issues/522

**Comment by rikvdkleij** [comment]
I will fix the difference in behavior.

**Comment by rikvdkleij** [comment]
Should be fixed in beta79.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.
