### ISSUE TITLE
Multi packages configuration with tests in more than one

### ISSUE THREAD

**Issue by nhenin** [rikvdkleij/intellij-haskell#608]
Hi, I have a multi packages configuration and I have tests now in more than one package...

when working on a test you are running the following command in background : 

```
stack repl dolla-consensus-base:test:test dolla-consensus-proposing-flushing:test:dolla-consensus-proposing-flushing-test --no-build --ghci-options -ghci-script=/Users/nhenin/Library/Caches/com.github.rikvdkleij.intellij-haskell/repl.ghci  --ghc-options -v1 --test
```
I have the following that is silently happening behind and that blocks the feedback from your pluging : 
```
* * * * * * * *
The main module to load is ambiguous. Candidates are:
1. Package `dolla-consensus-base' component dolla-consensus-base:test:test with main-is file: /Users/nhenin/dev/dolla/consensus-base/test/Spec.hs
2. Package `dolla-consensus-proposing-flushing' component dolla-consensus-proposing-flushing:test:dolla-consensus-proposing-flushing-test with main-is file: /Users/nhenin/dev/dolla/consensus-proposer/packages/flushing/test/Spec.hs
You can specify which one to pick by:
 * Specifying targets to stack ghci e.g. stack ghci dolla-consensus-base:test:test
 * Specifying what the main is e.g. stack ghci --main-is dolla-consensus-base:test:test
 * Choosing from the candidate above [1..2]
* * * * * * * *
```
In the console I'm using this command :  ``` stack test --fast --file-watch```

How can run it properly ?

**Comment by nhenin** [comment]
Actually `dolla-consensus-base' is a dependency of `dolla-consensus-proposing-flushing' is can help you...

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Some versions ago I changed the plugin of having one REPL per target to a REPL per target type. I have to make it some smarter to prevent your case by checking if there is a `main` defined in stanza  or back again to one REPL per target for test targets.

**Comment by rikvdkleij** [comment]
> How can run it properly ?

So I have fix this in the plugin.

**Comment by rikvdkleij** [comment]
I mean, I have to fix this.

>  is it a substantial modification to be done ?

Sorry, no, no other way.

**Comment by rikvdkleij** [comment]
@nhenin Should be fixed in beta80

**Comment by nhenin** [comment]
You made my day man ! :-) It's solved !

**Comment by rikvdkleij** [comment]
Great to hear!
