### ISSUE TITLE
Feature request: make Stack root path configurable

### ISSUE THREAD

**Issue by strump** [rikvdkleij/intellij-haskell#612]
Intellij Haskell plugin creates directory `%LOCALAPPDATA%\rikvdkleij\intellij-haskell` on Windows to store Stack cache, binaries, etc. This path is not configurable and hardcoded in [GlobalInfo.scala](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/GlobalInfo.scala#L24).

On some machines it could cause a problem. If I'm running out of space on `%LOCALAPPDATA%` disk I can't move Stack root path to another disk.

It would be great to have something like "Stack root directory:" field in the [HaskellConfigurable.scala](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/settings/HaskellConfigurable.scala)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Yes, can implement that but it will have to consequence that you will have to move the content manually to prevent the plugin has to rebuild all tools again.

**Comment by rikvdkleij** [comment]
@strump sorry for the delay. Is this feature request still valid?

**Comment by strump** [comment]
@rikvdkleij yes, this feature would be helpful for me

**Comment by rikvdkleij** [comment]
Should be fixed in beta85, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta85

**Comment by strump** [comment]
Tested "Cache path" setting with `v1.0.0-beta85`

Works ok :+1:

**Comment by rikvdkleij** [comment]
@strump Thanks for testing!
