### ISSUE TITLE
Hlint $ change works wrong 

### ISSUE THREAD

**Issue by sashasashasasha151** [rikvdkleij/intellij-haskell#617]
`Redundant $` change `a $ b` to `a a b b` (beta83)

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Yes, the HLint integration has to be improved. I know how but takes some time.

**Comment by rikvdkleij** [comment]
Should be fixed in beta85, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta85
