### ISSUE TITLE
Custom repository from README not updated?

### ISSUE THREAD

**Issue by mbwgh** [rikvdkleij/intellij-haskell#621]
The newest beta at the time of this writing is beta83. The official JetBrains repository goes up until beta81.

The README mentions adding https://plugins.jetbrains.com/plugins/alpha/8258 as a custom repository.
However, it appears that this in turn only goes as far as beta72?
Am I missing something here?

**Comment by rikvdkleij** [comment]
> Am I missing something here?

No, the latest versions are not uploaded to the Jetbrains repo because they contain small fixes. I don't want to release too often in that case.

**Comment by mbwgh** [comment]
> I don't want to release too often in that case.

Understandable. But isn't that what the alpha repo is for, then?
As per its description, it should point to beta83, not beta72...

**Comment by rikvdkleij** [comment]
Ok, I will upload latest to alpha repo.

**Comment by mbwgh** [comment]
Thanks :)

(Even though now it looks like I bullied you into it...)

**Comment by rikvdkleij** [comment]
> (Even though now it looks like I bullied you into it...)

No problem 😄
