### ISSUE TITLE
External tool output parsing breaks file encoding (UTF-8)

### ISSUE THREAD

**Issue by sgt** [rikvdkleij/intellij-haskell#623]
For example, when reformatting Haskell code which contains Unicode symbols (.e. emoticons) using either Ormolu or Stylish Haskell, the Unicode symbols return garbled.
The tools themselves do not break the encoding, my guess the culprit is the code which parses tools' output and loads it back into the editor.

**Comment by rikvdkleij** [comment]
Can you give an example?

I can't reproduce this issue.

**Comment by rikvdkleij** [comment]
![image](https://user-images.githubusercontent.com/509315/97908846-8c614300-1d47-11eb-9683-a5737576cecc.png)

**Comment by sgt** [comment]
![image](https://user-images.githubusercontent.com/5119/97917473-92feb300-1d65-11eb-83af-5e4a11c5071c.png)

After pressing Ctrl-Alt-L:

![image](https://user-images.githubusercontent.com/5119/97917573-b590cc00-1d65-11eb-990e-bf02a8fb26fd.png)

I'm on Windows. Finally got the plugin to compile, will try to investigate further if you can't manage to reproduce it on your side.

**Comment by rikvdkleij** [comment]
@sgt Again, your help is really appreciated!
