### ISSUE TITLE
HLint quick fix replacing wrongly

### ISSUE THREAD

**Issue by andipabst** [rikvdkleij/intellij-haskell#630]
Quick fixes from HLint are replacing the code in the wrong place.

Example: In `return $ ()`, HLint marks the `$` and proposes "Redundant $, change to \`return ()\`" as a quick fix. If I accept the quick fix, I would expect the code to be `return ()` afterwards. Instead it is `return return () ()`, so the `$` is replaced, instead of the whole line.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

This is a known issue and fixed in next version.

**Comment by andipabst** [comment]
Oh cool, thank you!

**Comment by rikvdkleij** [comment]
Should be fixed in beta85, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta85
