### ISSUE TITLE
REPL couldn't be started for target

### ISSUE THREAD

**Issue by gtier** [rikvdkleij/intellij-haskell#631]
I started a new Haskell project with `stack new` and get this error repeated in the event log.
```REPL couldn't be started for target `start:exe:start-exe` due to: cannot satisfy -package start-0.1.0.0```
I'm using stack version 2.5.1

**Comment by rikvdkleij** [comment]
The REPL for the exe component can't be started if the lib component contains an error.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.

**Comment by andreasewering** [comment]
Not OP, but having the same problem. I get the message for executable and test suite, although the project builds fine with
`stack build --test --haddock --no-haddock-hyperlink-source` (mentioned in the README).
`stack repl app:lib` or any other target also works without issues.
Kind of lost right now what the issue could be. 

The plugin is really working great for the lib code, but its really awkward to work with tests without any typechecking :/

**Comment by rikvdkleij** [comment]
@andreasewering can you create example project so I can try to reproduce this issue?

**Comment by andreasewering** [comment]
@rikvdkleij I'm currently trying to get a reproducible more minimal example, but for now, here is my current learning project where the issue occurs https://gitlab.com/andreasewering/safari-zone/-/tree/master/backend

If you have docker installed you should be able to reproduce the issue rather quickly (a running postgresql server is needed due to postgresql-typed compile-time checking). Steps to setup are in the README.

**Comment by andreasewering** [comment]
I can confirm that typechecking in tests and exe works for a hello-world-type project with a single lib, executable and test-suite. So the issue might either be compile-time IO or multiple sub packages.

**Comment by andreasewering** [comment]
@rikvdkleij Seems like it was a temporary problem. While I tried to reproduce the bug with a smaller repository, the bug fixed itself after a couple of minutes. I reopened my normal project and waited a while with just lib files open and after that, typechecking in testfiles worked as well 👍

**Comment by rikvdkleij** [comment]
@andreasewering Great to hear!
