### ISSUE TITLE
Import project from external model wizard has no stack option

### ISSUE THREAD

**Issue by pypelyne** [rikvdkleij/intellij-haskell#636]
Plugin is installed and stack works as intended.
However following the instructions doesn|t work. The wizard offers the external Tools "Gradle" and "Maven", but Stack is missing. 
Maybe related to that: the Haskell-Tab in IntelliJ-Menu doesn't look right. Something seems to be missing:
![image](https://user-images.githubusercontent.com/60760868/104810878-0312c600-57f8-11eb-9874-7dbad9a3d77b.png)

**Comment by rikvdkleij** [comment]
When you import an existing Stack project (`New / Project from Existing Sources` you will have to choose the `Haskell Stack` external model. And in next wizard page you'll will have to create Haskell Tool Stack SDK.

**Comment by pypelyne** [comment]
Thanks, that's what I got wrong. Now it works
