### ISSUE TITLE
Keywords Inside Quasi Quotes Cause a Parse Error

### ISSUE THREAD

**Issue by vshatskyi** [rikvdkleij/intellij-haskell#64]
To reproduce:

```haskell
{-# LANGUAGE QuasiQuotes #-}

import Data.String.Interpolate

foo = [i|something|] -- compiles.
bar = [i|instance|] -- error.
```

**Comment by rikvdkleij** [comment]
Thanks for reporting. I wil fix it in next beta.

**Comment by rikvdkleij** [comment]
Fixed in beta 4.

**Comment by rikvdkleij** [comment]
@vshatskyi Can this issue be closed?

**Comment by vshatskyi** [comment]
I guess so, @rikvdkleij. Although, keywords are still highlighted incorrectly. 
![image](https://cloud.githubusercontent.com/assets/188928/21977760/4004a5bc-dbe0-11e6-9f96-df1cc017b180.png)

**Comment by rikvdkleij** [comment]
@vshatskyi okay, improved parser again :smile:

**Comment by rikvdkleij** [comment]
Fixed in beta6.
