### ISSUE TITLE
[global-stack-repl] Stack REPL couldn't be started within 30 seconds

### ISSUE THREAD

**Issue by dervism** [rikvdkleij/intellij-haskell#647]
Hi

I have seen this issue mentioned and looked into since 2019, but since there is no other properly working editor for Haskell available, I really want to get this plugin working.

I downloaded and installed the plugin and created a new Haskell project from IntelliJ. While the plugin is downloading the tools to its cache folder, and also after when everything is complete, I am continuously getting error message saying "[global-stack-repl] Stack REPL couldn't be started within 30 seconds" and then I am getting warning message saying "REPL couldn't be started for target HaskellBook:exe:HaskellBook-exe due to: cannot satisfy -package HaskellBook-0.1.0.0".

The project builds and runs without a problem. However, I have no documentation when hovering over the code and the warnings and errors keeps popping up in my editor. For some reason that I cannot understand, it does work sometimes only to stop working again shortly after.

Any ideas why this happens?

**Comment by rikvdkleij** [comment]
To get more information about what’s going on, you can enable the Haskell Event log. See README.

**Comment by AustinZhu** [comment]
I have the same issue.
