### ISSUE TITLE
Broken library pathes 

### ISSUE THREAD

**Issue by alleksandrgall** [rikvdkleij/intellij-haskell#651]
Hello, 12 errors appeared after i tried to enable `polysemy-plugin` which requiers `-fplugin=Polysemy.Plugin` ghc option:

Library ghc-8.10.4 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-8.10.4 [Fix]
Library ghc-8.10.4 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-8.10.4 [Fix]
Library ghc-boot-8.10.4 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-boot-8.10.4 [Fix]
Library ghc-boot-8.10.4 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-boot-8.10.4 [Fix]
Library ghc-boot-th-8.10.4 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-boot-th-8.10.4 [Fix]
Library ghc-boot-th-8.10.4 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-boot-th-8.10.4 [Fix]
Library ghc-heap-8.10.4 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-heap-8.10.4 [Fix]
Library ghc-heap-8.10.4 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghc-heap-8.10.4 [Fix]
Library ghci-8.10.4 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghci-8.10.4 [Fix]
Library ghci-8.10.4 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\ghci-8.10.4 [Fix]
Library hpc-0.6.1.0 has broken classes paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\hpc-0.6.1.0 [Fix]
Library hpc-0.6.1.0 has broken sources paths:   C:\Users\gamergod88\AppData\Local\rikvdkleij\intellij-haskell\cache\lib\error-correcting-code-tester\hpc-0.6.1.0 [Fix]

**Comment by rikvdkleij** [comment]
This shouldn’t affect the working of the plugin. It means the source code hasn’t been downloaded.

**Comment by alleksandrgall** [comment]
Looks like the issue is indeed on the side of `polysemy-plugin`
