### ISSUE TITLE
No documentation available as Hoogle (database) isn't available

### ISSUE THREAD

**Issue by mhusmann** [rikvdkleij/intellij-haskell#659]
Installed intellij-haskell unfortunately getting above error message and I don't find a way to get hoogle running
hoogle runs perfectly in a shell window.

Running idea 2021.1.1 Community Edition on Arch Linux

**Comment by alleksandrgall** [comment]
Did you try building your project with haddock?
`stack build --haddock`

**Comment by mhusmann** [comment]
I just run *stack build --haddock*
Now it works.

Thank you for the advice
Michael

Am Do., 3. Juni 2021 um 15:09 Uhr schrieb alleksandrgall <
***@***.***>:

**Comment by marcozucchi** [comment]
Hoogle Documentation is not available for me out-of-the-box

**Comment by amryounis** [comment]
hi, i am running on windows. stack build --haddock did not work

![image](https://user-images.githubusercontent.com/3895133/196008087-b729d574-ce03-435f-a5c9-b6bccf212723.png)

**Comment by marcozucchi** [comment]
@amryounis try following the temporal fix I describe above your reply in CMD or Powershell

**Comment by amryounis** [comment]
thanks @marcozucchi . May I ask you to show the syntax for Windows?
