### ISSUE TITLE
Can't load Data.Map after stack.yaml add it.

### ISSUE THREAD

**Issue by jiamo** [rikvdkleij/intellij-haskell#663]
Use GHCI load module in ghci I got

```
/Users/jiamo/mtype/app/Named_func.hs:6:1: error:
    Could not load module ‘Data.Map’
    It is a member of the hidden package ‘containers-0.6.4.1’.
    You can run ‘:set -package containers’ to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Data.Map
  | ^^^^^^^^^^^^^^^
Failed, no modules loaded.
```
In console: `stack repl`

```
Using main module: 1. Package `mtype' component mtype:exe:mtype with main-is file: /Users/jiamo/mtype/app/Main.hs
Configuring GHCi with the following packages: mtype
GHCi, version 9.0.1: https://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( /Users/jiamo/mtype/app/Main.hs, interpreted )
Ok, one module loaded.
Loaded GHCi configuration from /private/var/folders/dn/h3lkn8751r56d14tdc687z1w0000gn/T/haskell-stack-ghci/a50491d1/ghci-script
ghci> import Data.Map

<no location info>: error:
    Could not load module ‘Data.Map’
    It is a member of the hidden package ‘containers-0.6.4.1’.
    You can run ‘:set -package containers’ to expose it.
    (Note: this unloads all the modules in the current scope.)
ghci>
```
However use `stack exec ghci` ok:

```
stack exec ghci
GHCi, version 9.0.1: https://www.haskell.org/ghc/  :? for help
ghci> import Data.Map
ghci>
```

with stack.yaml:

```
resolver: ghc-9.0.1
packages:
- .
extra-deps:
  - containers-0.6.5.1

system-ghc: true
install-ghc: false

```
The IDE also show the error:  

![Screen Shot 2021-08-03 at 22 34 10](https://user-images.githubusercontent.com/732751/128034163-b2913f74-0b29-4713-b374-990174012b3d.png)

**Comment by rikvdkleij** [comment]
You need to put normal dependencies like containers in cabal file, not in stack.yaml

**Comment by jiamo** [comment]
I will try later today. 
By the way
0.91 don't support idea-2020.2 ?

![Screen Shot 2021-08-04 at 9 38 15 AM](https://user-images.githubusercontent.com/732751/128108325-8f00b23c-b6a1-41fc-a46a-3912c8be65d1.png)

**Comment by rikvdkleij** [comment]
Latest version is https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta87

See also plugin repo.

**Comment by jiamo** [comment]
<img width="208" alt="Screen Shot 2021-08-04 at 5 43 20 PM" src="https://user-images.githubusercontent.com/732751/128159800-8b937bc5-ad26-41e6-845e-6bd9b76dccc4.png">

My mistake. may be we can put the latest beta version on right side page.

**Comment by jiamo** [comment]
After add  package in cable file. The ide don't show error. However send to ghci still have this error.

```
λ> :load /Users/jiamo/mtype/app/NewModule.hs
[1 of 1] Compiling Co               ( /Users/jiamo/mtype/app/NewModule.hs, interpreted )

/Users/jiamo/mtype/app/NewModule.hs:10:1: error:
    Could not find module ‘Data.HashMap.Lazy’
    Perhaps you meant
      Data.IntMap.Lazy (needs flag -package-id containers-0.6.4.1)
      Data.IntMap.Lazy (from containers-0.6.5.1)
      Data.Map.Lazy (needs flag -package-id containers-0.6.4.1)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
10 | import Data.HashMap.Lazy
   | ^^^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.

```
But. using the same stack comamnd 

```/usr/local/bin/stack ghci --ghci-options "-ghci-script /Users/jiamo/Library/Caches/com.github.rikvdkleij.intellij-haskell/8.2.1.ghci" mtype:exe:mtype --ghc-options -fdiagnostics-color=always``` 

in command line.  The import is ok
