### ISSUE TITLE
Applying Refactor (for hlint inspection by pressing Alt+Enter) clears the file contents.

### ISSUE THREAD

**Issue by dhruvin2910** [rikvdkleij/intellij-haskell#67]
Appending **--inplace** to the **--refactor-options** may solve this problem.

![hlint-refactor](https://cloud.githubusercontent.com/assets/9679326/20864573/6741a6ba-ba1c-11e6-83c0-685b5040a145.gif)

**Comment by rikvdkleij** [comment]
It looks Refactor tool returns nothing and also doesn't give errors.

In master I removed usage of Refactor tool and replaced by applying suggestions in plugin code itself. Refactor tool gave more issues.

I hope to release beta 4 soon.

**Comment by dhruvin2910** [comment]
I look forward to test that. Thank you for initiating this project and maintaining it. It helps me a lot (as I am new to Haskell). This stack-intero duo works like a charm.

**Comment by rikvdkleij** [comment]
Fixed in beta 4.

**Comment by dhruvin2910** [comment]
It works.
