### ISSUE TITLE
Refactoring module name

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#71]
Just for reminding the issues mentioned at #69.

**Comment by rikvdkleij** [comment]
Okay, I will revert PR and first solve the issue you mentioned.

**Comment by rikvdkleij** [comment]
I have reverted your PR but I can not reopen your PR.

**Comment by zjhmale** [comment]
@rikvdkleij how about revert the reverted PR?

**Comment by rikvdkleij** [comment]
Done, see https://github.com/rikvdkleij/intellij-haskell/pull/73

**Comment by zjhmale** [comment]
Oh, you just did it 😅 . Great!

**Comment by rikvdkleij** [comment]
Yes :smiley:

**Comment by rikvdkleij** [comment]
Fixed in beta11
