### ISSUE TITLE
Feature request: haskell-tools for refactorings

### ISSUE THREAD

**Issue by clojj** [rikvdkleij/intellij-haskell#85]
https://github.com/haskell-tools/haskell-tools

This looks very nice and cli/editor support should be good.

**Comment by zjhmale** [comment]
Great! I'll take a look at this.

**Comment by rikvdkleij** [comment]
We already have renaming support with help of Intero.  It works for top-level declarations/definitions and also in general for locally scoped definitions. Renaming works throughout project.

Renaming does not work in all cases. For example, names of type signatures next to implementations in where bindings are not taken into account when renaming identifier. Intero does not help in that case and PSI-tree is not precise enough.

**Comment by rikvdkleij** [comment]
`Extract binding` and `Generate exports` is something we missing.

`Organize imports` is already done by using Stylish-haskell.

**Comment by zjhmale** [comment]
@rikvdkleij I can't I rename the top-level definitions. Am I missing something here?

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21384562/01abb54c-c7a6-11e6-950e-36d80920d315.gif)

**Comment by rikvdkleij** [comment]
It's only possible to rename inside project files, not in library files.

**Comment by zjhmale** [comment]
Ok, and if not set the project SDK inappropriately will also disable the renaming of top-level definition.

**Comment by rikvdkleij** [comment]
Yes, renaming works only within project Haskell modules and if Project SDK is set. SDK should contain path to Stack binary.

If Project SDK is not set or path to Stack binary is empty, IntelliJ should give error. What was your case?

**Comment by zjhmale** [comment]
I did not set the project SDK, sorry 😅

**Comment by rikvdkleij** [comment]
No problem, I'm glad your issue is understandable :smile:
