### ISSUE TITLE
slow down/hang of project when editing

### ISSUE THREAD

**Issue by KasperJanssens** [rikvdkleij/intellij-haskell#9]
Hi,

Lately, as my project is growing a little bigger, I seem to experience rather long lag when editing through intellij. The IDE can become unresponsive for one or two seconds even. Do you have an idea why this could happen, something that triggers upon saving or so (I think intellij constantly 'saves' in the background, so this might explain).

Unfortunately, you will likely not see it in my talisman project, I have it with the project at work, which is proprietary so I can't really share it. I'm just looking if you would have an idea what might be going on or whether you maybe already have a suspect in your sights?

Kasper

**Comment by rikvdkleij** [comment]
@KasperJanssens I reopened ghc-mod issue #275 because I noticed that `ghc-modi check` is still not behaving consistently. I suspect this was causing your problem with flickering errors. I will go back to using ghc-mod for checking file.

Btw, I'm busy with big improvements in plugin. They need some time....

**Comment by KasperJanssens** [comment]
No problem, I understand. I started to use the haskforce plugin, they had
problems with performance as well through ghc-modi.

2015-01-15 16:38 GMT+01:00 Rik <notifications@github.com>:

**Comment by rikvdkleij** [comment]
@KasperJanssens  I released new beta with a lot of improvements. Hopefully you can give a try soon and we can close all open issues :-)

**Comment by rikvdkleij** [comment]
@KasperJanssens Btw, it's now possible to navigate to module by using Ctrl+N.

**Comment by KasperJanssens** [comment]
Cool, how did you do that, I though Ctrl - N was reserved for java classes
only, period?

I'm going to try it out one of these days, at work we switched to the
haskforce plugin because it has more cabal integration and you can run
tests and applications from intellij and so on. But for my personal
projects, I might give your plugin a spin again.

2015-01-21 11:32 GMT+01:00 Rik <notifications@github.com>:

**Comment by rikvdkleij** [comment]
Ctrl+N is used to navigate to declaration instead of class. A Haskell file contains (normally) a module declaration at the top.

Thanks. When you have closed your open issues I will release new version in Jetbrains repo.

**Comment by rikvdkleij** [comment]
@KasperJanssens  I will release new version because I do not want to wait longer :-)

**Comment by KasperJanssens** [comment]
Go ahead, I'm sorry, I didn't make it this weekend to testing.  I will,
though, it's a promise ;-)!

2015-01-26 12:37 GMT+01:00 Rik <notifications@github.com>:

**Comment by rikvdkleij** [comment]
okay :+1:

**Comment by rikvdkleij** [comment]
Fixed
